### PR TITLE
padding fix for header logo container #1216

### LINKED ISSUE #1216: Navigation header style fix
# Current behavior

The menu header is no more aligned with the underneath content:

Image

# Desired behavior

The menu header logo should be vertically aligned with the menu element icons. (there should be no margin and only a 4px left padding) 

The "collapse menu" icon should appear only on the menu hover (It should be hidden unless the navigation bar is being hovered). Add a 150ms fade transition from opacity 0% to opacity 100%

Image

### PR DESCRIPTION
**Pull request by Manikanta528**
fixes #1216 

Screenshot 2023-08-17 at 9 57 39 PM

- [x] padding fix for header
- [x] collapse menu hover and fade transition

### CODE REVIEW

File: front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx [hunk 1]
```diff
@@ -66,7 +68,7 @@ function NavWorkspaceButton() {
         ></StyledLogo>
         <StyledName>{currentWorkspace?.displayName ?? 'Twenty'}</StyledName>
       </StyledLogoAndNameContainer>
-      <NavCollapseButton direction="left" />
+      <NavCollapseButton direction="left" isHovered={_isHoverd.isHovered} />
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx:71]:
```suggestion
      <NavCollapseButton direction="left" isVisible={isHovered} />
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 2]
```diff
@@ -29,15 +32,27 @@ const StyledCollapseButton = styled.button`
...
+    }
+    100% {
+      opacity: 1;
+    }
+  }
 `;
 
 type CollapseButtonProps = {
   direction?: 'left' | 'right';
+  isHovered: boolean;
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:50]: `isHovered`is a bit misleading for this component as it reflects whether the button should show, not its hover status.
```suggestion
  isVisible: boolean;
```

**Review by emilienchvt — COMMENTED** [review]
Very nice start ! Thanks a bunch @Manikanta528 🔥 
I left a couple comments on naming mostly, let me know if you have questions

File: front/src/modules/ui/layout/page-bar/components/PageBar.tsx [hunk 3]
```diff
@@ -95,7 +95,7 @@ export function PageBar({
         <StyledLeftContainer>
           {!isNavbarOpened && (
             <StyledTopBarButtonContainer>
-              <NavCollapseButton direction="right" />
+              <NavCollapseButton direction="right" isHovered={true} />
```
[the remark this answers is not in the document]
Comment (Manikanta528) [reply front/src/modules/ui/layout/page-bar/components/PageBar.tsx:98]: To Make it always visible on the `NavCollapseButton` on the right side of the panel.

Screenshot 2023-08-22 at 8 46 17 PM

**Comment by Manikanta528** [comment]
@emilienchvt  Solved naming convention.

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 4]
```diff
@@ -29,15 +32,27 @@ const StyledCollapseButton = styled.button`
...
+    }
+    100% {
+      opacity: 1;
+    }
+  }
 `;
 
 type CollapseButtonProps = {
   direction?: 'left' | 'right';
+  isVisible: boolean;
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:50]: I'm not too sure about the API where developers need to explicitly state that the component is visible. Can we change this to have the component visible by default, and use a `hide` props instead ?

File: front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx [hunk 5]
```diff
@@ -47,7 +45,11 @@ const StyledName = styled.div`
   margin-left: ${({ theme }) => theme.spacing(2)};
 `;
 
-function NavWorkspaceButton() {
+type OwnProps = {
+  isHovered: boolean;
```
[the remark this answers is not in the document]
Comment (emilienchvt) [reply front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx:49]:
```suggestion
  hideCollapseButton: boolean;
```

File: front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx [hunk 6]
```diff
@@ -66,7 +68,7 @@ function NavWorkspaceButton() {
         ></StyledLogo>
         <StyledName>{currentWorkspace?.displayName ?? 'Twenty'}</StyledName>
       </StyledLogoAndNameContainer>
-      <NavCollapseButton direction="left" />
+      <NavCollapseButton direction="left" isVisible={isHovered} />
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavWorkspaceButton.tsx:71]:
```suggestion
      <NavCollapseButton direction="left" hide={hideCollapseButton} />
```

File: front/src/modules/ui/layout/page-bar/components/PageBar.tsx [hunk 7]
```diff
@@ -95,7 +95,7 @@ export function PageBar({
         <StyledLeftContainer>
           {!isNavbarOpened && (
             <StyledTopBarButtonContainer>
-              <NavCollapseButton direction="right" />
+              <NavCollapseButton direction="right" isVisible={true} />
```
Comment (emilienchvt) [inline front/src/modules/ui/layout/page-bar/components/PageBar.tsx:98]:
```suggestion
              <NavCollapseButton direction="right"/>
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx (hunk 4 above)
Comment (emilienchvt) [reply front/src/modules/ui/navbar/components/NavCollapseButton.tsx:50]:
```suggestion
  hide: boolean;
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 8]
```diff
@@ -29,15 +32,27 @@ const StyledCollapseButton = styled.button`
...
 };
 
 export default function NavCollapseButton({
   direction = 'left',
+  isVisible,
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:55]:
```suggestion
  hide =  false,
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 9]
```diff
@@ -10,8 +10,11 @@ import { useIsMobile } from '@/ui/utilities/responsive/hooks/useIsMobile';
 
 import { navbarIconSize } from '../constants';
 
-const StyledCollapseButton = styled.button`
+const StyledCollapseButton = styled.button<{
+  isHovered: boolean;
+}>`
   align-items: center;
+  animation: ${({ isHovered }) => (isHovered ? 'fadeIn 150ms' : 'none')};
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:17]:
```suggestion
  animation: ${({ hide }) => (hide ?  'none' : 'fadeIn 150ms')};
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 10]
```diff
@@ -29,15 +32,27 @@ const StyledCollapseButton = styled.button`
   padding: 0;
 
   user-select: none;
+  visibility: ${({ isHovered }) => (isHovered ? 'visible' : 'hidden')};
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:35]:
```suggestion
  visibility: ${({ hide }) => (hide ? 'hidden' : 'visible')};
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 11]
```diff
@@ -48,11 +63,17 @@ export default function NavCollapseButton({
   return (
     <>
       {direction === 'left' ? (
-        <StyledCollapseButton onClick={() => setIsNavOpen(!isNavOpen)}>
+        <StyledCollapseButton
+          isHovered={isVisible}
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:67]:
```suggestion
          hide={hide}
```

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx [hunk 12]
```diff
@@ -48,11 +63,17 @@ export default function NavCollapseButton({
...
+          onClick={() => setIsNavOpen(!isNavOpen)}
+        >
           <IconLayoutSidebarLeftCollapse size={iconSize} />
         </StyledCollapseButton>
       ) : (
-        <StyledCollapseButton onClick={() => setIsNavOpen(!isNavOpen)}>
+        <StyledCollapseButton
+          isHovered={isVisible}
```
Comment (emilienchvt) [inline front/src/modules/ui/navbar/components/NavCollapseButton.tsx:74]:
```suggestion
          hide={hide}
```

**Review by emilienchvt — COMMENTED** [review]
Thanks for addressing the comments, much clearer now 👏 
Added a couple of proposals for naming, in order to show render mounted components as default and clarify hover vs. visible state. Let me know what you think @Manikanta528

File: front/src/modules/ui/layout/page-bar/components/PageBar.tsx (hunk 7 above)
Comment (Manikanta528) [reply front/src/modules/ui/layout/page-bar/components/PageBar.tsx:98]: I Changed all requested proposals for naming  but for this, it will throw an error Property `hide` is missing

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx (hunk 9 above)
Comment (Manikanta528) [reply front/src/modules/ui/navbar/components/NavCollapseButton.tsx:17]: It will reverse the functionality.

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx (hunk 10 above)
Comment (Manikanta528) [reply front/src/modules/ui/navbar/components/NavCollapseButton.tsx:35]: It will reverse the functionality the same as above like `NavCollapseButton` will hidden when the mouse is hovered over the nav bar which leads to not being able to toggle at nav bar and visible at mouse leaves.

File: front/src/modules/ui/navbar/components/NavCollapseButton.tsx (hunk 8 above)
Comment (Manikanta528) [reply front/src/modules/ui/navbar/components/NavCollapseButton.tsx]: the default value is unnecessary.

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
Thank you!
