### PR TITLE
Fix command menu keyboard navigation

### LINKED ISSUE #2746: Add Keyboard navigation on IconPicker
## Scope & Context

Recently, we had introduced a re-usable SelectableList component which used in CommandMenu. It provides a simple way to track which item is selected with keyboard.
Right now it only support one dimension (arrow up and down) but we would like to:
- extend it to be 2-dimensions
- use it to add arrow selection on IconPicker

## Current behavior

On the IconPicker, it is not possible to select an icon using the keyboard (arrow up, down, left, right)

## Expected behavior

On the IconPicker, is is possible to select an icon using the keyboard

## Technical inputs

- Improve SelectableList API to support 2 dimensions selectableItemIds (string[] => string[][])
- improve SelectableList API to pass the Hotkeyscope (right now we have hardcoded CommandMenu one)
- use it within IconPicker

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Refer to: https://github.com/twentyhq/twenty/pull/2778#issuecomment-1848351421

Fixes #2746

### CODE REVIEW

File: packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx [hunk 1]
```diff
@@ -118,6 +120,17 @@ export const CommandMenu = () => {
       ],
     },
     limit: 3,
+    onCompleted: (data) => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx:123]: We should put all the onCompleted in useEffects, because onCompleted isn't retriggered when we're updating the cache with optimistic effects.

**Review by lucasbordeau — CHANGES_REQUESTED** [review]

File: packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx (hunk 1 above)
Comment (gitstart-twenty) [reply packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx]: Hey @lucasbordeau Adding a `useEffect` just caused too many rerenders, please check out the change I went with.

**Review by charlesBochet — APPROVED** [review]
Looks good, thank you!
