### PR TITLE
Remove onboarding flashes + close all dropdowns on CommandMenu close

### LINKED ISSUE #11105: Add new modal handleClickOutside doesnt trigger if new isnt created
## Bug Description

- when Adding a new field in either company or point of contact, if the add new modal is returned and not saved then the right drawer doesn't work until a field is chosen of add new list.

- Go to People/click any field/ Add new in Company or point of contact

## Current Behaviour

https://github.com/user-attachments/assets/fe445c59-46eb-4467-9e6d-83020221e8e8

## Expected behavior

handleClickOutside should work fine and drawer should close.

### PR DESCRIPTION
**Pull request by bosiraphael**
## Remove onboarding flashes

Tested:
- sign in with credentials
- sign in with social oAuth
- sign up with credentials
- multidomain
- single domain
- reset password

No more flashes, and code logic simplified!

## Close all dropdowns on CommandMenu close

Before:

https://github.com/user-attachments/assets/244ff935-3d40-47d5-a097-12d4cc3810dd

After:

https://github.com/user-attachments/assets/1de692f8-5032-404a-be74-025ebca67138

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownCloseOnCommandMenuShortcutEffect.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import { useDropdownV2 } from '@/ui/layout/dropdown/hooks/useDropdownV2';
+import { useScopedHotkeys } from '@/ui/utilities/hotkey/hooks/useScopedHotkeys';
+import { AppHotkeyScope } from '@/ui/utilities/hotkey/types/AppHotkeyScope';
+import { useComponentInstanceStateContext } from '@/ui/utilities/state/component-state/hooks/useComponentInstanceStateContext';
+import { isDefined } from 'twenty-shared/utils';
+
+export const DropdownCloseOnCommandMenuShortcutEffect = () => {
+  const { closeDropdown } = useDropdownV2();
+
+  const dropdownId = useComponentInstanceStateContext(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownCloseOnCommandMenuShortcutEffect.tsx:11]: dropdownId must be defined, I don't think it can't be set

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx [hunk 2]
```diff
@@ -186,6 +187,7 @@ export const Dropdown = ({
             onDropdownClose={onClose}
             onDropdownOpen={onOpen}
           />
+          <DropdownCloseOnCommandMenuShortcutEffect />
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx:190]: I'm not convinced by this abstraction, Dropdown shouldn't be aware of its implementations.

We should find a way to have the command menu closing any of its open dropdown by a synchronous hook call, because this is the way we want to go, instead of relying on effects in the dropdown, which we already tried and removed, let's not put more effect in the dropdown component and find a synchronous solution.

**Comment by charlesBochet** [comment]
@bosiraphael @lucasbordeau taking it to refactor with the new closeAnyDropdownTooling

**Comment by lucasbordeau** [comment]
The PR has been merged : https://github.com/twentyhq/twenty/pull/11504 

You can use it for your use case.

File: packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts [hunk 3]
```diff
@@ -1,40 +1,28 @@
...
-
-    if (
-      !isLoggedIn ||
-      onboardingStatus === OnboardingStatus.PLAN_REQUIRED ||
-      onboardingStatus === OnboardingStatus.PROFILE_CREATION ||
-      onboardingStatus === OnboardingStatus.WORKSPACE_ACTIVATION ||
-      onboardingStatus === OnboardingStatus.SYNC_EMAIL ||
-      onboardingStatus === OnboardingStatus.INVITE_TEAM
+      isMatchingLocation(AppPath.PlanRequired) ||
+      isMatchingLocation(AppPath.PlanRequiredSuccess)
```
Comment (martmull) [inline packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts:21]: jeez why did i do complicated stuff when something simple like that was possible <3

**Review by martmull — APPROVED** [review]
LGTM nice code

File: packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts (hunk 3 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/layout/hooks/useShowAuthModal.ts:21]: a lot of refactoring where required (I've made them earlier this week, took me a lot of sweat!)
