### PR TITLE
fixed issue Refine Settings Layout

### LINKED ISSUE #3411: Refine Settings Layout
# Current Behavior

1. The page layouts have different widths. For example, `/settings/profile` is much narrower (350px) than `/settings/objects` (512px)

| 350px | 512px |
|---|---|
| CleanShot 2024-01-12 at 17 08 04 | CleanShot 2024-01-12 at 17 08 54 |

2. The content is not horizontally centered on the page:

CleanShot 2024-01-12 at 16 58 04

# Desired Behavior

1. All the settings' content width should be 512px. Designs have been updated:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13273-96299&mode=design&t=cT75gYTM64rGg00A-11

CleanShot 2024-01-12 at 17 08 54

2. The content should be centered in the middle of the screen:

CleanShot 2024-01-12 at 17 00 41

### PR DESCRIPTION
**Pull request by abdul-irfan-k**
fixed #3411

Screenshot from 2024-01-14 18-25-05

Screenshot from 2024-01-14 18-25-24

Screenshot from 2024-01-14 18-26-07

Screenshot from 2024-01-14 18-26-21

Screenshot from 2024-01-14 18-26-56

### CODE REVIEW

**Comment by abdul-irfan-k** [comment]
[Screencast from 16-01-24 08:16:35 PM IST.webm](https://github.com/twentyhq/twenty/assets/114819335/f6d35bf2-93cc-48c0-b76d-cd6fbd4e510a)
it take 737px (1.6px for middle border)


[Screencast from 16-01-24 08:19:46 PM IST.webm](https://github.com/twentyhq/twenty/assets/114819335/b0d51f12-73f2-45c3-af4d-15ed7306f4db)
Screenshot from 2024-01-16 20-16-13

File: packages/twenty-front/src/modules/ui/utilities/screen-size/hooks/useScreenSize.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import { useEffect, useState } from 'react';
+
+export const useScreenSize = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/screen-size/hooks/useScreenSize.ts:3]: @abdul-irfan-k introducing this hook as based on design, it does not seem to be possible to handle this by css only

File: packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx [hunk 2]
```diff
@@ -76,7 +83,20 @@ export const DefaultLayout = ({ children }: DefaultLayoutProps) => {
       <StyledLayout>
         <CommandMenu />
         <KeyboardShortcutMenu />
-        <StyledPageContainer>
+
+        <StyledPageContainer
+          animate={{
+            marginLeft:
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/page/DefaultLayout.tsx:89]: applying the marginLeft here rather than on SettingsPage to allow animation between pages

**Review by charlesBochet — APPROVED** [review]
