### PR TITLE
fix relation fields preview in settings

### LINKED ISSUE #7084: Regression - Preview in relation field settings
# Current behavior

We used to display a relation record preview that's no longer shown.

CleanShot 2024-09-17 at 08 08 34@2x

# Desired Behavior

Display the first record identifier in the object preview. If the object is empty, the chip should contain `singular object name 1` with the object's first letter in the record image identifier. (Like the warehouse relationship on the image below)

CleanShot 2024-09-17 at 08 10 34@2x

### PR DESCRIPTION
**Pull request by etiennejouan**
Fixes :
- display relation fields in preview settings
- display note and task relation field in preview settings - 
- fix design (align and background color)

closes https://github.com/twentyhq/twenty/issues/7084

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx [hunk 1]
```diff
@@ -45,19 +50,40 @@ export const RelationFromManyFieldDisplay = () => {
...
+            }
+
+            return (
               <RecordChip
                 key={record.id}
                 objectNameSingular={objectNameSingular}
                 record={record[relationFieldName]}
+                forceDisableClick={isReadOnly}
               />
-            ) : undefined,
```
Comment (guillim) [inline packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx:59]: Probably stupid question, but why didn't you keep the `fieldValue.map` logic (in other terms why the need of `formattedRecords`) and simply shoot a `RecordChip` to substitute the `undefined` return ? Sounds easier DX to me no ?

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx [hunk 2]
```diff
@@ -113,6 +119,12 @@ export const SettingsDataModelFieldRelationSettingsFormCard = ({
                   initialRelationFieldMetadataItem.label,
                 ) || 'Field name',
               type: FieldMetadataType.RELATION,
+              relationDefinition: {
+                direction:
+                  relationType === RelationDefinitionType.MANY_TO_ONE
```
Comment (guillim) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/components/SettingsDataModelFieldRelationSettingsFormCard.tsx:124]: inverted

File: packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/usePreviewRecord.ts [hunk 3]
```diff
@@ -27,8 +28,15 @@ export const usePreviewRecord = ({
     getLabelIdentifierFieldMetadataItem(objectMetadataItem);
   const skip = skipFromProps || !labelIdentifierFieldMetadataItem;
 
+  let recordGqlFields: Record<string, boolean> | undefined = undefined;
+  if (objectMetadataItem.nameSingular === CoreObjectNameSingular.NoteTarget)
+    recordGqlFields = { id: true, note: true };
+  if (objectMetadataItem.nameSingular === CoreObjectNameSingular.TaskTarget)
+    recordGqlFields = { id: true, task: true };
```
[the remark this answers is not in the document]
Comment (guillim) [reply packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/usePreviewRecord.ts:35]: Shut up greptile, it's good enough for 2 cases without exhaustive casing !

File: packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useRelationFieldPreviewValue.ts [hunk 4]
```diff
@@ -15,8 +15,9 @@ type UseRelationFieldPreviewParams = {
 export const useRelationFieldPreviewValue = ({
   relationObjectMetadataItem,
   skip,
-}: UseRelationFieldPreviewParams) =>
-  usePreviewRecord({
+}: UseRelationFieldPreviewParams) => {
+  return usePreviewRecord({
```
Comment (guillim) [inline packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useRelationFieldPreviewValue.ts:19]: niptick: probably not necessary

**Review by guillim — CHANGES_REQUESTED** [review]
Really nice job. I had little remarks but nothing outstanding

**Review by guillim — APPROVED** [review]
great job
