### PR TITLE
Move http node to backend

### LINKED ISSUE #14491: HTTP Requests should always be sent from the server when testing.
## Bug Description

When testing an HTTP Request to an API in Workflows, the request is sent by the browser, causing an "origin" header to be present, which some APIs do not like. When testing the entire workflow though, the request is sent by the server without an "origin" header, leading to a successful API Request.

## Expected behavior

The API request should always be sent by the backend to have a consistent and accurate experience when testing workflows.

## Technical inputs

-

### PR DESCRIPTION
**Pull request by thomtrp**
Fixes https://github.com/twentyhq/twenty/issues/14491

Also adding an url validator.

### CODE REVIEW

**Comment by thomtrp** [comment]
@greptileai trigger

File: packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts [hunk 1]
```diff
@@ -21,12 +26,50 @@ export class HttpTool implements Tool {
...
+
+          if (options.all) {
+            callback(null, [
+              { address: safeUrlIP, family: options.family || 4 },
+            ]);
+          } else {
+            callback(null, safeUrlIP, options.family || 4);
+          }
+        },
+      });
```
[the remark this answers is not in the document]
Comment (thomtrp) [reply packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts]: this is wrong. The url hostname is not used, since lookup function has been overridden.

**Comment by thomtrp** [comment]
@greptileai trigger

File: packages/twenty-server/src/engine/core-modules/tool/tool.module.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+@Module({
+  imports: [
+    MessagingImportManagerModule,
+    TypeOrmModule.forFeature([FileEntity]),
+    FileModule,
+  ],
+  providers: [HttpTool, SendEmailTool, ToolRegistryService],
+  exports: [ToolRegistryService],
+})
+export class ToolModule {}
```
Comment (Weiko) [inline packages/twenty-server/src/engine/core-modules/tool/tool.module.ts:21]: As discussed, would prefer a better name but not a blocker for now!

File: packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts [hunk 3]
```diff
@@ -21,12 +26,53 @@ export class HttpTool implements Tool {
     const isMethodForBody = ['POST', 'PUT', 'PATCH'].includes(method);
 
     try {
+      const parsedUrl = new URL(url);
+
+      if (!['http:', 'https:'].includes(parsedUrl.protocol)) {
+        throw new Error('Invalid URL protocol');
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts]: CustomException with friendlyMessage

File: packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts [hunk 4]
```diff
@@ -21,12 +26,53 @@ export class HttpTool implements Tool {
...
+      }
+
       const axiosConfig: AxiosRequestConfig = {
         url,
         method: method,
         headers: headersCopy,
       };
 
+      if (!process.env.DISABLE_SSRF_PROTECTION) {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts]: HTTP_TOOL_SAFE_MODE_ENABLED

File: packages/twenty-server/src/engine/core-modules/tool/utils/get-safe-url-ip.util.ts [hunk 5]
```diff
@@ -0,0 +1,150 @@
...
+    /^0x7f\./i.test(addr) ||
+    /^fe80::1$/i.test(addr) ||
+    /^::1$/.test(addr) ||
+    /^::$/.test(addr)
+  );
+};
+
+const normalizeToLong = (addr: string) => {
+  const parts = addr.split('.').map((part) => {
+    // Handle hexadecimal format
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/tool/utils/get-safe-url-ip.util.ts]: remove comments

File: packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts [hunk 6]
```diff
@@ -66,6 +66,15 @@ export class ConfigVariables {
...
   IS_EMAIL_VERIFICATION_REQUIRED = false;
 
+  @ConfigVariablesMetadata({
+    group: ConfigVariablesGroup.OTHER,
+    description:
+      'Disable SSRF protection checks for HTTP requests (allows private IPs and other security risks)',
+    type: ConfigVariableType.BOOLEAN,
+  })
+  @IsOptional()
+  DISABLE_SSRF_PROTECTION = false;
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts]: default true?

File: packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts [hunk 7]
```diff
@@ -142,4 +147,37 @@ export class WorkflowVersionStepResolver {
...
+        success: result.success,
+        message: result.message,
+        result: result.result,
+        error: result.error,
+        status: result.status,
+        statusText: result.statusText,
+        headers: result.headers,
+      };
+    } catch (error) {
+      return {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/workflow/resolvers/workflow-version-step.resolver.ts]: shouldn't this be in an exception filter (and catch CustomException)

File: packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts (hunk 3 above)
Comment (thomtrp) [reply packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts]: this error is catch bellow. Only updating the message then

File: packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts (hunk 6 above)
Comment (thomtrp) [reply packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts]: inverted so yes :D

Comment (Weiko) [reply packages/twenty-server/src/engine/core-modules/twenty-config/config-variables.ts]: Reading "POSITIVE" form is more straightforward imho, I'd prefer ENABLE(D) (this also makes condition check simpler in the codebase) @thomtrp @charlesBochet wdyt

File: packages/twenty-server/src/engine/core-modules/tool/utils/get-secure-axios-adapter.util.ts [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+    if (!['http:', 'https:'].includes(url.protocol)) {
+      throw new Error('URL should use http/https protocol');
+    }
+
+    const { hostname } = url;
+
+    const { address: resolvedIp } = await dns.lookup(hostname);
+
+    const isSafeModeEnabled = process.env.HTTP_TOOL_SAFE_MODE_ENABLED ?? true;
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/tool/utils/get-secure-axios-adapter.util.ts]: we should use config variable module here. The issue is that we are in an util i guess can't we pass the variable from the service to this util as props? might be too heavy?

File: packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts [hunk 9]
```diff
@@ -36,12 +38,19 @@ export class HttpTool implements Tool {
         }
       }
 
-      const response = await axios(axiosConfig);
+      const safeAxiosClient = axios.create({
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/tool/tools/http-tool/http-tool.ts]: we could pass the config variable here (see comment above)

**Comment by charlesBochet** [comment]
Tested LGTM
image

**Comment by charlesBochet** [comment]
https://github.com/user-attachments/assets/eac81fa1-9538-4aa2-a66c-5d53f2f0344a

**Comment by charlesBochet** [comment]
image

**Review by charlesBochet — APPROVED** [review]
