### PR TITLE
Fixes person navigation after image upload

### LINKED ISSUE #8949: Cannot navigate to next record after uploading an image identifier
## Bug Description

After uploading an image identifier, the next button on a People record page does not navigate to the next record

**Example:** 

Go to _All People_

Click on a person to view their detail page.
Image

Click their profile image, in this case the circle with 'T' in it.
Upload a new image to their profile
Image

Click on the up `↑` or down `↓`  icon to navigate to the next record

Nothing happens.

https://github.com/user-attachments/assets/61ae4df9-d714-4dab-ba36-abb153b77fc8

If I go back to the previous record, I can then navigate again to the next records

## Expected behavior

The person being displayed is changed

### PR DESCRIPTION
**Pull request by mdrazak2001**
Fixes #8949

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts [hunk 1]
```diff
@@ -81,7 +83,9 @@ export const useRecordShowPagePagination = (
   const { loading: loadingRecordAfter, records: recordsAfter } =
     useFindManyRecords({
       skip: loadingCursor,
-      filter,
+      filter: {
+        id: { neq: objectRecordId },
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:87]: this does not feels right to me, we need to retrieve the previous (resp. next) record based on the viewFilters and sort. We cannot remove the filter as you are doing.

Could you explain your change and how you think it's fixing the issue?

**Review by charlesBochet — CHANGES_REQUESTED** [review]
Hi @mdrazak2001, thanks for opening a PR :)
Your fix does not feel right though, I've left a comment

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts (hunk 1 above)
Comment (mdrazak2001) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: Hi @charlesBochet,

Thanks for the feedback! You're right—replacing `filter` entirely was incorrect. I've updated the code to combine the original `filter` with `{ id: { neq: objectRecordId } }` to ensure we respect view filters and sorting while excluding the current record (to prevent duplicate pagination results).

Let me know if this works!

Thanks!

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: I'm a bit confused because to me this should not be tied to filters.
It should be tied to cursor / pagination logic. To get the next record for example, we do:
```
cursorFilter: cursorFromRequest
        ? {
            cursorDirection: 'after',
            cursor: cursorFromRequest,
            limit: 1,
          }
        : undefined,
```
This should already get the next item without having to change the filters. Why isn't this working?

Comment (mdrazak2001) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: I did some logging to understand the behavior further. Here’s what I observed:

1. Before the image upload (Added Dummy ids for the below example):

-         Records Before: []

        

-         Records After (contains the next person information):
            [
              {
                "__typename": "Person",
                "id": "B"
              }
            ]

2. After the image upload:
-         Records Before:
             [
                {
                  "__typename": "Person",
                  "id": "A"
                }
              ]

        

-         Records After :
             [
                {
                  "__typename": "Person",
                  "id": "A"
                },
                {
                  "__typename": "Person",
                  "id": "B"
                }
              ]

These responses were returned by `useFindManyRecords`. It seems that after the image upload, the Records After array includes both the current record and the next record. As a result, when the "Next" button is pressed, it navigates to the current person instead of the expected next person.
This behavior suggests that while the cursor logic retrieves records after the current position, the filtering isn't excluding the current record
Explicitly adding a filter like `{ id: { neq: currentRecordId } }` ensures the current record is excluded, preventing this duplication and aligning the navigation behavior with expectations.

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: Okay, I think this is an optimistic rendering issue. What's likely happening is that on record update (useUpdateOneRecord) we are triggering optimistic effects triggerUpdateRecordOptimisticEffect. 

This Optimistic effects (through cache.modify) is checking if the updated record match the query and if yes it adds it.

```
  const updatedRecordShouldBeAddedToRootQueryEdges =
          updatedRecordMatchesThisRootQueryFilter &&
          !updatedRecordFoundInRootQueryEdges;
```

However this logic does not take the cursor into account : it's not because it matches the filter that the record should be added to the query result, it should also check that if we have orderBy + cursor + limit, it should be added.

This is not a big change but might be a bit tricky to implement.

Now I understand your change and even if not completely right it might solve the issue for now

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: And I think it works

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
Thank you @mdrazak2001, interesting one

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts (hunk 1 above)
Comment (mdrazak2001) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:89]: Thank you @charlesBochet for the detailed explanation, am able to connect the dots now!
