### PR TITLE
preventing the last item to be unselected

### LINKED ISSUE #15867: [MORPH RELATIONS] - Cannot select destination objects anymore once all were uselected
## Bug Description
If you unselect all the possible destination objects, you can no longer access the UI to select one. 

Image

Image

Image

### PR DESCRIPTION
**Pull request by guillim**
Fix https://github.com/twentyhq/twenty/issues/15867

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/components/SettingsMorphRelationMultiSelect.tsx [hunk 1]
```diff
@@ -147,6 +147,9 @@ export const SettingsMorphRelationMultiSelect = ({
   const addOrRemoveFromArray = (array: string[], item: string) => {
     let newArray = new Set(array);
```
Comment (Devessier) [inline packages/twenty-front/src/modules/settings/components/SettingsMorphRelationMultiSelect.tsx:148]: nitpick: the variable is called `newArray` but it's not an array

**Review by Devessier — APPROVED** [review]
LGTM!
