### PR TITLE
Fix calendar events & messages fetching + fix timeline design

### LINKED ISSUE #9826: Update error message when message/calendar isn't shared
## Current behavior

Image

## Desired behavior

We should make it clear that this isn't really an error but just missing permissions

cc @Bonapara for input

### PR DESCRIPTION
**Pull request by etiennejouan**
Preview : 

Screenshot 2025-05-02 at 16 24 34

Done : 
- Fix getCalendarEventsFromPersonIds and getCalendarEventsFromCompanyId (include accountOwner check)
- Fix permission check on pre-hook - Pre-hook seems useless, calendar events are always on METADATA or SHARE_EVERYTHING visibility, else post hook always has the responsibility of returning the data user can access. >> To delete or to keep in case other visibility options are added ?
- Add post hook to secure finOne / findMany calendarEvents resolver
- Update design

To do :
- same on messages (PR to arrive)

closes : https://github.com/twentyhq/twenty/issues/9826

### CODE REVIEW

File: packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts [hunk 1]
```diff
@@ -183,7 +183,9 @@ export abstract class GraphqlQueryBaseResolverService<
         resultWithGettersArray,
       );
 
-      return resultWithGetters;
+      return Array.isArray(resultWithGetters)
```
Comment (etiennejouan) [inline packages/twenty-server/src/engine/api/graphql/graphql-query-runner/interfaces/base-resolver-service.ts:186]: @Weiko not satisfied of this, I use it as a patch to continue my issue.

executePostQueryHooks take resultWithGettersArray but base resolver returns resultWithGetters. Unfortunately, link between resultWithGetters and resultWithGettersArray is not kept: when updating resultWithGettersArray, resultWithGetters is not updated.

File: packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-many.post-query.hook.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    private readonly canReturnCalendarEventsService: CanReturnCalendarEventsService,
+  ) {}
+
+  async execute(
+    authContext: AuthContext,
+    _objectName: string,
+    payload: CalendarEventWorkspaceEntity[],
+  ): Promise<void> {
+    if (!authContext.workspaceMemberId) {
+      throw new BadRequestException('Workspace member id is required');
```
Comment (Weiko) [inline packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/calendar-event-find-many.post-query.hook.ts:28]: resolver hooks should throw graphql errors (UserInputError)

File: packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-return-calendar-events.service.ts [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+import { CalendarChannelEventAssociationWorkspaceEntity } from 'src/modules/calendar/common/standard-objects/calendar-channel-event-association.workspace-entity';
+import { CalendarChannelVisibility } from 'src/modules/calendar/common/standard-objects/calendar-channel.workspace-entity';
+import { CalendarEventWorkspaceEntity } from 'src/modules/calendar/common/standard-objects/calendar-event.workspace-entity';
+import { ConnectedAccountWorkspaceEntity } from 'src/modules/connected-account/standard-objects/connected-account.workspace-entity';
+
+@Injectable()
+export class CanReturnCalendarEventsService {
+  constructor(private readonly twentyORMManager: TwentyORMManager) {}
+
+  public async canReturnCalendarEvents(
```
Comment (Weiko) [inline packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-return-calendar-events.service.ts:17]: nit: the name does not imply that the payload will be modified and sounds like it's only validating input, maybe we can find a better name?

**Review by Weiko — APPROVED** [review]
LGTM, left a few comments @etiennejouan

File: packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-return-calendar-events.service.ts (hunk 3 above)
Comment (etiennejouan) [reply packages/twenty-server/src/modules/calendar/common/query-hooks/calendar-event/services/can-return-calendar-events.service.ts:17]: -> applyCalendarEventsVisibilityRestrictions
