### PR TITLE
fix billingCheckoutSession query param + enable redirect on workspace…

### LINKED ISSUE #668: Fix the Plan Urls params
# Current behavior

Can't use URL parameters like:
```
https://app.twenty.com/?billingCheckoutSessionState={"plan":"ENTERPRISE","interval":"Year","requirePaymentMethod":false}
```

System redirects to `app.twenty.com/welcome` and strips all parameters.

# Desired Behavior

URL parameters should be preserved during redirection or properly processed by the application.

Image

Image

- `Change plan` in the footer should redirect to twenty.com/pricing
- Don't forget `billed yearly` for yearly plan
- Rename the Enterprise plan to Organization plan

## Add new prices

_add a date in Stripe description to differentiate from existing pricing_

### Pro plan
- monthly -> 12$ per month 
- yearly -> 9$ per month billed yearly (108$)

### Organization plan
- monthly -> 25$ per month 
- yearly -> 19$ per month billed yearly (228$)

Image

### PR DESCRIPTION
**Pull request by etiennejouan**
… during onboarding

fixes : https://github.com/twentyhq/core-team-issues/issues/668

### CODE REVIEW

File: packages/twenty-front/src/modules/auth/components/Verify.tsx [hunk 1]
```diff
@@ -28,14 +34,16 @@ export const Verify = () => {
       });
     }
 
+    if (!clientConfigLoaded) return;
```
Comment (guillim) [inline packages/twenty-front/src/modules/auth/components/Verify.tsx:37]: as discussed this may cause a flash. to be changed to the SigninupLoading componennt

File: packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts [hunk 2]
```diff
@@ -8,14 +9,23 @@ export const useRedirectToWorkspaceDomain = () => {
...
     pathname?: string,
     searchParams?: Record<string, string | boolean>,
     target?: string,
   ) => {
     if (!isMultiWorkspaceEnabled) return;
-    redirect(buildWorkspaceUrl(baseUrl, pathname, searchParams), target);
+    redirect(
+      buildWorkspaceUrl(baseUrl, pathname, {
+        ...searchParams,
+        ...buildSearchParamsFromUrlSyncState(),
```
Comment (guillim) [inline packages/twenty-front/src/modules/domain-manager/hooks/useRedirectToWorkspaceDomain.ts:25]: make sure it works as expecrted (as we checked together)

File: packages/twenty-front/src/modules/domain-manager/hooks/useBuildSearchParamsFromUrlSyncState.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  const billingCheckoutSession = useRecoilValue(billingCheckoutSessionState);
+  const animateModal = useRecoilValue(animateModalState);
+
+  const buildSearchParamsFromUrlSyncState = () => {
+    return {
+      ...(billingCheckoutSession !== BILLING_CHECKOUT_SESSION_DEFAULT_VALUE
+        ? {
+            billingCheckoutSession: JSON.stringify(billingCheckoutSession),
+          }
+        : {}),
```
Comment (guillim) [inline packages/twenty-front/src/modules/domain-manager/hooks/useBuildSearchParamsFromUrlSyncState.ts:16]: We checked together that useRecoilCallback would fix this function

**Review by guillim — CHANGES_REQUESTED** [review]
see comments for changes

**Review by guillim — APPROVED** [review]
