### PR TITLE
Fix/csv import

### LINKED ISSUE #1338: [Timebox] Fix bugs on CSV Import

### PR DESCRIPTION
**Pull request by magrinj**
Fix some issues in csv import, and add support for mobile devices

### CODE REVIEW

File: front/src/modules/ui/dialog/components/Dialog.tsx [hunk 1]
```diff
@@ -86,6 +92,38 @@ export function Dialog({
     closed: { y: '50vh' },
   };
 
+  useHotkeys(
```
Comment (lucasbordeau) [inline front/src/modules/ui/dialog/components/Dialog.tsx:95]: Why not using useScopedHotkey ?

Comment (lucasbordeau) [reply front/src/modules/ui/dialog/components/Dialog.tsx:95]: We could use a DialogHotkeyScope that is set by usePreviousHotkeyScope and then we go back to previous scope on close.

Comment (magrinj) [reply front/src/modules/ui/dialog/components/Dialog.tsx]: @lucasbordeau done

**Review by lucasbordeau — APPROVED** [review]

**Review by charlesBochet — APPROVED** [review]
