### PR TITLE
fix - update error message and ease importable format for multi select

### LINKED ISSUE #14103: CSV Import Fails with Dropdown/Multi-Select Fields
**Description**
CSV import fails when mapping columns to dropdown or multi-select fields if the CSV contains option text labels (e.g., “In Progress”) instead of internal values. The error shown is generic and unhelpful. Even when the CSV contains the correct internal values (API labels from the Data Model in Settings → Advanced), the system only recognizes them if the CSV was previously exported from Twenty itself.

**Expected Result**

* Text labels should be matched to existing options during import, **or**
* A clear error should indicate that API labels are required.

**Actual Result**

* Imports fail for all mapped dropdown/multi-select fields unless the CSV was first exported from Twenty.
* Error message is vague and provides no guidance.

**Steps to Reproduce**

1. Create a custom dropdown/multi-select field (e.g., “Project Status”).
2. Add options (e.g., “Planning,” “Active,” “On Hold”).
3. Prepare a CSV with a column for “Project Status,” populated with the option text labels.
4. Import CSV, mapping the column to the field.
5. Observe the error.
6. Repeat using API labels from Settings → Data Model (Advanced). Import still fails unless CSV originated from Twenty export.

**User Impact**

* Users expect text labels to work and are forced to perform a confusing workaround (exporting data just to re-import).
* This adds unnecessary friction and makes bulk updates or migrations error-prone.

**Suggested Enhancement**

* Support text label matching during import, or at minimum accept valid API labels regardless of source.
* Optionally, auto-create missing values during import (similar to Monday.com).

### PR DESCRIPTION
**Pull request by etiennejouan**
- Add other string format ('option1,option2,..') for multi select import
- Update error message

closes : https://github.com/twentyhq/twenty/issues/14103

### CODE REVIEW

File: packages/twenty-front/src/modules/spreadsheet-import/utils/parseMultiSelectOptions.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { z } from 'zod';
+
+export const parseMultiSelectOptions = (value: unknown) => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/spreadsheet-import/utils/parseMultiSelectOptions.ts]: add "spreadsheet-import" in util naming

use parseJson existing util that will return null if it can't parse it

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/spreadsheet-import/utils/parseMultiSelectOptions.ts (hunk 1 above)
Comment (etiennejouan) [reply packages/twenty-front/src/modules/spreadsheet-import/utils/parseMultiSelectOptions.ts]: I expect an error if parsing fails, so I prefer keeping JSON.parse

File: packages/twenty-front/src/modules/spreadsheet-import/utils/spreadsheetImportParseMultiSelectOptions.ts [hunk 2]
```diff
@@ -0,0 +1,13 @@
+import { z } from 'zod';
+
+export const spreadsheetImportParseMultiSelectOptions = (value: unknown) => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/spreadsheet-import/utils/spreadsheetImportParseMultiSelectOptions.ts]: OrThrow
