### PR TITLE
Bug fixes batch

### LINKED ISSUE #16842: Can't stop running workflowRun
## Bug Description

I believe it used to be possible to stop a workflowRun in status in Running. Should be a straight forward fix unless this uncovers a specific race condition

### PR DESCRIPTION
**Pull request by thomtrp**
Fixes https://github.com/twentyhq/twenty/issues/18181

Fixes https://github.com/twentyhq/twenty/issues/16842
Iterators remain running, which prevent the stopping state to eventually become stopped

Fixes https://github.com/twentyhq/twenty/issues/18186

### CODE REVIEW

File: packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts [hunk 1]
```diff
@@ -218,17 +219,29 @@ export class WorkflowRunnerWorkspaceService {
...
+
       await this.workflowRunWorkspaceService.updateWorkflowRun({
         workflowRunId,
         workspaceId,
         partialUpdate: {
           status: WorkflowRunStatus.STOPPING,
+          state: {
+            ...workflowRun.state,
+            stepInfos: mergedStepInfos,
+          },
```
[the remark this answers is not in the document]
Comment (thomtrp) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts:244]: This is an acceptable behavior. Iterator will not update records so we prefer having it marked as stopped a bit earlier rather than keeping it running forever

File: packages/twenty-ui/src/components/chip/Chip.tsx [hunk 2]
```diff
@@ -197,7 +199,7 @@ export const Chip = ({
       maxWidth={maxWidth}
     >
       {leftComponent}
-      {!isLabelHidden && label && label.trim() ? (
+      {!isLabelHidden && isDefined(label) && isNonEmptyString(label) ? (
```
[the remark this answers is not in the document]
Comment (thomtrp) [reply packages/twenty-ui/src/components/chip/Chip.tsx:202]: that's intended

File: packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts [hunk 3]
```diff
@@ -218,17 +219,29 @@ export class WorkflowRunnerWorkspaceService {
...
-      workflowHasRunningSteps({
-        stepInfos: workflowRun.state.stepInfos,
-        steps: workflowRun.state.flow.steps,
-      })
-    ) {
+    const stepInfos = workflowRun.state.stepInfos;
+    const steps = workflowRun.state.flow.steps;
+
+    if (workflowHasRunningSteps({ stepInfos, steps })) {
+      const stoppedIteratorStepInfos = getStoppedIteratorStepInfos({
```
Comment (charlesBochet) [inline packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts]: naming improve: get means that we are not changing. Here we are mutating.
setAllIteratorsStepInfosAsStopped (is it really what we want btw?)

Comment (thomtrp) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts]: I renamed it but that's not a mutation yet, we are just building the infos.
That's what we want because current stoppage only works when there are no running steps left. But an iterator remain running until it has been called by its last iteration. Which will never happen if the iteration steps have been stopped.

Comment (charlesBochet) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts]: better still not happy with naming :p is the iterator the one stopping? I prefer: setAllIteratorsStepInfosAsStopped

Comment (charlesBochet) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workspace-services/workflow-runner.workspace-service.ts]: approving though, non blocking

**Review by charlesBochet — APPROVED** [review]
