### PR TITLE
fix IMAP breadcrumb

### LINKED ISSUE #13811: IMAP Feature Should Live in the User Level
## Bug Description
IMAP feature is currently located under User > Accounts. However, when we select "Connect Email Account" to access the IMAP feature the seems to be located under "Workspace". Not sure if this is just a front-end bug but it should live in the user level.
Image

## Expected behavior

Image

### PR DESCRIPTION
**Pull request by ehconitin**
closes https://github.com/twentyhq/twenty/issues/13811
figma - https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=72629-202079&t=CHbHe7QGamvPTnAi-0

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
LGTM (+ greptile comment) 👍

File: packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEditImapSmtpCaldavConnection.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ export const SettingsAccountsEditImapSmtpCaldavConnection = () => {
         title={t`Edit Email Account`}
         links={[
           {
-            children: t`Workspace`,
+            children: t`User`,
             href: getSettingsPath(SettingsPath.Workspace),
```
Comment (Weiko) [inline packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEditImapSmtpCaldavConnection.tsx]: Link should be changed too right?

Comment (ehconitin) [reply packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsEditImapSmtpCaldavConnection.tsx]: done! :)

**Review by Weiko — APPROVED** [review]

**Comment by ehconitin** [comment]
pushing some more changes -- lets wait on merge thankyou ;)

**Comment by ehconitin** [comment]
@greptileai trigger
