### PR TITLE
fixed button size

### LINKED ISSUE #2971: Back ton index button is no more square
# Current behavior

The button is not square:

Screenshot 2023-12-13 at 11 58 06

# Desired behavior

The button should be a 24px light icon button 

Screenshot 2023-12-13 at 11 58 58

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9901-34423&mode=design&t=pfE2hTyckvmdvs26-11

### PR DESCRIPTION
**Pull request by sumansahoo1**
Fix #2971

The width of the Title was set to 100% which I updated to adjust automatically with enabled and disabled back button. And set the size of buttons to 24px.

image

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx [hunk 1]
```diff
@@ -54,14 +54,23 @@ const StyledTitleContainer = styled.div`
...
+const StyledButtonDiv = styled.div`
+  align-items: center;
+  display: flex;
+  height: 24px;
+  justify-content: center;
   margin-right: ${({ theme }) => theme.spacing(1)};
+  width: 24px;
+`;
+const StyledBackIconButton = styled(IconButton)`
+  height: 24px;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx]: this actually looks unnecessary if you pass the right size to the IconButton (medium)

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx [hunk 2]
```diff
@@ -54,14 +54,23 @@ const StyledTitleContainer = styled.div`
   max-width: 50%;
 `;
 
-const StyledBackIconButton = styled(IconButton)`
+const StyledButtonDiv = styled.div`
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx]: I'm a bit confused why we would need a container here.
I'm taking a look!

**Review by charlesBochet — APPROVED** [review]
Thanks for the contribution! While taking a look at your PR, I have actually found ways to simplify a bit more, please take a look at the last commit.

Really appreciate the help, feel free to take any other good first issue!
