### PR TITLE
Field permission CRUD front-end implementation 

### LINKED ISSUE #1152: [FE] Add field permissions configuration
Let's add the field permission configuration layer!

[Figma](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=67064-202199&t=JQG66LoGsanwsami-0)

**Setup**
Feature flag to activate: `IS_FIELDS_PERMISSIONS_ENABLED` (Make sure to delete feature-flag-version and role-permissions-version keys in Redis for it to be taken into account)
Seed a field permission: e.g. update permission on Employee field on Company for Object-restricted role

**Specs**
0. On BE: enrich getRoles response
- getRoles should return fieldPermissions 

1. On role page: add existing field permissions display
Image

- add "See Fields" and "Edit fields" columns with values All / Some / None 

2. On object-level page: add field permission configuration section 
Image

- add See and Edit columns
- if the object is not editable, there should be no Edit column. The edit column should disappear as we tick off "Edit companies" from "Object-level permissions" section
- the field permission can only be restrictive: it can only be removed on a field if the role has the global permission on the object. E.g: permission to update "employee" field from Company can only be removed, and can be removed only if role has edition right on Company. 
- If read permission is removed, we should also remove update permission: (we should do the same behaviour as for objects):

https://github.com/user-attachments/assets/e3f78ee8-daf0-4c79-8b81-615b7143b8d6

- "Save" is performed after clicking "Finish" on object-level page then "Save" on role page (user is redirected to role page after clicking on "Finish" on object-level page). Save should call `upsertFieldPermissions` endpoint (from role.resolver). Field permission should only be saved if canUpdateFieldValue or canReadFieldValue is not null, unless it's a modification of an existing field permission: I can nullify an existing field permission if i want to cancel its effect (which would be the same as deleting it) but I cannot create a field permission if it has no effect. 
We actually need to update a bit of BE here to remove the EMPTY_FIELD_PERMISSION_NOT_ALLOWED exception thrown. Initially i thought we would want to delete the field permission in that case but it's ok to just nullify it.

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR implements what's needed to edit field permissions on a role.

Field permissions that aren't useful are kept in the database to avoid the overhead of adding cleaning logics both in front end and back end. They just won't be taken into account if object permission doesn't allow it.

In this PR we also handle the case were there's no object permission override but where there are only field permission overrides, which can happen if an object inherits from a "all object can read" but restricts read only on some fields.

image

image

Fixes https://github.com/twentyhq/core-team-issues/issues/1152

This PR lowers unit test coverage because the essential unit tests for this PR have been written and writing more tests would not be a great tradeoff for this feature which has already taken a lot of efforts.

### CODE REVIEW

**Review by ijreilly — COMMENTED** [review]
great job!!
Two issues that are linked: 
- when adding a field permission on an object that does not have any objectPermission yet, it creates an empty objectPermission. It shouldn't create an objectPermission at all
image

- if that objectPermission is missing, no row is added to Object-level section. Probably because it expects an objectPermission while it shouldn't

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useFilterObjectWithPermissionOverride.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    });
+
+  const filterObjectMetadataItemsWithPermissionOverride = useCallback(
+    (objectMetadataItem: ObjectMetadataItem) => {
+      const {
+        objectHasNoOverrideOnObjectPermission,
+        objectHasNoOverrideButFieldPermissionsShouldBeTakenIntoAccount,
+      } = getObjectPermissionDerivedStates(objectMetadataItem.id);
+
+      const shouldBeTaken =
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useFilterObjectWithPermissionOverride.ts]:
```suggestion
      const hasOverride =
```

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSeeFieldsValueForObject.tsx [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+  const { objectReadIsRestricted } = useObjectPermissionDerivedStates({
+    roleId,
+    objectMetadataItemId,
+  });
+
+  return (
+    <>
+      {objectReadIsRestricted
+        ? '-'
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/components/SettingsRolePermissionsObjectLevelSeeFieldsValueForObject.tsx:61]: @Bonapara, here it is suggested than when the read permission is restricted on an object because the object is not readable for the role, we display " - " under "See Fields". I feel "None" is more appropriate but Lucas didn't agree. what do you prefer ?

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableAllHeaderRow.tsx [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+      if (hasAnyRestrictionOnRead) {
+        for (const fieldPermissionToChange of fieldPermissionsForThisObject) {
+          upsertFieldPermissionInDraftRole({
+            ...fieldPermissionToChange,
+            canReadFieldValue: null,
+          });
+        }
+      } else {
+        if (fieldPermissionsForThisObject.length === 0) {
+          for (const fieldMetadataItem of restrictableFieldMetadataItems) {
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableAllHeaderRow.tsx]: what does this reflect?

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableAllHeaderRow.tsx [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+      if (hasAnyRestrictionOnUpdate) {
+        for (const fieldPermissionToChange of fieldPermissionsForThisObject) {
+          upsertFieldPermissionInDraftRole({
+            ...fieldPermissionToChange,
+            canUpdateFieldValue: null,
+            canReadFieldValue: null,
+          });
+        }
+      } else {
+        const shouldCreateUpdatePermissionForAllFields =
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/components/SettingsRolePermissionsObjectLevelObjectFieldPermissionTableAllHeaderRow.tsx]: sorry i have a hard time following, what does this represent?

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useGetObjectPermissionDerivedStates.ts [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+
+    const objectHasNoOverrideOnObjectPermission =
+      objectHasNoOverrideOnRead &&
+      objectHasNoOverrideOnUpdate &&
+      objectHasNoOverrideOnDelete &&
+      objectHasNoOverrideOnDestroy;
+
+    const objectReadIsRestricted =
+      (readIsRestrictedOnAllObjectsByDefault && objectHasNoOverrideOnRead) ||
+      (readIsAllowedOnAllObjectsByDefault && objectHasReadRevoked);
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/field-permissions/hooks/useGetObjectPermissionDerivedStates.ts]: I think `objectHasReadRevoked` involves `readIsAllowedOnAllObjectsByDefault`

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+    const isHigherPermission =
+      permissionKey === 'canUpdateObjectRecords' ||
+      permissionKey === 'canSoftDeleteObjectRecords' ||
+      permissionKey === 'canDestroyObjectRecords';
+
+    if (isHigherPermission && value !== false) {
+      newPermissions.canReadObjectRecords = value;
+    }
+
+    if (permissionKey === 'canReadObjectRecords' && !value) {
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts:37]: If value is undefined, do we need to set the "higher permissions" values to false ?

**Review by ijreilly — APPROVED** [review]
thank you x1000 !

File: packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts (hunk 6 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts:37]: I just took the existing code as is

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/settings/roles/role-permissions/object-level-permissions/hooks/useUpsertObjectPermission.ts:37]: I'm not sure that it's a good idea to start refactoring it since it works and that would involve a new QA effort, unless you think that it is not the good behavior right now.
