### PR TITLE
Fix transliteration for metadata + transliterate select options

### LINKED ISSUE #5403: [Transliteration] Cannot save a field, object, option with non-latin characters
## Bug Description

When inputting an object or field name with non-latin characters, save is disabled. 
When inputting an option name with non-latin characters, an error is thrown.

## Expected behavior

Names with non-latin characters should be savable and transliterated.

## Technical inputs

This is a regression for object and field name. A regex was probably introduced on the form validation. 
For the option it was not implemented, we need to add the same logic as for object and field.

### PR DESCRIPTION
**Pull request by ijreilly**
## Context 
Fixes #5403

Transliteration is now integrated to form validation through the schema. While it does not impede inputting an invalid value, it impedes submitting a form that will fail as the transliteration is not possible. Until then we were only performing the transliteration at save time in the front-end, but it's best to provide the information as soon as possible. Later we will add helpers to guide the user (eg "This name is not valid": https://github.com/twentyhq/twenty/issues/5428).

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/utils/getOptionValueFromLabel.ts [hunk 1]
```diff
@@ -1,15 +1,18 @@
 import snakeCase from 'lodash.snakecase';
 
+import { OPTION_VALUE_VALID_STRING_PATTERN } from '~/pages/settings/data-model/utils/constants.utils';
+import { formatLabelOrThrows } from '~/pages/settings/data-model/utils/format-label.util';
+
+export const transliterateLabel = (label: string) =>
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/utils/getOptionValueFromLabel.ts:6]: remove this function and only use formatLabelOrThrows

File: packages/twenty-front/src/pages/settings/data-model/utils/__tests__/constants.utils.test.ts [hunk 2]
```diff
@@ -0,0 +1,83 @@
+import {
+  METADATA_LABEL_VALID_STRING_PATTERN,
+  METADATA_NAME_VALID_STRING_PATTERN,
+  OPTION_VALUE_VALID_STRING_PATTERN,
+} from '~/pages/settings/data-model/utils/constants.utils';
+
+describe('METADATA_NAME_VALID_STRING_PATTERN', () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/settings/data-model/utils/__tests__/constants.utils.test.ts:7]: instead of testing regex, introduce computeMetadataNameFromLabelOrThrow(), computeSelectOptionValueOrThrow

computeMetadataNameFromLabelOrThrow = (string) => transliterateAndValidFormatOrThrow(string, VALID_PATTERN)

rename: formatLabelOrThrow(string, VALID_PATTERN) ==>  transliterateAndValidFormatOrThrow(string, VALID_PATTERN)

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-valid-graphql-enum-name.validator.ts [hunk 3]
```diff
@@ -4,7 +4,7 @@ import {
   ValidationArguments,
 } from 'class-validator';
 
-const graphQLEnumNameRegex = /^[_A-Za-z][_0-9A-Za-z]+$/;
+const graphQLEnumNameRegex = /^[_A-Za-z][_0-9A-Za-z]*$/;
```
Comment (ijreilly) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/validators/is-valid-graphql-enum-name.validator.ts:7]: @magrinj are you ok with this update? One-char long names are not an issue with graphql
