### PR TITLE
[groupBy] Fix order by nested date field

### LINKED ISSUE #1935: Ordering group-by results on relation date fields fails because backend doesn’t support granularity-aware order for relations
query:

Image

vars:

Image

error:

Image

### PR DESCRIPTION
**Pull request by ijreilly**
Fixes https://github.com/twentyhq/core-team-issues/issues/1935

### CODE REVIEW

File: packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-type-generators/input-types/order-by-input/object-metadata-order-by-base.generator.ts [hunk 1]
```diff
@@ -135,7 +136,7 @@ export class ObjectMetadataOrderByBaseGenerator {
         );
 
       if (!isDefined(orderByDateGranularityInputType)) {
-        throw new Error('OrderByDateGranularityInputType not found');
+        throw new Error('isForGroupByInputType not found');
```
Comment (Weiko) [inline packages/twenty-server/src/engine/api/graphql/workspace-schema-builder/graphql-type-generators/input-types/order-by-input/object-metadata-order-by-base.generator.ts]: is it expected? seems we are talking about orderByDateGranularityInputType (which is based on ORDER_BY_DATE_GRANULARITY_INPUT_KEY) but the log refers to isForGroupByInputType
@ijreilly

**Review by Weiko — APPROVED** [review]
LGTM
