### PR TITLE
fix: update dropdown width

### LINKED ISSUE #1891: Update the width of the Dropdown component when it's a DatePicker
## Scope & Context

Follows https://github.com/twentyhq/twenty/pull/1877#issuecomment-1749030983

Right now, we have a bug on the Table > Filter > Created_at filter where the dropdown is not large enough to fit the date picker.
image

1) We want to update the width of the Dropdown component based on its width props, but also we want to provide a hook API to update it programmatically later.
2) We want MultipleFiltersDropdownFilter to use this capability to set the dropdown width based on filter type

We don't want the dropdown to fit its content as we don't want the content to dictate the dropdown width by default, this should be case by case and that's why we need to expose a hook. In different cases, we want to enforce the dropdown width (example, we want filter dropdown to be 160px, but on the board, we want the Add new to be 200px)

## Technical inputs

Part 1: Dropdown component
- introduce a recoil state to store the dropdown width
- Create a `DropdownOnWidthChangeEffect` which contains a  useEffect that listens to the width props to store it in a state
- add { width, setWidth} to `useDropdown()` to modify the width of the component from outside of it
- Rename `DropdownEffect` to `DropdownOnToggleEffect`

Part2: MultipleFiltersDropdownFilter
- Also add MultipleFiltersDropdownFilterOnFilterChangedEffect to front/src/modules/ui/view-bar/components/MultipleFiltersDropdownContent.tsx . 
- this useEffect will listen to filterDefinitionUsedInDropdown.type and use dropdown setWidth to update the width

### PR DESCRIPTION
**Pull request by alfredlouisw8**
fixes: #1891 

any feedback about the code is appreciated :)

### CODE REVIEW

File: front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx [hunk 1]
```diff
@@ -34,8 +38,10 @@ export const MultipleFiltersDropdownContent = () => {
     ViewBarRecoilScopeContext,
   );
 
+  const dropdownWidth = useRecoilValue(dropdownWidthState);
+
   return (
-    <StyledDropdownMenu>
+    <StyledDropdownMenu width={dropdownWidth}>
```
Comment (charlesBochet) [inline front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx:44]: This has been renamed as DropdownMenu, could you rebase your PR on main?

**Review by charlesBochet — COMMENTED** [review]
Thank you! That's it! Could you rebase on main?

File: front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx (hunk 1 above)
Comment (alfredlouisw8) [reply front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownContent.tsx]: yes, i've rebased my pr

File: front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import { useRecoilState } from 'recoil';
+
+import { dropdownWidthState } from '@/ui/layout/dropdown/states/dropdownWidthState';
+
+export const MultipleFiltersDropdownFilterOnFilterChangedEffect = ({
+  filterDefinitionUsedInDropdownType,
+}: {
+  filterDefinitionUsedInDropdownType: string | undefined;
+}) => {
+  const [, setDropdownWidth] = useRecoilState(dropdownWidthState);
```
Comment (charlesBochet) [inline front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx:11]: so we would like this setDropdownWidth to be part of the external API of Dropdown.
Here, the developer has to know about dropdownWidthState which we want to avoid.

Could you:
- 1) add dropdownWidth getter and setter to useDropdownStates hook (this is our internal API but it makes sure to feed the state with the right "scopeId". You will find example in the code, your dropdown WidthState also needs to be refactored. The goal is to allow multiple dropdown with their own scoped state on the same page
- 2) expose this getter and setter through useDropdown (this is our external API)

File: front/src/modules/ui/layout/dropdown/states/dropdownWidthState.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
+import { atom } from 'recoil';
+
+export const dropdownWidthState = atom<number | undefined>({
```
Comment (charlesBochet) [inline front/src/modules/ui/layout/dropdown/states/dropdownWidthState.ts:3]: see my comment above, you will need to use a scopedState here

File: front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownButton.tsx [hunk 4]
```diff
@@ -14,13 +17,15 @@ type MultipleFiltersDropdownButtonProps = {
 export const MultipleFiltersDropdownButton = ({
   hotkeyScope,
 }: MultipleFiltersDropdownButtonProps) => {
+  const dropdownWidth = useRecoilValue(dropdownWidthState);
```
Comment (charlesBochet) [inline front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownButton.tsx:20]: I think we would prefer the other way around. We do not get dropdownWidth and pass it as a props to Dropdown here.
Instead:
- we don't pass it (or we pass an initialization value ; as we already have a default in Dropdown, we don't actually need to pass anything).
- from the inside of Dropdown, we listen to dropdownWidthState for changes.

We will need to introduce a DropdownOnWidthChangeEffect very similar to DropdownOnToggleEffect

File: front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx [hunk 5]
```diff
@@ -0,0 +1,24 @@
+import { useEffect } from 'react';
+import { useRecoilState } from 'recoil';
+
+import { dropdownWidthState } from '@/ui/layout/dropdown/states/dropdownWidthState';
+
+export const MultipleFiltersDropdownFilterOnFilterChangedEffect = ({
```
Comment (charlesBochet) [inline front/src/modules/ui/data/view-bar/components/MultipleFiltersDropdownFilterOnFilterChangedEffect.tsx:6]: yes!

**Review by charlesBochet — COMMENTED** [review]
Left a few comments on how we want to architecture the interactions between the components

**Comment by alfredlouisw8** [comment]
I've updated the PR, kindly review again :)

**Review by charlesBochet — APPROVED** [review]
LGTM thank you!
