### PR TITLE
fix: flickering when updating relation counts

### LINKED ISSUE #11853: Updating 1:N relations results in weird animation
**Scenario:**
1. Log in
2. Go to any tab (e.g. People)
3. Open record 
4. Update 1:N relation

**Actual:** Weird animation happens when updating the relation

https://github.com/user-attachments/assets/16a53b97-57dc-4e25-ab39-33330c5eb4a9

**Expected:** Smooth animation should appear

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
https://github.com/user-attachments/assets/f5a87f1d-7c9f-4351-b43a-8b9b47715f94

Closes #11853

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ export const RecordDetailRelationSection = ({
     isRecordReadOnly,
   });
 
-  if (loading || aggregateLoading || isFieldReadOnly) return null;
+  if (loading || isFieldReadOnly) return null;
 
   const relationRecordsCount = relationAggregateResult?.id?.COUNT ?? 0;
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx:128]: Maybe instead of showing 0 we can just not show (${relationRecordsCount}) if it's loading? So we'd keep your change but add a more granular check instead within the component

Thanks again for all your contributions @abdulrahmancodes!

**Comment by FelixMalfait** [comment]
+ could you please fix lint? (`npx nx lint twenty-front --fix`) 
Thank you!

File: packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx (hunk 1 above)
Comment (abdulrahmancodes) [reply packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx:128]: @FelixMalfait  That logic is already in place. We only show (${relationRecordsCount}) when the count is greater than 0, so 0 is never displayed.

Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx:127]: You're right I missed this! Thanks

**Review by FelixMalfait — APPROVED** [review]
Thank you!
