### PR TITLE
fixed: Links in note preview not visible #16043

### LINKED ISSUE #16043: Links in note preview not visible
## Scope & Context

Visibilty of note content 

## Current behavior

- Create a link inside a note
- Inside company/people view, the link is not shown in preview
- Open note
- Link is shown

Image

Image

## Expected behavior

- Link like any content of a note should be visible in preview

### PR DESCRIPTION
**Pull request by piyush-rj**
This PR fixes an issue where links added inside a note were not appearing in the preview shown under Company -> Notes. The link would only appear after opening the note, which led to inconsistent behavior.

Issue:
Blocknote represents text and links using different node types:
1. { "type": "text", "text": "Welcome to this demo!" }
2. {
  "type": "link",
  "content": { "type": "text", "text": "Example" },
  "href": "https://example.com"
}

The existing preview function only handled plain text nodes and completely ignored link nodes.
As a result:
- Links did not appear in the preview
- Links appeared only inside the full note view

Steps to Reproduce:
- Add a link inside a note
- Go to Company / People and view the note preview -> the link is missing
- Open the note -> the link appears correctly

How I fixed it:
- A new recursive text extraction function (extractText) was added to correctly read.
- Text nodes
- Link nodes (including inner content and the href)
- Nested child content
- Link previews now appear in the following format:
DisplayText (https://example.com)

Edit : closes https://github.com/twentyhq/twenty/issues/16043

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts [hunk 1]
```diff
@@ -1,16 +1,56 @@
-// TODO: merge with getFirstNonEmptyLineOfRichText (and one duplicate I saw and also added a note on)
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts:1]: Rem : Not sure we can remove this TODO

File: packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts [hunk 2]
```diff
@@ -1,16 +1,56 @@
...
+// Basic Rich-Text Node Types
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts]: nit : We avoid comment (in Twenty codebase). If you want to specify what is BaseNode, do not hesitate to be verbose :)

File: packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts [hunk 3]
```diff
@@ -1,16 +1,56 @@
...
+export interface BaseNode {
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts]: nit : Do not export these type if they are not used elsewhere. And if in future, they are used in an other file, export them from their own file

File: packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts [hunk 4]
```diff
@@ -1,16 +1,56 @@
...
+  const noteBody: RichTextNode[] = activityBody
+    ? JSON.parse(activityBody)
+    : [];
+
+  const extractText = (node: RichTextNode | undefined | null): string => {
+    if (!node) return '';
+
+    switch (node.type) {
+      case 'text':
+        return (node as TextNode).text ?? '';
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts]: nit : I prefer using type guard to avoid casting - not  very useful here but good habit to take

File: packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts [hunk 5]
```diff
@@ -1,16 +1,56 @@
...
+
+      case 'link': {
+        const linkNode = node as LinkNode;
+        const innerText = (linkNode.content ?? [])
+          .map(child => extractText(child))
+          .join('');
+        const href = linkNode.href ?? '';
+        return href ? `${innerText} (${href})` : innerText;
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/activities/utils/getActivityPreview.ts]: I think we don't want to preview href as we don't see it in editor view

**Review by etiennejouan — APPROVED** [review]
Hi @piyush-rj, congrats for your first PR !! 👏 
Good job, I took the liberty of updating the PR as it is small update.

Thank you for your contribution 🙏 
Please, do not hesitate to tackle other issues.
