### PR TITLE
fix: Use namePlural instead of labelPlural for favorite view URLs

### LINKED ISSUE #11404: Favourite views in non-English return error
**Scenario:**
1. Log in
2. Go to Settings > Experience and change language to any language other than English (e.g. Pseudo-English)
3. Go back to main page
4. Click view dropdown and add any view to favorites
5. Click favorite view

**Actual:** UI returns error

Image

**Expected:** UI must show favorite view

### PR DESCRIPTION
**Pull request by ehconitin**
closes #11404

Used `namePlural` instead of `labelPlural` for generating favorite view URLs to ensure proper routing across all languages.

### CODE REVIEW

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export const sortFavorites = (
           labelIdentifier: view?.name,
           link: getAppPath(
             AppPath.RecordIndexPage,
-            { objectNamePlural: labelPlural.toLowerCase() },
+            { objectNamePlural: namePlural.toLowerCase() },
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:57]: Probably no need for toLowerCase?

Comment (ehconitin) [reply packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:57]: ah yes `objectMetadataItemSchema` already makes sure it's in camelCase, nice catch!

**Review by FelixMalfait — APPROVED** [review]
