### PR TITLE
Fix: Bug with auto scroll

### LINKED ISSUE #1564: Bug with auto scroll
https://github.com/twentyhq/twenty/assets/26528466/8845c3ae-3587-47da-8f7d-72ecf581818f

If we have a soft focus on a cell, it will auto scroll every time we try to scroll vertically. 

This is problematic because we only want the table to auto scroll when we move the soft focus with the keyboard.

We should find a way to auto scroll only when moving the soft focus, and no other case.

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #1564

### CODE REVIEW

**Review by thaisguigon — APPROVED** [review]

File: front/src/modules/ui/table/editable-cell/components/EditableCellSoftFocusMode.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ export function EditableCellSoftFocusMode({ children }: OwnProps) {
 
   useEffect(() => {
     scrollRef.current?.scrollIntoView({ block: 'nearest' });
-  });
+  }, []);
```
Comment (lucasbordeau) [inline front/src/modules/ui/table/editable-cell/components/EditableCellSoftFocusMode.tsx:20]: Haha nice

**Review by lucasbordeau — APPROVED** [review]

File: front/src/modules/ui/table/editable-cell/components/EditableCellSoftFocusMode.tsx (hunk 1 above)
Comment (gitstart-twenty) [reply front/src/modules/ui/table/editable-cell/components/EditableCellSoftFocusMode.tsx:20]: Haha 😆
