### PR TITLE
Fix : #8825 If attachment token expires, it throws a 500 error instead of Unauthenticated

### LINKED ISSUE #8825: If attachment token expires, it throws a 500 error instead of Unauthenticated
## Bug Description

If attachment token expires, it throws a 500 error instead of Unauthenticated (http://localhost:3000/files/attachment/6e007a40-8da7-442a-a206-1de7a04a087f.png?token=xxx)

## Expected behavior

I would expect an unauthenticated error or something more descriptive to distinguish from unexpected server errors.

### PR DESCRIPTION
**Pull request by munch-lax**
Fixes #8825

FilePathGuard implements token verification via verifyWorkspaceToken function which throws AuthException error , 
since CanActivate expects a boolean value , we add a try catch while verifying the token 

if token is invalid/expired 
Screenshot 2024-12-12 at 9 44 58 PM
else 
Screenshot 2024-12-12 at 9 47 10 PM

### CODE REVIEW

File: packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts [hunk 1]
```diff
@@ -15,20 +16,31 @@ export class FilePathGuard implements CanActivate {
...
     const request = context.switchToHttp().getRequest();
     const query = request.query;
-
+    
     if (!query || !query['token']) {
       return false;
     }
-
-    const payload = await this.jwtWrapperService.verifyWorkspaceToken(
+    let payload:any ={}
```
[the remark this answers is not in the document]
Comment (charlesBochet) [reply packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts:23]: Please check run your linter: npx nx run twenty-server:lint

File: packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts [hunk 2]
```diff
@@ -15,20 +16,31 @@ export class FilePathGuard implements CanActivate {
...
       query['token'],
       'FILE',
-    );
-
+    )
+  }catch (error) {
+    if(error instanceof AuthException && error.code === AuthExceptionCode.UNAUTHENTICATED ){
+      return false
+    }
+    else{
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts:33]: no need for else as you are already returning

if (error instance of...) {
return
}

throw ...

Comment (charlesBochet) [reply packages/twenty-server/src/engine/core-modules/file/guards/file-path-guard.ts:33]: actually forget about this comment as I think we should have another strategy :)

**Review by charlesBochet — CHANGES_REQUESTED** [review]
Hi @munch-lax thanks for the PR. We would like to follow another strategy here:
1) Create a FileAPIExceptionFilter (similar to AuthRestApiExceptionFilter) this filter should be able to handle the AuthException (with  AuthExceptionCode.UNAUTHENTICATED)
2) use it on top of the file.controller.ts (see GoogleAPIsAuthController as an example)

Now the exception that is thrown in the file-path-guard will be properly handled.

**Comment by munch-lax** [comment]
Hey @charlesBochet do we need to return the error in the same format that is by using handleExceptionService.handleError ?

**Comment by charlesBochet** [comment]
It should be very similar to AuthRestApiExceptionFilter :) so same output format

File: packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts [hunk 3]
```diff
@@ -1,4 +1,12 @@
-import { Controller, Get, Param, Req, Res, UseGuards } from '@nestjs/common';
+import {
+  Controller,
+  Get,
+  Param,
+  Req,
+  Res,
+  UseFilters,
+  UseGuards,
+} from '@nestjs/common';
```
Comment (Ritzrawal) [inline packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts:9]:
```suggestion
import {
  Get,
  Req,
  Res,
  Param,
  UseGuards,
  Controller,
  UseFilters,
} from '@nestjs/common';
```

i think arranging in this pattern make it easier to reviewing the code  and helps to increase the code quality its just a suggestion

**Review by Ritzrawal — CHANGES_REQUESTED** [review]

File: packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts (hunk 3 above)
Comment (FelixMalfait) [reply packages/twenty-server/src/engine/core-modules/file/controllers/file.controller.ts:9]: The sorting should be done automatically via Linter rules :) (alphabetically, not by length)

**Comment by FelixMalfait** [comment]
Thanks! Let's keep unauthenticated as a 403 for now to stay consistent with the rest of the codebase but I created a followup issue here https://github.com/twentyhq/twenty/issues/9347

**Comment by FelixMalfait** [comment]
There's another issue with our current code which I'll fix (not linked to your PR). We've implemented a second notion of "expirationDate" just for the file service. The expiry is something JWT handle natively well and we should rely on the JWT expiry instead of introducing a second expirationDate. With the current code the file expiration date would be the lowest of the default token expiration date and the file token expiration date which doesn't make sense.

**Review by FelixMalfait — APPROVED** [review]
Good for me! But I'll let you check again before @charlesBochet since it can affect security

**Comment by charlesBochet** [comment]
I'm back from holidays, I'm taking a look

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
Thank you @munch-lax :) I've moved your code to a different location (file.exception.ts instead of auth.exception.ts and same for the filter)
