### PR TITLE
Fix infinite loop on FE

### LINKED ISSUE #15369: Tab crashes on custom object with no record view creation
Reproduction:
- create object ( here bug )
- create field text ( here www )
- exit settings
- navigate to bug view
- create a view ( here table prastoin )
- tab crashes. ~~`findManyBugs` infinite loops~~ server seems to send back a response might be an infinite loop front side

Video [here](https://github.com/twentyhq/private-issues/issues/334)

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes https://github.com/twentyhq/twenty/issues/15369

It's the first time we are hitting this weird behavior on apollo onCompleted / onError. Theoretically if the reference of the onCompleted (resp onError) callback is changing, this will trigger a re-run of onCompleted. But also theretically the reference here is a recoilCallback so should never change.

As this is synchronous I have move this logic to a sync way

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts [hunk 1]
```diff
@@ -126,6 +124,13 @@ export const useLazyFindManyRecords = <T extends ObjectRecord = ObjectRecord>({
         }
 
         const result = await findManyRecords();
+        if (isDefined(result?.error)) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts:127]: ***Question:*** Couldn't both be defined ? Also what if none are

**Review by prastoin — COMMENTED** [review]
Nice catch ! thanks for investigating that
Could this be applicable somewhere else in the app ?

File: packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts (hunk 1 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecords.ts:127]: I haven't actually tested the behavior with error, I can revisit that!

**Review by prastoin — APPROVED** [review]
