### PR TITLE
fix: navigate with arrow keys in select/multi-select

### LINKED ISSUE #4977: I should be able to navigate with arrow keys in select/multi-select
I noticed we broke the ability to navigate with up/down arrow keys on Select / Multi-select fields.

### PR DESCRIPTION
**Pull request by AdityaPimpalkar**
closes: #4977

https://github.com/twentyhq/twenty/assets/13139771/8121814c-9a8a-4a8d-9290-1aebe145220f

### CODE REVIEW

**Comment by lucasbordeau** [comment]
- Enter should select the hovered item, here it opens a drawer.
- We should fix it for multi select also in task relations for example

**Comment by charlesBochet** [comment]
@AdityaPimpalkar any update on this one?

**Comment by FelixMalfait** [comment]
Great work! It's already much better than the status quo and could be merged like this already

But two comments sent on Discord:
```
https://github.com/twentyhq/twenty/pull/5983/files in this PR how hard would it be to include "No company" / "Add new" into the arrow navigation? It feels a bit off that it isn't possible
I feel like we keep the selected field position from one row to another which is a bit weird, the selected item position should come back to the field's value when you open a field no?
```

If we fix this we would have a really really nice experience

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx [hunk 1]
```diff
@@ -49,88 +53,163 @@ export const SingleEntitySelectMenuItems = ({
...
+      }
+    : null;
+
+  const entitiesInDropdown = [
+    selectAll,
+    selectNone,
+    selectedEntity,
+    ...entitiesToSelect,
+    createNewRecord,
+  ].filter(
```
Comment (AdityaPimpalkar) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx:90]: Making the `Add New`, `Select All`, `Select none` buttons as a part of dropdown entities since the `SelectableList` keys operate on ids. Open to suggestions if we can do it better :)

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx [hunk 2]
```diff
@@ -63,6 +65,10 @@ export const Dropdown = ({
 
   const { isDropdownOpen, toggleDropdown, closeDropdown, dropdownWidth } =
     useDropdown(dropdownId);
+
+  const { handleResetSelectedPosition } = useSelectableList(
+    SINGLE_ENTITY_SELECT_BASE_LIST,
+  );
```
Comment (AdityaPimpalkar) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/Dropdown.tsx:71]: I'm not sure if this is a good idea to include this selectable list hook here, I had to do this because in `RecordDetailRelationSection`, we use `Dropdown` which already has a `KeyPress.Escape` handler, but we also use  `SingleEntitySelectMenuItemsWithSearch` as dropdownComponents which also has has a `KeyPress.Escape` handler. 

Not sure what I can do here, any suggestions are welcome 👍

**Comment by FelixMalfait** [comment]
Hey, it now works great for no company/add new company! But I think that broke the select/multi-select, they don't work for me anymore (I can't navigate with arrow keys at all). Do they work for you?

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx (hunk 1 above)
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx:90]: It's not the prettiest but that's an acceptable hack imo!

**Comment by AdityaPimpalkar** [comment]
https://github.com/user-attachments/assets/e73ef183-cf81-4c89-92ff-c03d084c99c5

It seems to working just fine?

**Comment by FelixMalfait** [comment]
Thanks @AdityaPimpalkar!
It seems multi-select has been fixed but select is still broken for me, are you sure it's not for you? Try in table view with stage field for example
Screenshot 2024-07-16 at 09 57 35

**Comment by AdityaPimpalkar** [comment]
Ahh yes! fixed it 👍

**Comment by FelixMalfait** [comment]
Great work! 

Imo we can merge it as it's already a big improvement (cc @charlesBochet leaving it to you to merge), but I still have an issue when trying to navigate with arrow keys and select "No stage" with the enter key it doesn't work

Screenshot 2024-07-16 at 18 42 45

**Comment by AdityaPimpalkar** [comment]
I think its because stage is a non-nullable field. So technically, we shouldn't be able to select a "No stage" option. Checking for isNullable of field metadata solves this 👍

**Comment by lucasbordeau** [comment]
@AdityaPimpalkar Could you maybe see if you can help on https://github.com/twentyhq/twenty/pull/6248 which is very close to what you're doing here.

**Comment by FelixMalfait** [comment]
@lucasbordeau could we merge this? It's way better than the current behavior which is broken. If you don't see any issue with code quality I think we should merge

**Comment by lucasbordeau** [comment]
@FelixMalfait I plan to work on this and another related PR in the following days.

File: packages/twenty-front/src/modules/object-record/relation-picker/components/MultiRecordSelect.tsx [hunk 3]
```diff
@@ -62,6 +69,21 @@ export const MultiRecordSelect = ({
     leading: true,
   });
 
+  useEffect(() => {
+    setHotkeyScope(relationPickerScopedId);
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/MultiRecordSelect.tsx:73]: Not the right way to do it we have a util

File: packages/twenty-front/src/modules/object-record/relation-picker/components/MultiRecordSelect.tsx [hunk 4]
```diff
@@ -97,14 +119,21 @@ export const MultiRecordSelect = ({
               <SelectableList
                 selectableListId={MULTI_OBJECT_RECORD_SELECT_SELECTABLE_LIST_ID}
                 selectableItemIdArray={objectRecordsIdsMultiSelect}
-                hotkeyScope={RelationPickerHotkeyScope.RelationPicker}
+                hotkeyScope={relationPickerScopedId}
+                onEnter={(selectedId) => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/MultiRecordSelect.tsx:123]: Not sure of this pattern

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx [hunk 5]
```diff
@@ -49,88 +53,164 @@ export const SingleEntitySelectMenuItems = ({
...
     (entity): entity is EntityForSelect =>
       isDefined(entity) && isNonEmptyString(entity.name),
   );
 
+  const { isSelectedItemIdSelector, handleResetSelectedPosition } =
+    useSelectableList(SINGLE_ENTITY_SELECT_BASE_LIST);
+
+  const isSelectedAddNewButton = useRecoilValue(
+    isSelectedItemIdSelector('add-new'),
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx:99]: Review those states

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx [hunk 6]
```diff
@@ -49,88 +53,164 @@ export const SingleEntitySelectMenuItems = ({
...
+                        onClick={() => onEntitySelected()}
+                        LeftIcon={EmptyIcon}
+                        text={emptyLabel}
+                        selected={!selectedEntity}
+                        hovered={isSelectedSelectNoneButton}
+                      />
+                    )
+                  );
+                }
+                case 'select-all': {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItems.tsx:186]: Review this

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
See https://github.com/twentyhq/twenty/issues/6698 for comments
