### PR TITLE
8304 - Fix Action Menu Buttons Alignment

### LINKED ISSUE #8304: Action menu buttons alignment
## Bug Description
@Bonapara 
Unnecessary gap after more button
**Example:** 

https://github.com/user-attachments/assets/e583f285-8a9b-41dc-b867-8fa0dc85f9a5

## Expected behavior

https://github.com/user-attachments/assets/07de86dc-13bf-4e0d-bdf2-0535f28eb605

### PR DESCRIPTION
**Pull request by bosiraphael**
Closes #8304

The position of the modal container wasn't absolute, so the gap was also applied after the `ShowPageMoreButton`

### CODE REVIEW

File: packages/twenty-front/src/modules/action-menu/components/ActionMenuConfirmationModals.tsx [hunk 1]
```diff
@@ -1,18 +1,23 @@
 import { actionMenuEntriesComponentSelector } from '@/action-menu/states/actionMenuEntriesComponentSelector';
 import { useRecoilComponentValueV2 } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentValueV2';
+import styled from '@emotion/styled';
+
+const StyledActionMenuConfirmationModals = styled.div`
+  position: absolute;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/action-menu/components/ActionMenuConfirmationModals.tsx:6]: display: none

**Review by charlesBochet — APPROVED** [review]
