### PR TITLE
Fixed single record picker missing dropdown separator

### LINKED ISSUE #12665: Missing dropdown separator with empty state in single record picker
Problem : 

Image

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes a missing dropdown menu separator when no result found in a single record picker.

Before : 

image 

After : 

image

Fixes https://github.com/twentyhq/twenty/issues/12665

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItemsWithSearch.tsx [hunk 1]
```diff
@@ -122,9 +122,7 @@ export const SingleRecordPickerMenuItemsWithSearch = ({
               onRecordSelected,
             }}
           />
-          {records.recordsToSelect.length > 0 && isDefined(onCreate) && (
-            <DropdownMenuSeparator />
-          )}
+          {isDefined(onCreate) && <DropdownMenuSeparator />}
           {isDefined(onCreate) && hasObjectUpdatePermissions && (
             <DropdownMenuItemsContainer scrollable={false}>
               {createNewButton}
```
Comment (Devessier) [inline packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItemsWithSearch.tsx]: Would it make sense always to render the separator when the createNewButton is?

```suggestion
          {isDefined(onCreate) && hasObjectUpdatePermissions && (
            <>
              <DropdownMenuSeparator />
              <DropdownMenuItemsContainer scrollable={false}>
                {createNewButton}
```

If `hasObjectUpdatePermissions` is `false`, we would render a separator but no button below. I didn't test, but I assume it might cause issues.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItemsWithSearch.tsx]: Yes I'll test

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItemsWithSearch.tsx]: Indeed, I fixed it

**Comment by lucasbordeau** [comment]
@Devessier Also fixed for search bar on bottom

**Comment by Devessier** [comment]
Great! Checking.

**Review by Devessier — APPROVED** [review]
Makes sense! It's good for me.
