### PR TITLE
fix(): several ui improvements

### LINKED ISSUE #10531: Too short background in Security subpages
**Scenario:**
1. Log in
2. Go to Settings > Security > SSO Identity Provider or Approved Access Domain

**Actual:** Background of those pages isn't extended to whole height of page

Image

**Expected:** Background of those pages must be extended to whole height of page like other pages

Image

### PR DESCRIPTION
**Pull request by AMoreaux**
Close #10531

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/page/components/PageBody.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ const StyledMainContainer = styled.div`
   padding-right: ${({ theme }) => theme.spacing(3)};
   padding-left: 0;
   width: 100%;
+  height: 100%;
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/ui/layout/page/components/PageBody.tsx:25]: Let's not modify PageBody to fix a problem for settings because it is used everywhere and the side effects will be hard to predict

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/layout/page/components/PageBody.tsx:25]: Especially since we spent a lot of time adjusting the global app layout and this particular CSS configuration might be the result of it.

File: packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainEffect.tsx [hunk 2]
```diff
@@ -1,48 +1,14 @@
...
-      pollIntervalFn = setInterval(checkCustomDomainValidRecordsPolling, 6000);
-    }
-
-    return () => {
-      if (isDefined(pollIntervalFn)) {
-        clearInterval(pollIntervalFn);
-      }
-    };
-  }, [checkCustomDomainValidRecordsPolling, currentWorkspace?.customDomain]);
+    checkCustomDomainRecords();
```
Comment (lucasbordeau) [inline packages/twenty-front/src/pages/settings/workspace/SettingsCustomDomainEffect.tsx:8]: If it only has to be run once, let's use a state instead of relying on a useEffect which is unpredictable on the long run and opens the door to future nasty side effects.

A simple atom like isCustomDomainChecked is ok

File: packages/twenty-front/src/pages/settings/workspace/hooks/useCheckCustomDomainValidRecords.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+  const setCustomDomainRecords = useSetRecoilState(customDomainRecordsState);
+
+  const checkCustomDomainRecords = () => {
+    setCustomDomainRecords((currentState) => ({
+      ...currentState,
+      loading: true,
+    }));
+    checkCustomDomainValidRecords({
+      onCompleted: (data) => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/pages/settings/workspace/hooks/useCheckCustomDomainValidRecords.ts:18]: onCompleted won't be executed on sub sequent calls, it is only executed on the first request, are you sure that's what you want ? If not it would be better to use a useEffect with a boolean state to know if that's already done.

Comment (AMoreaux) [reply packages/twenty-front/src/pages/settings/workspace/hooks/useCheckCustomDomainValidRecords.ts:18]: Why won't it be executed on subsequent calls?
It is executed when the page is loaded and when the user clicks the refresh button.

Comment (lucasbordeau) [reply packages/twenty-front/src/pages/settings/workspace/hooks/useCheckCustomDomainValidRecords.ts:18]: https://github.com/apollographql/react-apollo/issues/3709

**Review by lucasbordeau — APPROVED** [review]
