### PR TITLE
Fix sync statuses on the fe

### LINKED ISSUE #6685: Add messaging sync Status on the FE
## Scope & Context

We would like to display Connected Account sync status on the Settings UI:
image

See Figma here: https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34844-84769&t=EmToUlIDemK21HZA-0

In database, we have a syncStatus on the related calendarChannel (cC) and messagingChannel (mC). Here should be the logic to compute connectedAccount status:
- mCSyncStatus = 'ACTIVE' && cCSyncStatus = 'ACTIVE' ==> Synced
- mCSyncStatus = 'NOT_SYNCED' && cCSyncStatus = 'NOT_SYNCED' => Not synced
- if mCSyncStatus = 'NOT_SYNCED' ignore it in the upcoming conditions (same for cCSyncStatus = 'NOT_SYNCED' case)

- mCSyncStatus = 'ONGOING' || cCSyncStatus = 'ONGOING' ==> Importing
- mCSyncStatus = 'FAILED' or 'FAILED_INSUFFICIENT_PERMISSIONS' || cCSyncStatus = 'FAILED' or 'FAILED_INSUFFICIENT_PERMISSIONS' ==> Failed

### PR DESCRIPTION
**Pull request by bosiraphael**
Follows #6685

### CODE REVIEW

File: packages/twenty-front/src/modules/accounts/types/CalendarChannel.ts [hunk 1]
```diff
@@ -1,11 +1,39 @@
 import { CalendarChannelVisibility } from '~/generated/graphql';
 
+export enum CalendarChannelSyncStatus {
+  NOT_SYNCED = 'NOT_SYNCED',
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/accounts/types/CalendarChannel.ts:4]: don't we have these in the graphql codegen?

File: packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsRowRightContainer.tsx [hunk 2]
```diff
@@ -15,39 +16,26 @@ export const SettingsAccountsConnectedAccountsRowRightContainer = ({
...
-  }, [mCSyncStatus, cCSyncStatus]);
+  const status = computeSyncStatus(
+    messageChannelSyncStatus,
+    calendarChannelSyncStatus,
+  );
 
   return (
     <StyledRowRightContainer>
-      {status === 'Failed' && (
+      {status === SyncStatus.FAILED && (
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsConnectedAccountsRowRightContainer.tsx:29]: Love it :p

File: packages/twenty-front/src/modules/settings/accounts/enums/syncStatus.enum.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
+export enum SyncStatus {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/accounts/enums/syncStatus.enum.ts:1]: we don't have enums subfolder, use constants?

File: packages/twenty-front/src/modules/settings/accounts/utils/computeSyncStatus.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+  if (
+    messageChannelSyncStatus === MessageChannelSyncStatus.ONGOING ||
+    calendarChannelSyncStatus === CalendarChannelSyncStatus.ONGOING
+  ) {
+    return SyncStatus.IMPORTING;
+  }
+
+  if (
+    messageChannelSyncStatus === MessageChannelSyncStatus.NOT_SYNCED ||
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/accounts/utils/computeSyncStatus.ts:28]: I think this is wrong, in case of both NOT_SYNCED it should be NOT_SYNC
In case of one out of 2 NOT_SYNCED we should leverage the other one (which is actually the case because all other conditions are or, except the last one ACTIVE)

**Review by charlesBochet — APPROVED** [review]
