### PR TITLE
fix: prevent duplicate dropdowns in activity targets when editing in different contexts

### LINKED ISSUE #12361: When editing the relations of a tasks tied to two records (one in background, one in side panel), two dropdowns are opened
## Bug Description

When editing the relations of a tasks tied to two records (one in background, one in side panel), two dropdowns are opened

Image

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
Closes #12361

### Changes Made

- In `ActivityTargetsInlineCell`, we now use different component instance IDs based on context. This ensures that each instance of the component (whether in right drawer or main view) has its own isolated state, preventing state conflicts and duplicate dropdowns.
- The `MultipleRecordPicker` component now properly resets its state when closed, preventing state leakage between instances.

https://github.com/user-attachments/assets/deb99687-a803-417e-a339-cab061026739

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx [hunk 1]
```diff
@@ -30,11 +32,17 @@ export const ActivityTargetsInlineCell = ({
   showLabel = true,
   maxWidth,
   activityObjectNameSingular,
-  componentInstanceId,
+  componentInstanceId: originalComponentInstanceId,
 }: ActivityTargetsInlineCellProps) => {
   const { activityTargetObjectRecords } =
     useActivityTargetObjectRecords(activityRecordId);
 
+  const { isInRightDrawer } = useIsInRightDrawerOrThrow();
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/activities/inline-cell/components/ActivityTargetsInlineCell.tsx]: I would rather retrieve this in the above components and pass the componentInstanceId directly to avoid coupling this component with the show page

**Review by bosiraphael — COMMENTED** [review]
LGTM, good job 👏 We could also use this context in other components which uses isInRightDrawer instead of prop drilling.
I just left a comment to address before merging

**Comment by abdulrahmancodes** [comment]
@bosiraphael Thanks! I've addressed the comment and updated the code accordingly. Let me know if there's anything else.

**Review by bosiraphael — APPROVED** [review]
LGTM! Good job 👏
