### PR TITLE
fix: prevent unwanted newlines in note editor when typing

### LINKED ISSUE #12119: When editing a note that has just been created, a newline is inserted after each keystroke
## Bug Description

https://github.com/user-attachments/assets/05342205-e9d9-4139-abf1-c03405628622

I spotted the bug on my computer and twenty-eng (prod).

The bug disappears after a full page refresh or if I close the side panel and reopen it.

## Expected behavior

A newline should be added only when typing on the `Enter` key.

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
https://github.com/user-attachments/assets/16706d7a-fe0e-4979-bd72-00f4bfec594b

Closes #12119

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx [hunk 1]
```diff
@@ -306,6 +310,10 @@ export const ActivityRichTextEditor = ({
   useScopedHotkeys(
     '*',
     (keyboardEvent) => {
+      if (commandMenuPage !== CommandMenuPages.EditRichText) {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/activities/components/ActivityRichTextEditor.tsx:313]: It works but a more ideal solution would be to not mount that hook at all if we're editing, meaning we have the focus in the rich text editor. @bosiraphael

**Comment by etiennejouan** [comment]
Hi @abdulrahmancodes, thank you for your contribution.

The root cause of this issue seems to be a misbehaviour in hotKey scope settings when clicking on editor from title cell focus. It triggers the 'activity-body' hotKey from focus on editor but also the 'command-menu-focused' hotKey setting because of the click outside (unfortunately, 'activity-body' is set first and overwritten).

We have talk about this PR with @bosiraphael, solution would be to wait for stacked hotkey scopes refacto in few days. 
@lucasbordeau, you may have a better alternative  ?

**Review by etiennejouan — COMMENTED** [review]
Hi @abdulrahmancodes, thank you for your contribution.

The root cause of this issue seems to be a misbehaviour in hotKey scope settings when clicking on editor from title cell focus. It triggers the 'activity-body' hotKey from focus on editor but also the 'command-menu-focused' hotKey setting because of the click outside (unfortunately, 'activity-body' is set first and overwritten).

We have talk about this PR with @bosiraphael, solution would be to wait for stacked hotkey scopes refacto in few days.
@lucasbordeau, you may have a better alternative ?

**Comment by abdulrahmancodes** [comment]
> Hi @abdulrahmancodes, thank you for your contribution.
> 
> The root cause of this issue seems to be a misbehaviour in hotKey scope settings when clicking on editor from title cell focus. It triggers the 'activity-body' hotKey from focus on editor but also the 'command-menu-focused' hotKey setting because of the click outside (unfortunately, 'activity-body' is set first and overwritten).
> 
> We have talk about this PR with @bosiraphael, solution would be to wait for stacked hotkey scopes refacto in few days.
> @lucasbordeau, you may have a better alternative ?

@etiennejouan Ah, okay. should I close this PR then?

**Comment by charlesBochet** [comment]
Let's add a TODO and merge for now, it still fixes the bug efficiently :)
