### PR TITLE
Fix: Remove white gap in workflow HTTP headers input field

### LINKED ISSUE #12751: Workflow run HTTP headers white gap
# Current behavior

Image

# Desired Behavior

No white gap should be present. The inputs should take the full width when no button is there.

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
Closes #12751 

Screenshot 2025-06-24 at 3 39 33 PM

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Could you please address [this](https://github.com/twentyhq/twenty/issues/12751#issuecomment-2990023774) comment? 

thanks!


Screenshot 2025-06-24 at 13 39 10

**Comment by abdulrahmancodes** [comment]
@FelixMalfait Fixed the issue overflow issue.
Screenshot 2025-06-25 at 12 33 04 AM

File: packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/KeyValuePairInput.tsx [hunk 1]
```diff
@@ -31,6 +25,13 @@ const StyledPlaceholder = styled.div`
   height: ${({ theme }) => theme.spacing(8)};
 `;
 
+const StyledFormTextFieldInputContainer = styled.div`
+  width: 100%;
+  .ProseMirror {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/components/KeyValuePairInput.tsx]: This isn't how we usually do it in the codebase, did you try to find a solution that avoids harcoding the classname? Sometimes there is no way around but in many case there is.

**Comment by abdulrahmancodes** [comment]
Hey @FelixMalfait! I've addressed your comment. Could you please re-review?

**Comment by FelixMalfait** [comment]
Hey, this isn't resilient to side panel size change which could happen in the future Screenshot 2025-06-30 at 21 33 33

Maybe use a relative implementation instead (e.g. calc(50%- XXXpx) where X is a well defined const based on the icon)

**Review by Devessier — APPROVED** [review]
I solved the two bugs by using a CSS grid.


https://github.com/user-attachments/assets/fcd039b3-211d-460b-9c3b-c11646d6a56a

**Comment by Devessier** [comment]
Thanks for your work on the HTTP Request action, @abdulrahmancodes! I pushed a few changes as I had an idea about a solution.

**Comment by FelixMalfait** [comment]
Thanks a lot @Devessier!
