### PR TITLE
Fix front end

### LINKED ISSUE #1677: Bug: Front end is not running
**Current behavior**
The web app is not running due to an error merged recently

**Expected behavior**
The front end should be able to run normally

**Additional context**
Screenshot 2023-09-20 at 18 22 36

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #1677

### CODE REVIEW

File: front/src/modules/ui/table/components/EntityTableHeaderOptions.tsx [hunk 1]
```diff
@@ -83,6 +84,7 @@ export const EntityTableHeaderOptions = ({
             </StyledDropdownMenuItemsContainer>
           </StyledDropdownMenu>
         }
+        dropdownHotkeyScope={{ scope: TableHotkeyScope.Table }}
```
Comment (thaisguigon) [inline front/src/modules/ui/table/components/EntityTableHeaderOptions.tsx:87]: Thank you for your contribution!

Although, we need to create a new HotkeyScope for this, as `TableHotkeyScope.Table` will catch hotkeys specific to the table.

For instance: in `EntityTable`, you can see that a hotkey for `"escape"` has been set for the `Table` HotkeyScope, that resets table row selection. But when the dropdown is open, `"escape"` should close the dropdown instead.

If you use this scope for the dropdown, there will be conflicts between the table and dropdown hotkeys.

The new scope could be named `TableHotkeyScope.ColumnHeaderDropdown` for instance.

**Review by thaisguigon — CHANGES_REQUESTED** [review]

**Review by charlesBochet — APPROVED** [review]
