### PR TITLE
Fix empty combinedFindManyRecords query

### LINKED ISSUE #13220: When created user with limited permissions creates new entity error "Expected $, found )" appears
## Bug Description

Context:
1. root user created X data model
2. root user created second user with limited permissions to only this data model ("All objects" permissions unchecked)
3. second user logged in and get's to the X table (e.g. https://crm.twenty.com/objects/X)
4. User tries to create any new entry
5. Following error appears

Image

HOW TO BYPASS THIS:
1. go to created users in settings 
2. give view permissions for all the data models for user ("All objects" permissions)
3. revoke not needed "object-level" permissions

Hope it makes sense. I can share any extra info if needed, or have a call showing logs, etc..

### PR DESCRIPTION
**Pull request by ijreilly**
Fixes https://github.com/twentyhq/twenty/issues/13220#issuecomment-3084412760

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts [hunk 1]
```diff
@@ -84,6 +85,10 @@ export const useGenerateCombinedFindManyRecordsQuery = ({
       )
       .join(', ');
 
+  if (isEmpty(queryOperationSignatureWithObjectMetadataItemArray)) {
+    return null;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts:89]: **question:** shouldn't we return gql`` instead of null?

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts (hunk 1 above)
Comment (Weiko) [reply packages/twenty-front/src/modules/object-record/multiple-objects/hooks/useGenerateCombinedFindManyRecordsQuery.ts:89]: note: That was my question as well but it seems we already return null above for other use cases so I guess useQuery behaves correctly with null @ijreilly
