### PR TITLE
fix: adding https in checkurltype

### LINKED ISSUE #6287: Invalid URL Redirects for X and LinkedIn Fields
# Bug description

X and LinkedIn fields accept links without "https," but they fail to redirect to the corresponding pages on X and LinkedIn.

For instance, if I enter: 
linkedin.com/in/tdesfrancs/

I get redirected to:
https://app.twenty.com/objects/linkedin.com/in/tdesfrancs/

### PR DESCRIPTION
**Pull request by Princeyadav05**
# Fix URL handling for LinkedIn and Twitter links

Fixes #6287 

## Solution
Updated `checkUrlType` function to prepend "https://" to URLs if missing, ensuring proper handling of social media links.

## Changes
- Modified `/packages/twenty-front/src/utils/checkUrlType.ts`
- Added a check to prepend "https://" if URL doesn't start with a protocol

### CODE REVIEW

**Review by FelixMalfait — APPROVED** [review]

File: packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx [hunk 1]
```diff
@@ -18,6 +18,12 @@ export const LinkDisplay = ({ value }: LinkDisplayProps) => {
     return <></>;
   }
 
+  const absoluteUrl = url
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx:21]: we should leverage existing utils here :)

Comment (FelixMalfait) [reply packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx:21]: Yes good point, might as well change it here too then, 
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/URLDisplay.tsx#L32
