### PR TITLE
fix: Dropdown Overlapping Sidebar on Column Header Click in Horizontal Table When Scrolling

### LINKED ISSUE #8272: Dropdown Overlapping Sidebar on Column Header Click in Horizontal Table When Scrolling
## Bug Description

On any table view when the dropdown is expanded, the horizontal scroll is still active and user can scroll horizontally
this creates the weird floating dropdown overlapping the first name column and the menu sidebar as well

Attaching the video for the reference
### Recording

https://github.com/user-attachments/assets/efff459c-51d3-4f91-a7fb-c06a86f64b75

## Steps to recreate

1. On any table Click the dropdown on any column header and scroll

# Desired behavior

Prevent horizontal scroll when a field menu is opened.

### PR DESCRIPTION
**Pull request by Vardhaman619**
fixes : #8272

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadWithDropdown.tsx [hunk 1]
```diff
@@ -22,8 +24,21 @@ const StyledDropdown = styled(Dropdown)`
 export const RecordTableColumnHeadWithDropdown = ({
   column,
 }: RecordTableColumnHeadWithDropdownProps) => {
+  const { setEnableXScroll, setEnableYScroll } = useContext(
+    RecordTableScrollContext,
+  );
+  const handleDropdownOpen = useCallback(() => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadWithDropdown.tsx:30]: Please use recoil states V2 scoped by record table instead of this pattern which we don't use.

See an example here : `isPersistingViewFieldsComponentState.ts`

**Review by lucasbordeau — APPROVED** [review]
