### PR TITLE
fix: twenty-chrome-extension:"graphql:generate"

### LINKED ISSUE #5645: yarn nx run twenty-chrome-extension:"graphql:generate" not working on main
## Error
```
Error 0: Unknown type "CompanyCreateInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/mutations.ts:2:37
      Error 1: Cannot query field "createCompany" on type "Mutation".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/mutations.ts:3:5
      Error 2: Unknown type "CompanyFilterInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/queries.ts:2:30
      Error 3: Cannot query field "companies" on type "Query".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/company/queries.ts:3:5
      Error 4: Unknown type "PersonCreateInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/mutations.ts:2:36
      Error 5: Cannot query field "createPerson" on type "Mutation".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/mutations.ts:3:5
      Error 6: Unknown type "PersonFilterInput".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/queries.ts:2:29
      Error 7: Cannot query field "people" on type "Query".
      at /Users/charles/dev/twenty/twenty/packages/twenty-chrome-extension/src/graphql/person/queries.ts:3:5
```

### PR DESCRIPTION
**Pull request by AdityaPimpalkar**
fixes: #5645

### CODE REVIEW

File: packages/twenty-chrome-extension/codegen.ts [hunk 1]
```diff
@@ -1,9 +1,13 @@
...
 
 const config: CodegenConfig = {
-  schema: ['http://localhost:3000/graphql'],
-  overwrite: true,
-  documents: ['./src/**/*.ts', '!src/generated/**/*.*'],
+  schema: [`${import.meta.env.VITE_SERVER_BASE_URL}/graphql`],
+  overwrite: false,
+  documents: ['./src/**/*.ts', 
+    '!src/generated/**/*.*', 
+    '!src/graphql/company/*',
```
Comment (charlesBochet) [inline packages/twenty-chrome-extension/codegen.ts:8]: @AdityaPimpalkar Why are we ignoring these folders? Are these queries/mutations not useful?

Comment (AdityaPimpalkar) [reply packages/twenty-chrome-extension/codegen.ts]: Yes, seemed like a viable solution as those queries and mutations require authorization and they were standard objects so they won't change much any time soon, but I've changed and kept is as it was and just added authorization headers

**Review by charlesBochet — APPROVED** [review]
