### PR TITLE
Fixes active row state after opening the file preview

### LINKED ISSUE #12093: The active row doesn't always go back to its default state when side panel is closed
## Bug Description

If I select a note and click on an attachment in the side panel, it opens an attachment modal. If I close the modal and the side panel, the active row isn't unselected.

https://github.com/user-attachments/assets/da0ff42d-31ec-4c7c-b835-05b907b2b972

## Expected behavior

I expect the active row to be unselected. It shouldn't be either blue or gray.

### PR DESCRIPTION
**Pull request by bosiraphael**
Fixes #12093
This bug was quite hard to fix because it was an issue with the `AnimatePresence` component of the framer motion library.

After investigating the issue with @Devessier, here is what we understood:

Since the modal component has an exit animation but wasn't wrapped inside an `AnimatePresence` component, the animation seemed to never be marked as complete when we closed the modal and the component did not appear anymore but was still in the dom.

This caused an issue when closing the side panel because the state cleanup function of the command menu is triggered when its closing animation is complete. This cleanup function emits a right drawer close event, which is listened by the record table row to update it's state.

The `onExitComplete` was never triggered because the exit animation of the modal was never considered as complete, and since it's a children animation of the command menu `AnimatePresence`, this animation was never considered as complete either (see [PresenceChild doc](https://github.com/motiondivision/motion/blob/main/packages/framer-motion/src/components/AnimatePresence/PresenceChild.tsx).

This caused the cleanup function to never be executed and the close event to never be emitted, so the row stayed active.

Before:

https://github.com/user-attachments/assets/a165039b-6203-43d6-b992-dcfb4dfb8f2b

After:

https://github.com/user-attachments/assets/42eab2e8-62c9-4c25-85d6-78210d7ebe89

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx [hunk 1]
```diff
@@ -108,62 +107,60 @@ export const ConfirmationModal = ({
...
-          modalId={modalId}
-          onClose={() => {
-            onClose?.();
-          }}
-          onEnter={handleEnter}
-          isClosable={true}
-          padding="large"
-          modalVariant={modalVariant}
-          data-globally-prevent-click-outside
+    <>
```
Comment (Devessier) [inline packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx:110]: I think we don't need this fragment as there is only one child component here.

File: packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx [hunk 2]
```diff
@@ -221,7 +221,7 @@ export const Modal = ({
   };
 
   return (
-    <>
+    <AnimatePresence mode="wait">
```
Comment (Devessier) [inline packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx:224]: The tricky fix

**Review by Devessier — APPROVED** [review]
The changes look great to me! It was hard to find the root cause but we did it!
I left a small nitpick comment but I already approve.
