### PR TITLE
Fixes infinite loop on record data update in command menu

### LINKED ISSUE #957: Improve RecordValueSetterEffect
The effect component `RecordValueSetterEffect` causes infinite loops : https://twenty-v7.sentry.io/issues/6538271123/events/0ada05d7085c49379804f9439cd34459/?project=4507072563183616

### LINKED ISSUE #11079: Minified React error #185
Pressing `⌘⏎` too fast results in a front-end error. (Happened at normal usage speed; video is for demonstration purposes)

https://github.com/user-attachments/assets/5a5eb92e-f915-46aa-9a23-e1ba0c4265e3

Image

# Fixes

1. Implement a more visually appealing front-end error message (High priority)
2. Resolve the underlying issue (Medium priority)

### Expected Design

Image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=59142-196940&t=AbYtEVeDQbxGn4vh-11

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes the infinite loop that was happening in `RecordShowEffect` component due to a useEffect on `recordStoreFamilyState` which was creating a non-deterministic open loop.

The fix was to use a recoilCallback to avoid reading a stale state from Recoil with `useRecoilValue`, useRecoilCallback always gets the most fresh data and commits everything before React goes on with rendering, thus avoiding any stale value in a useEffect.

Fixes https://github.com/twentyhq/twenty/issues/11079
Fixes https://github.com/twentyhq/core-team-issues/issues/957

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { ObjectRecord } from '@/object-record/types/ObjectRecord';
 import { createFamilyState } from '@/ui/utilities/state/utils/createFamilyState';
 
 export const recordStoreFamilyState = createFamilyState<
-  ObjectRecord | null,
+  ObjectRecord | null | undefined,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts:5]: why do we introduce both null and undefined, I feel only one should be here. undefined seems more accurate than null

File: packages/twenty-front/src/modules/object-record/record-show/components/RecordShowEffect.tsx [hunk 2]
```diff
@@ -33,15 +34,25 @@ export const RecordShowEffect = ({
     withSoftDeleted: true,
   });
 
-  const [recordFromStore, setRecordFromStore] = useRecoilState(
-    recordStoreFamilyState(recordId),
+  const updater = useRecoilCallback(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-show/components/RecordShowEffect.tsx:37]: let's give it a better name: setRecordFromStore :D

File: packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts (hunk 1 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts:5]: As already discussed, there's not much gained from using null or undefined alone, it creates a complex nullable typing system that complexifies the DX more than it helps.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-store/states/recordStoreFamilyState.ts:5]: The most common problem is that you'll end up with one system that only handles null, another that only handles undefined, and one day you'll need to have both communicate with each other and you'll have a hard time.
