### PR TITLE
Fix bug reoder on table in view groups mode

### LINKED ISSUE #8403: Table with record groups can handle record re-order
Table in with multiple record groups should handle correctly re-order of record under the same record group.

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes #8403 

Added comments on the PR to explain changes

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx [hunk 1]
```diff
@@ -15,7 +15,8 @@ export const RecordTableNoRecordGroupRows = () => {
           <RecordTableRow
             key={recordId}
             recordId={recordId}
-            rowIndex={rowIndex}
+            rowIndexForFocus={rowIndex}
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/components/RecordTableNoRecordGroupRows.tsx:18]: I'm introducing two rowIndexes:
- one is used to handle focus, the other to give an index for drag

Right now the index used in focus / cell opening is handled at table level so it's a global index, the index use drag is at group level. I think long term we want to have the index for focus / cell opening at group level too and handle the jump between groups properly

I prefer introducing these two naming ForFocus and ForDrag because it's clear when to use which one in underlying components. Alternatively I could have introduced rowIndexInGroup and rowIndexInTable but this will make underlying components know about recordGroups and make if conditions which I think we should avoid to reduce complexity

File: packages/twenty-front/src/modules/object-record/record-table/hooks/useComputeNewRowPosition.ts [hunk 2]
```diff
@@ -1,90 +0,0 @@
-import { DropResult } from '@hello-pangea/dnd';
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/hooks/useComputeNewRowPosition.ts:1]: removing this hook as we should leave recordBoard, recordTable, recordTableWithGroups implement their way of selecting the right records + we already have getDraggedRecordPosition helper

File: packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyRecordGroupDragDropContextProvider.tsx [hunk 3]
```diff
@@ -38,33 +35,34 @@ export const RecordTableBodyRecordGroupDragDropContextProvider = ({
...
     ({ snapshot }) =>
       (result: DropResult) => {
-        const tableAllRecordIds = getSnapshotValue(
-          snapshot,
-          recordIndexAllRecordIdsSelector,
-        );
+        const destinationRecordGroupId = result.destination?.droppableId;
 
-        const recordGroupId = result.destination?.droppableId;
+        if (!isDefined(result.destination)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyRecordGroupDragDropContextProvider.tsx:47]: same logic but in case of viewGroups
