### PR TITLE
fix(SingleEntitySelectMenuItems): extract `Add New` button from entitiesToSelect

### LINKED ISSUE #8169: Standardize "Add New" button in dropdown menus
# Current Behavior

### Multi-select

The `Add New` button has its own container.

https://github.com/user-attachments/assets/856d8f59-df83-40ea-a4a5-d5b5a25585e9

### Select

The `Add New` button is within the Select choices container.

https://github.com/user-attachments/assets/417b8428-6851-4f00-8b3f-51b7abcccfbb

# Desired Behavior

We should apply the behavior of the multi-select to all dropdown menus. The `Add New` button should have its own container/menu section everywhere.

### PR DESCRIPTION
**Pull request by nicolasrouanne**
# Description
Closes #8169

Extract Add New button from entitiesToSelect and add it as a separate element .
There doesn't seem to be a point in having Add New as part of a list, it seems better off in its own component, apart from list items

## Rationale
There already is #8353 addressing the same issue, but it seems it doesn't really remove the duplicate "Add New" in the list, leaving a duplicate "Add New" in `SingleEntitySelect`

### CODE REVIEW

**Comment by nicolasrouanne** [comment]
Remaining work:

- [ ] check if wrapping "Add New" in `<DropdownMenuItemsContainer />` is needed, see https://github.com/nicolasrouanne/twenty/pull/1#discussion_r1838662324
- [ ] use the same naming convention for `MultiSelect` and `SingleSelect`: either `Record` or `Entity` see https://github.com/nicolasrouanne/twenty/pull/1#discussion_r1838517827

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx [hunk 1]
```diff
@@ -49,21 +52,15 @@ export const SingleEntitySelectMenuItemsWithSearch = ({
...
-    };
-  }
+  const createNewButton = isDefined(onCreate) && (
+    <DropdownMenuItemsContainer>
+      <CreateNewButton
+        onClick={() => onCreate?.(relationPickerSearchFilter)}
+        LeftIcon={IconPlus}
+        text="Add New"
+      />
+    </DropdownMenuItemsContainer>
```
Comment (nicolasrouanne) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:62]: Indeed, as per @FelixMalfait's [comment](https://github.com/nicolasrouanne/twenty/pull/1#discussion_r1838662324), wrapping the "Add New" button inside a `<DropdownMenuItemsContainer>` does add some nice padding 👍🏻 

### Before
Screenshot 2024-11-13 at 12 06 59

### After
Screenshot 2024-11-13 at 12 06 49

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx
Comment (nicolasrouanne) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:1]: I initially offered to change the file names to have the same naming convention between `Entity` and `Record` for `SingleSelect` and `MultiRecord`, but it seems too big a change (at least 5 to 10 files renamed) for such a small PR.

I'd rather do it in a separate PR.

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx [hunk 2]
```diff
@@ -104,6 +99,8 @@ export const SingleEntitySelectMenuItemsWithSearch = ({
           {results}
         </>
       )}
+      {entities.entitiesToSelect.length > 0 && <DropdownMenuSeparator />}
```
[the remark this answers is not in the document]
Comment (nicolasrouanne) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:102]: My bad, this separator is needed before the `SearchInput` a few lines down.

[the remark this answers is not in the document]
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:102]: Haha sorry, this AI is often irrelevant

[the remark this answers is not in the document]
Comment (nicolasrouanne) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx]: Yeah... it had a point though!
I forgot to add the "Add New" button in case `dropdownPlacement` included `end`. Nothing to do with its comment, but it made me realise 😂

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx [hunk 3]
```diff
@@ -15,6 +15,7 @@ export type SingleEntitySelectProps = {
 
 export const SingleEntitySelect = ({
   disableBackgroundBlur = false,
+  dropdownPlacement,
```
Comment (nicolasrouanne) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx:18]: I took the liberty of adding this prop and passing it down to `SingleEntitySelectMenuItemsWithSearch`. I don't know if it's a good idea:
- it does expand `SingleEntitySelect` contract... which I recon can be less maintainable.
- however the `dropdownPlacement` is already a prop available in `SingleEntitySelect` type interface; it just wasn't passed down to the underlying component, which I found was weird
- it allows testing and using this prop in _Storybook_


Let me know what you think.

File: packages/twenty-front/src/modules/object-record/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx [hunk 4]
```diff
@@ -80,3 +80,7 @@ export const WithSearchFilter: Story = {
     });
   },
 };
+
+export const WithEndPlacement: Story = {
+  args: { dropdownPlacement: 'bottom-end' },
+};
```
Comment (nicolasrouanne) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/__stories__/SingleEntitySelect.stories.tsx:86]: I added a story to check the select with an end placement

**Review by nicolasrouanne — COMMENTED** [review]
I passed down a prop in `SingleEntitySelect`. Don't know if it was a good idea, I can remove it if needed.

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx (hunk 3 above)
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelect.tsx:18]: Yes makes sense to pass it if the below component has it I agree!

**Comment by FelixMalfait** [comment]
This looks great thanks a lot! 

This introduced a small bug I think, I haven't dug into it yet
https://github.com/user-attachments/assets/c9ef43d5-3b51-4a57-8dcd-0bb056a49481

**Comment by FelixMalfait** [comment]
Actually I think there's a misunderstanding on what placement is supposed to be. This was a hack to maintain a stable place input. So the text input always remained in the same position, and the results were displayed either below or after the input depending on the space available.

**Comment by nicolasrouanne** [comment]
Thanks for your explanation, I would never have that figured out. I'm gonna try to dig a little deeper, just out of curiosity, to understand why the dropdown is out there floating. I'm gonna try to run the `playwright` tests too.

Once that's done, I'll remove exposing the `dropdownPlacement` and passing it down, which I think is the reason for the regression.

**Comment by FelixMalfait** [comment]
@nicolasrouanne thanks a lot! Let us know if it's too much word and you want us to take over

**Comment by nicolasrouanne** [comment]
I reverted exposing the `dropdownPlacement` prop in `SingleEntitySelect`, see c255ae5b2fcd8f40b6eb305f1f9e318250c703f6, it should fix the [dropdown placement regression](https://github.com/twentyhq/twenty/pull/8474#issuecomment-2474405877)

I tried to reproduce the bug using E2E tests, FWIW I didn't really managed to get E2E tests running in my local environment. Here's what I did:
```sh
cp ./packages/twenty-e2e-testing/.env.example ./packages/twenty-e2e-testing/.env # setup E2E env variables
npx nx test:e2e:setup twenty-e2e-testing # install playwright
npx nx database:reset twenty-server # reset dev database to start with a clean slate
npx nx start # start local dev server
npx nx test:e2e:ui twenty-e2e-testing # run using --ui to see playwright ui and browser
```

Tests failed in login and all subsequent tests using a login-like behaviour since I never get the "Continue with email" button, I always have the `tim@apple.dev` prefilled, with a "Continue" button.

It's probably an environment misconfiguration, I stopped investigating for now.

>[!NOTE]
> I feel that the developer guide would benefit from an explanation on how to run E2E tests

**Review by FelixMalfait — APPROVED** [review]
Great work! Thanks a lot. I didn't realize this would be so complex to fix everything, there are still a few glitches unrelated to the initial ask which we'll fix in another PR.

Agree with E2E tests, it's such a pain that I've never ran them locally I just wait for the CI

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx [hunk 5]
```diff
@@ -49,21 +52,13 @@ export const SingleEntitySelectMenuItemsWithSearch = ({
       excludedRelationRecordIds,
     });
 
-  const showCreateButton = isDefined(onCreate);
-
-  let onCreateWithInput = undefined;
-
-  if (isDefined(onCreate)) {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:56]: FYI I think we should have kept that https://github.com/twentyhq/twenty/issues/8529#issue-2665477804

Comment (nicolasrouanne) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:56]: Sorry to have introduced that 😢
I think I didn't really understand what it was used for.
I was under the impression my change didn't impact the public API of the component... but it seems I was wrong, sorry.

It's weird that TS didn't catch it

Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:56]: No problem at al! I should have seen it 😅 (+ lack of good tests on our codebase). That code looks ugly I would have been tempted to remove it too!
