### PR TITLE
fix: overflow issue in tableSection

### LINKED ISSUE #7327: Only the first 29 object fields are visible/editable
## Bug Description

When editing an object with 59 fields, only the first 29 are visible

image

image

## Expected behavior

All fields should be visible

## Technical inputs

Use this python code to create the fields in your development environment.

```python
import logging
from twenty_api import TwentyAPI
import os
from dotenv import load_dotenv
import uuid

# Set up logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# Initialize the API client
api = TwentyAPI(
    base_url=os.getenv("TWENTY_BASE_URL"),
    api_key=os.getenv("TWENTY_API_KEY")
)

def ensure_custom_object_exists(name_singular, name_plural, label_singular, label_plural, icon):
    # Check if the object already exists
    objects = api.get_objects()
    existing_object = next((obj for obj in objects['data']['objects'] if obj['nameSingular'] == name_singular), None)

    if existing_object:
        logger.info(f"Custom object '{name_singular}' already exists.")
        logger.debug(f"Existing object: {existing_object}")
        return existing_object['id']
    else:
        # Create the custom object
        new_object = api.create_object({
            "nameSingular": name_singular,
            "namePlural": name_plural,
            "labelSingular": label_singular,
            "labelPlural": label_plural,
            "description": f"Custom object for {label_plural}",
            "icon": icon
        })
        logger.info(f"Created custom object '{name_singular}'.")
        return new_object['data']['createOneObject']['id']

def ensure_custom_field_exists(api, object_id, field_name, field_type, field_label, field_description, field_icon, options=None):
    fields = api.get_fields()
    
    existing_field = next((field for field in fields if field['name'] == field_name), None)

    if existing_field:
        logger.info(f"Field '{field_name}' already exists for object {object_id}")
        return existing_field

    new_field_data = {
        "objectMetadataId": object_id,
        "name": field_name,
        "type": field_type,
        "label": field_label,
        "description": field_description,
        "icon": field_icon,
        "isCustom": True
    }

    if field_type == "SELECT" and options:
        new_field_data["options"] = options

    logger.debug(f"Creating new field with data: {new_field_data}")
    created_field = api.create_field(new_field_data)
    logger.info(f"Created new field '{field_name}' for object {object_id}")
    return created_field

def ensure_custom_fields_exist(api, object_id, fields_to_create):
    # Fetch all fields once
    all_fields = api.get_fields()
    
    for field_data in fields_to_create:
        logger.debug(f"Ensuring field exists: {field_data[0]}")
        field_name, field_type, field_label, field_description, field_icon, *options = field_data
        
        existing_field = next((field for field in all_fields if field['name'] == field_name), None)

        if existing_field:
            logger.info(f"Field '{field_name}' already exists for object {object_id}")
            continue

        new_field_data = {
            "objectMetadataId": object_id,
            "name": field_name,
            "type": field_type,
            "label": field_label,
            "description": field_description,
            "icon": field_icon,
            "isCustom": True
        }

        if field_type == "SELECT" and options:
            new_field_data["options"] = options[0]

        logger.debug(f"Creating new field with data: {new_field_data}")
        created_field = api.create_field(new_field_data)
        logger.info(f"Created new field '{field_name}' for object {object_id}")

def get_object_id_by_name(api, name_singular):
    objects = api.get_objects()
    object_data = next((obj for obj in objects['data']['objects'] if obj['nameSingular'] == name_singular), None)
    if object_data:
        return object_data['id']
    return None

def get_existing_relations(api, from_object_id, to_object_id):
    relations = api.get_relations()
    logger.debug(f"Fetched relations: {relations}")
    matching_relations = [r for r in relations['data']['relations'] if 
                          r['fromObjectMetadata']['id'] == from_object_id and 
                          r['toObjectMetadata']['id'] == to_object_id]
    logger.debug(f"Matching relations: {matching_relations}")
    return matching_relations

def main():
    property_object_id = ensure_custom_object_exists(
        name_singular="property",
        name_plural="properties",
        label_singular="Property",
        label_plural="Properties",
        icon="IconHome"
    )

    fields_to_create = [
        ("rent", "CURRENCY", "Rent", "Rent amount", "IconCurrencyDollar"),
        ("fmrrent", "CURRENCY", "HUD Fair Market Rent", "HUD Fair Market Rent amount", "IconCurrencyDollar"),
        ("piti", "CURRENCY", "PITI", "Principal, Interest, Taxes, and Insurance", "IconCurrencyDollar"),
        ("cashflow", "CURRENCY", "Comp Cash Flow", "(Avg Comp Rent - PITI) X .75", "IconCurrencyDollar"),
        ("mortgagepayment", "CURRENCY", "Mortgage Payment", "Monthly mortgage payment", "IconCurrencyDollar"),
        ("listprice", "CURRENCY", "ListPrice", "Listing price of the property", "IconCurrencyDollar"),
        ("mortgagebalance", "CURRENCY", "Mortgage Balance", "Remaining mortgage balance", "IconCurrencyDollar"),
        ("equity", "CURRENCY", "Equity", "Property equity", "IconCurrencyDollar"),
        ("compvalue", "CURRENCY", "Comp Value", "Comparable property value", "IconCurrencyDollar"),
        ("pricedifference", "CURRENCY", "Price Difference", "Comp value - listprice", "IconCurrencyDollar"),
        ("monthlytaxes", "CURRENCY", "Monthly Taxes", "Monthly property taxes", "IconCurrencyDollar"),
        ("monthlyhoa", "CURRENCY", "Monthly HOA", "Monthly HOA fees", "IconCurrencyDollar"),
        ("monthlyinsurance", "CURRENCY", "Monthly Insurance", "Monthly insurance cost", "IconCurrencyDollar"),
        ("ownerrent", "CURRENCY", "Owner Rent", "Rent amount set by owner", "IconCurrencyDollar"),
        ("offermonthly", "CURRENCY", "Offer Monthly", "Monthly offer amount", "IconCurrencyDollar"),
        ("offercashflow", "CURRENCY", "Offer Cash Flow", "Cash flow from offer", "IconCurrencyDollar"),
        ("offertotalpayments", "CURRENCY", "Offer Total Payments", "Total payments for offer", "IconCurrencyDollar"),
        ("offertotalprincipal", "CURRENCY", "Offer Total Principal Paid", "Total principal paid for offer", "IconCurrencyDollar"),
        ("offertotaltoseller", "CURRENCY", "Offer Total Paid to Seller", "Total amount paid to seller", "IconCurrencyDollar"),
        ("offerdownpayment", "CURRENCY", "Offer Down Payment", "Down payment for offer", "IconCurrencyDollar"),
        ("offerballoonpayment", "CURRENCY", "Offer Balloon Payment", "Balloon payment for offer", "IconCurrencyDollar"),
        ("offerinterestpaid", "CURRENCY", "Offer Interest Paid", "Total interest paid for offer", "IconCurrencyDollar"),
        ("offerprice", "CURRENCY", "Offer Price", "Price of the offer", "IconCurrencyDollar"),
        ("gy23price", "CURRENCY", "Gross Yield @ 23% Price", "Gross yield at 23% price", "IconCurrencyDollar"),
        ("gy30price", "CURRENCY", "Gross Yield @ 30% Price", "Gross yield at 30% price", "IconCurrencyDollar"),
        ("equitypct", "NUMBER", "Equity Percent", "Equity percentage", "IconPercentage"),
        ("interestrate", "NUMBER", "Interest Rate", "Interest rate percentage", "IconPercentage"),
        ("offerannualrate", "NUMBER", "Offer Annual Rate", "Annual rate for offer", "IconPercentage"),
        ("grossyield", "NUMBER", "Gross Yield", "Gross yield percentage", "IconPercentage"),
        ("listingstatus", "SELECT", "Listing Status", "Current status of the listing", "IconHome", [
            {"color": "green", "id": str(uuid.uuid4()), "label": "FOR_SALE", "position": 0, "value": "FOR_SALE"},
            {"color": "turquoise", "id": str(uuid.uuid4()), "label": "SOLD", "position": 1, "value": "SOLD"}
        ]),
        ("propertytype", "TEXT", "Property Type", "Type of property", "IconBuilding"),
        ("zillowlink", "LINKS", "Zillow Link", "Link to Zillow listing", "IconLink"),
        ("propstreamlink", "LINKS", "Propstream Link", "Link to Propstream", "IconLink"),
        ("dealchecklink", "LINKS", "Dealcheck Link", "Link to Dealcheck", "IconLink"),
        ("spotcrimelink", "LINKS", "Spotcrime Link", "Link to Spotcrime", "IconLink"),
        ("realtorlink", "LINKS", "Realtor Link", "Link to Realtor listing", "IconLink"),
        ("femafloodmap", "LINKS", "FEMA Flood Map", "Link to FEMA flood map", "IconMap"),
        ("streetaddress", "TEXT", "Street Address", "Property street address", "IconMapPin"),
        ("city", "TEXT", "City", "Property city", "IconBuilding"),
        ("state", "TEXT", "State", "Property state", "IconMap"),
        ("zipcode", "TEXT", "Zipcode", "Property zipcode", "IconMapPin"),
        ("county", "TEXT", "County", "Property county", "IconMap"),
        ("compcount", "NUMBER", "Comp Count", "Number of comparable properties", "IconCalculator"),
        ("yearbuilt", "NUMBER", "Year Built", "Year the property was built", "IconCalendar"),
        ("bedrooms", "NUMBER", "Bedrooms", "Number of bedrooms", "IconBed"),
        ("offerballoonyears", "NUMBER", "Offer Balloon Years", "Number of years for balloon payment", "IconCalendar"),
        ("offertermyears", "NUMBER", "Offer Term Years", "Number of years for offer term", "IconCalendar"),
        ("dateposted", "DATE", "Orig Date Posted", "Original date the property was posted", "IconCalendar"),
        ("saledate", "DATE", "Sale Date", "Date of sale", "IconCalendar"),
        ("livingarea", "NUMBER", "Sq ft", "Living area in square feet", "IconRuler"),
        ("bathrooms", "NUMBER", "Bathrooms", "Number of bathrooms", "IconBath")
    ]

    # for testing let's trunccate fields_to_create to 19 fields
    # fields_to_create = fields_to_create[:19]

    ensure_custom_fields_exist(api, property_object_id, fields_to_create)

    # Look up the Opportunities object ID
    opportunities_object_id = get_object_id_by_name(api, "opportunity")
    if not opportunities_object_id:
        logger.error("Opportunities object not found")
        return

    # Check if the relation already exists
    existing_relations = get_existing_relations(api, opportunities_object_id, property_object_id)
    if existing_relations:
        logger.info("Relation between Property and Opportunities objects already exists")
    else:
        # Add relation to Opportunities object
        relation_data = {
            "fromDescription": "Linked Property",
            "fromIcon": "IconHome",
            "fromLabel": "Property",
            "fromName": "property",
            "fromObjectMetadataId": opportunities_object_id,
            "relationType": "ONE_TO_ONE",
            "toDescription": "Linked Opportunity",
            "toIcon": "IconTarget",
            "toLabel": "Opportunity",
            "toName": "opportunity",
            "toObjectMetadataId": property_object_id
        }

        try:
            created_relation = api.create_relation(relation_data)
            logger.info("Created relation between Property and Opportunities objects")
        except Exception as e:
            logger.error(f"Failed to create relation: {str(e)}")

    logger.info("Custom object, fields, and relation have been created or verified.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logger.exception("An error occurred during execution:")
```

### PR DESCRIPTION
**Pull request by Shubhdeep12**
this PR fixes #7327

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/table/components/TableSection.tsx [hunk 1]
```diff
@@ -30,7 +30,8 @@ const StyledSectionHeader = styled.div<{ isExpanded: boolean }>`
 const StyledSection = styled.div<{ isExpanded: boolean }>`
   max-height: ${({ isExpanded }) => (isExpanded ? '1000px' : 0)};
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/ui/layout/table/components/TableSection.tsx:31]: I agree with grep, lets keep overflow as it is !
```suggestion
   max-height: ${({ isExpanded }) => (isExpanded ? 'fit-content' : 0)};
```

File: packages/twenty-front/src/modules/ui/layout/table/components/TableSection.tsx [hunk 2]
```diff
@@ -30,7 +30,8 @@ const StyledSectionHeader = styled.div<{ isExpanded: boolean }>`
...
   opacity: ${({ isExpanded }) => (isExpanded ? 1 : 0)};
-  overflow: hidden;
+  overflow-y: auto;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/ui/layout/table/components/TableSection.tsx:33]:
```suggestion
   overflow: 'hidden';
```

**Review by ehconitin — COMMENTED** [review]
Left some comments!

**Review by ehconitin — APPROVED** [review]
