### PR TITLE
[BUGFIX] Create optimistic cache generate `recordGqlFields` from prefilled record

### LINKED ISSUE #10153: First New Record Flash
# Current behavior

https://github.com/user-attachments/assets/245edabc-9130-4007-b03b-cc9ae3a4fbfb

# Desired Behavior

Should not Flash

### LINKED ISSUE #10199: [0.42] Creating an empty record does not refresh the view
## Bug Description
On 0.42
When creating a new record, without any values. The table won't get hydrated. Also row seems to get a weird position.

https://github.com/user-attachments/assets/9619f92c-8bd2-47fb-96cf-2bfdd496b2db

## Expected behavior

Created row should appear

## Technical inputs
It seems like the optimistic behavior is broken regarding single record creation, this might be a good first track.
This might also be related to the server side next position computation 🤔 at least we're not updating the cache correctly with this position TBD

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
The record does not appear in the table because the optimistic record input cached does not fulfill the mutation response fields, which result in it being considered as invalid response
close #10199 
close https://github.com/twentyhq/twenty/issues/10153

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts [hunk 1]
```diff
@@ -102,6 +102,7 @@ export const useCreateOneRecord = <
       recordInput: {
         ...baseOptimisticRecordInputCreatedBy,
         ...recordInput,
+        position: Number.NEGATIVE_INFINITY,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts:105]: ***Review:*** Might be quite radical but we always want new record to be displayed on top

File: packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts [hunk 2]
```diff
@@ -24,9 +24,13 @@ export const useCreateOneRecordInCache = <T extends ObjectRecord>({
   const apolloClient = useApolloClient();
 
   return (record: ObjectRecord) => {
+    const prefilledRecord = prefillRecord({
+      objectMetadataItem,
+      input: record,
+    });
     const recordGqlFields = generateDepthOneRecordGqlFields({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts:31]: I would split this in two methods: 
generateDepthOneRecordGqlFields(objectMetadataItem)
generateRecordGqlFields(objectMetadataItem, record)

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts (hunk 2 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts:31]: Will do in dedicated PR

Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/cache/hooks/useCreateOneRecordInCache.ts:31]: https://github.com/twentyhq/twenty/pull/10499
