### PR TITLE
fix no billing subscription error

### LINKED ISSUE #625: [redbins] Billing error
from redbins
```
[31m[Nest] 1 - [39m03/06/2025, 10:04:34 PM [31m ERROR[39m [38;5;3m[CleanerWorkspaceService] [39m[31mError while processing workspace c714d5c0-36b2-4efc-9abe-c5ffe43df7b4 Donna AI: Error: No billing subscription found for workspace c714d5c0-36b2-4efc-9abe-c5ffe43df7b4 Donna AI[39m
```

### PR DESCRIPTION
**Pull request by etiennejouan**
closes https://github.com/twentyhq/core-team-issues/issues/625

Context : 
Soft-deleted workspaces no longer have any subscriptions. Computing inactivity causes an error.

### CODE REVIEW

File: packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts [hunk 1]
```diff
@@ -326,32 +326,33 @@ export class CleanerWorkspaceService {
...
-          daysSinceSoftDeleted >
-            this.inactiveDaysBeforeDelete - this.inactiveDaysBeforeSoftDelete &&
-          deletedWorkspacesCount < this.maxNumberOfWorkspacesDeletedPerExecution
-        ) {
-          this.logger.log(
-            `${dryRun ? 'DRY RUN - ' : ''}Destroying workspace ${workspace.id} ${workspace.displayName}`,
-          );
-          if (!dryRun) {
-            await this.workspaceService.deleteWorkspace(workspace.id);
+        if (workspace.deletedAt) {
```
Comment (prastoin) [inline packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts:329]: ***Question:*** If a user restores a workspace would it still has a `deletedAt` date defined ?
***Nitpick:*** Would use `isDefined`
***Nitpick:*** Could early continue or filter out deleted workspace on iterated workspaces line `327`

**Review by prastoin — COMMENTED** [review]
Nice fix ! I understand the global necessity to compute billing information on deleted workspace
But this feels weird, if workspace is deleted delete workspace 🤔 
```ts
        if (workspace.deletedAt) {
            // ...
            if (!dryRun) {
              await this.workspaceService.deleteWorkspace(workspace.id);
            }
         }
```

File: packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts (hunk 1 above)
Comment (etiennejouan) [reply packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts:329]: Q : User can't restore a workspace and if we restore it, we have to clear the deletedAt field, yes.
N1: You're right, thanks !
N2: It could be more optimised but not sure it would be clearer. I prefer to highlight the softDeleted 'branch', then if softDeleted for less than 7 days or if deletion workspace quota is reached : early continue and if not : delete

**Comment by etiennejouan** [comment]
> Nice fix ! I understand the global necessity to compute billing information on deleted workspace But this feels weird, if workspace is deleted delete workspace 🤔
> 
> ```ts
>         if (workspace.deletedAt) {
>             // ...
>             if (!dryRun) {
>               await this.workspaceService.deleteWorkspace(workspace.id);
>             }
>          }
> ```

Yes that's true. In our code, we are not consistant, we have both soft-delete/delete and delete/destroy. By design with our orm, deletedAt flags soft deleted records - so it mays be better to only have delete/destroy. 

WorkspaceService and other services are in soft-delete/delete mode, so I keep this way in this service.

File: packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts (hunk 1 above)
Comment (prastoin) [reply packages/twenty-server/src/engine/workspace-manager/workspace-cleaner/services/cleaner.workspace-service.ts]: > N2: It could be more optimised but not sure it would be clearer. I highlight the softDeleted 'branch', then if softDeleted for less than 7 days or if deletion workspace quota is reached : early continue and if not : delete.
But if you're not agree it's clearer, I modify - the cleaning logic is getting more and more complex, that's why I prefer readability over optim.

Yes ok makes sense, sounds good to me !

**Comment by prastoin** [comment]
> > Nice fix ! I understand the global necessity to compute billing information on deleted workspace But this feels weird, if workspace is deleted delete workspace 🤔
> > ```ts
> >         if (workspace.deletedAt) {
> >             // ...
> >             if (!dryRun) {
> >               await this.workspaceService.deleteWorkspace(workspace.id);
> >             }
> >          }
> > ```
> 
> Yes I agree, it's weid. In our code, we are not consistant, we have both soft-delete/delete and delete/destroy. With our orm, deletedAt flags soft deleted records - so it mays be better to only have delete/destroy.
> 
> WorkspaceService and other services are in soft-delete/delete mode, so I keep this direction.

I would maybe create a dedicated const that could make this abstraction readable, something suchas `isSoftDeletedWorkspace`.

**Review by prastoin — APPROVED** [review]
Approving as remains only nitpicks ! Well done lets gooooooo shiiiiip 🐑
