### PR TITLE
Fixed left padding for switcher icon on the table checkboxes #4351

### LINKED ISSUE #4351: Align the view switcher icon on the table checkboxes
# Current behavior

The view switcher icon is not aligned with the table checkboxes 

CleanShot 2024-03-06 at 19 05 26

# Desired behavior

The view switcher icon should be centered above the checkboxes

CleanShot 2024-03-06 at 19 07 38

CleanShot 2024-03-06 at 19 15 15

Make sure to keep the kanban column header name aligned with the view switcher icon:

CleanShot 2024-03-06 at 19 22 12

# Figma

Inspect the Figma to get the good dimensions:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=sNBVaMdbaG082qYQ-11

### PR DESCRIPTION
**Pull request by rathodvinod5**
Closes #4351  - Fixed spacing issue in TopBar file.

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx [hunk 1]
```diff
@@ -7,14 +7,18 @@ type TopBarProps = {
   rightComponent?: ReactNode;
   bottomComponent?: ReactNode;
   displayBottomBorder?: boolean;
+  removeSpacing?: boolean;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx:10]: @rathodvinod5 Have you identified places where we want to keep the left padding?
We should enforce consistent layout accross the app and we should find a good design rule. If the API has too man parameters that are not justified, it will be harder to maintain

**Review by charlesBochet — DISMISSED** [review]

File: packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx (hunk 1 above)
Comment (rathodvinod5) [reply packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx:10]: Yes, currently there are only 2 places from where the component being called.

Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/layout/top-bar/TopBar.tsx:10]: can we remove the padding everywhere? does it make sense?

**Review by FelixMalfait — APPROVED** [review]
I ended up just removing the left padding, it looks nice this way. Thanks for the attempt!
