### PR TITLE
fix(882): fixes negative number submission for employees input

### LINKED ISSUE #882: Negative number of employees
Company can have negative number of employees - solution: assure that number of employees can't be less than 1 and it has to be a whole number, you can't divide a human

Scenario:
1. Add new record in Companies or modify existing record and insert zero or negative number or fraction of number

Actual: Company can have half of employee or -2 employees
Expected: Company should have at least 1 whole employee, inserting fraction or number less than 1 should result in error/clear message to user
```[tasklist]
### Tasks
- [ ] Create a cast-as-positive-integer-or-null guard like the cast-as-integer-or-null guard
- [ ] Add a metadata "isPositive": true in CompanyViewField and pass it in the GenericEditableNumberCell
- [ ] Use the guard there
```

### PR DESCRIPTION
**Pull request by srikarsams**
Fixes #882

### CODE REVIEW

**Comment by srikarsams** [comment]
Hey @FelixMalfait, Preview environment is not being created for some reason. Could you please help?

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx [hunk 1]
```diff
@@ -31,12 +35,27 @@ export function GenericEditableNumberCellEditMode({ viewField }: OwnProps) {
     if (newText === fieldValue) return;
 
     try {
-      const numberValue = parseInt(newText);
+      let numberValue = parseInt(newText);
 
       if (isNaN(numberValue)) {
```
Comment (Weiko) [inline front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:40]: We can remove this check as it is already done in canBeCastAsPositiveIntegerOrNull

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx [hunk 2]
```diff
@@ -31,12 +35,27 @@ export function GenericEditableNumberCellEditMode({ viewField }: OwnProps) {
...
+
+        if (valueCastedAsPositiveNumberOrNull === null) {
+          throw Error('Not a number');
+        }
+
+        numberValue = valueCastedAsPositiveNumberOrNull;
+      }
+
       // TODO: find a way to store this better in DB
       if (numberValue > 2000000000) {
```
Comment (Weiko) [inline front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:60]: We can move this check to canBeCastAsPositiveIntegerOrNull
Also let's use Number.MAX_SAFE_INTEGER instead of 2000000000

File: front/src/utils/__tests__/cast-as-positive-integer-or-null.test.ts [hunk 3]
```diff
@@ -0,0 +1,116 @@
+import {
+  canBeCastAsPositiveIntegerOrNull,
+  castAsPositiveIntegerOrNull,
+} from '~/utils/cast-as-positive-integer-or-null';
+
+describe('canBeCastAsPositiveIntegerOrNull', () => {
```
Comment (Weiko) [inline front/src/utils/__tests__/cast-as-positive-integer-or-null.test.ts:6]: Thanks for adding tests!

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx (hunk 1 above)
Comment (srikarsams) [reply front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:40]: Hey @Weiko, thanks for the review.  canBeCastAsPositiveIntegerOrNull check will only happen when isPositive flag is true. isNaN check is outside of that guard. If isPositive flag is false, we can't use canBeCastAsPositiveIntegerOrNull at all. Please correct me if I'm wrong. Thanks

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx (hunk 2 above)
Comment (srikarsams) [reply front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:60]: Hey @Weiko, if we move this to canBeCastAsPositiveIntegerOrNull, we can't do this check for scenarios where isPositive flag is false. Please let me know your thoughts. Thank you

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx (hunk 1 above)
Comment (Weiko) [reply front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:40]: That's true 🙂. I think at some point we can refactor both utils (castAsInteger and the new castAsPositive), the logic is very similar. The *AsInteger should do most of the validations and be called before *AsPositiveInteger imo. We can think about it later 👍

File: front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx (hunk 2 above)
Comment (Weiko) [reply front/src/modules/ui/table/editable-cell/type/components/GenericEditableNumberCellEditMode.tsx:60]: Yes indeed, same as my other comment.

nit: You can still use Number.MAX_SAFE_INTEGER at least. We might want to store in DB (in viewFieldMetada) later

**Review by Weiko — APPROVED** [review]
LGTM, thanks!
