### PR TITLE
fix: display label identifier field input in Show Page

### LINKED ISSUE #3003: [Timebox] Display the label identifer again on shows/ detail pages
# Current behavior

The identifier is displayed as a field:

Screenshot 2023-12-15 at 11 43 33

# Desired behavior

The identifier should not be displayed as a field but appear under the picture/initials:

Screenshot 2023-12-15 at 11 44 13

### PR DESCRIPTION
**Pull request by thaisguigon**
Fixes #3003

### CODE REVIEW

File: packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx [hunk 1]
```diff
@@ -102,8 +102,12 @@ export const SettingsObjectDetail = () => {
                         onEdit={() =>
                           navigate(`./${getFieldSlug(activeMetadataField)}`)
                         }
-                        onDisable={() =>
-                          disableMetadataField(activeMetadataField)
+                        onDisable={
+                          activeMetadataField.id ===
+                            activeObjectMetadataItem.labelIdentifierFieldMetadataId ||
+                          activeMetadataField.name === 'name'
```
Comment (Weiko) [inline packages/twenty-front/src/pages/settings/data-model/SettingsObjectDetail.tsx:108]: I think it's dangerous to rely on "name" here, I'm not sure we want to keep that in the future and we probably want to allow users to define their own labelIdentifier whilst keeping name as an independent field?
wdyt @charlesBochet ?

**Review by lucasbordeau — APPROVED** [review]

**Comment by Bonapara** [comment]
🎉🎉🎉
