### PR TITLE
fix: add dark mode version of Settings Object cover image

### LINKED ISSUE #3078: Settings Objects - Cover image is not adapted for Dark Mode
## Bug Description

In Settings Object page, the Cover Image matches the Light Theme color scheme, but it does not change when the Dark Theme is selected.

Image

## Expected behavior

When the Dark Theme is selected, the Cover Image should match the Dark Theme color scheme.

Image link: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17544-86243&mode=design&t=JJOijbrWPEg9mHWr-11

### PR DESCRIPTION
**Pull request by thaisguigon**
Fixes #3078

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
LGTM!

File: packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx [hunk 1]
```diff
@@ -8,11 +8,15 @@ import { Card } from '@/ui/layout/card/components/Card';
...
 
-import CoverImage from '../assets/cover.png';
+import DarkCoverImage from '../assets/cover-dark.png';
+import LightCoverImage from '../assets/cover-light.png';
 
 const StyledCoverImageContainer = styled(Card)`
   align-items: center;
-  background-image: url(${CoverImage.toString()});
+  background-image: ${({ theme }) =>
+    theme.name === 'light'
```
Comment (Weiko) [inline packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx:17]: Just wondering if we should change theme.ts and align with the backend to avoid potential bugs, it seems we store ColorScheme.Light with 'Light' in DB and not 'light'.

Comment (Weiko) [reply packages/twenty-front/src/modules/settings/data-model/objects/SettingsObjectCoverImage.tsx:17]: cc @charlesBochet
