### PR TITLE
fix: minor color changes

### LINKED ISSUE #15597: small color fix
Color issue on `/plan-required/payment-success` modal:

(seems to be dark mode in light mode)

Image

### PR DESCRIPTION
**Pull request by BKM14**
Closes #15597

The `color` of `OnBoardingModalCircularIcon` was set to `gray`. Now it is set to `inverted` and it is displayed properly. I couldn't figure out how to reach the onboarding screen, so I created a temporary path and rendered the element there to verify the changes. Attaching screenshots of the same.
Screenshot from 2025-11-05 00-11-05

Screenshot from 2025-11-05 00-10-32

Additionally, a border has been added to the color picker icons.
Screenshot from 2025-11-05 00-12-23

I noticed that the dropdown after clicking on the icon also renders a bunch of colors. Do let me know if these need the same border as well.
Screenshot from 2025-11-05 00-12-37

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx [hunk 1]
```diff
@@ -48,6 +48,9 @@ const StyledColorSample = styled(ColorSample)`
 
   margin-right: ${({ theme }) => theme.spacing(3.5)};
   margin-left: ${({ theme }) => theme.spacing(3.5)};
+  border: 1px solid
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx]: You can change directly the ColorSample component in twenty ui, because they all need the same border, as you mentioned in your description :)

Comment (BKM14) [reply packages/twenty-front/src/modules/settings/data-model/fields/forms/select/components/SettingsDataModelFieldSelectFormOptionRow.tsx]: Ah yes, I was just being safe in case it was used anywhere else. I have made the changes.

**Comment by BKM14** [comment]
@bosiraphael, suggestions are resolved now. Thanks.

**Comment by bosiraphael** [comment]
Thank you @BKM14. The code looks good to me. I'm just checking with @Bonapara if we want to also update the borders for the components in the dashboards:
CleanShot 2025-11-13 at 10 27 23@2x

**Comment by bosiraphael** [comment]
I pushed some updates to make it look like this after discussion with @Bonapara 
CleanShot 2025-11-13 at 10 49 34@2x

**Review by bosiraphael — APPROVED** [review]
LGTM
