### PR TITLE
Make filters and sorts work on record page pagination

### LINKED ISSUE #7929: Record Page - Record show page pagination does not take filters into account
## Bug Description

Steps to reproduce:

1. Open companies view.
step-1-no-filter

2. Add a filter that reduces the number of records in view.
step-2-filter

3. Open any company.
step-3-incorrect-company-count

In this example the show page for Claap shows `9 of 13 in Companies`.

## Expected behavior

In the example the show page for Claap should show `2 of 3 in Companies`.

### PR DESCRIPTION
**Pull request by bosiraphael**
Fixes #7929 

This PR implements a system to capture and preserve the filters and sorts when navigating from an index view to a record show page. This information is stored in a context store component state.

This allows users to navigate between records inside the record page while maintaining context from the index view.

### CODE REVIEW

File: packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromActiveFieldsOfViewOrDefaultView.ts [hunk 1]
```diff
@@ -1,22 +1,27 @@
+import { MAIN_CONTEXT_STORE_INSTANCE_ID } from '@/context-store/constants/MainContextStoreInstanceId';
+import { contextStoreRecordShowParentViewComponentState } from '@/context-store/states/contextStoreRecordShowParentViewComponentState';
 import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
 import { useFilterValueDependencies } from '@/object-record/record-filter/hooks/useFilterValueDependencies';
-import { useViewOrDefaultViewFromPrefetchedViews } from '@/views/hooks/useViewOrDefaultViewFromPrefetchedViews';
-import { useQueryVariablesFromView } from './useQueryVariablesFromView';
+import { useRecoilComponentValueV2 } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentValueV2';
+import { getQueryVariablesFromView } from './useQueryVariablesFromView';
 
 export const useQueryVariablesFromActiveFieldsOfViewOrDefaultView = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromActiveFieldsOfViewOrDefaultView.ts]: rename hook

File: packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromView.ts [hunk 2]
```diff
@@ -1,55 +1,32 @@
...
-import { getFilterableFieldsWithVectorSearch } from '@/views/utils/getFilterableFieldsWithVectorSearch';
-import { mapViewFilterGroupsToRecordFilterGroups } from '@/views/utils/mapViewFilterGroupsToRecordFilterGroups';
-import { mapViewFiltersToFilters } from '@/views/utils/mapViewFiltersToFilters';
-import { mapViewSortsToSorts } from '@/views/utils/mapViewSortsToSorts';
-import { isDefined } from 'twenty-shared/utils';
+import { RecordSort } from '@/object-record/record-sort/types/RecordSort';
 
-export const useQueryVariablesFromView = ({
-  view,
+export const getQueryVariablesFromView = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/hooks/useQueryVariablesFromView.ts]: move to utils + rename

File: packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx [hunk 3]
```diff
@@ -68,37 +75,48 @@ export const RecordShowRightDrawerOpenRecordButton = ({
...
+              objectNameSingular === CoreObjectNameSingular.Task
+              ? 'richText'
+              : 'timeline'
+            : activeTabIdInRightDrawer;
+
+        setActiveTabIdInRecordPage(tabIdToOpen);
+
+        const parentView = snapshot.getLoadable(parentViewState).getValue();
+
+        if (parentView?.parentViewObjectNameSingular !== objectNameSingular) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx:93]: this might be factorizable into a useNavigateToShowPageRecord

**Review by charlesBochet — APPROVED** [review]
