### PR TITLE
Fix  members table column alignment

### LINKED ISSUE #12287: Members table column alignement
# Current behavior

Image

# Desired Behavior

The expiry chips should be aligned with their headers and provide more room for the email column.

### PR DESCRIPTION
**Pull request by DivyanshuLohani**
Fixes: #12287 

image

### CODE REVIEW

File: packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx [hunk 1]
```diff
@@ -308,21 +308,21 @@ export const SettingsWorkspaceMembers = () => {
           {isNonEmptyArray(workspaceInvitations) && (
             <StyledTable>
               <TableRow
-                gridAutoColumns="150px 1fr 1fr"
```
Comment (etiennejouan) [inline packages/twenty-front/src/pages/settings/SettingsWorkspaceMembers.tsx:311]: Can you try increasing to 300px ?

**Review by etiennejouan — COMMENTED** [review]
Hi @DivyanshuLohani 👋  Thank you for your contribution :) 

It looks good but does not work as expected with long email ⬇️ 
Screenshot 2025-05-28 at 16 06 26

**Review by etiennejouan — APPROVED** [review]
> Sorry I am new to contributing I didn't test it well my bad

It's ok ! Please, feel free to take other issues. Thank you for your contribution :)
