### PR TITLE
fix(sso): improve enterprise key var management

### LINKED ISSUE #8070: Error about missing enterprise key when entering Security tab
**Scenario:**
1. Log in
2. Go to Settings > Security

**Actual:** When user doesn't have set key, error in UI and logs appears informing about missing enterprise key
image

**Expected:** No error must appear when no key is set

Error:
```
[Nest] 85520  - 10/25/2024, 6:42:08 PM   ERROR [ExceptionsHandler] Enterprise key must be defined to use SSO
Error: Enterprise key must be defined to use SSO
    at SSOProviderEnabledGuard.canActivate (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/auth/guards/sso-provider-enabled.guard.ts:19:13)
    at GuardsConsumer.tryActivate (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
    at canActivateFn (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:155:59)
    at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:73:37)
    at Object.listSSOIdentityProvidersByWorkspaceId (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:30)
    at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/user/Desktop/projects/twenty/node_modules/graphql-yoga/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
    at async Promise.all (index 0)
Exception Captured
  {
    operation: { name: 'ListSSOIdentityProvidersByWorkspaceId', type: 'query' },
    document: 'query ListSSOIdentityProvidersByWorkspaceId {\n' +
      '  listSSOIdentityProvidersByWorkspaceId {\n' +
      '    type\n' +
      '    id\n' +
      '    name\n' +
      '    issuer\n' +
      '    status\n' +
      '    __typename\n' +
      '  }\n' +
      '}',
    user: User {
      id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
      firstName: 'Tim',
      lastName: 'Apple',
      email: 'tim@apple.dev',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
      canImpersonate: false,
      createdAt: 2024-10-25T16:31:19.234Z,
      updatedAt: 2024-10-25T16:31:19.234Z,
      deletedAt: null,
      defaultWorkspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419'
    }
  }
  [
    Error: Enterprise key must be defined to use SSO
        at SSOProviderEnabledGuard.canActivate (/home/user/Desktop/projects/twenty/packages/twenty-server/src/engine/core-modules/auth/guards/sso-provider-enabled.guard.ts:19:13)
        at GuardsConsumer.tryActivate (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
        at canActivateFn (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:155:59)
        at target (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-context-creator.js:73:37)
        at Object.listSSOIdentityProvidersByWorkspaceId (/home/user/Desktop/projects/twenty/node_modules/@nestjs/core/helpers/external-proxy.js:9:30)
        at field.resolve (/home/user/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:48)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at /home/user/Desktop/projects/twenty/node_modules/graphql-yoga/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
        at async Promise.all (index 0) {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'Enterprise key must be defined to use SSO'
      }
    }
  ]

```

### PR DESCRIPTION
**Pull request by AMoreaux**
Resolve https://github.com/twentyhq/twenty/issues/8070

### CODE REVIEW

File: packages/twenty-front/src/pages/settings/security/SettingsSecurity.tsx [hunk 1]
```diff
@@ -23,7 +23,18 @@ export const SettingsSecurity = () => {
     >
       <SettingsPageContainer>
         <Section>
-          <H2Title title="SSO" description="Configure an SSO connection" />
+          <H2Title
+            title="SSO"
+            description="Configure an SSO connection"
+            addornment={
+              <Tag
```
Comment (FelixMalfait) [inline packages/twenty-front/src/pages/settings/security/SettingsSecurity.tsx:30]: I feel like in future iteration it will be worth abstraction this into something re-usable but we can do it later!

**Review by FelixMalfait — APPROVED** [review]
Great work! I just made a very subjective variable name change
