### PR TITLE
UNAUTHORIZED gmail error 

### LINKED ISSUE #11895: insufficient permission
## Description

Generated from note: messaging error handling

We throw an throw `MessageImportExceptionCode.UNKNOWN`

while we should send an Insufficient permission

Sentry reference :

<https://twenty-v7.sentry.io/issues/6565219219/?environment=prod&project=4507072499810304&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=freq&stream_index=3>

 Created by: Guillaume Lancrenon

### PR DESCRIPTION
**Pull request by guillim**
# Gmail OAuth authentication flow issues

### TLDR
This error is not an error and therefore should be treated as a simple redirect with a snackbar.

### More details
Fixing incomplete OAuth token exchange processes and improving error handling for empty Gmail inboxes. 
The changes include modifications to OAuth guards, to ensure that if a user clicks "cancel" instead of completing the authentication workflow if fails

## Before:
Redirection from `/settings/accounts` to `app.twenty.com` with an `UNAUTHORIZED` error

## After :
Screenshot 2025-05-26 at 18 04 37

Fixes https://github.com/twentyhq/twenty/issues/11895

### CODE REVIEW

**Comment by charlesBochet** [comment]
@guillim closing it to keep the history clean, let's re-open once ready!

File: packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx [hunk 1]
```diff
@@ -36,6 +40,22 @@ export const SettingsAccounts = () => {
     recordGqlFields: generateDepthOneRecordGqlFields({ objectMetadataItem }),
   });
 
+  const { enqueueSnackBar } = useSnackBar();
+  const [searchParams, setSearchParams] = useSearchParams();
+  const errorMessage = searchParams.get('errorMessage');
+
+  useEffect(() => {
```
[the remark this answers is not in the document]
Comment (charlesBochet) [reply packages/twenty-front/src/pages/settings/accounts/SettingsAccounts.tsx:47]: Let's create a TriggerSnackBarErrorFromUrlErrorMessageEffect that is instantiated in app provider

File: packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts [hunk 2]
```diff
@@ -75,6 +82,7 @@ export class GuardRedirectService {
       customDomain: string | null;
       isCustomDomainEnabled?: boolean;
     },
+    pathname: string,
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts:85]: same make this object

File: packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts [hunk 3]
```diff
@@ -25,6 +25,7 @@ export class GuardRedirectService {
       customDomain: string | null;
       isCustomDomainEnabled?: boolean;
     },
+    pathname = '/verify',
```
[the remark this answers is not in the document]
Comment (charlesBochet) [reply packages/twenty-server/src/engine/core-modules/guard-redirect/services/guard-redirect.service.ts:28]: (neat)

File: packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts [hunk 4]
```diff
@@ -128,10 +128,11 @@ export class DomainManagerService {
   computeRedirectErrorUrl(
     errorMessage: string,
     workspace: WorkspaceSubdomainCustomDomainAndIsCustomDomainEnabledType,
+    pathname: string,
   ) {
     const url = this.buildWorkspaceURL({
       workspace,
-      pathname: '/verify',
+      pathname: pathname,
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts:135]: style: pathname,

File: packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts [hunk 5]
```diff
@@ -58,4 +92,30 @@ export class GoogleAPIsOauthExchangeCodeForTokenGuard extends AuthGuard(
...
+      });
+
+      if (!workspace) {
+        throw new Error(
+          `Error extracting workspace from transientToken for Google APIs connect for ${workspaceId}`,
+        );
+      }
+
+      return workspace;
+    } catch (tokenError) {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-oauth-exchange-code-for-token.guard.ts:114]: remove catch
