### PR TITLE
Fix: Save view by clicking outside popup while editing

### LINKED ISSUE #4657: Save view by clicking outside popup while editing
# Current Behavior

Pressing `Enter` while editing a view is necessary to save changes. However, this momentarily disables the "Delete" button, giving the impression it has been clicked.

https://github.com/twentyhq/twenty/assets/19412894/7c6c0d3e-67a6-42e0-883f-ba14234c1750

# Desired Behavior

Changes should be saved when clicking outside the popup or closing it with the "X" button. 

The popup should close instantly and save data in the background when 'Enter' is pressed, the popup is clicked outside, or the 'X' button is clicked.

### PR DESCRIPTION
**Pull request by jeet1desai**
Fix: #4657 

https://github.com/twentyhq/twenty/assets/52026385/5e9441ea-027c-44e4-8a9a-eb381ff09086

### CODE REVIEW

File: packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx [hunk 1]
```diff
@@ -62,13 +65,22 @@ export const ViewPickerDropdown = () => {
   const { getIcon } = useIcons();
   const CurrentViewIcon = getIcon(currentViewWithCombinedFiltersAndSorts?.icon);
 
+  const handleClickOutside = async () => {
+    if (isViewsListDropdownOpen && viewPickerMode !== 'list') {
+      if (viewPickerMode !== 'create') {
+        await handleUpdate();
+      }
+    }
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/views/view-picker/components/ViewPickerDropdown.tsx:73]:
```suggestion
   if (isViewsListDropdownOpen && viewPickerMode === 'edit') {
      await handleUpdate();
    }
```

File: packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContent.tsx [hunk 2]
```diff
@@ -102,11 +102,18 @@ export const ViewPickerCreateOrEditContent = () => {
 
   const { availableFieldsForKanban } = useGetAvailableFieldsForKanban();
 
+  const handleClose = async () => {
+    if (viewPickerMode !== 'create') {
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContent.tsx:106]:
```suggestion
    if (viewPickerMode === 'edit') {
```

**Review by bosiraphael — COMMENTED** [review]
Hello @jeet1desai, thank you for contributing :) Good work! I just left a couple of suggestions before approving.

**Review by bosiraphael — APPROVED** [review]
LGTM :) Thank you @jeet1desai
