### PR TITLE
Fix file preview modal to always open full screen from command menu

### LINKED ISSUE #16434: File preview should be opened in full screen
**Current behavior:**
It's too small and impossible to read, preview becomes useless.
Image

**Desired behavior:**
Modal should be full screen

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
Closes #16434 

https://github.com/user-attachments/assets/ecf838ea-9f59-42d9-9a2d-97a4fa3b7910

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx [hunk 1]
```diff
@@ -223,11 +224,13 @@ export const Modal = ({
...
   dataGloballyPreventClickOutside = false,
   shouldCloseModalOnClickOutsideOrEscape = true,
+  ignoreContainer = false,
 }: ModalProps) => {
   const isMobile = useIsMobile();
   const modalRef = useRef<HTMLDivElement>(null);
   const { container } = useModalContainer();
-  const isInContainer = container !== null;
+  const effectiveContainer = ignoreContainer ? null : container;
+  const isInContainer = effectiveContainer !== null;
```
Comment (Devessier) [inline packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx]:
```suggestion
  const isInContainer = isDefined(effectiveContainer);
```

File: packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx [hunk 2]
```diff
@@ -300,8 +303,8 @@ export const Modal = ({
     </AnimatePresence>
   );
 
-  if (container !== null) {
-    return createPortal(modalContent, container);
+  if (effectiveContainer !== null) {
```
Comment (Devessier) [inline packages/twenty-front/src/modules/ui/layout/modal/components/Modal.tsx]:
```suggestion
  if (isDefined(effectiveContainer)) {
```

**Review by Devessier — COMMENTED** [review]
Two nitpicks. Otherwise it looks good to me. Thank you.

**Review by Devessier — APPROVED** [review]
