### PR TITLE
fix(approved-access-domain): Improve ux 

### LINKED ISSUE #13324: Friction with adding Approved Access Domains
# Bug Description

There are a number of small issues I ran into when trying to set up Approved Access Domains.

## 1. Confirmation email never arrived

I didn't know that I needed to set up SMTP credentials first, and it took me a while to figure out that the "email sent" logs I was seeing were just a logger function.

It would be helpful if the Approved Domains page showed a warning when the email driver is set to LOGGER.

## 2. Broken image link in email

The Workspace logo in the email message fails to load with a 403 Forbidden Resource error

Image

## 3. Approval status doesn't update

After clicking the **Validate domain** button, when the Approved Domains page opens it shows a success message down at the bottom of the screen, but the domain still says "Pending" and it doesn't update.

Image

Image

## 4. Reloading Validate Domain link triggers error

Because of the ambiguity above, I reloaded the page to see if the domain was actually approved (it was). This however triggers an error message. If the domain is already approved, it would be ideal if the message instead just confirmed that the domain was already approved.

Image

### PR DESCRIPTION
**Pull request by AMoreaux**
Fix #13324

### CODE REVIEW

File: packages/twenty-emails/src/constants/DefaultWorkspaceLogo.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+export const DEFAULT_WORKSPACE_LOGO =
+  'https://twentyhq.github.io/placeholder-images/workspaces/twenty-logo.png';
```
Comment (FelixMalfait) [inline packages/twenty-emails/src/constants/DefaultWorkspaceLogo.ts:2]: This is 32x32 and therefore will be pixelized in this context, could we replace it on the placeholder-images by a slightly higher res?

**Review by FelixMalfait — APPROVED** [review]
