### PR TITLE
fix: hidden settings menu affects settings layout

### LINKED ISSUE #6746: Hidden left menu affects Settings layout
**Scenario:**
1. Log in
2. Hide left menu
3. Go to Settings using shortcut G + S

**Actual:** Settings layout is moved to the left
[Uploading Screencast from 2024-08-26 18-25-07.webm…]()

**Expected:** Main page layout shouldn't affect the Settings

### PR DESCRIPTION
**Pull request by Khaan25**
This PR fixes #6746

### CODE REVIEW

File: packages/twenty-front/src/utils/currentPage.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { useLocation } from 'react-router-dom';
+
+/**
+ * Custom hook to check if the current route matches the given path.
+ * @param path The route to match.
+ * @returns True if the current route matches the given path, false otherwise.
+ */
+export const useIsRoute = (path: string): boolean => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/utils/currentPage.ts:8]: a few feedbacks about this file:
1) we don't add JS doc in the project as we try to avoid comments and we are already using typescript to provide a nice dev xp. Function names should be clear enough to avoid doing it
2) useIsRoute is a hook so it should not be in a utils folder
3) I don't thin this s actually useful, we can just do useLocation().pathname === path whenever we need

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx [hunk 2]
```diff
@@ -109,11 +110,12 @@ export const PageHeader = ({
   const isMobile = useIsMobile();
   const theme = useTheme();
   const isNavigationDrawerOpen = useRecoilValue(isNavigationDrawerOpenState);
+  const isSettingsPage = useIsRoute('/settings/profile');
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx:113]: we should not only check for settings/profile but for all settings route

File: packages/twenty-front/src/utils/currentPage.ts (hunk 1 above)
Comment (charlesBochet) [reply packages/twenty-front/src/utils/currentPage.ts:8]: So I would remove this hook actually

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx (hunk 2 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx:113]: https://stackoverflow.com/questions/61235191/react-router-v6-check-if-path-matches-a-pattern

**Review by charlesBochet — COMMENTED** [review]
Thanks @Khaan25, I have left comments :)

File: packages/twenty-front/src/utils/currentPage.ts (hunk 1 above)
Comment (Khaan25) [reply packages/twenty-front/src/utils/currentPage.ts:8]: Right. I'll remove it.

I was also thinking the same

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx (hunk 2 above)
Comment (Khaan25) [reply packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx:113]: Thanks for the link, I'll have a look

**Comment by Khaan25** [comment]
There you go! @charlesBochet

File: packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx [hunk 3]
```diff
@@ -109,14 +110,15 @@ export const PageHeader = ({
 }: PageHeaderProps) => {
   const isMobile = useIsMobile();
   const theme = useTheme();
-  const isNavigationDrawerExpanded = useRecoilValue(
-    isNavigationDrawerExpandedState,
-  );
+  const isNavigationDrawerOpen = useRecoilValue(isNavigationDrawerOpenState);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx:113]: not sure why you changed the state name here

Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/layout/page/PageHeader.tsx:113]: this is actually breaking the app

**Review by charlesBochet — COMMENTED** [review]
@Khaan25 Thanks for pushing changes/

1) I have taken a new look and found that we actually already have a
`useIsSettingsPage` hook

2) fixing the state name (mentioned in comment), we are still having a blank Settings menu
image

**Comment by Khaan25** [comment]
That's strange. I've tested it multiple times. Let me double check and get back to you.

Regarding the change, there was new code on the repo and I pulled in the latest changes.

**Comment by Khaan25** [comment]
Here you go! @charlesBochet 

It's fixed :) Let me know if there's any other issue with more points 😄You can assign me

https://github.com/user-attachments/assets/1384053a-d048-437a-838d-d3bb67a407be

**Comment by Khaan25** [comment]
Hey, could you review it? I can work on other issues?

**Comment by Khaan25** [comment]
Hey @charlesBochet, could you please review :)

**Comment by charlesBochet** [comment]
On it :)

File: packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerCollapseButton.tsx [hunk 4]
```diff
@@ -28,9 +30,22 @@ export const NavigationDrawerCollapseButton = ({
...
     isNavigationDrawerExpandedState,
   );
+  const isNavigationDrawerExpanded = useRecoilValue(
+    isNavigationDrawerExpandedState,
+  );
+
+  // Check if the user is on the settings page and the navigation drawer is not expanded
+  // Then open it automatically
+  useEffect(() => {
+    if (!isNavigationDrawerExpanded && isSettingsPage) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerCollapseButton.tsx:45]: we don't put side effects in components as we don't want to encourage developers to implement behaviors during rendering (this is pushing them to take dependencies on variables and trigger re-renders). Instead, we either:
- implement sync behaviors (in callbacks, event handlers, ...)
- move useEffects to ComponentEffects that have no children so it's not a big deal from a performance perspective

**Review by charlesBochet — COMMENTED** [review]
Current behavior is functional but I'm not a fan of this useEffect

File: packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerCollapseButton.tsx (hunk 4 above)
Comment (Khaan25) [reply packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerCollapseButton.tsx:45]: Right. I should be creating a custom hook to achieve it, right?

**Comment by Khaan25** [comment]
I believe that we need to have this useEffect because it's gonna only trigger it when we've settings page :)

I really thought about solving without useEffect but I ran into bugs as we've had before.

File: packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts [hunk 5]
```diff
@@ -5,13 +5,24 @@ import { AppHotkeyScope } from '../types/AppHotkeyScope';
 
 import { useSequenceHotkeys } from './useSequenceScopedHotkeys';
 
-export const useGoToHotkeys = (key: Keys, location: string) => {
+type GoToHotkeysProps = {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts:8]: changing the API to take an object which is better from a dev XP as parameters are named when using the hook

File: packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffectsProvider.tsx [hunk 6]
```diff
@@ -0,0 +1,37 @@
+import { GoToHotkeyItemEffect } from '@/app/effect-components/GoToHotkeyItemEffect';
+import { useNonSystemActiveObjectMetadataItems } from '@/object-metadata/hooks/useNonSystemActiveObjectMetadataItems';
+import { isNavigationDrawerExpandedState } from '@/ui/navigation/states/isNavigationDrawerExpanded';
+import { navigationDrawerExpandedMemorizedState } from '@/ui/navigation/states/navigationDrawerExpandedMemorizedState';
+import { navigationMemorizedUrlState } from '@/ui/navigation/states/navigationMemorizedUrlState';
+import { useGoToHotkeys } from '@/ui/utilities/hotkey/hooks/useGoToHotkeys';
+import { useLocation } from 'react-router-dom';
+import { useRecoilCallback } from 'recoil';
+
+export const GotoHotkeysEffectsProvider = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/app/effect-components/GotoHotkeysEffectsProvider.tsx:10]: I'm actually only renaming this file from GoToHokeysEffect

File: packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts [hunk 7]
```diff
@@ -5,13 +5,24 @@ import { AppHotkeyScope } from '../types/AppHotkeyScope';
...
+  key: Keys;
+  location: string;
+  preNavigateFunction?: () => void;
+};
+
+export const useGoToHotkeys = ({
+  key,
+  location,
+  preNavigateFunction,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts:17]: passing a a preNavigationFunction to update the problematic state

File: packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts (hunk 5 above)
Comment (Khaan25) [reply packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts:8]: Yes, I fully agree, Object is way more easier to debug and use. 

I always to that :)

**Comment by charlesBochet** [comment]
@Khaan25 I have made some changes to avoid useEffects. Could you pull the changes and see if the functional behavior look good?

**Comment by Khaan25** [comment]
Sure, let me try

File: packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts (hunk 7 above)
Comment (Khaan25) [reply packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useGoToHotkeys.ts:17]: Could you please explain me how this part is working?

I mean we did avoid useEffect but how's it solving the problem?

**Comment by charlesBochet** [comment]
@Khaan25 I can't reproduce, what are you doing to get this error?

**Comment by charlesBochet** [comment]
I think we are good, I'll merge it :)

**Review by charlesBochet — APPROVED** [review]

**Comment by Khaan25** [comment]
I just ran the twenty-front, maybe it's cache or something. Will try again and let you know it gives error again
