### PR TITLE
fix: Create a client config function that is retrieved when app is loading

### LINKED ISSUE #436: Create a client config function that is retrieved when app is loaded
**Issue:** 
On the frontend we don't always have access to config parameters from the backend.
For example, to prefill the login/password in local env I had to check node_env.
Or if tomorrow we want to hide the Google sign-in button if Google Auth parameters weren't filled in server.env

**Backend:**
- Create graphQL field named clientConfig  (resolver)
-  It could return could be something like this
```
{
  "flags": {
     "display_google_login":  process.env.AUTH_GOOGLE_CLIENT_ID !== ...
     "prefill_login_with_seed": process.env.NODE_ENV === ...
  }  
}
```

**Frontend**
- Do a request to load this clientConfig when app is loaded (no need to refresh automatically or implement any complex behavior, loading once when app is loaded is enough)
- Create a client config module with a provider that apps can access to retrieve config (it's better to abstract with a module that using recoil directly to retrieve the module, cf userProvider which I think was done this way already)

### PR DESCRIPTION
**Pull request by deepaksing**
Fixes #436

### CODE REVIEW

File: front/src/modules/auth/states/prefillLoginWithSeed.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import { atom } from 'recoil';
+
+export const prefillLoginWithSeed = atom<boolean>({
+  key: 'prefillLoginWithSeed',
+  default: true,
```
Comment (FelixMalfait) [inline front/src/modules/auth/states/prefillLoginWithSeed.ts:5]: probably default behavior should be false for seeds, we usually want to fall back on the production behavior (if e.g. the clientConfig happens to fail in prod because user has bad network, then we don't want strange a strange behavior like this login happening)

File: front/src/providers/clientConfig/ClientConfigProvider.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+export const ClientConfigProvider: React.FC<React.PropsWithChildren> = ({
+  children,
+}) => {
+  const [, setDisplayGoogleLogin] = useRecoilState(displayGoogleLogin);
+  const [, setPrefillLoginWithSeed] = useRecoilState(prefillLoginWithSeed);
+  const clientConfig = useFetchClientConfig();
+
+  useEffect(() => {
+    setDisplayGoogleLogin(clientConfig?.display_google_login ?? true);
+    setPrefillLoginWithSeed(clientConfig?.prefill_login_with_seed ?? true);
```
Comment (FelixMalfait) [inline front/src/providers/clientConfig/ClientConfigProvider.tsx:17]: false

File: server/package.json [hunk 3]
```diff
@@ -9,7 +9,7 @@
     "prebuild": "rimraf dist",
     "build": "nest build",
     "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
-    "start": "nest start",
+    "start": "set NODE_ENV=development&& nest start",
```
Comment (FelixMalfait) [inline server/package.json:12]: Are you on Windows? I think it's "export" on unix no? 
What made you put it here vs .env, it didn't work there? (just curious, not saying it's best in .env!)

File: front/src/modules/auth/states/displayGoogleLogin.ts [hunk 4]
```diff
@@ -0,0 +1,6 @@
+import { atom } from 'recoil';
+
+export const displayGoogleLogin = atom<boolean>({
```
Comment (FelixMalfait) [inline front/src/modules/auth/states/displayGoogleLogin.ts:3]: Tbd how this will evolve when we have a great number of feature toggles in the future.
For now I think your approach is the best and cleanest, and we can merge like this in my opinion.
But one day we'll probably 50+ state (feature flags of all kinds), in that case maybe a single clientConfig state with an array would work out best

**Review by FelixMalfait — COMMENTED** [review]
Great work! 🙌

File: server/package.json (hunk 3 above)
Comment (deepaksing) [reply server/package.json:12]: yes, i am on windows. 
in this blog https://tacomanator.medium.com/environments-with-create-react-app-7b645312c09d.
i read that for react,

> **The value of NODE_ENV is set automatically to development (when using npm start), test (when using npm test) or production (when using npm build).**

So i thought of doing the same in nest.js(server), thats why i am setting the NODE_ENV to development for yarn start.

File: front/src/modules/auth/states/displayGoogleLogin.ts (hunk 4 above)
Comment (deepaksing) [reply front/src/modules/auth/states/displayGoogleLogin.ts:3]: Thanks for the suggesetion, i will work on this.
