### PR TITLE
Fix API key not displayed

### LINKED ISSUE #9761: API key is not displayed when creating a new one
## Bug Description

In Settings > (Advanced Settings) > API & Webhooks

API key is not displayed when creating a new one

## Expected behavior

Creating a new API key should display the token for the first time after creation

## Technical inputs

Graphql response seems to return the token but the FE does not dispay it

### PR DESCRIPTION
**Pull request by FelixMalfait**
Fixes #9761

Instead of cleaning RecoilState we should keep the api key visible as long as the user didn't refresh/leave the app, it's better from a UX perspective and the code is also more elegant, removing a useEffect

Note: the root cause of the bug was a missing "/settings" path in isMatchingLocation in useCleaningRecoilState (due to the recent refactoring) ; but I think this fix is better

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/states/activityTitleHasBeenSetFamilyState.ts [hunk 1]
```diff
@@ -1,9 +0,0 @@
-import { createFamilyState } from '@/ui/utilities/state/utils/createFamilyState';
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/activities/states/activityTitleHasBeenSetFamilyState.ts:1]: This isn't directly related to this PR but this wasn't used anywhere

**Review by Weiko — APPROVED** [review]
LGTM
