### PR TITLE
Fix inline cell interactions

### LINKED ISSUE #831: While editing the name of a person, pressing the "delete" keyboard closes the side-panel
I wanted to remove the 3 from Collison3 but instaed of removing the letter, the whole side-panel got closed

Image

### PR DESCRIPTION
**Pull request by etiennejouan**
@bosiraphael I've slightly updated [your recent pr](https://github.com/twentyhq/twenty/pull/11654)
- before
Screenshot 2025-04-22 at 17 48 26

- after
Screenshot 2025-04-22 at 17 47 41

closes https://github.com/twentyhq/core-team-issues/issues/831 and https://github.com/twentyhq/core-team-issues/issues/828

### CODE REVIEW

**Review by guillim — APPROVED** [review]
LGTM

File: packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx [hunk 1]
```diff
@@ -154,7 +155,12 @@ export const FieldsCard = ({
                   }),
                   useUpdateRecord: useUpdateOneObjectRecordMutation,
                   isDisplayModeFixHeight: true,
-                  isReadOnly: isRecordReadOnly,
+                  isReadOnly: isFieldValueReadOnly({
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx:158]: ***Question:*** Shoudn't this be an intersection of both `isRecordReadOnly` and `isFieldValueReadOnly` ?

File: packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx [hunk 2]
```diff
@@ -42,8 +45,18 @@ export const RecordTitleFullNameFieldDisplay = () => {
...
 
+  const { setHotkeyScopeAndMemorizePreviousScope } = usePreviousHotkeyScope(
+    INLINE_CELL_HOTKEY_SCOPE_MEMOIZE_KEY,
+  );
   return (
-    <StyledDiv onClick={() => openInlineCell()}>
+    <StyledDiv
+      onClick={() => {
+        setHotkeyScopeAndMemorizePreviousScope(
+          TitleInputHotkeyScope.TitleInput,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx:55]: ***Question:*** You did not had to create a new key scope ?

**Review by prastoin — APPROVED** [review]
Left few non blocking comments
Nice job !

File: packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx (hunk 2 above)
Comment (etiennejouan) [reply packages/twenty-front/src/modules/object-record/record-title-cell/components/RecordTitleFullNameFieldDisplay.tsx:55]: You're right, to be cleaner I'll create a 'title-full-name-input' hotkey scope

File: packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx (hunk 1 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx:158]: Shouldn't we apply the same logic to the above form field ?

Comment (etiennejouan) [reply packages/twenty-front/src/modules/object-record/record-show/components/FieldsCard.tsx:163]: > Shouldn't we apply the same logic to the above form field ?
You're right. done

> It's passed as a parameter and instant used to early return 🤔, I feel like this should be included in the call itself, maybe we wanna build an equivalent hook having a dependency to the record's readability one ?
As we discussed it, it mays be a bit more complex and we will talk about refactoring useIsFieldValueReadOnly hook with you, @charlesBochet 👋
