### PR TITLE
Fixed global hotkey conflict in inputs

### LINKED ISSUE #13197: "?" shortcut taking over and closing panel
when typing "?" in the search bar or in a rich text fields it closes the panel and opens the shortcut menu.

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes a focus conflict with global hotkeys, mainly "?" that opens the shortcut helper dialog.

This fix works but we should maybe think about a more generic approach in another issue, like disabling global hotkeys when certain types of components are open (input, dropdown, etc.)

Fixes https://github.com/twentyhq/twenty/issues/13197

### CODE REVIEW

**Review by prastoin — COMMENTED** [review]
I feel like this option should be required or not defaulted to false

**Review by bosiraphael — CHANGES_REQUESTED** [review]
This is not the right fix, we still want shortcuts with modifiers to be accessible. The right fix is to set `containsModifier` to false in `useGlobalHotkeys` in `KeyboardShortcutMenu`.

**Comment by bosiraphael** [comment]
> I feel like this option should be required or not defaulted to false

No, it should always be defaulted to false, the cases where we don't want shortcuts with modifiers are extremely rare.

**Comment by lucasbordeau** [comment]
If I instead set modifiers to false, it also fixes the issue but then it does not work on the drawer without any field open, is it the expected behavior ?

**Comment by bosiraphael** [comment]
> If I instead set modifiers to false, it also fixes the issue but then it does not work on the drawer without any field open, is it the expected behavior ?

Yes, I think so

**Comment by lucasbordeau** [comment]
https://github.com/user-attachments/assets/5b1667c4-41c6-44f6-bb76-ffb2472fd07a

File: packages/twenty-front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const KeyboardShortcutMenu = () => {
       closeCommandMenu();
       toggleKeyboardShortcutMenu();
     },
-    true,
+    false,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx]: ***Nitpick:*** naming a const variable or updating the hook to expect an options record with explicitly named keys

**Review by prastoin — COMMENTED** [review]
I feel like this option should be required or not defaulted to false

**Review by bosiraphael — APPROVED** [review]
LGTM
