### PR TITLE
Fix environment variable casting

### LINKED ISSUE #4628: Environment variable typing is incorrect leading to boolean misinterpretation
## Bug Description

I'll take the example of `CALENDAR_PROVIDER_GOOGLE_ENABLED` environment variable.
Let's set it to `CALENDAR_PROVIDER_GOOGLE_ENABLED=false` in our `.env`

It's registered in environment-variables.ts by:
```
  @CastToBoolean()
  @IsBoolean()
  CALENDAR_PROVIDER_GOOGLE_ENABLED: boolean = false;
```

However, when we get it through environmentService, we get it as a `string`:
image

This leading to issue as Typescript believes it's a `boolean` an allow if (CALENDAR_PROVIDER_GOOGLE_ENABLED) which will return true even if CALENDAR_PROVIDER_GOOGLE_ENABLED=false

### PR DESCRIPTION
**Pull request by FelixMalfait**
Fixes #4628

### CODE REVIEW

File: packages/twenty-server/src/utils/generate-front-config.ts [hunk 1]
```diff
@@ -1,17 +1,14 @@
-import { ConfigService } from '@nestjs/config';
-
 import * as fs from 'fs';
 import * as path from 'path';
 
-import { EnvironmentService } from 'src/engine/integrations/environment/environment.service';
-
-const environmentService = new EnvironmentService(new ConfigService());
+import { config } from 'dotenv';
+config();
```
Comment (FelixMalfait) [inline packages/twenty-server/src/utils/generate-front-config.ts:5]: Tbh I'm not 100% sure this is required but it was there in other similar raw files (e.g. core.datasource.ts)

Comment (FelixMalfait) [reply packages/twenty-server/src/utils/generate-front-config.ts:5]: In main.ts it isn't there but I'm guessing is done by a depedency ; tI ried changing the port and it worked

File: packages/twenty-server/src/main.ts [hunk 2]
```diff
@@ -64,7 +61,7 @@ const bootstrap = async () => {
   // Create the env-config.js of the front at runtime
   generateFrontConfig();
 
-  await app.listen(app.get(EnvironmentService).get('PORT'));
+  await app.listen(process.env.PORT ?? 3000);
```
Comment (FelixMalfait) [inline packages/twenty-server/src/main.ts:64]: Default value a bit duplicate from the env service, especially for variable that would most likely be accessed only through process.env and never in the context of the envService/app like this one. But I think it doesn't hurt too much this way - it's the best options to keep things that way imo

**Review by charlesBochet — APPROVED** [review]
