### PR TITLE
Import - fixes

### LINKED ISSUE #1065: Import - Other issues
- From recordView in command menu, "options > export" export only record Id - **(can't reproduce anymore)** ✅ 
- When exporting custom object (ok with standard), relation FromMany are not exported (nok with standard also) - **(can't reproduce anymore)** ✅ 
- When import failed, modal steps are blocked on loading state - ability to reload (to do later with progress upload bar)
- I should have an error message when trying to match Multi select or select field with field not working ✅ 
- Add validation for Rating field ✅

### LINKED ISSUE #1066: Match column step - Many fixes
- update banner colour for select and multiselect matching field [link](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=64635-223321&t=71CWJVcQR0TgJ2aA-4) ✅ 
- error message in multi-select matching field ✅ 
- field type in matching column menu ✅ 
- ability to unmatch an option in select and multiselect field ✅

### PR DESCRIPTION
**Pull request by etiennejouan**
Screenshot 2025-06-12 at 15 22 49

To test : 
- unselect an option on select/multi-select matching (matching step)
- match a mutli-select field with an other field

closes : https://github.com/twentyhq/core-team-issues/issues/1065
closes : https://github.com/twentyhq/core-team-issues/issues/1066

### CODE REVIEW

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/TemplateColumn.tsx [hunk 1]
```diff
@@ -78,6 +85,9 @@ export const TemplateColumn = <T extends string>({
         options={selectOptions}
         columnIndex={column.index.toString()}
       />
+      {column.type === SpreadsheetColumnType.matchedError && (
+        <StyledErrorMessage>{`"${selectValue?.label}" ${column.errorMessage}`}</StyledErrorMessage>
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/TemplateColumn.tsx]: double check error message clarity

**Review by charlesBochet — APPROVED** [review]
Same ! LGTM
