### PR TITLE
Fix: danger font color values & acc. to design specs

### LINKED ISSUE #5325: Secondary Button accent danger problem in dark mode
# Current Behavior

When deleting an API key in `Settings/Developers`, the confirmation button currently appears as follows:

image

# Desired Behavior

The button should match the design system's color specifications.

CleanShot 2024-05-07 at 17 11 44

### PR DESCRIPTION
**Pull request by its-id**
fixes: #5325

changes done (commits in order):

1. **Fixed fontLight & fontDark 'danger' color as per design spec**: changed theme.font.color.danger to match the disabled color theme (for light and dark) as followed by the BorderDark and BorderLight. Use the updated colors for Buttons

2. **Replace theme.font.color.danger with theme.color.red (5 changed files)**: Since `theme.font.color.danger` has now been updated to contain the disabled button color values, we use the `theme.color.red` color in all the places using `theme.font.color.danger` as it contains same value that was used to be of `theme.font.color.danger` before.

3. **fixed hover color of StyledConfirmationButton in ConfirmationModal**: issue can be seen when going to /settings/workspace and trying to hover on delete the workspace button in dark mode. fixed with this commit.

**Important Note**: The files `/twenty-front/src/modules/ui/theme/constants/FontLight.ts` and `/twenty-front/src/modules/ui/theme/constants/FontDark.ts` **are of no use** as theme for the entire 'twenty-front' and 'twenty-chrome-extension' packages use the same files from '@/ui/theme' (twenty-ui package)

dark mode :
Screenshot 2024-05-09 at 9 14 35 PM

when disabled:
Screenshot 2024-05-09 at 9 13 46 PM

on hover:
Screenshot 2024-05-09 at 9 14 05 PM

<br>

<br>

light mode (when disabled):
Screenshot 2024-05-09 at 9 13 14 PM

on hover:
Screenshot 2024-05-09 at 9 14 18 PM

### CODE REVIEW

**Review by erivanstdio — APPROVED** [review]

File: packages/twenty-ui/src/theme/constants/FontDark.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export const FONT_DARK = {
     light: GRAY_SCALE.gray50,
     extraLight: GRAY_SCALE.gray55,
     inverted: GRAY_SCALE.gray100,
-    danger: COLOR.red,
+    danger: COLOR.red70,
```
Comment (charlesBochet) [inline packages/twenty-ui/src/theme/constants/FontDark.ts:13]: @Bonapara I feel this was right before @its-id change.
the danger color font should be red #f83e3e according to Figma


Could you confirm?

File: packages/twenty-ui/src/theme/constants/FontLight.ts [hunk 2]
```diff
@@ -10,7 +10,7 @@ export const FONT_LIGHT = {
     light: GRAY_SCALE.gray35,
     extraLight: GRAY_SCALE.gray30,
     inverted: GRAY_SCALE.gray0,
-    danger: COLOR.red,
+    danger: COLOR.red20,
```
Comment (charlesBochet) [inline packages/twenty-ui/src/theme/constants/FontLight.ts:13]: same here

File: packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx [hunk 3]
```diff
@@ -38,7 +38,7 @@ export const StyledMenuItemBase = styled.li<MenuItemBaseProps>`
     switch (accent) {
       case 'danger': {
         return css`
-          color: ${theme.font.color.danger};
+          color: ${theme.color.red};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/navigation/menu-item/internals/components/StyledMenuItemBase.tsx:41]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx [hunk 4]
```diff
@@ -69,7 +69,7 @@ const StyledText = styled.span`
 `;
 
 const StyledErrorText = styled.span`
-  color: ${({ theme }) => theme.font.color.danger};
+  color: ${({ theme }) => theme.color.red};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/ImageInput.tsx:72]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx [hunk 5]
```diff
@@ -39,7 +39,7 @@ export const SettingsApiKeysFieldItemTableRow = ({
       <TableCell
         color={
           fieldItem.expiration === 'Expired'
-            ? theme.font.color.danger
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx:42]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx [hunk 6]
```diff
@@ -56,7 +56,7 @@ const StyledDueDate = styled.div<{
 }>`
   align-items: center;
   color: ${({ theme, isPast }) =>
-    isPast ? theme.font.color.danger : theme.font.color.secondary};
+    isPast ? theme.color.red : theme.font.color.secondary};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx:59]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/activities/calendar/components/CalendarCurrentEventCursor.tsx [hunk 7]
```diff
@@ -32,7 +32,7 @@ const StyledCurrentEventCursor = styled(motion.div)`
   transform: translateY(-50%);
 
   &::before {
-    background-color: ${({ theme }) => theme.font.color.danger};
+    background-color: ${({ theme }) => theme.color.red};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/calendar/components/CalendarCurrentEventCursor.tsx:35]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/activities/calendar/components/CalendarCurrentEventCursor.tsx [hunk 8]
```diff
@@ -22,7 +22,7 @@ type CalendarCurrentEventCursorProps = {
 
 const StyledCurrentEventCursor = styled(motion.div)`
   align-items: center;
-  background-color: ${({ theme }) => theme.font.color.danger};
+  background-color: ${({ theme }) => theme.color.red};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/calendar/components/CalendarCurrentEventCursor.tsx:25]: this should not be necessary if we keep font.color.danger = color.red, see comment below

File: packages/twenty-front/src/modules/ui/input/button/components/Button.tsx [hunk 9]
```diff
@@ -194,7 +194,7 @@ const StyledButton = styled.button<
               box-shadow: ${!disabled && focus
                 ? `0 0 0 3px ${theme.color.red10}`
                 : 'none'};
-              color: ${!disabled ? theme.font.color.danger : theme.color.red20};
+              color: ${!disabled ? theme.color.red : theme.font.color.danger};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/button/components/Button.tsx:197]: @Bonapara could you provide the value of the red disabled button color for dark mode. I cannot find it in the Figma :(

For the light one, I see that you are actually not changing the font but changing the overall opacity which could be an issue depending what's behind the button. is this intended?

File: packages/twenty-front/src/modules/ui/input/button/components/IconButton.tsx [hunk 10]
```diff
@@ -181,7 +181,7 @@ const StyledButton = styled.button<
               box-shadow: ${!disabled && focus
                 ? `0 0 0 3px ${theme.color.red10}`
                 : 'none'};
-              color: ${!disabled ? theme.font.color.danger : theme.color.red20};
+              color: ${!disabled ? theme.color.red : theme.font.color.danger};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/button/components/IconButton.tsx:184]: same as above here

File: packages/twenty-front/src/modules/ui/input/button/components/Button.tsx (hunk 9 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/input/button/components/Button.tsx:197]: image

Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/input/button/components/Button.tsx:197]: Per discussion with Bonapara, we should update Button and IconButton to have same font as non disabled but opacity to 0.24%

File: packages/twenty-ui/src/theme/constants/FontDark.ts (hunk 1 above)
Comment (its-id) [reply packages/twenty-ui/src/theme/constants/FontDark.ts:13]: So, to understand the fix: a brief about the issue itself. Earlier the FontLight and FontDark both were hardcoded to take only single color which turned out to be an issue in disabled mode. (ref to issue screenshot)

The fix revolved around the usage of FontDark and FontLight to work same as BorderLight and BorderDark in disabled mode. So, I made FontDark and FontLight danger color to use same value same as being used by BorderLight (#fed8d8) and BorderDark (#441f1f). This now becomes much more cleaner and easier to use as acc. to current changes, fontDark and fontLight danger is being used only for disabled mode. 

And as for the other files which were previously using font.color.danger value  which was basically COLOR.red (#f83e3e), I switched to theme.color.red making sure their color value doesn't change.

File: packages/twenty-front/src/modules/ui/input/button/components/Button.tsx (hunk 9 above)
Comment (its-id) [reply packages/twenty-front/src/modules/ui/input/button/components/Button.tsx:197]: Ok. What I did was follow the same color design being used by the border's light and dark variant in disabled mode. since, button's border is working fine as expected.

I was trying to use the existing values without introducing any new color values which basically work great and is tested as well on multiple pages with dark and light mode.

Comment (its-id) [reply packages/twenty-front/src/modules/ui/input/button/components/Button.tsx:197]: > @Bonapara could you provide the value of the red disabled button color for dark mode. I cannot find it in the Figma :(
> 
> For the light one, I see that you are actually not changing the font but changing the overall opacity which could be an issue depending what's behind the button. is this intended?

image

I don't think there is an opacity added to the color. the colors red20 and red70 do not have any opacity as I can see.

**Review by its-id — COMMENTED** [review]
Added some comments. Pls have a look. 

For better understanding of the fix I did, pls refer to the PR description as well.

**Comment by FelixMalfait** [comment]
Thanks for the contribution! I'm merging with a simpler alternative that achieves the same result. We could eventually introduce a new color in font for that variant but I think it's okay to do it this way for now
