### PR TITLE
Two cells can be focused at the same time in the tables Fixes #1826

### LINKED ISSUE #1826: Two cells can be focused at the same time in the tables
## Bug Description

When pressing the escape key after selecting a cell and using the arrow keys to move, two cells are focused at once.

https://github.com/twentyhq/twenty/assets/71827178/1e4224b7-7dc8-42b9-b504-dafaf5c0f382

## Expected behavior

Only one cell should be focused, at the final position after pressing the arrow keys.

### PR DESCRIPTION
**Pull request by Davidkramer1999**
Fixes #1826

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hotkeys don't work anymore on table cells, we can't close a table cell with esc, tab, etc.

**Comment by Davidkramer1999** [comment]
> Hotkeys don't work anymore on table cells, we can't close a table cell with esc, tab, etc.

Yes i will fix it today

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 Could you help with this issue ? 

We have to look at some complexities : 
- The mouseEnter event keeps firing if we move the soft focus with keyboard
- We have to correctly handle the switch of hotkey scopes : table / soft focus / edit mode
- We may have to create a state / selector isSomeCellInEditMode

**Comment by AyushAgrawal-A2** [comment]
Hey @Davidkramer1999,
I have pushed changes to this branch on your forked repo.
Please check.
If you merge it in your fork, it should appear hear.

**Comment by Davidkramer1999** [comment]
Thank you for your help @AyushAgrawal-A2. I've should seen it this is very good solution. Sorry I didn't solve it by my self...

**Comment by AyushAgrawal-A2** [comment]
Hey, @Davidkramer1999 

> We may have to create a state / selector isSomeCellInEditMode

This is still pending, if some cell is in edit mode and the mouse is moved then the new cell gets selected exiting edit mode and canceling any changes made there.

Would you like me to implement this as well?

**Comment by Davidkramer1999** [comment]
Frist i will try to solve it by my self. Maybe today or tommorow. I will keep you updated.

File: front/src/modules/ui/data-table/table-cell/hooks/useTableCell.ts [hunk 1]
```diff
@@ -47,8 +51,10 @@ export const useTableCell = () => {
       navigate(`${fieldDefinition.basePathToShowPage}${entityId}`);
       return;
     }
-
+    // eslint-disable-next-line no-console
+    console.log('openTableCell');
```
Comment (lucasbordeau) [inline front/src/modules/ui/data-table/table-cell/hooks/useTableCell.ts:55]: Console.log

File: front/src/modules/ui/data-table/table-cell/hooks/useTableCell.ts [hunk 2]
```diff
@@ -13,25 +13,29 @@ import { useCloseCurrentTableCellInEditMode } from '../../hooks/useCloseCurrentT
...
-
   const customCellHotkeyScope = useContext(CellHotkeyScopeContext);
 
   const closeTableCell = () => {
     setDragSelectionStartEnabled(true);
     closeCurrentTableCellInEditMode();
+    setIsSomeCellInEditMode(false);
     setHotkeyScope(TableHotkeyScope.TableSoftFocus);
+    // eslint-disable-next-line no-console
+    console.log('closeTableCell');
```
Comment (lucasbordeau) [inline front/src/modules/ui/data-table/table-cell/hooks/useTableCell.ts:38]: console.log

**Review by lucasbordeau — COMMENTED** [review]
Nice !

**Comment by lucasbordeau** [comment]
Ok now we need to work on the re-render side effect of this feature,

The TableCellContainer component cannot directly subscribe to the new isSomeCellInEditMode state, because when we open/close a cell, every TableCellContainer will re-render.

I see some options : 
- Create a useRecoilCallback that will just read isSomeCellInEditMode and return the value, that you can call in the handlers, so the component won't subscribe and the read in the Recoil store will only be triggered once per mouse event.
- Turn the mouse handlers into useRecoilCallbacks (maybe not the best solution)
- Put the writes of this atom not in the handlers, but in the relevant hooks : closeCurrentTableCellInEditMode, setCurrentTableCellInEditMode.

**Comment by lucasbordeau** [comment]
You need to have React devtools installed and activate the re-render debugger : 

Capture d’écran 2023-10-09 à 11 01 11

File: front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx [hunk 3]
```diff
@@ -64,7 +64,8 @@ export const TableCellContainer = ({
   const hasSoftFocus = useIsSoftFocusOnCurrentTableCell();
 
   const setSoftFocusOnCurrentTableCell = useSetSoftFocusOnCurrentTableCell();
-  const { isSomeCellInEditMode } = useIsSomeCellInEditMode();
+  const { useIsSomeCellInEditMode } = useSomeCellInEditMode();
+  const cellInEditMode = useIsSomeCellInEditMode();
```
Comment (lucasbordeau) [inline front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx:68]: It's not a hook that is returned by useRecoilCallback but a function that should be named like `getIsSomeCellInEditMode` and it should be called in your handler directly.

**Comment by AyushAgrawal-A2** [comment]
> because when we open/close a cell, every TableCellContainer will re-render.

@lucasbordeau is this a bug or expected behavior?
opening / closing a cell should only re-render that cell. I am unable to understand why all cells should re-render.

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 yes it shouldn't re-render all the cells. We want only the cell that is opening/closing to re-render.

@Davidkramer1999 I just tested and it still re-renders all the cells when we open/close.

**Comment by AyushAgrawal-A2** [comment]
> @AyushAgrawal-A2 yes it shouldn't re-render all the cells. We want only the cell that is opening/closing to re-render.
> 
> @Davidkramer1999 I just tested and it still re-renders all the cells when we open/close.

@lucasbordeau  
That happens in the main branch already, it is not due to changes made in this PR.

@Davidkramer1999 
We should investigate elsewhere why that happens.

**Comment by AyushAgrawal-A2** [comment]
@Davidkramer1999 
Fixed it, it was a bug in the useDragSelect hook, please check PR in your fork.

**Comment by Davidkramer1999** [comment]
Okay I hope we solved now the problem. Good job @AyushAgrawal-A2  Sorry I didn't done more by my self.

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau
Submitting again for review.

P.S. Selecting a row by clicking on the checkbox should only rerender the checkbox... right? Currently, in the main branch, it rerenders the entire table.

**Comment by lucasbordeau** [comment]
Oh nice I didn't notice that regression ! Killing two birds with one stone, thank you !

File: front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx [hunk 4]
```diff
@@ -58,7 +59,12 @@ export const TableCellContainer = ({
 }: EditableCellProps) => {
   const { isCurrentTableCellInEditMode } = useCurrentTableCellEditMode();
 
-  const [isHovered, setIsHovered] = useState(false);
+  const isHovered = useRef<boolean>(false);
```
Comment (lucasbordeau) [inline front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx:62]: We try to avoid using useRef as state management as stated in the documentation : https://docs.twenty.com/developer/frontend/best-practices#do-not-use-useref-to-store-state

You can use a simple useState here, it works just as well.

**Review by lucasbordeau — CHANGES_REQUESTED** [review]

File: front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx (hunk 4 above)
Comment (Davidkramer1999) [reply front/src/modules/ui/data-table/table-cell/components/TableCellContainer.tsx]: Okay I removed useRef so you can check again @lucasbordeau

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau

Asking for my understanding only

When isHovered is set as a component state(using useState), it causes more re-renders than when it is set as a boolean flag(using useRef)
- with useState (hover and in edit-mode)

https://github.com/twentyhq/twenty/assets/54364088/3f53b12f-77d7-4506-84c2-89b2c6942645

- with useRef (hover and in edit-mode)

https://github.com/twentyhq/twenty/assets/54364088/e16955d6-bd65-4e77-9b5d-afb8730a1355

In this situation, isHovered is required as a boolean flag only, to prevent onMoveEnter retriggers.
Is there a way to avoid useRef and prevent additional re-renders?

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 I pushed what I asked in a previous comment https://github.com/twentyhq/twenty/pull/1866#discussion_r1350321386 

It is tempting to fallback on useRef for avoiding re-renders, but the same result can be obtained with useRecoilCallback, which allows us to access the Recoil store in read/write without triggering re-renders.

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
Thank you for your work @Davidkramer1999 and @AyushAgrawal-A2 ! This was a tricky PR and the result is now better in terms of UX and optimized for re-renders.
