### PR TITLE
fix(email-verification): prevent double email validation

### LINKED ISSUE #12171: Email verification error
https://twenty-v7.sentry.io/issues/6606375182/?project=4507072499810304&query=is%3Aunresolved%20%21issue.type%3A%5Bperformance_consecutive_db_queries%2Cperformance_consecutive_http%2Cperformance_file_io_main_thread%2Cperformance_db_main_thread%2Cperformance_n_plus_one_db_queries%2Cperformance_n_plus_one_api_calls%2Cperformance_p95_endpoint_regression%2Cperformance_slow_db_query%2Cperformance_render_blocking_asset_span%2Cperformance_uncompressed_assets%2Cperformance_http_overhead%2Cperformance_large_http_payload%5D&referrer=issue-stream&sort=date&stream_index=4

This will be removed from sentry-back as it is a 4xx error, but I think it reveals a real error as I don't expect users to use the api to verify their email, and we have regular occurences.

### LINKED ISSUE #12177: Invalid email verification token
[sentry](https://twenty-v7.sentry.io/issues/6606375182/?project=4507072499810304&query=is%3Aunresolved%20%21issue.type%3A%5Bperformance_consecutive_db_queries%2Cperformance_consecutive_http%2Cperformance_file_io_main_thread%2Cperformance_db_main_thread%2Cperformance_n_plus_one_db_queries%2Cperformance_n_plus_one_api_calls%2Cperformance_p95_endpoint_regression%2Cperformance_slow_db_query%2Cperformance_render_blocking_asset_span%2Cperformance_uncompressed_assets%2Cperformance_http_overhead%2Cperformance_large_http_payload%5D&referrer=issue-stream&sort=date&stream_index=4)

We will be removing this issue from sentry as it is a 400 error ([see PR](https://github.com/twentyhq/twenty/pull/12174)), but it most likely reflects a real error as it is quite unexpected that a lot of users would use the api to verify their email.

### PR DESCRIPTION
**Pull request by AMoreaux**
Fix #12177 
Fix #12171

### CODE REVIEW

File: packages/twenty-front/src/modules/auth/hooks/useAuth.ts [hunk 1]
```diff
@@ -207,9 +207,14 @@ export const useAuth = () => {
   );
 
   const handleGetLoginTokenFromEmailVerificationToken = useCallback(
-    async (emailVerificationToken: string, captchaToken?: string) => {
+    async (
+      emailVerificationToken: string,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/hooks/useAuth.ts:211]: neat: { emailVerificationToken, email, captchaToken }

**Review by charlesBochet — APPROVED** [review]
LGTM!
