### PR TITLE
fix merge records network race condition

### LINKED ISSUE #13643: Merge Records - Small issues
- Issue 1
From table view, when selecting records and merging them, two merge requests are launch. The second one fails.
Image

- Issue 2
From a record view, when merging duplicate with "Second record holds priority", it returns an error.
Image

### PR DESCRIPTION
**Pull request by neo773**
/closes #13643

image

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-merge/hooks/useMergePreview.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { useMergeManyRecords } from '@/object-record/hooks/useMergeManyRecords';
 import { useMergeRecordRelationships } from '@/object-record/record-merge/hooks/useMergeRecordRelationships';
 import { useUpsertRecordsInStore } from '@/object-record/record-store/hooks/useUpsertRecordsInStore';
 import { type ObjectRecord } from '@/object-record/types/ObjectRecord';
+import { mergeInProgressState } from '../states/mergeInProgressState';
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/object-record/record-merge/hooks/useMergePreview.ts]: Nit: would you mind renaming to isMergeInProgress? It's the pattern most frequently used

**Review by FelixMalfait — APPROVED** [review]
