### PR TITLE
[Workflows] Fix filtering on relative date

### LINKED ISSUE #16054: [Workflows] Filtering on relative date is not working
please see the attached video, reported by a customer
I can reproduce in production

Clicking on the "This"/"Past"/"Next" button does not select the value on which the user clicked. 

He also showed a few other issues during his video

https://share.zight.com/d5udWLbW

Front logo [Front conversations](https://app.frontapp.com/open/top_3rxv12)

### PR DESCRIPTION
**Pull request by Devessier**
https://github.com/user-attachments/assets/4079d59e-0550-401f-a29b-b235edd8ed48

Closes https://github.com/twentyhq/twenty/issues/16054

### CODE REVIEW

**Review by martmull — APPROVED** [review]

File: packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx [hunk 1]
```diff
@@ -39,6 +40,8 @@ export const RelativeDatePickerHeader = ({
   readonly,
   unitDropdownWidth,
 }: RelativeDatePickerHeaderProps) => {
+  const instanceId = useId();
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: I suggest not using useId has it is not resistant to re-renders, we should always use a static if that we can obtain from the context.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: We already apply this strategy throughout the codebase, there's always information we can use to craft a unique identifier.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: This is especially true for dropdown ids which should be determined by their environment and not generated.

Comment (Devessier) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: It is resistant to re-renders but not to remounts. I agree that it’s better to use a higher-level identifier. I’ll give it a try.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: You can add a required props `id` or `dropdownIdSuffix` if there's nothing that allows to craft a unique identifier from the context inside this component.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: Of course but a remount happens easily if the parent re-renders and recreates its children which can happen very easily for a component that is generic like this one.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: Better safe than sorry, by not allowing something to bug, it won't bug, that should be a principle like least privilege in security.

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: With our dropdowns, there is a lot of internal logic and hooks to open / close remotely, if the id changes between the open and close events it can be very hard to debug, it has already happened.

Comment (Devessier) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: @lucasbordeau, I found a way to use an existing id everywhere. It continues to work correctly.

Form fields all use `useId` so I kept it here.

Comment (Devessier) [reply packages/twenty-front/src/modules/ui/input/components/internal/date/components/RelativeDatePickerHeader.tsx]: Merging.

**Comment by StephanieJoly4** [comment]
thank you @Devessier 
when will it please be in production so I can inform the user?
