### PR TITLE
fixed issue Display field name on Kanbans & Shows

### LINKED ISSUE #3406: Display field name on Kanbans & Shows
# Current behavior

On show pages and kanbans, we can't see the field name of inline fields.

# Desired behavior

### Custom placeholder

When no `Field name` is displayed on `Inline cells` we want to adapt its placeholder from `Empty` to the `Field name` value: 

CleanShot 2024-01-12 at 15 16 58

This smart rule should work on any inline field, not just Kanban views: "If the field name is hidden, display it as a placeholder; otherwise, display `Empty`"

### Display field name on Show pages inline fields

- Change the field name font-size from 13px to 12px

CleanShot 2024-01-12 at 15 18 21

Make sure all field values are aligned:

CleanShot 2024-01-12 at 15 20 30

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-72411&mode=design&t=cT75gYTM64rGg00A-11

Thanks @daallgeier for the idea!

### PR DESCRIPTION
**Pull request by abdul-irfan-k**
fix  #3406

Screenshot from 2024-01-14 10-42-58

### CODE REVIEW

File: packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts [hunk 1]
```diff
@@ -28,6 +34,8 @@ export const formatFieldMetadataItemAsColumnDefinition = ({
     position,
     fieldMetadataId: field.id,
     label: field.label,
+    showLabel,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemAsColumnDefinition.ts:37]: I have added these on FieldDefinition so they can be passed through the FieldContext provider (this avoid having to drill down props and let the page / section decide if we should display label or not)

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx [hunk 2]
```diff
@@ -133,8 +133,10 @@ export const RecordInlineCellContainer = ({
               <IconLabel stroke={theme.icon.stroke.sm} />
             </StyledIconContainer>
           )}
-          {label && (
-            <StyledLabel labelFixedWidth={labelFixedWidth}>{label}</StyledLabel>
+          {showLabel && label && (
+            <StyledLabelContainer width={labelWidth}>
+              <EllipsisDisplay maxWidth={labelWidth}>{label}</EllipsisDisplay>
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx:138]: use EllipsisDisplay here to make sure the label is not too long

**Review by charlesBochet — APPROVED** [review]
@abdul-irfan-k I have made some modification to your PR and left comments to explain why :) Might be helpful for future contributions
Thanks a lot for the help
