### PR TITLE
Fix country selector text overflow issue

### LINKED ISSUE #7906: Country Select Picker Text Overflow Issue
# Current behavior

Address field Country Select picker doesn't crop values

image

# Desired Behavior

The text should fill the container and be truncated with "..." when it exceeds the available space.

### PR DESCRIPTION
**Pull request by BKM14**
Closes #7906 

Modified the two children(`TextInputV2` and `CountrySelect`) in the `StyledHalfRowContainer` component to always be equal in size and divide the available space equally. 
The `StyledIconChevronDown` component has a `flex-shrink: 0` to prevent it from completely disappearing. The same applies for the `selectedOption.Icon`.
A `p` tag had to be added to the label to correctly handle the text overflow.

### CODE REVIEW

**Comment by BKM14** [comment]
Hey @Devessier, what do you think about this?

**Comment by Devessier** [comment]
Hey @BKM14, thank you very much for your contribution. I made some changes to minimize the number of files that were changed. These files are often used across the application, and we can easily break something if we make a mistake.

**Comment by BKM14** [comment]
Yeah, I knew it was a little shabby given the number of files I had to change. I spent a whole day breaking my head trying to fix this. 

Glad you minimized the changes.
Thank you.

File: packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx [hunk 1]
```diff
@@ -45,18 +55,18 @@ export const SelectControl = ({
...
             }
             size={theme.icon.size.md}
             stroke={theme.icon.stroke.sm}
           />
-        )}
-        {selectedOption?.label}
-      </StyledControlLabel>
+        </StyledIconContainer>
+      ) : null}
+      <StyledLabel>{selectedOption.label}</StyledLabel>
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx:69]: would it make sense to use OverflowingTextWithTooltipe here?

File: packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx [hunk 2]
```diff
@@ -15,21 +15,31 @@ const StyledControlContainer = styled.div<{ disabled?: boolean }>`
...
+  flex-grow: 1;
+  flex-shrink: 1;
 `;
 
 const StyledIconChevronDown = styled(IconChevronDown)<{
   disabled?: boolean;
 }>`
   color: ${({ disabled, theme }) =>
     disabled ? theme.font.color.extraLight : theme.font.color.tertiary};
+  flex-shrink: 0;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx:29]: are all these flex-shrink mandatory? looks a bit too much everywhere

File: packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx [hunk 3]
```diff
@@ -15,21 +15,31 @@ const StyledControlContainer = styled.div<{ disabled?: boolean }>`
...
+`;
+
+const StyledIconContainer = styled.span`
+  display: flex;
+  flex-shrink: 0;
+`;
+
+const StyledLabel = styled.span`
+  flex-grow: 1;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx:38]: is this flex-grow necessary?
This code looks very similar to OverflowingTextWithTooltip

File: packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx (hunk 1 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx]: Done! It works great. However, I'm not sure how accessible using this component here is.

File: packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx (hunk 2 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/ui/input/components/SelectControl.tsx]: I cleaned the layouting by using a unified grid layout.

**Comment by Devessier** [comment]
Thank you a lot for your time, @BKM14. I know truncating text can be tricky. The root issue was that the modal had no max-width, making it hard to truncate text, which requires setting a max-width beyond which the text should be truncated.

**Review by charlesBochet — APPROVED** [review]
