### PR TITLE
[FIX] remove blue outline for Phones, Emails, and Domains fields

### LINKED ISSUE #8252: Use simple input for Phones, Emails, and Domains fields
# Current Behavior

When opening a field that can store multiple values, we display the following component:

CleanShot 2024-10-31 at 14 52 33

It appears inconsistent with other fields, particularly due to the blue focus.

# Desired Behavior

**When the field is empty**, we should display a simple input first, followed by the multiple input component:

https://github.com/user-attachments/assets/e38d82ef-d46d-4437-b506-cba4ff8298fc

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3014-103307&node-type=instance&t=L4Zw8NIeonoYkIdd-11

Error state:

CleanShot 2024-10-31 at 15 02 51

### PR DESCRIPTION
**Pull request by siv-io**
FIX: #8252

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx [hunk 1]
```diff
@@ -53,8 +53,7 @@ const StyledRightContainer = styled.div`
 
 const StyledErrorDiv = styled.div`
   color: ${({ theme }) => theme.color.red};
-  padding: 0 ${({ theme }) => theme.spacing(2)}
-    ${({ theme }) => theme.spacing(1)};
+  padding: 0 ${({ theme }) => theme.spacing(2)};
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx:56]: Since the original issue doesn't mention padding, could you please add a comment to explain the issue you've found/are fixing here? Thanks!

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx [hunk 2]
```diff
@@ -22,13 +22,13 @@ const StyledInput = styled.input<{
   position: relative;
   width: 100%;
 
-  &:focus {
+  /* &:focus {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx:25]: Don't be afraid to delete code, that's what git is for - we can always find it if we need it! So don't leave commented code in the codebase :)

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx (hunk 1 above)
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuInput.tsx:48]: Why did you resolve @Hitarthsheth07? Thanks
