### PR TITLE
escaping special chars for events

### LINKED ISSUE #12827: [messaging] invalid byte sequence for encoding "UTF8": 0x00
Sentry Issue: [TWENTY-SERVER-5BK](https://twenty-v7.sentry.io/issues/6567295627/?referrer=github_integration)

```
Error: Unknown error importing calendar events for calendar channel e9069... in workspace 589996d9-90ff-49d2-8999-dc4a30d3f5ab: Unknown error importing calendar events for calendar channel e9069... in workspace 589996d9-90ff-49d2-8999-dc4a30d3f5ab: invalid byte sequence for encoding "UTF8": 0x00
  File "../../../../../../src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.ts", line 168, in {CalendarEventImportErrorHandlerService#2}.handleUnknownException
    const calendarEventImportException = new CalendarEventImportException(
  File "../../../../../../src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.ts", line 66, in {CalendarEventImportErrorHandlerService#2}.handleDriverException
    await this.handleUnknownException(
  File "../../../../../../src/modules/calendar/calendar-event-import-manager/services/calendar-fetch-events.service.ts", line 126, in {CalendarFetchEventsService#2}.fetchCalendarEvents
    await this.calendarEventImportErrorHandlerService.handleDriverException(
  File "../../../../../../src/modules/calendar/calendar-event-import-manager/jobs/calendar-event-list-fetch.job.ts", line 66, in {CalendarEventListFetchJob#2}.handle
    await this.calendarFetchEventsService.fetchCalendarEvents(
  File "../../../../../src/engine/core-modules/message-queue/message-queue.explorer.ts", line 208, in {MessageQueueExplorer#2}.invokeProcessMethods
    await instance[processMethodName].call(instance, job.data);
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by guillim**
Escaping newly discovered special chars for events

- \x00 is a Unicode for nul
- \x7f is a Unicode for delete

Edit:
i initially, just in case after looking at the logs, i removed the single quotes as well (there are fobiden in the standard RFC 5545) but after reflexion other props than icalUID rely on this sanitization so leaving as such. It should already be taken care of anyway by typeorm

Ref sentry : https://twenty-v7.sentry.io/issues/6567295627/?environment=prod&environment=prod-eu&project=4507072499810304&query=&referrer=issue-stream&stream_index=13

Fixes https://github.com/twentyhq/twenty/issues/12827

### CODE REVIEW

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts [hunk 1]
```diff
@@ -23,5 +23,9 @@ export const sanitizeCalendarEvent = <T extends Record<string, any>>(
 };
 
 const sanitizeString = (value: string): string => {
-  return value.replace('\u0000', '');
+  return value
+    .replace('\u0000', '')
+    .replace('0x00', '')
+    .replace('\x7f', '')
+    .replace(`'`, '');
```
[the remark this answers is not in the document]
Comment (guillim) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts]: IMO it's clearer this way and does not impact perfomances

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts [hunk 2]
```diff
@@ -23,5 +23,5 @@ export const sanitizeCalendarEvent = <T extends Record<string, any>>(
 };
 
 const sanitizeString = (value: string): string => {
-  return value.replace('\u0000', '');
+  return value.replace('\u0000', '').replace('\x00', '').replace('\x7f', '');
```
Comment (prastoin) [inline packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts:26]: ***Nitpick:*** Would create a constant for each char to make this more human readable

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts [hunk 3]
```diff
@@ -77,23 +77,39 @@ describe('formatGoogleCalendarEvents', () => {
     );
   });
 
-  it('should sanitize a UCALID with improper exit char 0x00', () => {
-    const mockGoogleEventWithImproperUcalid: calendarV3.Schema$Event = {
-      ...mockGoogleEvent,
-      iCalUID: '\u0000eventStrange@google.com',
-    };
+  const testCases = [
```
Comment (prastoin) [inline packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts]: ***Massive nitpick:*** Could the `EachTestingContext`

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts]: Ok with both

**Review by prastoin — APPROVED** [review]
Could other special be involved ? Should look programmatically for all special char using negative match ?

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts (hunk 3 above)
Comment (guillim) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts]: can you provide more details ? Is that an object from Jest ?

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts (hunk 2 above)
Comment (guillim) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts:26]: TBO, there is no need since it's just shit that should not be there

Comment (guillim) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/utils/sanitizeCalendarEvent.ts:26]: We can find names for these but they would be kind of useless "zeroEncodedCharforUTF8"

File: packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts (hunk 3 above)
Comment (prastoin) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts]: No that's a generic we use in order to force convention on context and title disposition of jest tables

Comment (prastoin) [reply packages/twenty-server/src/modules/calendar/calendar-event-import-manager/drivers/google-calendar/utils/__tests__/format-google-calendar-event.util.spec.ts]: You can find the type from twenty-shared
