### PR TITLE
Fix edge x position

### LINKED ISSUE #1058: [Workflow] [Bug] Workflow arrows between steps are not properly aligned
Image

### PR DESCRIPTION
**Pull request by martmull**
## Before
image

## After
image

### CODE REVIEW

File: packages/twenty-front/src/modules/workflow/workflow-diagram/constants/CreateStepNodeWidth.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import { NODE_BORDER_WIDTH } from '@/workflow/workflow-diagram/constants/NodeBorderWidth';
+
+export const CREATE_STEP_NODE_WIDTH = 24 + 8 + NODE_BORDER_WIDTH; // New step icon width + step padding + border width
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/workflow/workflow-diagram/constants/CreateStepNodeWidth.ts]: **neat:** prefer:
const ICON_WIDTH = 24
const STEP_PADDING = 8
export const CREATE_STEP_NODE_WIDTH = ICON_WIDTH + STEP_PADDING + NODE_BORDER_WIDTH

instead of adding a comment

**Review by charlesBochet — COMMENTED** [review]
I haven't tested the functional behavior but code LGTM, added a "neat" comment

**Review by thomtrp — APPROVED** [review]
LGTM
