### PR TITLE
fixing Numbers formatting 

### LINKED ISSUE #13880: Ex: Add custom field from Companies / People table options menu
Add option to display numbers without comma separators.

Image

### PR DESCRIPTION
**Pull request by ketanMehtaa**
fix #13880

### CODE REVIEW

**Comment by ketanMehtaa** [comment]
@FelixMalfait i am a little new to nest gql (backend ) , can someone from team help me out in backend part for mental model i tried adding below code in workspace-member.workspace-entity.ts and while running the migration command getting error no schema change .

```
WorkspaceField({
    standardId: WORKSPACE_MEMBER_STANDARD_FIELD_IDS.numberFormat,
    type: FieldMetadataType.SELECT,
    label: msg`Number format`,
    description: msg`User's preferred number format`,
    icon: 'IconNumbers', // Consider using 'IconNumbers' or 'IconHash'
    options: [
      {
        value: WorkspaceMemberNumberFormatEnum.COMMAS_AND_DOT,
        label: 'Commas and dot (1,234.56)',
        position: 0,
        color: 'blue',
      },
      {
        value: WorkspaceMemberNumberFormatEnum.SPACES_AND_COMMA,
        label: 'Spaces and comma (1 234,56)',
        position: 1,
        color: 'green',
      },
      {
        value: WorkspaceMemberNumberFormatEnum.SPACES_AND_DOT,
        label: 'Spaces and dot (1 234.56)',
        position: 2,
        color: 'orange',
      },
      {
        value: WorkspaceMemberNumberFormatEnum.MAGNITUDE_SUFFIXES,
        label: 'Magnitude suffixes (1.2k)',
        position: 3,
        color: 'purple',
      },
    ],
    defaultValue: `'${WorkspaceMemberNumberFormatEnum.COMMAS_AND_DOT}'`,
  })
  @WorkspaceIsSystem()
  numberFormat: string;
```

**Comment by FelixMalfait** [comment]
@ketanMehtaa I think you're running typeorm migration command. We have our own migration mechanism for workspace objects since each workspace gets its own schema in Postgres, a lot of custom logic has been built to handle that. 

I recommend using database:reset as mentionned in the other command, but you can also try `yarn command:prod workspace:sync-metadata -f` if you just want to apply the difference.

Also I would leave aside MAGNITUDE_SUFFIXES at the field level since it's a different purpose and already exist (it's more like "is this field short vs long" while the options are more "are you French or American", so let's focus on the first 3 options only for now)

**Comment by FelixMalfait** [comment]
Also please make sure to fix lint/typecheck errors, thanks a lot!

File: packages/twenty-front/src/modules/localization/states/dateTimeFormatState.ts [hunk 1]
```diff
@@ -1,17 +1,20 @@
...
   dateFormat: DateFormat;
   timeFormat: TimeFormat;
+  numberFormat: NumberFormat;
 }>({
   key: 'dateTimeFormatState',
   defaultValue: {
     timeZone: detectTimeZone(),
     dateFormat: DateFormat.MONTH_FIRST,
     timeFormat: TimeFormat['HOUR_24'],
+    numberFormat: NumberFormat.COMMAS_AND_DOT,
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/localization/states/dateTimeFormatState.ts]: Like for other settings let's introduce a system value  (default value) and when it's that system then it's our job based on browser info available to guess what's the most likely/best format to use 

(that's what we do already for the first day of the week or time/date format)

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        {
+          label: 'Spaces and comma (1 234,56)',
+          value: NumberFormat.SPACES_AND_COMMA,
+        },
+        {
+          label: 'Spaces and dot (1 234.56)',
+          value: NumberFormat.SPACES_AND_DOT,
+        },
+        {
+          label: 'Magnitude suffixes (1.2k)',
```
Comment (FelixMalfait) [inline packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: Let's remove this one and focus on supporting system instead

**Comment by ketanMehtaa** [comment]
@FelixMalfait  when running 

npx nx run twenty-server:typeorm migration:generate src/database/typeorm/core/migrations/add-number-format-to-workspace-member -d src/database/typeorm/core/core.datasource.ts  

getting this -

No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command

also when tested with npx nx run twenty-server:command workspace:sync-metadata -f
code is working. so how to generate the migration. :)

File: packages/twenty-front/src/modules/localization/states/dateTimeFormatState.ts (hunk 1 above)
Comment (ketanMehtaa) [reply packages/twenty-front/src/modules/localization/states/dateTimeFormatState.ts]: done

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx (hunk 2 above)
Comment (ketanMehtaa) [reply packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: removed magnitude suffixes from complete PR

File: packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts [hunk 3]
```diff
@@ -23,6 +23,7 @@ export const USER_QUERY_FRAGMENT = gql`
     onboardingStatus
     workspaceMember {
       ...WorkspaceMemberQueryFragment
+      numberFormat
```
[the remark this answers is not in the document]
Comment (ketanMehtaa) [reply packages/twenty-front/src/modules/users/graphql/fragments/userQueryFragment.ts]: done

File: packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/display/components/NumberFieldDisplay.tsx [hunk 4]
```diff
@@ -1,22 +1,33 @@
...
+  }
 
-  return <NumberDisplay value={value} decimals={decimals} />;
+  const numericValue = Number(fieldValue);
+  let formattedValue: string;
+
+  if (type === 'percentage') {
+    formattedValue = `${formatNumber(numericValue * 100, numberFormat)}%`;
+  } else if (type === 'shortNumber') {
+    formattedValue = formatNumber(numericValue, numberFormat);
```
[the remark this answers is not in the document]
Comment (ketanMehtaa) [reply packages/twenty-front/src/modules/object-record/record-field/ui/meta-types/display/components/NumberFieldDisplay.tsx]: done

File: packages/twenty-front/src/modules/localization/utils/detectNumberFormat.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
+import { NumberFormat } from '@/localization/constants/NumberFormat';
+
+export const detectNumberFormat = (): NumberFormat => {
+  try {
+    const language = navigator.language;
```
[the remark this answers is not in the document]
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/localization/utils/detectNumberFormat.ts]: Yes I agree with Greptile's comment @ketanMehtaa - this is what we did in detectDateFormat for example

File: packages/twenty-front/src/modules/localization/utils/detectNumberFormat.ts [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+    }
+    if (language.startsWith('fr')) {
+      return NumberFormat.SPACES_AND_COMMA;
+    }
+    if (language.startsWith('de')) {
+      return NumberFormat.SPACES_AND_DOT;
+    }
+
+    return NumberFormat.COMMAS_AND_DOT;
+  } catch {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/localization/utils/detectNumberFormat.ts:20]: This shouldn't be a try/catch. Maybe you wanted to do a switch instead?

File: packages/twenty-front/src/modules/localization/utils/formatNumber.ts [hunk 7]
```diff
@@ -0,0 +1,40 @@
+import { NumberFormat } from '@/localization/constants/NumberFormat';
+
+export const formatNumber = (
+  value: number,
+  numberFormat: NumberFormat,
+): string => {
+  switch (numberFormat) {
+    case NumberFormat.SYSTEM:
+      return new Intl.NumberFormat(navigator.language, {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/localization/utils/formatNumber.ts]: Why navigator.language here? Should you use the detect function you created instead?

File: packages/twenty-front/src/modules/localization/utils/formatNumber.ts [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+      }).format(value);
+
+    case NumberFormat.SPACES_AND_COMMA:
+      return new Intl.NumberFormat('fr-FR', {
+        minimumFractionDigits: 0,
+        maximumFractionDigits: 2,
+      }).format(value);
+
+    case NumberFormat.SPACES_AND_DOT:
+      return new Intl.NumberFormat('en-US', {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/localization/utils/formatNumber.ts]: Why 0/2? What is the previous behavior? If someone enters 0.00001 maybe they have a valid use-case for it? This seems arbitraty

File: packages/twenty-front/src/modules/localization/utils/formatNumber.ts [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+        minimumFractionDigits: 0,
+        maximumFractionDigits: 2,
+      })
+        .format(value)
+        .replace(/,/g, ' ');
```
[the remark this answers is not in the document]
Comment (FelixMalfait) [reply packages/twenty-front/src/modules/localization/utils/formatNumber.ts]: Feels off  that we have to format this way yes

File: packages/twenty-front/src/modules/localization/utils/formatNumber.ts (hunk 7 above)
Comment (ketanMehtaa) [reply packages/twenty-front/src/modules/localization/utils/formatNumber.ts]: working on formatnumber.ts and detectnumberformat.ts right now

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+  const handleNumberFormatChange = async (value: NumberFormat) => {
+    if (!currentWorkspaceMember?.id) {
+      logError('User is not logged in');
+      return;
+    }
+
+    const workspaceNumberFormat =
+      value === NumberFormat.SYSTEM
+        ? WorkspaceMemberNumberFormatEnum.SYSTEM
+        : (value as unknown as WorkspaceMemberNumberFormatEnum);
```
Comment (FelixMalfait) [inline packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: Don't use "as" but type properly, and don't use unknown/any

Comment (ketanMehtaa) [reply packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: will remove it

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx [hunk 11]
```diff
@@ -0,0 +1,101 @@
...
+
+      setDateTimeFormat((prev) => ({
+        ...prev,
+        numberFormat: value,
+      }));
+    } catch (error) {
+      logError(error);
+    }
+  };
+  const testNumber = 1234.56;
```
Comment (FelixMalfait) [inline packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx:59]: What is that? This is dirty!

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+
+  const formatLabel = (format: NumberFormat) => {
```
Comment (FelixMalfait) [inline packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: This function isn't necessary imo and could be removed

Comment (FelixMalfait) [reply packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: This makes it look more complex than it actually is

File: packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts [hunk 13]
```diff
@@ -51,6 +51,19 @@ export enum WorkspaceMemberTimeFormatEnum {
...
 }
 
+export enum WorkspaceMemberNumberFormatEnum {
+  SYSTEM = 'SYSTEM',
+  COMMAS_AND_DOT = 'COMMAS_AND_DOT',
+  SPACES_AND_COMMA = 'SPACES_AND_COMMA',
+  SPACES_AND_DOT = 'SPACES_AND_DOT',
+}
+
+// Register the enum with GraphQL
```
Comment (FelixMalfait) [inline packages/twenty-server/src/modules/workspace-member/standard-objects/workspace-member.workspace-entity.ts]: Don't add un-necessary comments

**Review by FelixMalfait — COMMENTED** [review]
Thank you, can you please fix all tests?

File: packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx (hunk 12 above)
Comment (ketanMehtaa) [reply packages/twenty-front/src/pages/settings/profile/appearance/components/NumberFormatSettings.tsx]: okay

**Comment by ketanMehtaa** [comment]
@FelixMalfait  Should I move the content of formatNumber.ts into the previously used numbers.ts (packages/twenty-front/src/utils/format/number.ts) file, or keep them as separate.

**Comment by FelixMalfait** [comment]
Hey, could you please check the tests so that we can review?

> Should I move the content of formatNumber.ts into the previously used numbers.ts (packages/twenty-front/src/utils/format/number.ts) file, or keep them as separate.

- One export = One file is always better
- We should not have two formatNumber, keep just one that maintains all functionality iso

Thanks!

**Comment by ketanMehtaa** [comment]
@FelixMalfait  I don't know why the tests are falling , can you help ?
I have merged the formatNumber function in one file and now in that file there are 2 functions for formating , a lot of places right now using the formatNumber(old function) and i am not able to decide where to use new and where to use old formating as some components are related to billing .

**Review by FelixMalfait — APPROVED** [review]
Thank you!

**Comment by ketanMehtaa** [comment]
Thank you @FelixMalfait  for refactoring .
I am not sure but if user is in system settings  on number format  , then there will be multiple calls to detectNumberFormat() and it may impact performance.

**Comment by FelixMalfait** [comment]
Yes you're right, a lot of mess around all preferences generally. I'll make a big refactoring today that unifies all preferences!
