### PR TITLE
fix: reset table selection when navigating away from index page

### LINKED ISSUE #9132: Reset Context Selection When Navigating Between Indexes
# Current behavior

When navigating to another index, the selection context is kept into memory (When I navigate through a show, as clicking outside a table remove the context)

https://github.com/user-attachments/assets/7a22e1c1-51f6-4d5a-a3eb-2724f0df7c0d

https://github.com/user-attachments/assets/cddd2163-ec56-4adb-acc7-c50090242ea7

# Desired Behavior

We should reset the context selection. No records should be selected when coming back on an index

### PR DESCRIPTION
**Pull request by samyakpiya**
Fixes #9132 

## Purpose
Currently, when navigating away from an index page and returning, previously checked selections remain checked. This fix ensures the selection context is properly reset on navigation.

## Changes
- Add `RecordIndexResetSelectionEffect` component to handle selection cleanup
- Integrate effect into `RecordIndexPage`
- Uses existing `useResetTableRowSelection` hook to clear selections

## Testing
1. Go to any index page (e.g., Companies)
2. Select some records using checkboxes
3. Navigate to a detail page
4. Return to the index page
5. Verify that no records are selected

## Demo
I've recorded a short video demonstrating how this PR fixes the issue:

[Loom Video Link](https://www.loom.com/share/72ca46a5dc194b5092e1944a985fa0d2?sid=55c95d8b-2376-4ac5-b406-6483aa7e341f)

Before fix: Selections persist after navigation
After fix: Selections are properly reset

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you :)

**Comment by charlesBochet** [comment]
@samyakpiya I have approved first but we actually would like to test a different pattern. We are trying to get rid of the useEffects completely on the codebase

The right way to do that is to let the caller synchronously reset the table selection. But how could the link in RecordDetailSectionHeader know that it should reset the table selection: let's introduce a <NavigateToIndexPageLink> component that will include a <Link to={...} onClick{resetTableSelection} />

**Review by charlesBochet — CHANGES_REQUESTED** [review]
see comment above

**Comment by samyakpiya** [comment]
@charlesBochet Thanks for the feedback! I understand we want to move away from useEffect and handle the selection reset synchronously through the Link component's onClick. I'll update the PR to implement this pattern instead.

**Comment by samyakpiya** [comment]
@charlesBochet I've considered the pattern you suggested but have some technical concerns to discuss.

The current suggestion to handle reset via `<Link onClick={resetTableSelection}>` would only cover the show page → index page navigation path. However, shouldn't the table selection reset whenever we leave the index page, regardless of destination? For instance:

1. Workspace switches
2. Direct URL changes (browser back/forward)
3. Navigation to any other route
4. External links

Additionally, implementing this through Links would require lifting state management up the component tree to make the reset function available to both index and show pages.

Would it make more sense to handle this at the routing/navigation level instead? This would ensure consistent behavior regardless of how the user leaves the index page. I'm happy to explore alternative patterns that don't use useEffect while still covering all these edge cases.

**Comment by lucasbordeau** [comment]
@samyakpiya Let's implement an isLeavingIndexPage in PageChangeEffect, we'll refactor when we refactor PageChangeEffect.

**Comment by samyakpiya** [comment]
Sounds good, thanks!

**Comment by samyakpiya** [comment]
@lucasbordeau `useResetTableRowSelection(objectNamePlural)` seems to throw whenever `objectNamePlural` is an empty string because of [this](https://github.com/twentyhq/twenty/blob/4f7fa7adcdf9598c94a4806e678b48a1cc5e3da0/packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts#L16C1-L19C5).

But if we're setting the reset logic in this `PageChangeEffect`, since hooks can't be called conditionally, every time the code reaches this point:

```
const resetTableSelections = useResetTableRowSelection(objectNamePlural);
```

and the user is not currently in the `RecordIndexPage`, this is bound to throw. I've currently used `CoreObjectNamePlural.Person` as a workaround, but don't think this the right way to do it. How would you handle it?

File: packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx [hunk 1]
```diff
@@ -38,6 +45,11 @@ export const PageChangeEffect = () => {
 
   const eventTracker = useEventTracker();
 
+  const objectNamePlural =
```
Comment (samyakpiya) [inline packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx:48]: @lucasbordeau `useResetTableRowSelection(objectNamePlural)` seems to throw whenever `objectNamePlural` is an empty string because of [this](https://github.com/twentyhq/twenty/blob/4f7fa7adcdf9598c94a4806e678b48a1cc5e3da0/packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useResetTableRowSelection.ts#L16C1-L19C5).

But if we're setting the reset logic in this `PageChangeEffect`, since hooks can't be called conditionally, every time the code reaches this point:

```
const resetTableSelections = useResetTableRowSelection(objectNamePlural);
```

and the user is not currently in the `RecordIndexPage`, this is bound to throw. I've currently used `CoreObjectNamePlural.Person` as a workaround, but don't think this the right way to do it. How would you handle it?

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx:48]: This is technical debt at this point, we have to refactor this hook. 

I suggest that you add a TODO comment and let your current fix which is enough for now.

**Review by lucasbordeau — APPROVED** [review]

**Review by charlesBochet — APPROVED** [review]
