### PR TITLE
Navigation drawer scroll padding fix

### LINKED ISSUE #9026: Clean scroll paddings in Navigation Drawer
## Current behavior
Currently, we hide the scroll in the NavigationDrawer(#8896) because, with the current implementation, it is rendered over the NavigationDrawerItems.

Image

## Expected behavior
We want a clean scroll bar with correct paddings/positioning(it should not clip over NavigationDrawerItems)

### LINKED ISSUE #9312: Unable to scroll horizontally?
0.35.2

https://github.com/user-attachments/assets/e53c91c5-3f08-43e8-b4b3-7146added7bc

### PR DESCRIPTION
**Pull request by ehconitin**
closes https://github.com/twentyhq/twenty/issues/9026
fixes #9312

https://github.com/user-attachments/assets/3d7df3ec-8a5e-4308-8993-82c715edc683

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx [hunk 1]
```diff
@@ -106,11 +107,7 @@ export const ScrollWrapper = ({
           id: contextProviderName,
         }}
       >
-        <StyledScrollWrapper
-          ref={scrollableRef}
-          className={className}
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx:111]: why are we removing the scrollHide?

File: packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx [hunk 2]
```diff
@@ -9,4 +10,25 @@ const StyledSection = styled.div`
...
-export { StyledSection as NavigationDrawerSection };
+const StyledSectionInnerContainerMinusScrollPadding = styled.div<{
+  isMobile: boolean;
+}>`
+  width: calc(
+    100% - ${({ isMobile, theme }) => (isMobile ? 0 : theme.spacing(2))}
+  );
+`;
+
+export const NavigationDrawerSection = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx:21]: I don't understand all these changes? Looks big changes for a small fix, could you explain it a bit more?

File: packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx (hunk 1 above)
Comment (ehconitin) [reply packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx:111]: We use scrollHide specifically to hide NavigationDrawer's scroll, but we have new requirements :). We are to show the scroll but with clear paddings

File: packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx (hunk 2 above)
Comment (ehconitin) [reply packages/twenty-front/src/modules/ui/navigation/navigation-drawer/components/NavigationDrawerSection.tsx:21]: We can't just remove scrollHide and use the ScrollWrapper in the drawer since it overlaps over the NavigationDrawerItems(for reference #9026), so the idea is to remove the right padding of the NavigationDrawers animated container. And since NavigationDrawerSection controls the width, have an internal wrapper that would minus the width required for the scroll.
Is this the right approach? also, ignore the scroll paddings and widths being changed in ScrollWrapper, I was just trying something out!

**Comment by FelixMalfait** [comment]
What is missing to move this PR forward? Thanks!

**Review by lucasbordeau — APPROVED** [review]
