### PR TITLE
fix timeline activity deleted field

### LINKED ISSUE #6362: Timeline activity crashes when attempting to report updates on deleted field
## Bug Description
Timeline activity section will report updates even on since-update-deleted fields, causing the show page to crash.

https://github.com/user-attachments/assets/b086abe3-2e27-45ea-b490-cfd4af065ab5

### PR DESCRIPTION
**Pull request by Weiko**
Fixes https://github.com/twentyhq/twenty/issues/6362

### CODE REVIEW

**Review by ijreilly — APPROVED** [review]

File: packages/twenty-front/src/modules/activities/timelineActivities/utils/filterOutInvalidEvents.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
+import { TimelineActivity } from '@/activities/timelineActivities/types/TimelineActivity';
+import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
+
+export const filterOutInvalidEvents = (
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/timelineActivities/utils/filterOutInvalidEvents.ts:4]: use timelineActivity naming

**Review by charlesBochet — APPROVED** [review]
