### PR TITLE
[BUGFIX] `GenerateDefaultRecordChipData` returns `RecordChipData`

### LINKED ISSUE #11030: Cannot read property of undefined reading id
I've seen this error in prod which seems quite critical.

I'm not sure what are the exact steps to reproduce it but I took 2 screenshots.

Image

Image

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
closes https://github.com/twentyhq/twenty/issues/11030, might not fix the issue as it seems to be related to the passed record to `identifierChipGeneratorPerObject` about to dig deeper in this generator code => found nothing revelant doubled check each `RecordChip` invocation that could provide undefined record
Fixed wrong default generated `RecordChipData` signature

## Reproducibility
I've only been able to reproduce the bug in production using the very same opportunity than within the issue, but not all the time
https://crm.twenty-internal.com/objects/opportunities?viewId=b709d3d1-2dd2-455d-ba73-784f3ab00883
```json
// Removed timelineActivities to prevent linking ids
{
  "data": {
    "opportunity": {
      "__typename": "Opportunity",
      "closeDate": null,
      "company": null,
      "companyId": null,
      "createdAt": "2024-06-17T09:45:22.357Z",
      "deletedAt": null,
      "id": "006a22dd-6bd6-4247-a24b-42fb164cd48c",
      "name": "test",
      "pointOfContact": null,
      "pointOfContactId": null,
      "position": 0,
      "probability": "0",
      "stage": "NEW_STAGE",
      "updatedAt": "2025-03-20T16:27:51.927Z",
      "amount": {
        "__typename": "Currency",
        "amountMicros": null,
        "currencyCode": "USD"
      },
      "attachments": {
        "__typename": "AttachmentConnection",
        "edges": []
      },
      "createdBy": {
        "__typename": "Actor",
        "source": "MANUAL",
        "workspaceMemberId": null,
        "name": "",
        "context": {}
      },
      "favorites": {
        "__typename": "FavoriteConnection",
        "edges": []
      },
      "taskTargets": {
        "__typename": "TaskTargetConnection",
        "edges": []
      },
      "noteTargets": {
        "__typename": "NoteTargetConnection",
        "edges": [
          {
            "__typename": "NoteTargetEdge",
            "node": {
              "__typename": "NoteTarget",
              "appEventId": null,
              "companyId": null,
              "createdAt": "2025-01-22T17:11:07.801Z",
              "deletedAt": null,
              "feedbackId": null,
              "id": "2e8eca1c-e2c2-425a-93fc-ef2aeb65f410",
              "issueId": null,
              "listingId": null,
              "noteId": "ab586b51-6931-4a4a-9c24-0d16226211b2",
              "opportunityId": "006a22dd-6bd6-4247-a24b-42fb164cd48c",
              "personId": null,
              "somethingId": null,
              "testId": null,
              "updatedAt": "2025-01-22T17:11:07.801Z"
            }
          }
        ]
      },
    }
  }
}
```

### CODE REVIEW

File: packages/twenty-front/src/modules/object-metadata/utils/generateDefaultRecordChipData.ts [hunk 1]
```diff
@@ -1,15 +1,25 @@
...
+    ? `${record.name.firstName} ${record.name.lastName}`
     : (record.name ?? '');
 
   return {
-    name,
-    avatarUrl: name,
     avatarType: 'rounded',
-    linkToShowPage: false,
+    avatarUrl: name,
+    isLabelIdentifier: false,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-metadata/utils/generateDefaultRecordChipData.ts:20]: ***Question:*** What should be the default value here ?

**Comment by prastoin** [comment]
Discovered something

**Review by lucasbordeau — APPROVED** [review]
LGTM
