### PR TITLE
Fix broken dropdown auto resize behavior

### LINKED ISSUE #725: The advanced filter dropdown should be responsive
Currently the advanced filter dropdown will push the border of the main app container and break the UI if it’s either on a small portrait screen or has too many filters to display vertically.

We would like to obtain the same behavior as other dropdowns that avoid breaking the main container UI and resize or move to stay visible and UX friendly.

Here since it is a bigger dropdown, and that it is fixed at the bottom of the advanced filter chip, it should be scrollable when it overflows, and should resize to fit the main container.

We should use the same middleware strategy that is used for other dropowns.

Image

Image

### LINKED ISSUE #11409: Regression on scrollable dropdowns
Dropdown used to be scrollable, now they overflow outside the app

Image

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR was originally about fixing advanced filter dropdown auto resize to avoid breaking the app main container, but the regression is not limited to advanced filter dropdown, so this PR fixes the regression for every dropdown in the app.

This PR adds a max dropdown max width to allow resizing dropdowns horizontally also, which can happen easily for the advanced filter dropdown.

In this PR we also start removing `fieldMetadataItemUsedInDropdown` in component `AdvancedFilterDropdownTextInput` because it has no impact outside of this component which is used only once.

The autoresize behavior determines the right padding-bottom between mobile and PC.

Mobile : 

Capture d’écran 2025-04-07 à 16 03 12

PC :

Capture d’écran 2025-04-07 à 16 03 30

Fixes https://github.com/twentyhq/core-team-issues/issues/725
Fixes https://github.com/twentyhq/twenty/issues/11409

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/states/dropdownMaxWidthComponentStateV2.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { DropdownComponentInstanceContext } from '@/ui/layout/dropdown/contexts/DropdownComponeInstanceContext';
+import { createComponentStateV2 } from '@/ui/utilities/state/component-state/utils/createComponentStateV2';
+
+export const dropdownMaxWidthComponentStateV2 = createComponentStateV2<
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/dropdown/states/dropdownMaxWidthComponentStateV2.ts:4]: removeV2

**Review by charlesBochet — APPROVED** [review]
