### PR TITLE
fix: composite type migrations not well formatted

### LINKED ISSUE #3002: fix: can't query object with currency column
## Scope & Context

A bug seems to prevent querying objects when we add a field of type `CURRENCY`.

## Current behavior

The following error is thrown:

```json
{
    "errors": [
        {
            "message": "Malformed result from GraphQL query",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "people"
            ]
        }
    ],
    "data": null
}
```

## Expected behavior

The query should work properly.

### PR DESCRIPTION
**Pull request by magrinj**
When using custom fields inside standards or custom objects, the generated `targetColumnMap` was not generated with the custom prefix `_`.
So we got an error during the query, because we're trying to retrieve column that doesn't exist.
This PR fix the issue.

Fix #3002

### CODE REVIEW

File: packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts [hunk 1]
```diff
@@ -2,10 +2,22 @@ import { ObjectMetadataInterface } from 'src/metadata/field-metadata/interfaces/
...
   fieldMetadata?: FieldMetadataInterface,
 ): FieldMetadataInterface[] => {
+  const targetColumnMap = fieldMetadata
+    ? generateTargetColumnMap(
+        fieldMetadata.type,
+        fieldMetadata.isCustom ?? false,
+        fieldMetadata.name,
+      )
+    : {
+        amountMicros: 'amountMicros',
```
Comment (Weiko) [inline packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts:17]: So basically if fieldMetadata is here, this is used to map for pg_graphql. 

If fieldMetadata is not here, this is for the return of the schema builder so we don't want the name of the field and have a clean 
budget {
  amountMicros
  currencyCode
}

I'm wondering if it was a good idea to use the same code for 2 things that seem quite different?
Wdyt?

**Review by Weiko — APPROVED** [review]
LGTM but left a comment
