### PR TITLE
5509 remove flash on intermediate verify step when sign in with sso

### LINKED ISSUE #5509: Remove Flash on intermediate Verify step when sign In with SSO
## How to reproduce

IsBillingEnabled = false

Sign In (Authenticate) With SSO
After authenticate with SSO, we are redirected to:
- /verify/ID
- /create/workspace
- /
- /object/companies

https://github.com/twentyhq/twenty/assets/29927851/5b83efa0-1eab-48cf-9c3e-1d046312387b

### LINKED ISSUE #5510: Remove Flash on intermediate Verify step when sign Up with SSO or Email/Password
## How to reproduce

IsBillingEnabled = true

Sign Up (Register) With SSO or Email/Password
After authenticate with SSO or Email/Password, we are redirected to:

/verify/ID
/create/workspace
/plan-required

Ex with SSO
https://github.com/twentyhq/twenty/assets/29927851/fa8309f4-dd97-462b-aef3-e687499d8aca

### PR DESCRIPTION
**Pull request by martmull**
- remove flash on /verify
- remove flash on signInUp
- remove useless redirections and hooks
- Remove DefaultHomePage component
- Move redirections to /objects/companies in PageChangeEffect
- add useShowAuthModal hooks and tests
- add usePageChangeEffectNaviteLocation hooks and tests
- fix refresh token expired produces blank screen

### CODE REVIEW

File: packages/twenty-front/src/effect-components/PageChangeEffect.tsx [hunk 1]
```diff
@@ -5,48 +5,41 @@ import { IconCheckbox } from 'twenty-ui';
...
 
   const [previousLocation, setPreviousLocation] = useState('');
 
-  const onboardingStatus = useOnboardingStatus();
-
   const setHotkeyScope = useSetHotkeyScope();
 
   const location = useLocation();
 
+  const pageChangeEffectNavigateLocation =
```
Comment (charlesBochet) [inline packages/twenty-front/src/effect-components/PageChangeEffect.tsx:34]: awesome

Comment (charlesBochet) [reply packages/twenty-front/src/effect-components/PageChangeEffect.tsx:34]: thanks for adding tests

File: packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx [hunk 2]
```diff
@@ -105,24 +102,18 @@ export const useSignInUp = (form: UseFormReturn<Form>) => {
...
-              )
-            : await signUpWithCredentials(
-                data.email.toLowerCase().trim(),
-                data.password,
-                workspaceInviteHash,
-                token,
-              );
-
-        navigateAfterSignInUp(currentWorkspace, currentWorkspaceMember);
+        signInUpMode === SignInUpMode.SignIn && !isInviteMode
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSignInUp.tsx:105]: I think we should keep the sync navigate here, it's the more precise we have

**Review by charlesBochet — APPROVED** [review]
