### PR TITLE
fix: trigger onClickOutside when click escape for closing the model a…

### LINKED ISSUE #12319: Exiting a filter creation/update from the table column header with escape doesn't remove the editable filter chip
It should be removed, like when we click outside.

https://github.com/user-attachments/assets/a6d130d3-206d-4ea4-8643-4e3ff01438c2

### PR DESCRIPTION
**Pull request by AjayAdsule**
Description:
Resolved a bug where pressing the Escape key did not clear the filter chips when no filter value was present.
Added a call to onClickOutside inside the useScopedHotkeys hook to ensure filter chips are removed when Escape is pressed and the dropdown is open but empty.

https://github.com/user-attachments/assets/42ed35b0-f5a8-4d26-8407-fdd5e2cc4a42

fix #12319

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx [hunk 1]
```diff
@@ -121,9 +121,10 @@ export const DropdownInternalContainer = ({
       if (isDropdownOpen) {
         closeDropdown();
       }
+      onClickOutside?.();
```
[the remark this answers is not in the document]
Comment (AjayAdsule) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx]: oh i take reference from useListenClickOutside hook so i call outside

Comment (bosiraphael) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx]: We don't necessarily want the same behavior on click outside and on escape. What we should instead do is put the desire behavior inside the `onClose` of the specific component you want to fix: `ObjectFilterDropdownFilterInput`.

Comment (AjayAdsule) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx]: okay

Comment (AjayAdsule) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/internal/DropdownInternalContainer.tsx]: please review

**Review by bosiraphael — APPROVED** [review]
LGTM thank you for your contribution 👏
