### PR TITLE
Advanced filter bug bash

### LINKED ISSUE #655: Bug company filter dropdown search input not cleared
When we close and re-open the company filter dropdown input, it should clear the search input.

### LINKED ISSUE #724: Having a deleted add filter in advanced filter should be visible
When we have a deleted at filter in advanced filters, it will show up soft deleted records.

Because we’re allowed to obtain this state without going through the action “See deleted record”, we should signify to the user that we are seeing deleted records.

As this is currently told by the filter chip being red, we want to apply the same UI style to advanced filters.

So we should have a red advanced filter chip if it contains any deleted at filter : 

Image

The current state is this :

Image

### LINKED ISSUE #726: Advanced filter count should only count the root level rules
In advanced filter dropdown, we are currently counting all record filters.

Instead we want to only count root level record filters and record filter groups.

So if we have 1 record filter and 2 record filter groups, we want to count 3, even if the filter groups contains many record filters each.

Current state :

Image

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes some bugs on advanced filters dropdown.

See reference master issue : https://github.com/twentyhq/core-team-issues/issues/648

Fixes https://github.com/twentyhq/core-team-issues/issues/726
Fixes https://github.com/twentyhq/core-team-issues/issues/724
Fixes https://github.com/twentyhq/core-team-issues/issues/655

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts [hunk 1]
```diff
@@ -29,7 +30,7 @@ export const useCheckIsSoftDeleteFilter = () => {
     }
 
     return (
-      foundFieldMetadataItem.name === 'deletedAt' &&
+      foundFieldMetadataItem.name === SOFT_DELETE_FILTER_FIELD_NAME &&
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts:33]: Should we replace it in other places where it's used? (Can be in a followup PR)

Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts:33]: Oh I see it's just local. But maybe we should rename this to SOFT_DELETE_FIELD_NAME in object-record constants and use it for every instance of the fieldname?

**Review by FelixMalfait — APPROVED** [review]
Great!

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts (hunk 1 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts:33]: It's quite clear in the backend that deletedAt is a standard field name.

See `BaseWorkspaceEntity` : 

```tsx 
@WorkspaceField({
    standardId: BASE_OBJECT_STANDARD_FIELD_IDS.deletedAt,
    type: FieldMetadataType.DATE_TIME,
    label: msg`Deleted at`,
    description: msg`Date when the record was deleted`,
    icon: 'IconCalendarMinus',
    settings: {
      displayAsRelativeDate: true,
    },
  })
  @WorkspaceIsNullable()
  deletedAt: string | null;
```

And `standard-field-ids.ts` : 

```tsx
export const BASE_OBJECT_STANDARD_FIELD_IDS = {
  id: '20202020-eda0-4cee-9577-3eb357e3c22b',
  createdAt: '20202020-66ac-4502-9975-e4d959c50311',
  updatedAt: '20202020-d767-4622-bdcf-d8a084834d86',
  deletedAt: '20202020-b9a7-48d8-8387-b9a3090a50ec',
};
```

I don't think that going further is necessary, because it seems pretty stable across time already. 

But we could add a constant in shared and have for example : 

```tsx
export const SOFT_DELETE_FIELD_NAME = 'deletedAt';

export const BASE_OBJECT_STANDARD_FIELD_IDS = {
  id: '20202020-eda0-4cee-9577-3eb357e3c22b',
  createdAt: '20202020-66ac-4502-9975-e4d959c50311',
  updatedAt: '20202020-d767-4622-bdcf-d8a084834d86',
 [SOFT_DELETE_FIELD_NAME]: '20202020-b9a7-48d8-8387-b9a3090a50ec',
};
```

Should we do this in an issue ?

Comment (FelixMalfait) [reply packages/twenty-front/src/modules/object-record/record-filter/hooks/useCheckIsSoftDeleteFilter.ts:33]: It's just that your change felt like a middle-ground, but I'm not sure if this is really a priority, probably not
