### PR TITLE
Fix object metadata view creation issue

### LINKED ISSUE #26: Newly created object is visible only after refreshing page
**Scenario:**
1. Log in
2. Go to Settings > Data Model and create new object
3. Go back to main page

**Actual:** Newly created object is visible only after refreshing page or logging out and logging in

https://github.com/user-attachments/assets/6c33995f-a00f-4476-800f-5314f7082329

**Expected:** Newly created object should be visible immediately after creation

### LINKED ISSUE #9350: App freezes for few seconds after adding new field
**Scenario:**
1. Log in
2. Go to Settings > Data model > any existing object
3. Add field of any type

**Actual:** After adding new field, app freezes for few seconds (probably because of refreshing cache, logs show that every time new field is added, new data source with higher metadata version is created)

**Expected:** After adding new field, app shouldn't freeze for few seconds

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes https://github.com/twentyhq/core-team-issues/issues/26
Fixes https://github.com/twentyhq/twenty/issues/9350

### CODE REVIEW

File: packages/twenty-front/src/modules/favorites/components/WorkspaceFavorites.tsx [hunk 1]
```diff
@@ -1,11 +1,10 @@
-import { useFilteredObjectMetadataItemsForWorkspaceFavorites } from '@/navigation/hooks/useObjectMetadataItemsInWorkspaceFavorites';
+import { useWorkspaceFavorites } from '@/favorites/hooks/useWorkspaceFavorites';
 import { NavigationDrawerSectionForObjectMetadataItems } from '@/object-metadata/components/NavigationDrawerSectionForObjectMetadataItems';
 import { NavigationDrawerSectionForObjectMetadataItemsSkeletonLoader } from '@/object-metadata/components/NavigationDrawerSectionForObjectMetadataItemsSkeletonLoader';
 import { useIsPrefetchLoading } from '@/prefetch/hooks/useIsPrefetchLoading';
 
 export const WorkspaceFavorites = () => {
-  const { activeObjectMetadataItems: objectMetadataItemsToDisplay } =
-    useFilteredObjectMetadataItemsForWorkspaceFavorites();
+  const { workspaceFavoritesObjectMetadataItems } = useWorkspaceFavorites();
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/favorites/components/WorkspaceFavorites.tsx:7]: refactoring this hook to remove code

File: packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts [hunk 2]
```diff
@@ -52,5 +54,29 @@ export const useWorkspaceFavorites = () => {
     ],
   );
 
-  return { sortedWorkspaceFavorites };
+  const workspaceFavoriteIds = new Set(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts:57]: this part of the code was (and still is) a big "spaghetti". I think here we should have one hook to encapsulate the workspaceFavorite logic instead of having many hooks relying on eachother.

Comment (charlesBochet) [reply packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts:57]: the logic is too coupled to be split in different hooks IMO

File: packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneObjectMetadataItem.ts [hunk 3]
```diff
@@ -42,15 +35,7 @@ export const useCreateOneObjectMetadataItem = () => {
     return createdObjectMetadata;
   };
 
-  const findManyRecordsCache = async () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/hooks/useCreateOneObjectMetadataItem.ts:45]: this is not needed as the PrefetchQueries will update themselves as ObjectMetadataItems are refreshed

File: packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts [hunk 4]
```diff
@@ -72,10 +72,14 @@ export const useFindManyRecords = <T extends ObjectRecord = ObjectRecord>({
     useQuery<RecordGqlOperationFindManyResult>(findManyRecordsQuery, {
       skip: skip || !objectMetadataItem,
       variables: {
-        filter: {
-          ...filter,
-          ...(withSoftDeleted ? withSoftDeleterFilter : {}),
-        },
+        ...(filter || withSoftDeleted
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/hooks/useFindManyRecords.ts:75]: this was an issue: always adding filter: {} not matter what. Not what we want

File: packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx [hunk 5]
```diff
@@ -59,7 +59,7 @@ const StyledInput = styled.input<
   padding: ${({ theme, sizeVariant }) =>
     sizeVariant === 'sm' ? `${theme.spacing(2)} 0` : theme.spacing(2)};
   padding-left: ${({ theme, LeftIcon }) =>
-    LeftIcon ? `px` : theme.spacing(2)};
+    LeftIcon ? `calc(${theme.spacing(4)} + 16px)` : theme.spacing(2)};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx:62]: regression fixed

File: packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx [hunk 6]
```diff
@@ -53,8 +52,6 @@ export const SettingsNewObject = () => {
           ? { objectNamePlural: response.createOneObject.namePlural }
           : undefined,
       );
-
-      await findManyRecordsCache();
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/settings/data-model/SettingsNewObject.tsx:57]: not useful anymore see comment above

File: packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx [hunk 7]
```diff
@@ -137,6 +137,10 @@ export const SettingsObjectNewFieldConfigure = () => {
     formValues: SettingsDataModelNewFieldFormValues,
   ) => {
     try {
+      navigate(SettingsPath.ObjectDetail, {
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/settings/data-model/SettingsObjectNewField/SettingsObjectNewFieldConfigure.tsx:140]: let's navigate sooner to enhance UX

**Review by Weiko — APPROVED** [review]
LGTM
