### PR TITLE
Fixes #7105: Fixed column header on Kanban boards

### LINKED ISSUE #7105: Fixed column header on Kanban boards
# Current Behavior

Currently, Kanban column headers are not fixed. When the page is scrolled, they disappear.

https://github.com/user-attachments/assets/c6649976-62f2-4b20-b4d3-9684c091776c

# Desired Behavior

Change the column header position to fixed so they stay on top while scrolling the page

image

Video to explain the expected behavior:

https://github.com/user-attachments/assets/1825fe2c-392d-4ef2-a53c-998bfe1d4096

# Figma

Introduce a 40px heigh column header container CleanShot 2024-09-17 at 18 20 50

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194300&node-type=frame&t=vjg6Ofev4bkaijG1-11

### PR DESCRIPTION
**Pull request by dilshad-knk**
Issue Reference: Fixes #7105

Description:
This pull request introduces adjustments to the styling of the RecordBoardColumnHeader component. The modifications enhance the layout and visual consistency of the Kanban board headers.

Changes Made:
Margin Adjustment:

Increased the bottom margin from theme.spacing(2) to theme.spacing(6) for better spacing below the header.
Header Container Enhancements:

Added a background color sourced from the theme (theme.background.primary) to the header container for improved visibility and aesthetics.
Set a fixed height of 40px for the header to ensure a consistent size across different screens.
Applied a fixed position to the header container to keep it visible at the top during scrolling.
Added padding at the top using theme.spacing(2) for better alignment of content within the header.

Before :

https://github.com/user-attachments/assets/fd1c2d65-5e50-489a-a388-c0c4e1bd015b

Now :

[now.webm](https://github.com/user-attachments/assets/bd4cfb86-fc14-4902-b84c-99d27b07859e)

### CODE REVIEW

**Comment by ehconitin** [comment]
@dilshad-knk Thank you for the PR! However, I believe this may not be the right approach.

The hover button in the header isn't functioning as expected, and scrolling still affects the tabs above the headers (specifically the view/filter tab).

Take your time with this. A more elegant solution might be to find a way to exclude those tabs/components from the `RecordBoards` `scrollWrapper`, keeping only the columns within it.

That said, I'm not sure if the hint I gave would work, so feel free to reach out if you have any questions or need further clarification!


https://github.com/user-attachments/assets/e37c864f-bead-452b-a15b-17ea84819226

File: packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx [hunk 1]
```diff
@@ -45,9 +45,13 @@ const StyledHeaderActions = styled.div`
   margin-left: auto;
 `;
 const StyledHeaderContainer = styled.div`
+  background: ${({ theme }) => theme.background.primary};
   display: flex;
+  height: 40px;
   justify-content: space-between;
+  position: fixed;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnHeader.tsx:52]: I think this might be the issue hover buttons are not working as expected!

**Comment by Bonapara** [comment]
Hi @dilshad-knk, thanks for raising this PR. A few feedbacks:


https://github.com/user-attachments/assets/16dfe858-255f-4688-9456-1a402d15fcec

The column header bar should be sticky, not fixed (It should not goes under the view bar when trying to scroll top for instance)


https://github.com/user-attachments/assets/0fa76399-8ef5-40b6-bddd-9c3007c0cee6

Box shadows should not be visible when the card passes behind the column header. (The column header should take the full column width)

CleanShot 2024-10-09 at 11 43 10

The view bar border bottom should be visible (Figma image above)

CleanShot 2024-10-09 at 11 43 57

The header bar extends beyond the container on the left side.

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40088-434680&node-type=frame&t=emAJEVbp4fn8hzHL-11

**Review by charlesBochet — APPROVED** [review]
LGTM

**Comment by ehconitin** [comment]
@charlesBochet 
I noticed that the margins between columns does not extend to the bottom :(

Screenshot 2024-10-16 at 15 28 22
