### PR TITLE
Handle no value options in filters 

### LINKED ISSUE #11323: Incorrect aggregate query when hiding the "No value" column
### Steps to reproduce 
 
- Create a new Select field (Opportunity.Stage is not nullable so it won't work)
- Create a new Kanban field on that field
- Hide the "No value" column
- Try to create a new record from the kanban view
- An error appears saying that the select field enum value is not recognized

### What's happening
This is because the query for the aggregate value on the view switcher send an incorrect filter value with an empty string

Maybe related to https://github.com/twentyhq/twenty/pull/11094/files @martmull? Not sure!

### PR DESCRIPTION
**Pull request by ijreilly**
Fixes #11323 - see description to reproduce

The issue was that the filter was malformed for no value options: 
Capture d’écran 2025-04-02 à 14 56 25
causing
Capture d’écran 2025-04-02 à 14 56 43

after fix: 
Capture d’écran 2025-04-02 à 14 39 56

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts [hunk 1]
```diff
@@ -584,20 +584,38 @@ export const computeFilterRecordGqlOperationFilter = ({
...
+      const nonEmptyOptions = options.filter((opt) => opt !== '');
+
       switch (filter.operand) {
-        case RecordFilterOperand.Contains:
-          return {
-            [correspondingField.name]: {
-              containsAny: options,
-            } as MultiSelectFilter,
-          };
+        case RecordFilterOperand.Contains: {
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts:591]: I needed to fix SELECT case for the bug but I thought we also need to update the logic here, wdyt?

File: packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts [hunk 2]
```diff
@@ -584,20 +584,38 @@ export const computeFilterRecordGqlOperationFilter = ({
 
       if (options.length === 0) return;
 
+      const noValueOptions = options.filter((opt) => opt === '');
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts:587]: Can we fix this typescript error ? 

"option" would be better to avoid using abreviation even for anonymous function parameters, as we try to do as much as possible in the codebase.

File: packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts (hunk 1 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-filter/utils/computeViewRecordGqlOperationFilter.ts:591]: Since we shouldn't be able right now to land this is not mandatory but why not yes.

**Review by Weiko — APPROVED** [review]
LGTM, let's add more tests maybe?
