### PR TITLE
Fix: positioning of label to rename columns

### LINKED ISSUE #795: Bug: positioning of label to rename columns
See here: https://www.loom.com/share/8b329c2d80184e6d92918d528d04ab89

From 0:08 to 0:18 this is the right behavior. But somehow when I clicked on the last column, it messed things up and the label is now displayed somewhere else

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #795 

Demo:
https://www.loom.com/share/d3bf12ed4f884b5181de982e68b230cb?sid=3692a9a7-28ce-47fb-8612-b9f4252ab8b1

### CODE REVIEW

File: front/src/modules/ui/board/components/BoardColumn.tsx [hunk 1]
```diff
@@ -21,6 +21,7 @@ export const StyledColumn = styled.div<{ isFirstColumn: boolean }>`
   min-width: 200px;
 
   padding: ${({ theme }) => theme.spacing(2)};
+  position: relative;
```
Comment (gitstart-twenty) [inline front/src/modules/ui/board/components/BoardColumn.tsx:24]: The position of the `BoardColumnMenu`, which is `absolute` positioned, gets affected when certain columns in the KanBan board are hidden. To address this problem, setting the `BoardColumn` as the closest positioned ancestor by giving it a `position: relative` style resolves the issue.

**Review by charlesBochet — APPROVED** [review]
Thanks!
