### PR TITLE
Fix for view switcher default icon display

### LINKED ISSUE #6947: View Switcher - Default Icon Display
# Current behavior

If not customized, The view icon is set to the `Kanban` or `Table` icon. But the icon displayed in the `Icon Picker` doesn't reflect this. (It displayed the last icon selected in the picker, and by default the list icon)

https://github.com/user-attachments/assets/3f8c94f8-419a-475a-a685-2e6eb80c228f

# Desired Behavior

The picker should display the Table icon by default. If the icon hasn't been edited, the picker should reflect the default icon (Table or Kanban) until the user takes control and chooses a custom icon.

### PR DESCRIPTION
**Pull request by rathodvinod5**
Fixes #6947 (View switcher default icon display)

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx [hunk 1]
```diff
@@ -29,6 +35,7 @@ export type IconPickerProps = {
   variant?: IconButtonVariant;
   className?: string;
   disableBlur?: boolean;
+  takeControlOfCustomIcon?: boolean;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx:38]: I don't think we need this additional props, we can already provide the selectedIconKey directly

File: packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx [hunk 2]
```diff
@@ -147,6 +155,16 @@ export const IconPicker = ({
     [matchingSearchIconKeys],
   );
 
+  const getIconForIconPicker = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/input/components/IconPicker.tsx:158]: same here, I don't think we need this logic, we already have the selectedIconKey

File: packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContent.tsx [hunk 3]
```diff
@@ -104,6 +108,7 @@ export const ViewPickerCreateOrEditContent = () => {
   );
 
   const onIconChange = ({ iconKey }: { iconKey: string }) => {
+    toggleTakeControlOfCustomIcon(true);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/view-picker/components/ViewPickerCreateOrEditContent.tsx:111]: instead of introducing this "takeControlOfCustomIcon" logic, why not setting the viewPickerSelectedIcon on dropdown opening.
I would do that in ViewPickerCreateOrEditContentEffect, we already set the Icon from there for editView case, we can set it to table or kanban in case of createView

**Review by charlesBochet — COMMENTED** [review]
Thanks for the PR!

See my comments :)
1) Let's not introduce a new props and behavior on IconPicker
2) Let's set the default icon in ViewPickerCreateOrEditContentEffect instead for viewCreation case
3) you are pushing a new yarn.lock which is incorrect could you remove this file from your commit?

**Review by lucasbordeau — APPROVED** [review]

**Comment by rathodvinod5** [comment]
@lucasbordeau thanks for the guide, I will follow this practice in my future PR's.
