### PR TITLE
fix: recordBoard sticky header + scrollThumb

### LINKED ISSUE #8944: RecordBoard Header dissappears on page scroll up + missing scrollbar thumb
1. The Record Board Header disappears after some amount of scroll, even though it's sticky
2. It also misses vertical Scrollbar thumb(track)

https://github.com/user-attachments/assets/fbf44093-c51a-432f-9ac3-c8de387e21e9

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #8944 

[Screencast from 2024-12-08 00-43-19.webm](https://github.com/user-attachments/assets/b6e15fcc-46a1-4ab0-aacf-86056248bb69)

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx [hunk 1]
```diff
@@ -52,9 +52,9 @@ const StyledContainer = styled.div`
 `;
 
 const StyledContainerWithPadding = styled.div`
-  height: calc(100% - 40px);
+  height: calc(100% - ${({ theme }) => theme.spacing(10)});
   margin-left: ${({ theme }) => theme.spacing(2)};
-  width: 100%;
+  width: calc(100% - ${({ theme }) => theme.spacing(2)});
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx:57]: Could we use `box-sizing: border-box` instead of calculating width?

**Review by ehconitin — COMMENTED** [review]
LGTM! Left a comment!

File: packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx (hunk 1 above)
Comment (harshrajeevsingh) [reply packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx:57]: I tried! It didn't work ;(

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainer.tsx:57]: @ehconitin could you try taking over this change?

File: packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ import 'overlayscrollbars/overlayscrollbars.css';
 
 const StyledScrollWrapper = styled.div<{ scrollHide?: boolean }>`
   display: flex;
-  height: fit-content;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx:20]: This change introduced in #9062 broke the scroll on the recordboard, reverted!

**Review by ehconitin — APPROVED** [review]
LGTM! 
@harshrajeevsingh Great work, Thanks! 
box-sizing: border-box; does work instead of calculating width :)
I am not sure why it didn't work on your side, could you please re-verify if the reason of it not working is linux specific?

**Comment by harshrajeevsingh** [comment]
> LGTM! @harshrajeevsingh Great work, Thanks! box-sizing: border-box; does work instead of calculating width :) I am not sure why it didn't work on your side, could you please re-verify if the reason of it not working is linux specific?

It's working not because of `box-sizing: border-box;` but because you removed the `width` property from that container. So, even if you remove the `box-sizing: border-box;`  from this code, it will still work :)
