### PR TITLE
fix(recaptcha|sso): recaptcha not generated issue

### LINKED ISSUE #9759: Invalid captcha error
When redirected to the right domain with an existing account, I'm getting a non-blocking captcha error

https://github.com/user-attachments/assets/c12692de-2bde-4590-b6ba-f1f1496df7eb

### PR DESCRIPTION
**Pull request by AMoreaux**
Fix https://github.com/twentyhq/twenty/issues/9759 https://github.com/twentyhq/twenty/issues/9694 https://github.com/twentyhq/twenty/issues/9323

### CODE REVIEW

File: packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx [hunk 1]
```diff
@@ -25,13 +25,18 @@ import { useCleanRecoilState } from '~/hooks/useCleanRecoilState';
 import { useIsMatchingLocation } from '~/hooks/useIsMatchingLocation';
 import { usePageChangeEffectNavigateLocation } from '~/hooks/usePageChangeEffectNavigateLocation';
 import { isDefined } from '~/utils/isDefined';
+import { isCheckUserExistsQueryReadyState } from '@/auth/states/isCheckUserQueryReadyState';
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/app/effect-components/PageChangeEffect.tsx:28]: isAuthCheckUserExistsQueryReadyState

File: packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx [hunk 2]
```diff
@@ -49,6 +50,9 @@ export const SignInUpGlobalScopeForm = () => {
   const setSignInUpStep = useSetRecoilState(signInUpStepState);
   const [signInUpMode, setSignInUpMode] = useRecoilState(signInUpModeState);
 
+  const isCheckUserExistsQueryReady = useRecoilValue(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/sign-in-up/components/SignInUpGlobalScopeForm.tsx:53]: if you keep it isAuthFormInitialLoading

**Review by charlesBochet — APPROVED** [review]
