### PR TITLE
fix: workflow node classification

### LINKED ISSUE #13391: Workflow Node Classification
## Current Problem
- Some nodes have color while others don't  
- There is no existing rule that classifies them

Image
Image

## Solution: Classify Node Types with Color and Labels
Figma link: https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=45225-477892&t=trIv3IjMXHFvO7vI-1

- Adding colors and new categories to better classify and identify different node types 
- Trigger Colors: Data (palette blue), Other (palette purple)
- Action Colors: Data (text/tertiary), AI (palette pink), Flow (tag green), Core (palette red), Human Input (palette orange)

Image
Image

## Workflow on Canvas
- Node color stays constant during workflow run time and node selection
Image
Image

### PR DESCRIPTION
**Pull request by Harshith-2208**
closes #13391 
As the solution said to classify workflow nodes based on colors I have updated them with the following colors and new categories to better classify and identify different node types as told:

  - Trigger Colors: Data (palette blue), Other (palette purple)
  - Action Colors: Data (text/tertiary), AI (palette pink), Flow (tag green), Human Input (palette orange)
 
image

image

image

image

### CODE REVIEW

**Comment by charlesBochet** [comment]
@thomtrp could you take a look?

File: packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx [hunk 1]
```diff
@@ -83,30 +85,26 @@ export const CommandMenuWorkflowSelectActionContent = ({
     );
   };
 
+  const theme = useTheme();
+
   return (
     <RightDrawerStepListContainer>
       <RightDrawerWorkflowSelectStepTitle>
-        Records
+        Data
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx]: use lingui to translate strings

File: packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx [hunk 2]
```diff
@@ -83,30 +85,26 @@ export const CommandMenuWorkflowSelectActionContent = ({
...
+      </RightDrawerWorkflowSelectStepTitle>
+        {ActionMenuItems(RECORD_ACTIONS, theme, handleCreateStep)}
+      <RightDrawerWorkflowSelectStepTitle>
+        AI
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/command-menu/pages/workflow/action/components/CommandMenuWorkflowSelectActionContent.tsx]: AI should appear only when there are actions available

File: packages/twenty-front/src/modules/command-menu/utils/ActionMenuItems.tsx [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import { useIcons } from 'twenty-ui/display';
+import { getActionIconColorOrThrow } from '@/workflow/workflow-steps/workflow-actions/utils/getActionIconColorOrThrow';
+import { type WorkflowActionType } from '@/workflow/types/Workflow';
+import { MenuItemCommand } from 'twenty-ui/navigation';
+
+type Action = { type: WorkflowActionType; label: string; icon: string };
+
+export const ActionMenuItems = (
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/command-menu/utils/ActionMenuItems.tsx]: Rename `WorkflowActionMenuItems`

Comment (thomtrp) [reply packages/twenty-front/src/modules/command-menu/utils/ActionMenuItems.tsx]: This component should be in `packages/twenty-front/src/modules/command-menu/pages/workflow/action/components`

File: packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/useFilteredAIActions.ts [hunk 4]
```diff
@@ -1,11 +1,11 @@
 import { useIsFeatureEnabled } from '@/workspace/hooks/useIsFeatureEnabled';
 import { FeatureFlagKey } from '~/generated/graphql';
-import { OTHER_ACTIONS } from '../constants/OtherActions';
+import { AI_ACTIONS } from '../constants/AIActions';
 
-export const useFilteredOtherActions = () => {
+export const useFilteredAIActions = () => {
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/hooks/useFilteredAIActions.ts]: this component does not make sense anymore. Just check `isAiEnabled` before displaying the AI section. And directly use `AI_ACTIONS`

File: packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerCronForm.tsx [hunk 5]
```diff
@@ -75,7 +75,7 @@ export const WorkflowEditTriggerCronForm = ({
           });
         }}
         Icon={getIcon(headerIcon)}
-        iconColor={theme.font.color.tertiary}
+        iconColor={theme.color.purple}
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerCronForm.tsx]: it should use `getTriggerIconColor`

Comment (thomtrp) [reply packages/twenty-front/src/modules/workflow/workflow-trigger/components/WorkflowEditTriggerCronForm.tsx]: same for all triggers

File: packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeIcon.tsx [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+const StyledStepNodeLabelIconContainer = styled.div`
+  align-items: center;
+  background: ${({ theme }) => theme.background.transparent.light};
+  border-radius: ${({ theme }) => theme.spacing(1)};
+  display: flex;
+  justify-content: center;
+  padding: ${({ theme }) => theme.spacing(1)};
+`;
+
+export const WorkflowDiagramStepNodeIcon = ({
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/workflow/workflow-diagram/components/WorkflowDiagramStepNodeIcon.tsx]: We already have a `WorkflowDiagramStepNodeIcon`. See `packages/twenty-front/src/modules/workflow/workflow-diagram/workflow-nodes/components/WorkflowDiagramStepNodeIcon.tsx`. I think it has been added recently

**Review by thomtrp — COMMENTED** [review]
Sounds promising, thank you for your contribution!

I still see a few nodes in the wrong color though. It may come from changes that happen after you opened the PR (see form, send email)

Capture d’écran 2025-08-19 à 13 59 06

**Comment by Harshith-2208** [comment]
I'll resolve the above conversations and get back
Thank you

**Comment by Harshith-2208** [comment]
@thomtrp  Done with resolving conversations. You can go ahead.
Thank you .

**Comment by charlesBochet** [comment]
Thanks @Harshith-2208! Looks like the CI is read (front / typechecks)

**Review by thomtrp — APPROVED** [review]
Great job @Harshith-2208 🔥 💪 

Trying to fix the CI then I'll merge
