### PR TITLE
Fix issue 2126: DataTable '+' button dropdown positioning glitch

### LINKED ISSUE #2126: DataTable '+' button dropdown positioning glitch
## Bug Description

On Table pages (ex: /companies), the "+" button dropdown is badly positionned.
image

## Expected behavior

It should be floating below the "+" button and aligned right on the "+" button.

## Technical inputs

Refactor the plus button to use DropdownMenu (specifying clickable component and dropdown component). A good example is `SettingsObjectDisabledMenuDropDown` component.

### PR DESCRIPTION
**Pull request by ttlpta**
Fixes https://github.com/twentyhq/twenty/issues/2126
image

### CODE REVIEW

File: front/src/modules/ui/data/data-table/components/DataTableHeaderPlusButtonContent.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import { MenuItem } from '@/ui/navigation/menu-item/components/MenuItem';
+import { useRecoilScopedValue } from '@/ui/utilities/recoil-scope/hooks/useRecoilScopedValue';
+
+import { useTableColumns } from '../hooks/useTableColumns';
+import { TableRecoilScopeContext } from '../states/recoil-scope-contexts/TableRecoilScopeContext';
+import { hiddenTableColumnsScopedSelector } from '../states/selectors/hiddenTableColumnsScopedSelector';
+import { ColumnDefinition } from '../types/ColumnDefinition';
+
+export const DataTableHeaderPlusButtonContent = () => {
+  const { closeDropdown } = useDropdown();
```
Comment (charlesBochet) [inline front/src/modules/ui/data/data-table/components/DataTableHeaderPlusButtonContent.tsx:16]: as DataTableHeaderPlusButtonContent.tsx is called within DropdownScope, useDropdown is able to retrieve the right dropdown scope id by itself

**Review by charlesBochet — APPROVED** [review]
