### PR TITLE
Navigation drawer refactor

### LINKED ISSUE #11195: Regression: Navbar advanced mode dots disappeared
# Current behavior

Image

# Desired Behavior

Image

### LINKED ISSUE #11199: Setting navbar right spacing
# Desired behavior

Image

related to https://github.com/twentyhq/twenty/issues/11195

### PR DESCRIPTION
**Pull request by ehconitin**
closes #11195
closes #11199

### Context

The yellow dots in the Settings Navigation Drawer (used to indicate advanced settings) were being hidden due to ScrollWrapper's overflow handling. This required both a fix for the visibility issue and an improvement to the component structure.

### Changes
1. Keep scrolling logic of the MainNavigationDrawer and SettingsNavigationDrawer in one place, and conditionally apply `<StyledScrollableInnerContainer>` when isSettingsDrawer is true.

2. Fixed Yellow Dots Visibility
Added specific padding in NavigationDrawerScrollableContent to accommodate yellow dots:
```
  padding-left: ${theme.spacing(5)}; // Space for yellow dots
  padding-right: ${theme.spacing(8)}; // Space for no-padding scroll
  ```
  
  This ensures the yellow dots are visible while maintaining proper scroll behavior

3. Improved Component Composition
Using proper component composition instead of passing components as props
Components are now composed in a more React-idiomatic way:
```
  <NavigationDrawer>
    <NavigationDrawerScrollableContent>
      <SettingsNavigationDrawerItems />
    </NavigationDrawerScrollableContent>
    <NavigationDrawerFixedContent>
      <AdvancedSettingsToggle />
    </NavigationDrawerFixedContent>
  </NavigationDrawer>
  ```

### CODE REVIEW

File: packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx [hunk 1]
```diff
@@ -31,31 +31,40 @@ export const AppNavigationDrawer = ({
...
   return (
     <NavigationDrawer
       className={className}
-      title={drawerProps.title}
-      footer={drawerProps.footer}
-    >
-      {drawerProps.children}
-    </NavigationDrawer>
+      title={drawerBaseProps.title}
+      fixedTopItems={drawerBaseProps.fixedTopItems}
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx:65]: I'm not a fan of this pattern where we pass components as props.

Instead, why not compose components
SettingsNavigationDrawer:
<NavigationDrawer>
<SettingsFixedNavigationDrawerItems />
<SettingsCrollableNavigationDrawerItems />
</NavigationDrawer>

MainNavigationDrawer
<NavigationDrawer>
<MainFixedNavigationDrawerItems />
<MaiScrollableNavigationDrawerItems />
</NavigationDrawer>

Comment (charlesBochet) [reply packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx:65]: Looking at the code it looks not that bad, what motivates this refactoring?

I'm not against introducing SettingsNavigationDrawer and MainNavigationDrawer (right now we only have MainNavigationDrawerItems and SettingsNavigationDrawerItems) though but let's keep a "compose" them instead of passing Components as props

Comment (ehconitin) [reply packages/twenty-front/src/modules/navigation/components/AppNavigationDrawer.tsx]: The motivation was just to keep the scrolling behavior of both settings and the main navigation drawer in one place, as we would need conditional paddings for both, one thing led to another and now it's a refactor -- I have updated the PR description for more context :)

**Comment by ehconitin** [comment]
@greptileai review

**Review by charlesBochet — APPROVED** [review]
Thanks for re-working it! It's much better :)

I feel we could have avoid using "isSettings" in NavigationDrawerScrollContent (and FixedContent) and duplicated them as they are too different but it's a nitpick
