### PR TITLE
Fix: When opening a filter, the focus is not put on the input search / filter input

### LINKED ISSUE #1718: When opening a filter, the focus is not put on the input search / filter input
## Bug Description

When opening a filter input like this one for address : 

image

We have to click on the input which slows down the process of creating a filter.

## Expected behavior

We should have an autofocus on every search / input component in filters.

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
Fixes #1718

https://www.loom.com/share/fdfd78dd9c9044f5b33e35900dc07a79?sid=d45317c6-e3cf-4aa4-9242-a2e19d29c049

### CODE REVIEW

File: front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx [hunk 1]
```diff
@@ -38,6 +38,12 @@ export const DropdownMenuSearchInput = forwardRef<
   InputHTMLAttributes<HTMLInputElement>
 >((props, ref) => (
   <StyledDropdownMenuSearchInputContainer>
-    <StyledInput autoComplete="off" placeholder="Search" {...props} ref={ref} />
+    <StyledInput
+      autoFocus
```
Comment (thaisguigon) [inline front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx:42]: Hello @AyushAgrawal-A2, thank you for contributing!

So the reason why `autoFocus` is not set to `true` by default in this component is that we could imagine a case where several inputs are needed in one Dropdown.

Could you set the `autoFocus` prop on this component where it is called in the "filter" components, instead of here? (`FilterDropdownEntitySearchInput`, `FilterDropdownNumberSearchInput`, `FilterDropdownTextSearchInput`)

Thank you 🙏

**Review by thaisguigon — CHANGES_REQUESTED** [review]

File: front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx (hunk 1 above)
Comment (AyushAgrawal-A2) [reply front/src/modules/ui/dropdown/components/DropdownMenuSearchInput.tsx]: @thaisguigon done

**Review by thaisguigon — APPROVED** [review]
