### PR TITLE
Fixing Singup sequence FLASHING💥

### LINKED ISSUE #660: Improve Signup loading sequence
# Current behavior

## Overview

https://github.com/user-attachments/assets/bd6dd8c9-ff66-4fe7-82c9-73dcb24bcfaf

### 1
`https://app.twenty.com/welcome`
Image

### 2
`https://app.twenty.com/welcome`
Image
Missing workspace name

### 3
Image

### 4
Image

### 5
Image

### 6
Image

### 7
Image

# Desired Behavior

### 1
`https://app.twenty.com/welcome`
Detect whether the user has an account or not
Image

### 2
Add a loading on the Continue button until page `3` is loaded
Image

### 3
Image

### PR DESCRIPTION
**Pull request by guillim**
After investiagting the different options ([see related issue](https://github.com/twentyhq/core-team-issues/issues/660#issuecomment-2766030972)) I decided to add a "Verify Component" and a to build a custom Layout for this route. 

Reason I cannot use the default one is to have all preloaded once the user changes website and lands on the verify route.

Reason I did not modify the DefaultLayout to match our need is that is would require many changes in order to avoid preloading states for our specific usecase.

Fixes https://github.com/twentyhq/core-team-issues/issues/660

### CODE REVIEW

**Comment by AMoreaux** [comment]
You should do the same thing for VerifyEmailEffect component

File: packages/twenty-front/src/pages/auth/SignInUpLoading.tsx [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+  return (
+    <StandardContent
+      workspacePublicData={workspacePublicData}
+      signInUpForm={
+        <>
+          <StyledContentContainer>
+            <StyledForm>
+              <MainButton
+                disabled={true}
+                title={'Continue'}
```
Comment (prastoin) [inline packages/twenty-front/src/pages/auth/SignInUpLoading.tsx:82]: ***Nitpick:*** Unless I'm mistaken should be translated

File: packages/twenty-front/src/pages/auth/SignInUpLoading.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+  const { workspaceInviteHash, workspace: workspaceFromInviteHash } =
+    useWorkspaceFromInviteHash();
+
+  const title = useMemo(() => {
+    if (isDefined(workspaceInviteHash)) {
+      return `Join ${workspaceFromInviteHash?.displayName ?? ''} team`;
+    }
+    const workspaceName = !isDefined(workspacePublicData?.displayName)
+      ? DEFAULT_WORKSPACE_NAME
+      : workspacePublicData?.displayName === ''
```
Comment (prastoin) [inline packages/twenty-front/src/pages/auth/SignInUpLoading.tsx:61]: ***Nitpick:*** Could use IsNonEmptyString

File: packages/twenty-front/src/pages/auth/SignInUpLoading.tsx (hunk 1 above)
Comment (guillim) [reply packages/twenty-front/src/pages/auth/SignInUpLoading.tsx:82]: correct

**Review by prastoin — COMMENTED** [review]
Atm we're challenging the custom layout

File: packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx [hunk 3]
```diff
@@ -84,6 +84,10 @@ const StyledLinkGroup = styled.div`
   }
 `;
 
+const StyledChooseYourPlanPlaceholder = styled.div`
+  height: 566px;
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/onboarding/ChooseYourPlan.tsx:88]: see with Thomas if we want to have a fix width on Modals (if it's driven by content, this will not handle well loading states)

File: packages/twenty-server/src/engine/core-modules/email/email.module.ts [hunk 4]
```diff
@@ -16,7 +18,9 @@ export class EmailModule {
       useFactory: (...args: any[]) => {
         const config = options.useFactory(...args);
 
-        return config ? new SmtpDriver(config) : new LoggerDriver();
+        return config && isObject(config) && Object.keys(config).length !== 0
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/email/email.module.ts:21]: revert!

**Review by charlesBochet — APPROVED** [review]
LGTM!
