### PR TITLE
Field widget fix dropdowns

### LINKED ISSUE #2023: [Record Page Layouts] Nested dropdowns aren't supported in Field widget
https://github.com/user-attachments/assets/6f20f1f8-cfdb-405c-b5dd-3a8edc1a7faa

### PR DESCRIPTION
**Pull request by Devessier**
## Before

https://github.com/user-attachments/assets/a78f6561-a519-455e-a838-c4e138fb336f

## After

https://github.com/user-attachments/assets/ec704406-b16b-491a-8a88-8aa6fe25254b

Closes https://github.com/twentyhq/core-team-issues/issues/2023

### CODE REVIEW

File: packages/twenty-front/src/modules/page-layout/widgets/field/hooks/useIsFieldWidgetEditing.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+  instanceId,
+}: {
+  instanceId: string;
+}) => {
+  const focusStack = useRecoilValue(focusStackState);
+
+  // The focusId pushed to the stack starts with instanceId.
+  // For nested dropdowns (e.g., Links field sub-dropdowns), the focusId
+  // will have additional suffixes, so we use startsWith to catch all of them.
+  const isEditing = focusStack.some((item) =>
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/page-layout/widgets/field/hooks/useIsFieldWidgetEditing.ts]: Not a fan of this, the instance id is in the focus stack component normally

**Review by bosiraphael — APPROVED** [review]
LGTM
