### PR TITLE
wip: api playground fixes

### LINKED ISSUE #10926: API Playground follow-ups
### Glitch on opening

https://github.com/user-attachments/assets/f119e2c6-0272-4956-9e72-1d63b40e10b5

### Breadcrumb padding left is 8px instead of 12px

Image

### Add a 12px padding to match the look & feel of other pages

+ Border-color: Medium
+ Border-radius: 8px

Image

### PR DESCRIPTION
**Pull request by Nabhag8848**
# ISSUE 
- closes #10926 

- [x] fix paddings
- [x] fix page change to playground animation
- [x] fixes multiple skeletons issues

---

- Also was showing multiple skeletons on reloading, **before**: 

https://github.com/user-attachments/assets/0cdef639-c121-4cbb-b056-b89e60862c54

### CODE REVIEW

**Comment by ehconitin** [comment]
taking over

File: packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx [hunk 1]
```diff
@@ -23,6 +24,12 @@ const StyledContainer = styled.div`
 `;
 
 export const UserOrMetadataLoader = () => {
+  const isShowFullscreen = useShowFullscreen();
+
+  if (isShowFullscreen) {
+    return <></>;
+  }
+
```
Comment (ehconitin) [inline packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx]: Hi @Nabhag8848 👋🏻! I noticed this change and wasn't quite sure about the reason behind it, so I removed it for now. Was it added to address a laggy transition? If it's necessary, please let me know—I’d really appreciate a bit of context!

Comment (Nabhag8848) [reply packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx]: there is attached video in PR comment for same. 

> multiple skeletons when refreshing on playground screen. 

but i believe addition of it had made the experience worst due to lazy load of components.

Comment (ehconitin) [reply packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx]: oh now I see! Thanks! makes sense

Comment (ehconitin) [reply packages/twenty-front/src/loading/components/UserOrMetadataLoader.tsx]: @Bonapara we would need the correct skeletons for full screens but it could be a separate issue.

File: packages/twenty-front/src/modules/settings/playground/components/RestPlayground.tsx [hunk 2]
```diff
@@ -64,7 +78,7 @@ export const RestPlayground = ({ onError, schema }: RestPlaygroundProps) => {
               },
             },
             baseServerURL: REACT_APP_SERVER_BASE_URL + '/' + schema,
-            forceDarkModeState: theme.name === 'dark' ? 'dark' : 'light',
+            theme: 'none',
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/settings/playground/components/RestPlayground.tsx:81]: Are you sure of this change? Why remove forceDarkModeState?

File: packages/twenty-front/src/modules/ui/layout/page/components/PageHeader.tsx [hunk 3]
```diff
@@ -27,7 +28,8 @@ const StyledTopBarContainer = styled.div`
   justify-content: space-between;
   min-height: ${PAGE_BAR_MIN_HEIGHT}px;
   padding: ${({ theme }) => theme.spacing(2)};
-  padding-left: 0;
+  padding-left: ${({ isShowFullscreen, theme }) =>
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/ui/layout/page/components/PageHeader.tsx:31]: It feels a bit ugly to have this special condition in header, ideally the header should remain the same everything. Can't we have this in the parent component?

File: packages/twenty-front/src/modules/settings/playground/components/RestPlayground.tsx (hunk 2 above)
Comment (ehconitin) [reply packages/twenty-front/src/modules/settings/playground/components/RestPlayground.tsx]: I assumed it would ignore the vars, but that wasn't the case.

**Review by FelixMalfait — APPROVED** [review]
