### PR TITLE
Fix Boolean field for hotkey

### LINKED ISSUE #1841: We should be able to toggle boolean TableCell with enter hotkey.
## Scope & Context

In a TableCell component, we can have a `BooleanFieldInput` shown on field of type boolean.

## Current behavior

Currently we can only toggle its state by clicking on it.

## Expected behavior

We want to be able to toggle it with "enter" hotkey when the soft focus is on a TableCell which contains a BooleanFieldInput.

## Technical inputs

Please implement the useScopedHotkey hook in `BooleanInput` look for an example in other Input components.

### PR DESCRIPTION
**Pull request by tomalexing**
Fix https://github.com/twentyhq/twenty/issues/1841
First off all, useScopedHotkeys hook is very insidious. Because listener is registered with enabled option with true or false depends on what cell we are hovering first (isFieldInputOnly or not). So if it was boolean it would be false and not working for all others, and otherwise if it was false it would fire even for boolean field.
```
TableCellSoftFocusMode.tsx

useScopedHotkeys(
    'enter',
    () => {
      openTableCell();
    },
    TableHotkeyScope.TableSoftFocus,
    [openTableCell],
    {
      enabled: !isFieldInputOnly,
    },
  );
```

So we use it as 

```
  const { ref: fieldRef } = useContext(FieldContext);
  (skipped)
  useScopedHotkeys(
    'enter',
    () => {
      if (!isFieldInputOnly) {
        openTableCell();
      } else {
        // Maybe check for probability field
        fieldRef?.current?.click();
      }
    },
    TableHotkeyScope.TableSoftFocus,
    [openTableCell],
  );
```
I decided to add ref (fieldRef in example ) to FieldContext. Its convinient for many reasons, clicking for ex. Because I should call persistField(newValue) to correct save new value , and new value is internalValue(useState) from BooleanInput. 
For other fields ref could be attached to dom too.

https://github.com/twentyhq/twenty/assets/9631913/e045361c-809d-49e0-8dfd-b55448104687

### CODE REVIEW

**Comment by charlesBochet** [comment]
@lucasbordeau could you have a look tomorrow morning? :)

File: front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx [hunk 1]
```diff
@@ -27,34 +30,37 @@ export const TableCellSoftFocusMode = ({
   useScopedHotkeys(
     'enter',
     () => {
-      openTableCell();
+      if (!isFieldInputOnly) {
+        openTableCell();
+      } else {
+        // Maybe check for probability field
+        fieldRef?.current?.click();
```
Comment (lucasbordeau) [inline front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx:37]: I think we shouldn't rely on automating user inputs here, instead we should stay focused on the minimal scope of our ticket : handling boolean fields only. 

So I see no problem creating custom logic for boolean type only where it's needed.

Preferably we would want to put this into an abstracted hook like useToggleEditOnlyInput and do the switch (or if else) statement in this hook with our isBoolean typeguard.

Comment (lucasbordeau) [reply front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx:37]: Also we should avoid relying on refs here because there are many layers, and although it's a complex part of the app that must be managed with care, we shouldn't rely on shortcuts but instead take the time to understand the different layers to chose the right one to place or new logic.

Comment (lucasbordeau) [reply front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx:37]: useToggleEditOnlyInput would also allow us to handle other types like probability you mentionned.

Comment (tomalexing) [reply front/src/modules/ui/data/data-table/table-cell/components/TableCellSoftFocusMode.tsx]: Thank you for your review. I've implemented useToggleEditOnlyInput hook. But I have to say the previous one was not a shortcut but rather a way of imperative change the intrinsic state of component. I know there are not much in logic of reversing state but it's about the component only knows how to update itself.

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
Nice implementation.
