### PR TITLE
Fix dragging behavior below the last card when dragging below the new CTA button

### LINKED ISSUE #10197: [0.42] Reordering a Kanban below `new` CTA result in noop
## Bug Description

In 0.42
After drag and dropping a Kanban element below `new` call to action results in a no-operation

https://github.com/user-attachments/assets/a07050c3-e441-4767-aa8d-3cd40579b85d

## Expected behavior

Not sure about what to expect ! What do you think @Bonapara ?
Should it still gets updated to the highest position ?

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
- Fixed an issue where dragging an item below the last card didn't work when the card was dragged below the new CTA button (`destination.index === items.length` case).
- Moved the "new record" button outside of the draggable list

### Demo
https://github.com/user-attachments/assets/370f2c1f-4bb2-403b-b8ed-4afda064c98d

Closes #10197

### CODE REVIEW

**Review by prastoin — COMMENTED** [review]
Hey @abdulrahmancodes thanks for your contributions, I think that's pretty good ! It fits the expected behavior and resolves previous suggested implementation caveats !

Made few updates:
- Restore styling in order to stick to previous container's heigh and attributes
- Centralized before and after recordIds retrieval in a dedicated util ( now "gracefully" handles 0 index )

As I've modified the PR I won't approve. @lucasbordeau could you please give it a review ?

File: packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+type getBeforeAndAfterIndexRecordIds = {
+  draggedRecordIndex: number;
+  otherRecordIds: string[];
+};
+type getBeforeAndAfterIndexRecordIdsReturnType = {
+  recordBeforeId?: string;
+  recordAfterId?: string;
+};
+export const getBeforeAndAfterIndexRecordIds = ({
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts:9]: I would improve the naming with more context, because out of context it's difficult to understand.

**Review by lucasbordeau — APPROVED** [review]
I would improve the naming of the util and the variables to include more context about what it does, otherwise LGTM.

File: packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts (hunk 1 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts:9]: Thanks for the review @lucasbordeau 
In my opinion we could also make this function very low level and record agnostic such as, `getIndexBeforeAndAfterElementsInArray` or `getIndexNeighboursElementsInArray`

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts:9]: Sure why not

Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/record-board/utils/getBeforeAndAfterIndexRecordIds.ts]: Done
