### PR TITLE
3272 add a page to create and edit webhook

### LINKED ISSUE #3272: Add a page to create and edit webhook
Followup of #3271 

Edit
Edit

We already have the backend completed for webhooks.
We need to be able to create a new webhook.
Note: set `operations` column on webhooks table to be equal to `*.*` that will mean every event should be sent to that URL (in later iterations we will let users customize this)

### LINKED ISSUE #3854: Error when deleting an api key
## Bug Description

image

## Expected behavior

No error and redirection to /settings

### PR DESCRIPTION
**Pull request by martmull**
close #3272 
- add create and edit pages
- remove soon pills
- update page paths at the top left (make it coherent between Apis and Webhooks)

https://github.com/twentyhq/twenty/assets/29927851/d91f7281-da07-42a8-b7f1-307796d0035a

### CODE REVIEW

File: packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    targetUrl: string;
+    operation: string;
+  }>({
+    targetUrl: '',
+    operation: '*.*',
+  });
+  const { createOneRecord: createOneWebhook } = useCreateOneRecord<Webhook>({
+    objectNameSingular: CoreObjectNameSingular.Webhook,
+  });
+  const onSave = async () => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/pages/settings/developers/webhooks/SettingsDevelopersWebhooksNew.tsx:29]: handleSave

**Review by lucasbordeau — APPROVED** [review]
