### PR TITLE
Fix dev mode

### LINKED ISSUE #1922: [Extensibility] [v1] Fix watch mode exit on error
as title, should not exit

### PR DESCRIPTION
**Pull request by martmull**
Fixes infinite loop in dev mode

Solution -> We stop generating in dev mode

### CODE REVIEW

File: packages/twenty-apps/hello-world/src/actions/create-new-post-card.ts [hunk 1]
```diff
@@ -21,6 +22,9 @@ export const main = async (params: { recipient?: string }) => {
         id: true,
       },
     });
+
+    console.log('createPostCard result', createPostCard);
```
Comment (prastoin) [inline packages/twenty-apps/hello-world/src/actions/create-new-post-card.ts:26]: ***Polish:*** could be removed ?

File: packages/twenty-sdk/package.json
Comment (prastoin) [inline packages/twenty-sdk/package.json:70]: ***Polish:*** could be removed

**Review by prastoin — APPROVED** [review]
Looks good !

File: packages/twenty-sdk/package.json
Comment (martmull) [reply packages/twenty-sdk/package.json:70]: it is generated automatically

File: packages/twenty-apps/hello-world/src/actions/create-new-post-card.ts (hunk 1 above)
Comment (martmull) [reply packages/twenty-apps/hello-world/src/actions/create-new-post-card.ts:26]: I have added that so it provides an example for the `twenty app logs` command

**Comment by prastoin** [comment]
By calling the sync application service directly you're bypassing the sdk generation ?
