### PR TITLE
Fix aggregate bar

### LINKED ISSUE #10943: Aggregate bar gets over column header bar on view groups view
https://github.com/user-attachments/assets/fada0b83-2998-407f-9734-af9087e3ef1b

### PR DESCRIPTION
**Pull request by charlesBochet**
Closes https://github.com/twentyhq/twenty/issues/10943

Also adds stories:
image

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx [hunk 1]
```diff
@@ -26,21 +26,21 @@ const StyledTableHead = styled.thead`
...
-      z-index: 5;
+      z-index: 6;
       transition: 0.3s ease;
     }
 
     th:nth-of-type(2) {
       position: sticky;
       left: 11px;
-      z-index: 5;
+      z-index: 6;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeader.tsx:36]: 5 is the aggregate bar, sticky header should be 6

File: packages/twenty-ui/src/layout/animated-placeholder/components/AnimatedPlaceholder.tsx [hunk 2]
```diff
@@ -12,6 +12,7 @@ const StyledContainer = styled.div`
   align-items: center;
   justify-content: center;
   position: relative;
+  min-height: 100px;
```
Comment (charlesBochet) [inline packages/twenty-ui/src/layout/animated-placeholder/components/AnimatedPlaceholder.tsx:15]: unrelated glitch where the empty table placeholder is flashing

**Review by Weiko — APPROVED** [review]
