### PR TITLE
Fix: Adjust chevron alignment to the right edge

### LINKED ISSUE #7403: Webhooks chevron is not on the right edge enough
# Current behavior

The webhook list chevron right in `Settings > Developers` are too much on the left

2eb1abd382a3eaff2249a150ca9ffc3b9a1ea297903a21055bd04fea1b12f3aa

# Desired Behavior

They should be only 4px to the right edge of the table

708578e737a4621d06bbaa6ffc3e2eaa35115252b51ce06c159c360c9a1c1ada

### PR DESCRIPTION
**Pull request by Vardhaman619**
This pull request addresses the alignment issue of the chevron icon, ensuring that it is positioned correctly on the right edge.
Fixes [#7403](https://github.com/twentyhq/twenty/issues/7403)

after fix

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { TableCell } from '@/ui/layout/table/components/TableCell';
 import { TableRow } from '@/ui/layout/table/components/TableRow';
 
 export const StyledApisFieldTableRow = styled(TableRow)`
-  grid-template-columns: 312px 132px 68px;
+  grid-template-columns: 312px auto 24px;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/settings/developers/components/SettingsApiKeysFieldItemTableRow.tsx:10]: lets make it 28px since there is a padding on right of 4px
```suggestion
  grid-template-columns: 312px auto 28px;
```

File: packages/twenty-front/src/modules/settings/developers/components/SettingsDevelopersWebhookTableRow.tsx [hunk 2]
```diff
@@ -8,7 +7,7 @@ import { TableCell } from '@/ui/layout/table/components/TableCell';
 import { TableRow } from '@/ui/layout/table/components/TableRow';
 
 export const StyledApisFieldTableRow = styled(TableRow)`
-  grid-template-columns: 444px 68px;
+  grid-template-columns: 1fr 24px;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/settings/developers/components/SettingsDevelopersWebhookTableRow.tsx:10]:
```suggestion
  grid-template-columns: 1fr 28px;
```

**Review by ehconitin — COMMENTED** [review]
left some comments :) Thanks

**Review by ehconitin — APPROVED** [review]
LGTM! 
Thankyou @Vardhaman619 ;)

**Review by martmull — APPROVED** [review]
LGTM thanks
