### PR TITLE
Fix race condition on stripe subscription

### LINKED ISSUE #191: Race condition Stripe signup
Handle when stripe webhook is not called before stripe checkout redirection
- don't redirect on payment success page
- request workspace.status on create/workspace page

### PR DESCRIPTION
**Pull request by martmull**
Fixes https://github.com/twentyhq/core-team-issues/issues/191
- remove automatic redirection on payment success page when subscription status is undefined
- add an effect component to refresh the subscription status on payment success page

Observation: Locally, I had to delay the stripe webhook subscription created endpoint by 7s to see race condition issue

https://github.com/user-attachments/assets/463e1816-34fd-4c4f-b590-3994a3a3e91a

### CODE REVIEW

File: packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts [hunk 1]
```diff
@@ -18,6 +18,10 @@ export const usePageChangeEffectNavigateLocation = () => {
     isMatchingLocation(AppPath.Invite) ||
     isMatchingLocation(AppPath.ResetPassword);
 
+  const isMatchingOpenSignedInRoute = isMatchingLocation(
```
Comment (charlesBochet) [inline packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts:21]: not sure to understand this: why isMatchingOpenSignedInRoute and matching PlanRequired?

Also, @etiennejou is refactoring this to display the trial choice screen now so this will conflict

I think @etiennejou should include your change in its own PR

File: packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+        const refreshedSubscriptionStatus =
+          currentUser?.currentWorkspace?.currentBillingSubscription?.status;
+        if (
+          isDefined(refreshedSubscriptionStatus) &&
+          isDefined(currentUser?.currentWorkspace)
+        ) {
+          setCurrentUser(currentUser);
+          break;
+        }
+        await sleep(1_000);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx:32]: typo?

File: packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+  const setCurrentUser = useSetRecoilState(currentUserState);
+
+  useEffect(() => {
+    const getSubscriptionStatus = async () => {
+      let refreshAttempts = 0;
+      while (refreshAttempts < 5 && !isDefined(subscriptionStatus)) {
+        const result = await getCurrentUser({ fetchPolicy: 'network-only' });
+        const currentUser = result.data?.currentUser;
+        const refreshedSubscriptionStatus =
+          currentUser?.currentWorkspace?.currentBillingSubscription?.status;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx:24]: this looks to be the subscriptionStatus from useSubscriptionStatus already

**Review by charlesBochet — COMMENTED** [review]
Left comments! I think we can merge the change on PaymentSuccess and on RefreshSubStatusEffect.

Questioning the change in usePageChangeEffect: I don't get how it works + will be overridden by @etiennejouan change

File: packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx (hunk 2 above)
Comment (martmull) [reply packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx:32]: no, 1_000 is understand like 1000 but is improve code readability
1000000 can be written 1_000_000
image

File: packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts [hunk 4]
```diff
@@ -29,13 +33,16 @@ export const usePageChangeEffectNavigateLocation = () => {
...
-    isMatchingLocation(AppPath.PlanRequired) ||
-    isMatchingLocation(AppPath.PlanRequiredSuccess);
+    isMatchingLocation(AppPath.PlanRequired);
 
   if (isMatchingOpenRoute) {
     return;
   }
 
+  if (isLoggedIn && isMatchingOpenSignedInRoute) {
+    return;
```
[the remark this answers is not in the document]
Comment (FelixMalfait) [reply packages/twenty-front/src/hooks/usePageChangeEffectNavigateLocation.ts:43]: Yes maybe adding !isMatchinLocation(AppPath.PlanRequiredSuccess) on line 53 would be simpler instead of introducing this new concept of OpenSignedRoute (open meaning no subscription required in this context I guess but I don't think that would be clear to the reader, and in that case why not include PlanRequired/SettingsPath.Billing in it)

File: packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx (hunk 2 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/billing/components/RefreshSubscriptionStatusEffect.tsx:32]: no way! what is this dark magic!

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx [hunk 5]
```diff
@@ -36,16 +40,32 @@ const StyledButtonContainer = styled.div`
...
+  const [getCurrentUser] = useGetCurrentUserLazyQuery();
+  const setCurrentUser = useSetRecoilState(currentUserState);
   const color =
     theme.name === 'light' ? theme.grayScale.gray90 : theme.grayScale.gray10;
 
+  const checkSubscriptionStatus = async () => {
+    if (!isDefined(subscriptionStatus)) {
+      const result = await getCurrentUser({ fetchPolicy: 'network-only' });
+      const currentUser = result.data?.currentUser;
+      if (isDefined(currentUser)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:53]: let's make a deep equal here (make it a useRecoilCallback and check the currentUser in the snapshot, this will avoid unnecessary re-renders)

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx [hunk 6]
```diff
@@ -36,16 +40,32 @@ const StyledButtonContainer = styled.div`
...
+        setCurrentUser(currentUser);
+      }
+    }
+  };
+
+  const onClick = async () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:59]: does not look useful

if it was, we would name it handleButtonClick
onClick is the event and callbacks are always named in infinitive form

**Review by charlesBochet — APPROVED** [review]
Left a final comment :) LGTM on the rest, much better indeed!

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx [hunk 7]
```diff
@@ -34,11 +41,38 @@ const StyledButtonContainer = styled.div`
...
+    const refreshedSubscriptionStatus =
+      currentUser?.currentWorkspace?.currentBillingSubscription?.status;
+
+    if (isDefined(currentUser) && isDefined(refreshedSubscriptionStatus)) {
+      setCurrentUser(currentUser);
+      navigate(AppPath.CreateWorkspace);
+      return;
+    }
+
+    throw new Error(
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:69]: shouldn't we use a Snackbar here?

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx [hunk 8]
```diff
@@ -34,11 +41,38 @@ const StyledButtonContainer = styled.div`
...
+  const onboardingStatus = useOnboardingStatus();
+  const [getCurrentUser] = useGetCurrentUserLazyQuery();
+  const setCurrentUser = useSetRecoilState(currentUserState);
   const color =
     theme.name === 'light' ? theme.grayScale.gray90 : theme.grayScale.gray10;
 
-  if (currentUser?.onboardingStatus === OnboardingStatus.Completed) {
+  const navigateWithSubscriptionCheck = async () => {
+    if (isDefined(subscriptionStatus)) {
+      navigate(AppPath.CreateWorkspace);
```
Comment (charlesBochet) [inline packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:54]: I don't get this, won't it always redirect here?

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx (hunk 7 above)
Comment (martmull) [reply packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:69]: yes, but we also want the error to be send to sentry, so I throw an error (in add snackBar and send error to sentry)

File: packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx (hunk 8 above)
Comment (martmull) [reply packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:54]: no, if we receive the stripe subscription create event after the stripe checkout redirection, subscriptionStatus will be undefined.
In that case, we refresh subscriptionStatus, redirect if not undefined, and throw error if undefined

Comment (charlesBochet) [reply packages/twenty-front/src/pages/onboarding/PaymentSuccess.tsx:54]: ok!

**Review by charlesBochet — APPROVED** [review]
