### PR TITLE
2727-fix(front): CommandMenu and KeyboardMenu invoke handled

### LINKED ISSUE #2727: Invoking Command Menu should close Keyboard Menu
## Bug Description

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

**Example:** 
```
When Command Menu is invoked, if keyboard menu is open it should close and vice-a-versa.
Currently they are getting overlayed.
```

## Expected behavior

A clear and concise description of what the expected behavior is.

**Example:** 
```
Only one dialog should be visible at a time.
```

## Technical inputs

**Example:** 
```
Requires change in toggle handler.
```

### PR DESCRIPTION
**Pull request by Kanav-Arora**
Closes #2727

### CODE REVIEW

File: front/src/modules/command-menu/components/CommandMenu.tsx [hunk 1]
```diff
@@ -89,14 +91,20 @@ export const CommandMenu = () => {
   const isCommandMenuOpened = useRecoilValue(isCommandMenuOpenedState);
   const [search, setSearch] = useState('');
   const commandMenuCommands = useRecoilValue(commandMenuCommandsState);
-
+  const { closeKeyboardShortcutMenu } = useKeyboardShortcutMenu();
+  const isKeyboardShortcutMenuOpened = useRecoilValue(
```
Comment (charlesBochet) [inline front/src/modules/command-menu/components/CommandMenu.tsx:95]: @Kanav-Arora We don't want to use the states directly outside of its component. This allow us to provide a nice API for our components. 

This is also to optimize for re-renders. Here it's not too bad but, every time isKeyboardShortcutMenuOpened changed, the whole CommandMenu will re-render. That's why, while designing Keyboard shortcut menu API (aka useKeyboardShortcutMenu), we really need to ask ourselve what we want to expose in order to not push our component users to not trigger re-renders.

In this particular case, I think we don't ant to listen at this  isKeyboardShortcutMenuOpenedState at all, we want to close the keyboardShortCutMenu in any case, worst case nothing happens

File: front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx [hunk 2]
```diff
@@ -20,9 +22,14 @@ export const KeyboardShortcutMenu = () => {
   const isKeyboardShortcutMenuOpened = useRecoilValue(
     isKeyboardShortcutMenuOpenedState,
   );
+  const isCommandMenuOpened = useRecoilValue(isCommandMenuOpenedState);
```
Comment (charlesBochet) [inline front/src/modules/keyboard-shortcut-menu/components/KeyboardShortcutMenu.tsx:25]: same here!

**Review by charlesBochet — COMMENTED** [review]
Thank you @Kanav-Arora :)

**Review by charlesBochet — APPROVED** [review]
@Kanav-Arora I'm merging it with changes (see comments) because we are planning to move many files over the week-end, it would be too bad that your PR would have many conflicts.
I'm also including an unrelated fix that I found while working on your PR

Thank you!
