### PR TITLE
Fix message opening

### LINKED ISSUE #3686: Fix message opening
## Scope & Context

We should be able to click on the whole message to expand it but only on the header to collapse it.

### PR DESCRIPTION
**Pull request by bosiraphael**
Closes #3686

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx [hunk 1]
```diff
@@ -20,6 +22,12 @@ const StyledThreadMessageHeader = styled.div`
   flex-direction: column;
   justify-content: space-between;
   margin-bottom: ${({ theme }) => theme.spacing(2)};
+  padding: ${({ theme }) => theme.spacing(0, 6)};
+`;
+
+const StyledThreadMessageBody = styled.div`
+  /* padding: ${({ theme }) => theme.spacing(4, 6)}; */
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx:29]: remove comment

File: packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx [hunk 2]
```diff
@@ -11,7 +11,9 @@ const StyledThreadMessage = styled.div`
   border-bottom: 1px solid ${({ theme }) => theme.border.color.light};
   display: flex;
   flex-direction: column;
-  padding: ${({ theme }) => theme.spacing(4, 6)};
+
+  padding-top: ${({ theme }) => theme.spacing(4)};
+  padding-bottom: ${({ theme }) => theme.spacing(4)};
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx:16]: `padding: ${({ theme }) => theme.spacing(4, 0)};`

**Review by thomtrp — APPROVED** [review]
Approved with changes
