### PR TITLE
Fix on view filters

### LINKED ISSUE #14058: Inconsistent sorting
We had a bug report from a user, that when they edit a field in this view, then the view occasionally re-sorts itself in a completely different order.

Image

I suspect we don't always add an "order by position" at the end and we should do this or something similar to guarantee stability. 

(Setting the bug as high because it's coming from a top client)

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes https://github.com/twentyhq/twenty/issues/14058

### CODE REVIEW

File: packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ export const usePersistViewFilterRecords = () => {
             variables: {
               id: viewFilter.id,
               input: {
-                value: parseJson(viewFilter.value),
+                value: viewFilter.value,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts:89]: this was a regression, viewFilter.value is a JSON in the backend and a string in the FE. We should align both on BE behavior

File: packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-order/graphql-query-order.parser.ts [hunk 2]
```diff
@@ -65,6 +69,19 @@ export class GraphqlQueryOrderFieldParser {
...
   }
 
+  private getOptionalOrderByCasting(
+    fieldMetadata: Pick<FieldMetadataEntity, 'type'>,
+  ): string {
+    if (
+      fieldMetadata.type === FieldMetadataType.SELECT ||
+      fieldMetadata.type === FieldMetadataType.MULTI_SELECT
+    ) {
+      return '::text';
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-parsers/graphql-query-order/graphql-query-order.parser.ts:79]: otherwise it sorts based on the order in the enum!
