### PR TITLE
Fix-inline-height

### LINKED ISSUE #11442: Fix inline field height
# Current behavior

Image

# Desired Behavior

**All inline fields in all states should always have a 24px height**

### PR DESCRIPTION
**Pull request by guillim**
Follow up from inline height #11553 related to PR #11442

we had some issues with hover styles

Fixes https://github.com/twentyhq/twenty/issues/11442#issuecomment-2805893663

### CODE REVIEW

**Comment by etiennejouan** [comment]
triggered @greptileai

File: packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/AddressFieldDisplay.tsx [hunk 1]
```diff
@@ -2,6 +2,13 @@ import { isNonEmptyString } from '@sniptt/guards';
 
 import { useAddressFieldDisplay } from '@/object-record/record-field/meta-types/hooks/useAddressFieldDisplay';
 import { TextDisplay } from '@/ui/field/display/components/TextDisplay';
+import styled from '@emotion/styled';
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/AddressFieldDisplay.tsx:5]: use linaria

File: packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/BooleanFieldDisplay.tsx [hunk 2]
```diff
@@ -1,8 +1,18 @@
...
+  display: flex;
+  height: 20px;
+`;
 export const BooleanFieldDisplay = () => {
   const { fieldValue } = useBooleanFieldDisplay();
 
-  return <BooleanDisplay value={fieldValue} />;
+  return (
+    <StyledBooleanDisplay>
+      <BooleanDisplay value={fieldValue} />
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/BooleanFieldDisplay.tsx:15]: same here

**Review by charlesBochet — APPROVED** [review]

**Review by etiennejouan — APPROVED** [review]
