### PR TITLE
[BUG] Refactor actor composite type

### LINKED ISSUE #10200: [PROD] Creating a record in a new Object Model has empty `CreatedBy`
## Bug Description

After just creating a new object model, creating a new record in its table result in having empty `createdBy` field value

https://github.com/user-attachments/assets/f5dea7cc-ee3d-48d9-9fc3-c8218a75eb5e

## Expected behavior

It should fill `createdBy` using `currentWorkspaceMember`

### PR DESCRIPTION
**Pull request by mdrazak2001**
fixes #10200 

The FieldActor Zod schema was updated to correctly handle null context.

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts [hunk 1]
```diff
@@ -9,9 +9,11 @@ const actorSchema = z.object({
   workspaceMemberId: z.optional(z.string().nullable()),
   name: z.string(),
   context: z.optional(
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts:11]: ***Remark:*** Unless I'm mistaken this is not `optional` anymore, as now `nullable`

**Review by prastoin — COMMENTED** [review]
Nice catch !
Still needs to dig deeper a little bit more in order to stamp this, as we need to be sure we do not store empty objects as null db side and so on. Can't remember consensus on this

File: packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts (hunk 1 above)
Comment (mdrazak2001) [reply packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts:11]: @prastoin: Thanks! Yes, I think I can clarify a few things about the `context` handling:


1. Current state has a default Value:
```typescript
// In database:
// Some records have:
context: null
// Others have:
context: {}

2. For newly created objects with the ACTOR type, the context field currently comes as null/undefined. However, existing objects have a context: {}.

Because of this inconsistency, the newly created objects did not match the Zod schema. Therefore, I made the context field nullable to accommodate cases where this field might be undefined from the database.

Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/record-field/types/guards/isFieldActorValue.ts:11]: Also I don't like the idea that we maintain two source of truth regarding theses models. IMO we should be inferring typing from zod schema

File: packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts [hunk 2]
```diff
@@ -288,14 +287,17 @@ type FieldActorSource =
...
+  source: z.string(),
+  workspaceMemberId: z.string().nullable(),
+  name: z.string(),
+  context: z
+    .object({
+      provider: z.nativeEnum(ConnectedAccountProvider).optional(),
+    })
+    .nullable(),
+});
+export type FieldActorValue = z.infer<typeof actorSchema>;
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-field/types/FieldMetadata.ts:300]: @lucasbordeau what do you think of such a gymnastic ? 
I feel like we have several duplicated type declaration between `type` and zod `schemas`, we could factorize them in order to avoid desyncrhonization

**Comment by prastoin** [comment]
We need this to be merged in next production patch
In this way we will handle standardization afterwards
Implemented a permissive validation schema ftm

**Review by Weiko — COMMENTED** [review]
Note: As discussed, let's do the change in the backend instead, to make sure it does not return null context 🙂

**Comment by prastoin** [comment]
Lets make things clean !

**Comment by prastoin** [comment]
# Introduction
In the end we decided to go full in and handle this both from the root cause which was located server side

## Actor composite type mutation:
From:
```ts
export type ActorMetadata = {
  source: FieldActorSource;
  workspaceMemberId?: string;
  name: string;
  context?: {
    provider?: ConnectedAccountProvider;
  };
};
```
To:
```ts
export type ActorMetadata = {
  source: FieldActorSource;
  workspaceMemberId: string | null;
  name: string;
  context: {
    provider?: ConnectedAccountProvider;
  };
};
```
Context is not optional anymore, but is defaulted in the pre-hook-created-by resolvers. In this way such as a defaulted parameters in TypeScript it by definition optional.

In this way in database we will now be storing as context only `{}` or `{ "someKey": "someValue" }` no more NULL

## Migration command
We have some legacy on existing workspaces that might have introduced NULL value as context, created a command to pass on all of them in order to set them to `{}` if`NULL`

File: packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    }
+    case isDefined(user): {
+      logger.warn("User doesn't have a workspace member id in the token");
+      const workspaceMemberRepository =
+        await twentyORMGlobalManager.getRepositoryForWorkspace<WorkspaceMemberWorkspaceEntity>(
+          workspace.id,
+          'workspaceMember',
+        );
+
+      const workspaceMember = await workspaceMemberRepository.findOneOrFail({
```
Comment (prastoin) [inline packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts:43]: ***Remark:*** Decided to consume `orFail` here instead of checking afterwards, might have an impact on the previously returned error signature

File: packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    }
+    case isDefined(apiKey): {
+      return buildCreatedByFromApiKey({
+        apiKey,
+      });
+    }
+    default: {
+      // TODO handle gracefully
+      // Not managed from now
+      throw new Error('TODO');
```
Comment (prastoin) [inline packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts:62]: ***Remark:*** To be discussed

File: packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-standardization-of-actor-composite-context-type.ts [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+    this.logger.log(`Running add-context-to-actor-composite-type command`);
+
+    if (options?.dryRun) {
+      this.logger.log(chalk.yellow('Dry run mode: No changes will be applied'));
+    }
+
+    for (const workspaceId of workspaceIds) {
+      try {
+        await this.execute(workspaceId, options?.dryRun);
+        this.logger.verbose(`Added for workspace: ${workspaceId}`);
```
Comment (charlesBochet) [inline packages/twenty-server/src/database/commands/upgrade-version/0-42/0-42-standardization-of-actor-composite-context-type.ts:55]: let's add a counter to know where we are compared to the totalCount of worksapce too

File: packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+  logger: Logger;
+};
+export const buildCreatedByFromAuthContext = async ({
+  authContext,
+  twentyORMGlobalManager,
+  logger,
+}: BuildCreatedByFromAuthContextArgs): Promise<ActorMetadata> => {
+  const { workspace, workspaceMemberId, user, apiKey } = authContext;
+
+  switch (true) {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts:24]: new pattern, why not but we usually use early if return

File: packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts (hunk 3 above)
Comment (charlesBochet) [reply packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts:43]: const [workspaceMember] = await workspaceMemberRepository.find()

if (!workspaceMember) {
throw CustomException // likely ActorException
}

**Review by charlesBochet — COMMENTED** [review]
Add unit test on the util that should be migrated to service

File: packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts (hunk 6 above)
Comment (prastoin) [reply packages/twenty-server/src/engine/core-modules/actor/utils/build-created-by-from-auth-context.util.ts:24]: Indeed no real + value here

File: packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-many.pre-query-hook.ts [hunk 7]
```diff
@@ -72,46 +65,11 @@ export class CreatedByCreateManyPreQueryHook
...
-      };
-    }
-
-    if (authContext.apiKey) {
-      createdBy = {
-        source: FieldActorSource.API,
-        name: authContext.apiKey.name,
-      };
-    }
+    const createdBy = await buildCreatedByFromAuthContext({
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-many.pre-query-hook.ts:68]: Definitely !

File: packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-one.pre-query-hook.ts [hunk 8]
```diff
@@ -72,46 +61,8 @@ export class CreatedByCreateOnePreQueryHook
       return payload;
```
Comment (prastoin) [inline packages/twenty-server/src/engine/core-modules/actor/query-hooks/created-by.create-one.pre-query-hook.ts:61]: ***Remark:*** Could have factorized this behavior too, but nitpick as it seems to be TMP

**Comment by prastoin** [comment]
@greptileai trigger

**Review by charlesBochet — APPROVED** [review]
