### PR TITLE
Remove selected record id on related relation record detach

### LINKED ISSUE #12544: Selecting relation in show page is not working
Steps to reproduce : 
- Go to a person show page
- Select a company
- Select another company

The selected company should be the previously selected company instead of the selected company

https://github.com/user-attachments/assets/6ec78ff4-49ad-4609-8089-5fe9357fa435

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
Verified for multi select record picker and it's already working
Also works for both single and multi after record deletion
Fixes https://github.com/twentyhq/twenty/issues/12544

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordFieldCardRelationPickerDropdownId.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import { FieldContext } from '@/object-record/record-field/contexts/FieldContext';
+import { useContext } from 'react';
+
+export const useRecordFieldCardRelationPickerDropdownId = () => {
+  const { fieldDefinition, recordId } = useContext(FieldContext);
+
+  return `record-field-card-relation-picker-${fieldDefinition.fieldMetadataId}-${recordId}`;
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordFieldCardRelationPickerDropdownId.ts]: I would rather create a util with fieldMetadataId and recordId as arguments which returns `record-field-card-relation-picker-${fieldDefinition.fieldMetadataId}-${recordId}` than creating a whole new hook

**Review by bosiraphael — APPROVED** [review]
LGTM, left a small nitpick
