### PR TITLE
remove activity fallback record in RelationFromManyFieldDisplay

### LINKED ISSUE #12218: Invalid input syntax for type uuid: "fallback-id"
[sentry](https://twenty-v7.sentry.io/issues/6563624590/events/caa2d25052544612aed7abfa6e934410/?environment=prod&environment=prod-eu&project=4507072499810304&query=is%3Aunresolved%20%21issue.type%3A%5Bperformance_consecutive_db_queries%2Cperformance_consecutive_http%2Cperformance_file_io_main_thread%2Cperformance_db_main_thread%2Cperformance_n_plus_one_db_queries%2Cperformance_n_plus_one_api_calls%2Cperformance_p95_endpoint_regression%2Cperformance_slow_db_query%2Cperformance_render_blocking_asset_span%2Cperformance_uncompressed_assets%2Cperformance_http_overhead%2Cperformance_large_http_payload%5D%20timesSeen%3A%3E10&referrer=next-event&sort=date&stream_index=0)

This will removed from sentry back issues, but is a real issue (we are forging a fallback-id on our FE).

### PR DESCRIPTION
**Pull request by etiennejouan**
EDITED ⬇️ 

Context
When fixing relation fields preview in this [PR](https://github.com/twentyhq/twenty/pull/11745/files#diff-10073c6310707810d002bceef587936ed5d31dba2ea5babbb4d452a7f1e756b5R31-R35), I've (try to) fixed NoteTarget (and TaskTarget) field preview adding [fallback record](https://github.com/twentyhq/twenty/pull/11745/files#diff-da3ccb70824f1792351457dbee66dd75e48e45ff8e6e0f768f402e35256377bcR54-R61).

It introduces the sentry error (findOneNote/Task with 'fallback-id') : when activity is soft deleted, associated activityTarget is not. In TableView, when displaying Note/Task field in view for a record with a soft deleted ntoe/task, 'fallback-id' record chip is clickable.

Solution - seen with Charles - Remove fallback-id record + Hide NoteTarget and TaskTarget field preview - awaiting ManyToMany relation are updated in few weeks

Screenshot 2025-05-23 at 11 07 06

Test - RelationFromManyFieldDisplay in Table view & Settings field preview

closes https://github.com/twentyhq/twenty/issues/12218

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
LGTM

File: packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export const RelationFromManyFieldDisplay = () => {
         return {
           ...record,
           [relationFieldName]: {
-            id: 'fallback-id',
+            id: 'a7b2c3d4-e5f6-4789-a123-456789abcdef', // fake fallback uuid
```
Comment (Weiko) [inline packages/twenty-front/src/modules/object-record/record-field/meta-types/display/components/RelationFromManyFieldDisplay.tsx:59]: fake uuid usually start with `20202020-` in our codebase if you prefer! @etiennejouan

**Review by ijreilly — COMMENTED** [review]
I think we should not do the call instead

**Review by charlesBochet — CHANGES_REQUESTED** [review]
Discussed with Etienne, let's remove this hacky part and prevent preview on Settings for many to many relations as long as they are not impelmented in the BE properly

**Review by charlesBochet — APPROVED** [review]
