### PR TITLE
fix: standardize GraphQL schema UUID field types

### LINKED ISSUE #1264: Replace String IDs with UUIDs in GraphQL Schema
### Problem
GraphQL schema inconsistently uses `Scalars['String']` for ID fields instead of `Scalars['UUID']`.

### Current State
- Some entities correctly use `Scalars['UUID']` (Agent, User, Workspace, etc.)
- Many entities incorrectly use `Scalars['String']` (AdminPanelHealthServiceData, Role, SsoConnection, etc.)

### Solution
1. Audit all GraphQL schema ID fields
2. Replace `Scalars['String']` with `Scalars['UUID']` where appropriate
3. Update backend resolvers and frontend types
4. Add UUID validation at GraphQL layer

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
Closes [#1264](https://github.com/twentyhq/core-team-issues/issues/1264)

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Great! I know it's ongoing, looks like more are missing:

Screenshot 2025-08-01 at 13 23 48

**Comment by FelixMalfait** [comment]
It looks like this got corrupted? I often see you rebasing PRs. Not need to rebase main, you can just merge it directly. We don't care if the commit history isn't clean because we squash PRs into a single commit

File: packages/twenty-front/src/generated-metadata/graphql.ts [hunk 1]
```diff
@@ -3332,7 +3332,7 @@ export type SignUpInWorkspaceMutationVariables = Exact<{
   workspaceInviteHash?: InputMaybe<Scalars['String']>;
   workspacePersonalInviteToken?: InputMaybe<Scalars['String']>;
   captchaToken?: InputMaybe<Scalars['String']>;
-  workspaceId: Scalars['UUID'];
+  workspaceId?: InputMaybe<Scalars['UUID']>;
```
Comment (FelixMalfait) [inline packages/twenty-front/src/generated-metadata/graphql.ts:3466]: Let's stick to our single goal of this PR otherwise we might introduce breaking changes we don't notice

**Review by FelixMalfait — APPROVED** [review]

File: packages/twenty-server/src/engine/core-modules/workflow/dtos/delete-workflow-version-step-input.dto.ts [hunk 2]
```diff
@@ -1,14 +1,16 @@
...
 export class DeleteWorkflowVersionStepInput {
-  @Field(() => String, {
+  @Field(() => UUIDScalarType, {
     description: 'Workflow version ID',
     nullable: false,
   })
   workflowVersionId: string;
 
-  @Field(() => String, {
+  @Field(() => UUIDScalarType, {
```
Comment (thomtrp) [inline packages/twenty-server/src/engine/core-modules/workflow/dtos/delete-workflow-version-step-input.dto.ts:13]: step id can be 'trigger', so this change breaks the call

File: packages/twenty-server/src/engine/core-modules/workflow/dtos/create-workflow-version-step-input.dto.ts [hunk 3]
```diff
@@ -16,13 +17,13 @@ export class CreateWorkflowVersionStepInput {
   })
   stepType: WorkflowActionType;
 
-  @Field(() => String, {
+  @Field(() => UUIDScalarType, {
```
Comment (thomtrp) [inline packages/twenty-server/src/engine/core-modules/workflow/dtos/create-workflow-version-step-input.dto.ts:20]: same here @FelixMalfait @abdulrahmancodes

File: packages/twenty-server/src/engine/core-modules/workflow/dtos/delete-workflow-version-step-input.dto.ts (hunk 2 above)
Comment (abdulrahmancodes) [reply packages/twenty-server/src/engine/core-modules/workflow/dtos/delete-workflow-version-step-input.dto.ts:13]: Ah! Let me revert this
