### PR TITLE
[REFACTOR][BUG] Dynamically compute field to write in cache CREATE

### LINKED ISSUE #9927: Fix optimistic cache on records import
## Bug Description
After importing records on `Object Model` that has `composite field` the optimistic cache update will be aborted because some expected Apollo expected field are missing.

It does not have an impact on the final operation for the back. Also the UI seems to be working fine because we mutate the cache on response. But we do not get optimistic cache plus value in that flow.

https://github.com/user-attachments/assets/85659f16-5c72-4614-aa33-9dc8ec04a260

## Expected behavior
We should provide a value for each expected fields.

## Technical inputs
That might highly be due to the `prefillRecord` method replacing instead of merging with override `input` on `defaultValues`.
We might have to check metadata to determine if current value could be an`Iterable` or not in order to spread and merge `defaultValues` and `Input`
To dig deeper

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
While importing records encountering missing expected fields when writting a fragment from apollo cache

### 1/ `createdBy` Default value
When inserting in cache in create single or many we will now make optimistic behavior on the createdBy value

### 2/ `createRecordInCache` dynamically create `recordGrqlFields`
When creating an entry in cache, we will now dynamically generate fields to be written in the fragment instead of expecting all of them. As by nature record could be partial

### 3/ Strictly typed `RecordGqlFields`

# Conclusion
closes #9927

### CODE REVIEW

**Comment by prastoin** [comment]
@greptileai trigger

File: packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerTitleRecordInlineCell.tsx [hunk 1]
```diff
@@ -26,7 +26,9 @@ export const RightDrawerTitleRecordInlineCell = () => {
   const draftValue = useRecoilValue(getDraftValueSelector());
 
   useListenRightDrawerClose(() => {
-    persistField(draftValue);
+    if (draftValue !== undefined) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-right-drawer/components/RightDrawerTitleRecordInlineCell.tsx:29]: ***Todo:*** Double check if necessary, might be out of scope

File: packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts [hunk 2]
```diff
@@ -4,14 +4,22 @@ import { generateEmptyFieldValue } from '@/object-record/utils/generateEmptyFiel
 import { v4 } from 'uuid';
 import { stripSimpleQuotesFromString } from '~/utils/string/stripSimpleQuotesFromString';
 
-export const generateDefaultFieldValue = (
-  fieldMetadataItem: Pick<FieldMetadataItem, 'defaultValue' | 'type'>,
-) => {
+type GenerateEmptyFieldValueArgs = {
+  fieldMetadataItem: Pick<FieldMetadataItem, 'defaultValue' | 'type'>;
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts:8]: ***To discuss:*** Inconsistency in typing, called `generateEmptyFieldValue` expects `Pick<FieldMetadataItem, 'type' | 'relationDefinition'>` where `relationDefinition` is optional as only associated to `relationField`.

As it will never be provided the `generateEmptyFieldValue` relation use case condition based on it will never occur, always returning null instead of []

This might be problematic

File: packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts [hunk 3]
```diff
@@ -22,4 +30,5 @@ export const generateDefaultFieldValue = (
     default:
       return defaultValue;
   }
+  ///
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts:33]: rm

File: packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts [hunk 4]
```diff
@@ -5,11 +5,14 @@ import { getSettingsFieldTypeConfig } from '@/settings/data-model/utils/getSetti
 import { isFieldTypeSupportedInSettings } from '@/settings/data-model/utils/isFieldTypeSupportedInSettings';
 import { isDefined } from 'twenty-shared';
 
+type getFieldPreviewValueArgs = {
+  fieldMetadataItem: Pick<FieldMetadataItem, 'type' | 'defaultValue'>;
+  workspaceMemberId: string | undefined;
+};
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/settings/data-model/fields/preview/utils/getFieldPreviewValue.ts:11]: It is

File: packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationGqlRecordFields.ts [hunk 5]
```diff
@@ -1,3 +1,3 @@
-import { RecordGqlFields } from '@/object-record/graphql/types/RecordGqlFields';
+import { RecordGqlFieldsDeprecated } from '@/object-record/graphql/types/RecordGqlFieldsDeprecated';
 
-export type RecordGqlOperationGqlRecordFields = RecordGqlFields;
+export type RecordGqlOperationGqlRecordFields = RecordGqlFieldsDeprecated;
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlOperationGqlRecordFields.ts:3]: In fact it's contrary

File: packages/twenty-front/src/modules/object-record/graphql/utils/isRecordGraphlFieldsNode.ts [hunk 6]
```diff
@@ -0,0 +1,7 @@
+import { RecordGqlFields } from '@/object-record/graphql/types/RecordGqlFields';
+import { isDefined } from 'twenty-shared';
+
+export const isRecordGqlFieldsNode = (
+  recordGql: RecordGqlFields | boolean | undefined,
+): recordGql is RecordGqlFields =>
+  isDefined(recordGql) && typeof recordGql !== 'boolean';
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/graphql/utils/isRecordGraphlFieldsNode.ts:7]: I can hear that

File: packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts [hunk 7]
```diff
@@ -82,7 +86,14 @@ export const useCreateManyRecords = <
...
           objectMetadataItems,
-          recordInput: recordToCreate,
+          currentWorkspaceMember: currentWorkspaceMember,
+          recordInput: {
+            createdBy: {
+              source: 'MANUAL',
+              context: {},
+            },
+            ...recordToCreate,
+          },
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/hooks/useCreateManyRecords.ts]: that's expected

File: packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts [hunk 8]
```diff
@@ -77,9 +81,17 @@ export const useCreateOneRecord = <
...
       cache: apolloClient.cache,
+      currentWorkspaceMember: currentWorkspaceMember,
       objectMetadataItem,
       objectMetadataItems,
-      recordInput: { ...recordInput, id: idForCreation },
+      recordInput: {
+        createdBy: {
+          source: 'MANUAL',
+          context: {},
+        },
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/hooks/useCreateOneRecord.ts]: It's default fallback, can get override from input

File: packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts [hunk 9]
```diff
@@ -56,16 +56,17 @@ export const useOpenObjectRecordsSpreadsheetImportDialog = (
...
+              fields: availableFieldMetadataItems,
+            });
 
           return fieldMapping;
         });
 
         try {
-          await createManyRecords(createInputs, true);
+          const upsert = true;
+          await createManyRecords(createInputs, upsert);
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog.ts:69]: It's configurable

File: packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts [hunk 10]
```diff
@@ -23,11 +23,12 @@ export const usePrefetchedData = <T extends ObjectRecord>(
     objectNameSingular,
   });
 
+  const recordGqlFields =
+    operationSignatureFactory({ objectMetadataItem }).fields ?? filter;
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts:27]: We should create a ticket

File: packages/twenty-front/src/testing/mock-data/workspace-members.ts [hunk 11]
```diff
@@ -26,3 +33,26 @@ export const mockWorkspaceMembers = [
...
+    ({
+      id,
+      locale,
+      name,
+      avatarUrl,
+      colorScheme,
+      dateFormat,
+      timeFormat,
+      timeZone,
+    }) => ({
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/testing/mock-data/workspace-members.ts:48]: they're

File: packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts [hunk 12]
```diff
@@ -1 +1,3 @@
-export type RecordGqlFields = Record<string, any>;
+export type RecordGqlFields = {
+  [k: string]: boolean | RecordGqlFields | undefined;
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts:2]: Since undefined should not be here, might be good to add a TODO and create an issue.

File: packages/twenty-front/src/modules/object-metadata/utils/objectMetadataItemHasFieldCreatedBy.ts [hunk 13]
```diff
@@ -0,0 +1,10 @@
+import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
+import { FieldMetadataType } from 'twenty-shared';
+
+export const objectMetadataItemHasFieldCreatedBy = (
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-metadata/utils/objectMetadataItemHasFieldCreatedBy.ts:4]: check as a prefix to respect the function naming convention

File: packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts (hunk 12 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts:2]: As we discussed, we would like to have only `[key: string]: true | RecordGqlFields` to close the API and avoid having to handle undefined, key presence and false.

File: packages/twenty-front/src/modules/object-record/graphql/utils/isRecordGraphlFieldsNode.ts [hunk 14]
```diff
@@ -0,0 +1,10 @@
+import { RecordGqlFields } from '@/object-record/graphql/types/RecordGqlFields';
+import { isDefined } from 'twenty-shared';
+
+export const isRecordGqlFieldsNode = (
+  recordGql: RecordGqlFields | boolean | undefined,
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/graphql/utils/isRecordGraphlFieldsNode.ts:5]: We would change here too

File: packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts [hunk 15]
```diff
@@ -14,15 +17,43 @@ import { isDefined } from 'twenty-shared';
 import { RelationDefinitionType } from '~/generated-metadata/graphql';
 import { FieldMetadataType } from '~/generated/graphql';
 
+const buildDefaultActorFieldValue = (
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/utils/computeOptimisticRecordFromInput.ts:20]: One file per method, one file per type, etc.

File: packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts (hunk 2 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/utils/generateDefaultFieldValue.ts:8]: Create an issue

File: packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/prefetch/hooks/usePrefetchedData.ts:27]: See if we create a separate issue ?

**Review by prastoin — COMMENTED** [review]
Thanks for your review @lucasbordeau 
As discussed with Lucas, about to create three issues respectively for the following points:
- Refactor the `RecordGqlFields` type follow:
```ts
type RecordGqlFields = Record<string, RecordGqlFields | true>
```
In order to simplify `recordGqlFields` interactions and generation
- Refactor the `RecordGqlOperationGqlRecordFields` which is the last type to consumed the `RecordGqlFieldsDeprecated` type.
Especially within the `usePrefetchData.ts` file where
```ts

  const recordGqlFields =
    operationSignatureFactory({ objectMetadataItem }).fields ?? filter; // Is not RecordGqlFields
  const { records } = useFindManyRecords<T>({
    skip: !isDataPrefetched,
    objectNameSingular: objectNameSingular,
    recordGqlFields, // ts-error
  });
```
- Refactor the `mapObjectMetadataToGraphQLQuery` call to `mapFieldMetadataToGraphQLQuery` which expect `relationDefinition` from `fieldMetadataType` but never provided by the caller as not picked which might result in a never op
At least refactor typing to makes things clear, even the `type` seems to be unexpected here but seems to be provided at runtime 🤔 
Seeing
```ts
type MapFieldMetadataToGraphQLQueryArgs = {
  objectMetadataItems: ObjectMetadataItem[];
  field: Pick<FieldMetadataItem, 'name' | 'type' | 'relationDefinition'>;
  relationRecordGqlFields?: RecordGqlFields;
  computeReferences?: boolean;
};

type MapObjectMetadataToGraphQLQueryArgs = {
  objectMetadataItems: ObjectMetadataItem[];
  objectMetadataItem: Pick<ObjectMetadataItem, 'nameSingular' | 'fields'>;
  recordGqlFields?: RecordGqlFields;
  computeReferences?: boolean;
  isRootLevel?: boolean;
};
```

File: packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts (hunk 12 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/graphql/types/RecordGqlFields.ts:2]: Indeed would simplify DX !

**Review by lucasbordeau — APPROVED** [review]
