### PR TITLE
Fixed soft focus stuck

### LINKED ISSUE #5626: Soft focus hovering stuck randomly
## Bug Description

When hovering with the mouse on a record table, the soft focus is sometimes stuck.

## Expected behavior

It shouldn't be stuck and should always follow the mouse pointer.

## Technical inputs

It is certainly caused by the recent refactor with custom event and soft focus for optimizing cells.

### PR DESCRIPTION
**Pull request by lucasbordeau**
Soft focus could be stuck when exiting edit mode, in some cases it would prevent to have soft focus if just moving the mouse into a cell.

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useHandleContainerMouseEnter.ts [hunk 1]
```diff
@@ -28,16 +27,22 @@ export const useHandleContainerMouseEnter = ({
...
-        setIsHovered,
-        cellPosition,
-      }: HandleContainerMouseEnterArgs) => {
+      ({ cellPosition }: HandleContainerMouseEnterArgs) => {
         const currentTableCellInEditModePositionState = extractComponentState(
           currentTableCellInEditModePositionComponentState,
           tableScopeId,
         );
 
+        const isSoftFocusOnTableCellState = extractComponentFamilyState(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/hooks/internal/useHandleContainerMouseEnter.ts:36]: isSoftFocusOnTableCellFamilyState

**Review by charlesBochet — COMMENTED** [review]
Thanks, I have left a small comment :)

**Review by thomtrp — APPROVED** [review]

**Comment by FelixMalfait** [comment]
@lucasbordeau should we merge this? since it's been approved feel free to go ahead and merge it yourself
