### PR TITLE
fix: set `content-type` header for isMethodWithBody

### LINKED ISSUE #13781: Workflow HTTP POST body format wrong
## Bug Description

When creating an HTTP POST workflow the body variables are coming into n8n in the wrong format. I am able to get the correct format in an existing workflow that I created in Twenty v1.1 but the new workflow in v1.3.1 seems to be producing different results even though the node is setup the exact same. 

New HTTP Settings:
Image

New workflow result:
Image

v1.1 HTTP Settings:
Image

v1.1 workflow result:

Image

## Expected behavior

In order to use the data from the POST command it needs to be structured correctly for use in n8n. 

**Example:** 
I need the body to look like this:
```json
{
"id": "<GUID>"
}
```
What I am getting:
```json
{
\n"id":"<GUID>"\n
}:[empty]
```

### PR DESCRIPTION
**Pull request by neo773**
Fixes Workflow HTTP Request not setting `content-type` header for JSON body it was defaulting to `application/x-www-form-urlencoded` causing parsing issues

image

/closes #13781

### CODE REVIEW

File: packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/hooks/useHttpRequestForm.ts [hunk 1]
```diff
@@ -51,6 +51,16 @@ export const useHttpRequestForm = ({
       newFormData = { ...newFormData, body: undefined };
     }
 
+    if (field === 'method' && isMethodWithBody(value as string)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/workflow/workflow-steps/workflow-actions/http-request-action/hooks/useHttpRequestForm.ts:57]: typing issue, can we avoid it?
isNonEmptyString?

**Comment by thomtrp** [comment]
Tested the PR with a post request and it actually added the content-type: application/json header a second time, while it was already set.

**Comment by neo773** [comment]
@thomtrp 
That's pretty odd from my testing it did not append it and the default header was `application/x-www-form-urlencoded`

**Comment by FelixMalfait** [comment]
Let's maybe re-open this? @thomtrp it seems there was an issue reported so there must be something wrong though 🤔

**Comment by charlesBochet** [comment]
@thomtrp could you take another look?

**Review by thomtrp — APPROVED** [review]
@neo773 my bad, only the Test action was broken. I fixed it.
Thank you for your contribution 👌
