### PR TITLE
Fix relation field unknown target object

### LINKED ISSUE #12867: Create relation field with unknown target object metadata id results in `INTERNAL_SERVER_ERROR`
# Introduction

Related https://github.com/twentyhq/twenty/pull/12866

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes https://github.com/twentyhq/twenty/issues/12867

Issue:
when you have a variable `toto` which is: `Record<string, MyType>` and you do toto['xxx'], this will be typed as `MyType` instead of `MyType | undefined`

Solutions:
- activate `noUncheckedIndexedAccess` check in tsconfig, this is the preferred solution but will take time to get there (this raises 600+ errors)
- use a Map: cf https://github.com/twentyhq/twenty/pull/13125/files
- set the type to Partial<Record<string, MyType>>. Drawback is that when you do Object.values(toto), you'll get `Array<MyType | undefined>`. Hence why we have to filter these behind

image

### CODE REVIEW

File: packages/twenty-server/src/engine/core-modules/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts [hunk 1]
```diff
@@ -172,7 +172,7 @@ export const mockObjectMetadataItemsWithFieldMaps: ObjectMetadataItemWithFieldMa
       fieldIdByJoinColumnName: {},
     },
     {
-      id: '',
+      id: '20202020-540c-4397-b872-2a90ea2fb809',
```
Comment (prastoin) [inline packages/twenty-server/src/engine/core-modules/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts:175]: Interesting :)
This might have a huge impact on tests that would always fallback to the latest object metadata declaration as they were overrided on each Record<''> declaration

Might be the reason why tests fail rn

File: packages/twenty-server/src/engine/dataloaders/dataloader.service.ts [hunk 2]
```diff
@@ -114,8 +114,14 @@ export class DataloaderService {
             { workspaceId },
           );
 
-        const indexMetadataCollection = objectMetadataIds.map((id) =>
-          Object.values(objectMetadataMaps.byId[id].indexMetadatas).map(
+        const indexMetadataCollection = objectMetadataIds.map((id) => {
+          const objectMetadata = objectMetadataMaps.byId[id];
+
+          if (!isDefined(objectMetadata)) {
+            return [];
```
Comment (prastoin) [inline packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:121]: ***Question:*** Why not throwing an exception here ?

File: packages/twenty-server/src/engine/core-modules/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts (hunk 1 above)
Comment (charlesBochet) [reply packages/twenty-server/src/engine/core-modules/__mocks__/mockObjectMetadataItemsWithFieldMaps.ts:175]: yes, this looks too far from real data IMO so I've put a UUID

File: packages/twenty-server/src/engine/dataloaders/dataloader.service.ts (hunk 2 above)
Comment (charlesBochet) [reply packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:121]: we could, I was hesitant to change the current behavior which was swallowing

File: packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts [hunk 3]
```diff
@@ -75,7 +76,9 @@ export class WorkspaceResolverFactory {
       Mutation: {},
     };
 
-    for (const objectMetadata of Object.values(objectMetadataMaps.byId)) {
+    for (const objectMetadata of Object.values(objectMetadataMaps.byId).filter(
```
Comment (Weiko) [inline packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts:79]: that means we have explicitly set undefined/null values in our map? How can this happen?

File: packages/twenty-server/src/engine/dataloaders/dataloader.service.ts [hunk 4]
```diff
@@ -114,8 +114,14 @@ export class DataloaderService {
             { workspaceId },
           );
 
-        const indexMetadataCollection = objectMetadataIds.map((id) =>
-          Object.values(objectMetadataMaps.byId[id].indexMetadatas).map(
+        const indexMetadataCollection = objectMetadataIds.map((id) => {
```
Comment (prastoin) [inline packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:117]: ***Out of PR scope question:*** Nested array ? From my understanding this should return a one dim `IndexMetadataDTO[]`. Should we use `flatMap` here ?

We should type this map, I'm afraid `DataLoader` swallows a `TypeScript` error here

File: packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts [hunk 5]
```diff
@@ -75,7 +76,9 @@ export class WorkspaceResolverFactory {
...
+      isDefined,
```
Comment (Weiko) [inline packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory.ts:80]: Also can we extract the result in a collection above the loop? It seems a bit off to do a filter directly in the iterable expression

**Review by Weiko — COMMENTED** [review]
Left some comments, I don't fully understand why our storage contains undefined values. Could we fix this issue at the source instead of adding filters (and might forget about them) or maybe I'm missing something?

File: packages/twenty-server/src/engine/dataloaders/dataloader.service.ts (hunk 4 above)
Comment (charlesBochet) [reply packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:117]: In my understanding, that's not how the dataloader works, they expect you to return an array of array

Comment (prastoin) [reply packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:117]: Same for, I have to be wrong
```ts
    const fieldMetadataLoader = this.createFieldMetadataLoader();
    const indexMetadataLoader = this.createIndexMetadataLoader();
    const indexFieldMetadataLoader = this.createIndexFieldMetadataLoader();

```

Comment (prastoin) [reply packages/twenty-server/src/engine/dataloaders/dataloader.service.ts:117]: Ok indeed, RAS my bad

**Comment by prastoin** [comment]
> Left some comments, I don't fully understand why our storage contains undefined values. Could we fix this issue at the source instead of adding filters (and might forget about them) or maybe I'm missing something?

It does not really contains `undefined` value but might not contain the key we're trying to retrieve at runtime.
By definition when reading in `Record<string, unknown>` or `Array<unknown>[42]` this can result to optional runtime access ( returning undefined ) that's what https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess is used for.

**Review by Weiko — APPROVED** [review]
LGTM

**Comment by charlesBochet** [comment]
> > Left some comments, I don't fully understand why our storage contains undefined values. Could we fix this issue at the source instead of adding filters (and might forget about them) or maybe I'm missing something?
> 
> It does not really contains `undefined` value but might not contain the key we're trying to retrieve at runtime. By definition when reading in `Record<string, unknown>` or `Array<unknown>[42]` this can result to optional runtime access ( returning undefined ) that's what https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess is used for.

Discussed with @Weiko offline and he agrees

**Review by prastoin — APPROVED** [review]
Very cool !

**Comment by prastoin** [comment]
About to create and document a tech project that will aim to activate the https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess flag
