### PR TITLE
fix: Poor contrast on SlashMenu

### LINKED ISSUE #5304: Poor contrast on Notes & Tasks "block menu"
# Current behavior

The menu contrast is not great

CleanShot 2024-05-06 at 16 06 52

# Desired Behavior

It should look like other Menus.

```
Color: text-secondary
Background: transparent-secondary
backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%);
```

CleanShot 2024-05-06 at 16 12 28

### PR DESCRIPTION
**Pull request by its-id**
fixes [#5304](https://github.com/twentyhq/twenty/issues/5304#issue-2280984063)

dark mode
Screenshot 2024-05-09 at 1 59 56 AM

<br>
<br>
Light mode
Screenshot 2024-05-09 at 2 01 06 AM

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx [hunk 1]
```diff
@@ -10,10 +10,12 @@ const StyledDropdownMenu = styled.div<{
       ? 'none'
       : 'blur(12px) saturate(200%) contrast(50%) brightness(130%)'};
 
+  color: ${({ theme }) => theme.font.color.secondary};
+
   background: ${({ theme, disableBlur }) =>
     disableBlur
       ? theme.background.primary
-      : theme.background.transparent.secondary};
+      : theme.background.transparent.primary};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx:18]: the background looks correct according to the ticket (transparent.secondary)

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx [hunk 2]
```diff
@@ -10,10 +10,12 @@ const StyledDropdownMenu = styled.div<{
       ? 'none'
       : 'blur(12px) saturate(200%) contrast(50%) brightness(130%)'};
 
+  color: ${({ theme }) => theme.font.color.secondary};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx:13]: +1

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx (hunk 1 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx:18]: Why are we changing this?

**Review by charlesBochet — COMMENTED** [review]
Hi @its-id, thanks for your contribution, I have left comments :)

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx (hunk 1 above)
Comment (its-id) [reply packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenu.tsx:18]: > the background looks correct according to the ticket (transparent.secondary)

the current background is more lighter which makes it a bit different in looks when compared to that of menu bars opened when click on table action buttons.

since, the requirement was to make all menu bar follow same theme. that's why i did change the background color as well. (although the bg used in table menus on the left uses theme.background.primary | i went for transparent.primary as we are also having some blur css so wanted to keep its point).

else, i can revert back to original background and show you the difference if you want.

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
@Bonapara is going to rework this background transparency issue so I'm merging this as it is fixing the problem for now.

**Comment by Bonapara** [comment]
@FelixMalfait, I think there's a small bug in the report 😅
