### PR TITLE
fix: Prevent isDisabled prop from passing to DOM in Settings/Security Link

### LINKED ISSUE #8297: Error in devtools while checking Security tab
**Scenario:**
1. Log in
2. Go to Settings > Security

**Actual:** There's error in devtools about `isDisabled` attribute
image

**Expected:** There should be no error in devtools

CC: @AMoreaux

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #8297

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCard.tsx [hunk 1]
```diff
@@ -13,7 +13,9 @@ import styled from '@emotion/styled';
 import { useRecoilValue } from 'recoil';
 import { IconKey } from 'twenty-ui';
 
-const StyledLink = styled(Link)<{ isDisabled: boolean }>`
+const StyledLink = styled(Link, {
+  shouldForwardProp: (prop) => prop !== 'isDisabled',
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCard.tsx:17]: Could you also add `&& isPropValid(prop)` ? Thanks!

Comment (harshrajeevsingh) [reply packages/twenty-front/src/modules/settings/security/components/SettingsSSOIdentitiesProvidersListCard.tsx]: Done

**Review by FelixMalfait — APPROVED** [review]
Thank you!
