### PR TITLE
morph Board mode

### LINKED ISSUE #1323: [frontend] Morph on Board
- [ ] Spotted an issue in the one2many display in the Board. Note that the INPUT picker is properly loaded
SEE useRecordBoardRecordGqlFields -> try to replace with  useRecordFieldGqlFields

Image

- [ ] Spotted an issue in the many2one display in the Board. Clicking on the Empty placeholder crashed the frontend

Image

### PR DESCRIPTION
**Pull request by guillim**
Here's a concise PR description for your changes:

---

## Fix morph relation fields showing placeholder in kanban view

**Problem:** Morph relation fields always displayed placeholders in kanban view even when records were selected, because `useRecordFieldValue` was checking the base field name (e.g., `"favorite"`) instead of the computed morph field names (e.g., `"favoriteCompany"`).

**Solution:** Modified `useRecordFieldValue` to accept an optional `fieldDefinition` parameter and added special handling for morph relations that uses `recordStoreMorphManyToOneValueWithObjectNameFamilySelector` and `recordStoreMorphOneToManyValueWithObjectNameFamilySelector` to correctly retrieve values. Updated `useIsFieldEmpty` to pass the field definition through, enabling proper empty state detection for morph relation fields.

**Impact:** Morph relation fields now correctly display their values in kanban board cards instead of showing placeholders.

Fixes https://github.com/twentyhq/core-team-issues/issues/1323

Screenshot 2025-10-22 at 14 11 07

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-store/hooks/useRecordFieldValue.tsx [hunk 1]
```diff
@@ -1,16 +1,49 @@
...
+import { isFieldMorphRelation } from '@/object-record/record-field/ui/types/guards/isFieldMorphRelation';
+import { isFieldMorphRelationOneToMany } from '@/object-record/record-field/ui/types/guards/isFieldMorphRelationOneToMany';
 import { recordStoreFamilySelector } from '@/object-record/record-store/states/selectors/recordStoreFamilySelector';
-import { useRecoilValue } from 'recoil';
+import { recordStoreMorphManyToOneValueWithObjectNameFamilySelector } from '@/object-record/record-store/states/selectors/recordStoreMorphManyToOneValueWithObjectNameFamilySelector';
+import { recordStoreMorphOneToManyValueWithObjectNameFamilySelector } from '@/object-record/record-store/states/selectors/recordStoreMorphOneToManyValueWithObjectNameFamilySelector';
+import { useRecoilCallback } from 'recoil';
+import { FieldMetadataType } from 'twenty-shared/types';
 
 export const useRecordFieldValue = <T,>(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-store/hooks/useRecordFieldValue.tsx]: rename file name: useRecordFieldValue

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-store/hooks/useRecordFieldValue.tsx]: recordStoreFamilySelector => recordStoreGqlFieldFamilySelector

+ introduce recordStoreFieldFamilySelector

File: packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx [hunk 2]
```diff
@@ -1,16 +1,49 @@
...
-import { useRecoilValue } from 'recoil';
+import { recordStoreMorphManyToOneValueWithObjectNameFamilySelector } from '@/object-record/record-store/states/selectors/recordStoreMorphManyToOneValueWithObjectNameFamilySelector';
+import { recordStoreMorphOneToManyValueWithObjectNameFamilySelector } from '@/object-record/record-store/states/selectors/recordStoreMorphOneToManyValueWithObjectNameFamilySelector';
+import { useRecoilCallback } from 'recoil';
+import { FieldMetadataType } from 'twenty-shared/types';
 
 export const useRecordFieldValue = <T,>(
   recordId: string,
   fieldName: string,
+  fieldDefinition?: FieldDefinition<FieldMetadata>,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx]: make sure to Pick here

File: packages/twenty-front/src/modules/object-record/record-field/ui/utils/isFieldValueEmpty.ts [hunk 3]
```diff
@@ -82,9 +82,23 @@ export const isFieldValueEmpty = ({
...
 
   if (isFieldMorphRelation(fieldDefinition)) {
-    return isArray(fieldValue)
-      ? !isNonEmptyArray(fieldValue)
-      : isValueEmpty(fieldValue);
+    if (!isArray(fieldValue)) {
+      return isValueEmpty(fieldValue);
+    }
+
+    const areValuesEmpty = fieldValue
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/ui/utils/isFieldValueEmpty.ts:89]: add this case to isFieldValueEmpty.test.ts

File: packages/twenty-front/src/modules/object-record/record-store/hooks/useRecordFieldValue.tsx (hunk 1 above)
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-store/hooks/useRecordFieldValue.tsx]: makes fieldDefinition mandatory

File: packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx (hunk 2 above)
Comment (guillim) [reply packages/twenty-front/src/modules/object-record/record-store/contexts/RecordFieldValueSelectorContext.tsx]: cannot if i wanna use the assertFieldMetadata. Do you prefer me to remove the assertFieldMetadata in order to `Pick<FieldDefinition<FieldMetadata>, 'type' | 'metadata' | 'morphRelations'>,`

**Review by charlesBochet — APPROVED** [review]
