### PR TITLE
Exclude workflows from relation field object dropdown when inactive

### LINKED ISSUE #11996: Selectable workflow run migration target whereas Workflows are disabled
## Bug Description

When creating a relation field, Workflow runs data model is selectable whereas workflows are disabled in the lab for current workspace

https://github.com/user-attachments/assets/4d2103a2-bb5a-4e9f-a1c0-58a33ea9ddee

## Expected behavior

Should not display workflow run item

### PR DESCRIPTION
**Pull request by ehconitin**
closes #11996
- Switched the “Object destination” select in SettingsDataModelFieldRelationForm to use activeObjectMetadataItems.filter(...) so workflows, system, and remote objects are excluded
- Updated useRelationSettingsFormInitialValues to fall back on the same filtered activeObjectMetadataItems list for its initial value

This ensures workflows (and any unwanted system/remote objects) no longer show up in the dropdown or as the default.

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts [hunk 1]
```diff
@@ -27,17 +27,20 @@ export const useRelationSettingsFormInitialValues = ({
...
       relationObjectMetadataItemFromFieldMetadata ??
       objectMetadataItem ??
-      objectMetadataItems.filter(isObjectMetadataAvailableForRelation)[0],
-    [
-      objectMetadataItem,
-      objectMetadataItems,
-      relationObjectMetadataItemFromFieldMetadata,
-    ],
-  );
+      availableItems[0]
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts:37]: ***Remark:*** This could be undefined and ends up in runtime error below

**Review by prastoin — APPROVED** [review]
Nicely done ! Left a comment regarding a legacy potential undefined read attempt

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts [hunk 2]
```diff
@@ -34,7 +34,8 @@ export const useRelationSettingsFormInitialValues = ({
     return (
       relationObjectMetadataItemFromFieldMetadata ??
       objectMetadataItem ??
-      availableItems[0]
+      availableItems[0] ??
+      activeObjectMetadataItems[0]
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts:38]: By definition `activeObjectMetadataItems[0]` could also be `undefined` any uncheckedIndex access to an array is ( unless it's a tuple )
I would rather prefer an explicit invariant throw here I think if by design it should never occur

Could be harder to debug

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts [hunk 3]
```diff
@@ -31,12 +31,17 @@ export const useRelationSettingsFormInitialValues = ({
...
     );
-    return (
+    const initialObjectCandidate =
       relationObjectMetadataItemFromFieldMetadata ??
       objectMetadataItem ??
       availableItems[0] ??
-      activeObjectMetadataItems[0]
-    );
+      activeObjectMetadataItems[0];
+    if (!initialObjectCandidate) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts:39]: ***Nitpick:*** `isDefined` usage

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts [hunk 4]
```diff
@@ -27,17 +27,26 @@ export const useRelationSettingsFormInitialValues = ({
...
       objectMetadataItem ??
-      objectMetadataItems.filter(isObjectMetadataAvailableForRelation)[0],
-    [
-      objectMetadataItem,
-      objectMetadataItems,
-      relationObjectMetadataItemFromFieldMetadata,
-    ],
-  );
+      availableItems[0] ??
+      activeObjectMetadataItems[0];
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts:38]: ***Remark:*** If adding invariant check I would stick to the previous fallback on `      objectMetadataItems.filter(isObjectMetadataAvailableForRelation)[0],` only in order to do not over complexify this

If the invariant comes to occur then we should indeed improve the fallback

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts [hunk 5]
```diff
@@ -27,17 +27,26 @@ export const useRelationSettingsFormInitialValues = ({
...
+    if (!initialObjectCandidate) {
+      throw new Error(
+        'Relation Form initialization error: no valid objects to relate to. Please create a custom object in your workspace.',
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/relation/hooks/useRelationSettingsFormInitialValues.ts:41]: `Please create a custom object in your workspace.` Would replace by something like this should never occur if we're well sure this is an invariant

**Review by prastoin — APPROVED** [review]
Looks good to me ! well done ! Thanks for handling nitpicks !
