### PR TITLE
disable workflow execution if billing issue

### LINKED ISSUE #404: forbid user from executing workflow nodes if they don't have an active subscription
As Twenty we don't want that a workspace can execute workflow nodes if they don't have an ongoing subscription (Subsription status is active trialing or past due)
Right now it only show us a log

**Steps to follow**

1. Update Billing Feature can be used to check if there is an ongoing subscription instead of a not canceled one
2. Refactor some functions to get subscriptions and move them in order to maintain a logic
3. Throw a new  Billing Exception in workflow node runner when there is no active subscription Or `hasReachedCurrentPeriodCap` if subscription is 'trialing'
- run-workflow.job.ts - at workflow level
- workflow-executor.workspace - at node execution level
4. Add this exception to the Billing Rest Api listener
5. Verify that we can't execute the workflow when the Billing exception is throw
~~6. Ensure that the exception is sent to Sentry~~

### PR DESCRIPTION
**Pull request by etiennejouan**
closes https://github.com/twentyhq/core-team-issues/issues/404

### CODE REVIEW

File: packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts [hunk 1]
```diff
@@ -159,4 +178,26 @@ export class WorkflowExecutorWorkspaceService implements WorkflowExecutor {
       workspaceId,
     );
   }
+
+  private async canBillWorkflow() {
+    if (!this.billingService.isBillingEnabled()) {
+      return { canBillWorkflow: true, billingErrorOutput: {} };
```
Comment (Devessier) [inline packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:184]: nitpick: I'm unsure about that. If the billing is not enabled, we can bill the workflow?

File: packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts [hunk 2]
```diff
@@ -41,3 +41,14 @@ const isValidPriceUsageBased = (priceUsageBased?: string) => {
...
+const isValidProductKey = (productKey?: string) => {
+  switch (productKey) {
+    case BillingProductKey.BaseProduct:
+      return true;
+    case BillingProductKey.WorkflowNodeExecution:
+      return true;
+    default:
+      return false;
+  }
+};
```
Comment (Devessier) [inline packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts:54]: nitpick: I see we already wrote similar code above. However, we may need to use a more robust validation mechanism. We could at least do the following:

```ts
return Object.values(BillingProductKey).includes(productKey)
```

**Review by Devessier — COMMENTED** [review]
Great job! I will let someone else approve the PR as I'm not an expert of the backend. I left a few nitpicks.

File: packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts (hunk 2 above)
Comment (thomtrp) [inline packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts:54]: I would build something you do not need to maintain. Like: 
```
const isValidProductKey = (productKey?: string) => {
  return Object.values(BillingProductKey).includes(productKey as BillingProductKey);
};
```

File: packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts [hunk 3]
```diff
@@ -159,4 +178,26 @@ export class WorkflowExecutorWorkspaceService implements WorkflowExecutor {
       workspaceId,
     );
   }
+
+  private async canBillWorkflow() {
```
Comment (thomtrp) [inline packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:182]: `canBillWorkflowNodeExecution`

File: packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts [hunk 4]
```diff
@@ -159,4 +178,26 @@ export class WorkflowExecutorWorkspaceService implements WorkflowExecutor {
...
+
+    const canBillWorkflow = await this.billingService.canBillMeteredProduct(
+      workspaceId,
+      BillingProductKey.WorkflowNodeExecution,
+    );
+
+    const billingErrorOutput = canBillWorkflow
+      ? {}
+      : {
+          error: 'Unable to execute workflow. Please verify your subscription.',
```
Comment (thomtrp) [inline packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:198]: I don't think this is this function should build the output. Let's keep it for the main executor and return a boolean here

Comment (thomtrp) [reply packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:198]: also, let's use a more explicit error, saying we are enable to execute because of missing credits. I don't know how we should formulate this

File: packages/twenty-server/test/integration/billing/utils/create-mock-stripe-product-updated-data.util.ts [hunk 5]
```diff
@@ -17,8 +18,8 @@ export const createMockStripeProductUpdatedData = (
     marketing_features: [],
     metadata: {
       planKey: 'base',
-      isBaseProduct: 'true',
       priceUsageBased: BillingUsageType.LICENSED,
+      productKey: BillingProductKey.BaseProduct,
```
Comment (thomtrp) [inline packages/twenty-server/test/integration/billing/utils/create-mock-stripe-product-updated-data.util.ts:22]: do you know why we sometimes use camel, sometimes snake case? Looks like billing mainly use snake case for values

Comment (etiennejouan) [reply packages/twenty-server/test/integration/billing/utils/create-mock-stripe-product-updated-data.util.ts:22]: You're true, billing is in snake case, i modify

File: packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts [hunk 6]
```diff
@@ -12,32 +13,22 @@ export function isStripeValidProductMetadata(
...
-    case BillingUsageType.LICENSED:
-      return true;
-    default:
-      return false;
-  }
+const isValidEnumValue = <T>(
+  value: string | undefined,
+  enumObject: Record<string, T>,
+): boolean => {
+  return Object.values(enumObject).includes(value as T);
```
Comment (thomtrp) [inline packages/twenty-server/src/engine/core-modules/billing/utils/is-stripe-valid-product-metadata.util.ts:33]: ❤️

File: packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts [hunk 7]
```diff
@@ -159,4 +183,14 @@ export class WorkflowExecutorWorkspaceService implements WorkflowExecutor {
       workspaceId,
     );
   }
+
+  private async canBillWorkflowNodeExecution() {
+    const workspaceId =
+      this.scopedWorkspaceContextFactory.create().workspaceId ?? '';
+
+    return await this.billingService.canBillMeteredProduct(
```
Comment (thomtrp) [inline packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:191]: `return await` is only useful when performing a `try catch`. You can do `return` here

**Review by thomtrp — APPROVED** [review]
LGTM, one last comment. Let me know if you need help for testing

File: packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts (hunk 7 above)
Comment (etiennejouan) [reply packages/twenty-server/src/modules/workflow/workflow-executor/workspace-services/workflow-executor.workspace-service.ts:191]: nice thanks, i've never thought about it
