### PR TITLE
fix: can't properly drag and drop in empty record group

### LINKED ISSUE #8968: Record group can't drag in empty group

### PR DESCRIPTION
**Pull request by magrinj**
Fix #8968 

Fix issue with drag and drop when record group are empty.
Happy to discuss the implementation, as it's limited to the `@hello-pangea/dnd` api.

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx [hunk 1]
```diff
@@ -36,33 +36,39 @@ const StyledEmptyTd = styled.td`
...
   const theme = useTheme();
 
-  const visibleColumns = useRecoilComponentValueV2(
-    visibleTableColumnsComponentSelector,
-  );
+  const { visibleTableColumns } = useRecordTableContextOrThrow();
 
   return (
-    <StyledTrContainer onClick={onClick}>
+    <StyledRecordTableDraggableTr
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx:58]: why do we need to make the RecordTableActionRow draggable?

File: packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+import {
+  Draggable,
+  DraggableId,
+  DraggableProvided,
+  DraggableStateSnapshot,
+} from '@hello-pangea/dnd';
+import { forwardRef, ReactNode } from 'react';
+
+import { RecordTableTr } from '@/object-record/record-table/record-table-row/components/RecordTableTr';
+import { mergeRefs } from '~/utils/mergeRefs';
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx:11]: not sure to understand why we need useRef and mergeRefs here

File: packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx [hunk 3]
```diff
@@ -78,55 +77,37 @@ export const RecordTableRowWrapper = ({
   }, [inView, onIndexRecordsLoaded]);
 
   return (
-    <Draggable
+    <RecordTableDraggableTr
       key={recordId}
+      ref={(node) => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableRowWrapper.tsx:82]: aaaaargh

File: packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx (hunk 2 above)
Comment (magrinj) [reply packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableDraggableTr.tsx:11]: Because we need to manipulate the forwarded ref in the wrapper

File: packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx (hunk 1 above)
Comment (magrinj) [reply packages/twenty-front/src/modules/object-record/record-table/record-table-row/components/RecordTableActionRow.tsx:58]: If this one is not draggable we can't drag and drop properly rows within an empty group, the load more button and create new will not move, so it looks like it's not working

File: packages/twenty-front/src/utils/mergeRefs.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import { isDefined } from '~/utils/isDefined';
```
Comment (charlesBochet) [inline packages/twenty-front/src/utils/mergeRefs.ts:1]: already useCombinedRefs

**Review by charlesBochet — APPROVED** [review]
