### PR TITLE
🦣🦣🦣 Table virtualization

### LINKED ISSUE #1613: Table virtualization fixes before merge
Those issues are needed to stabilize table virtualization for sending to production

- [x]  Bug when going back to list from a record at the end of the list (see RecordTableNoRecordGroupScrollToPreviousRecordEffect)
- [x]  Small fix and refactor draggable clone that does not display with correct column widths
- [x]  Fix d&d not working after first 200 rows (the record disappears ?)
- [x]  Fix row active and focused not displaying well (border switch)
- [x]  Fix last line loading (one line loading at the end)
- [x]  Small fix - refactor RecordTableCellLoading with Linaria component (small perf improvement)
- [x]  Small fix - apply Linaria to RecordTableVirtualizedBodyPlaceholder
- [x]  Small fix - linaria to RecordTableRowVirtualizedContainer

### PR DESCRIPTION
**Pull request by lucasbordeau**
This big PR implements table virtualization with an offset paging, allowing a way more fluid UX.

It is a v1 that should be improved in the future with partial data loading and optimization of the browser display performance of a row.

But with this PR we have the solid enough technical foundation, both frontend and backend, to get to a smooth table UX.

Fixes and improvements after first successful round of development (needed to have main clean) : 

- [x] Delete should refresh virtualized portion only and reset all table
- [x] Fix add new : top and bottom
- [x] Table empty shouldn’t show when first loading
- [x] Fix d&d
- [x]  Fix sorts
- [x]  Fix drag when scrolling after a full virtual page (it throws an error)
- [x]  Si update mais qu’on a un sort ou filter, alors il faut trigger le refresh
- [x]  Reset scroll position between tables
- [x]  Reset scroll shadows between tables
- [x]  Setup d&n for virtual list : https://github.com/hello-pangea/dnd/blob/main/docs/patterns/virtual-lists.md
- [x]  Full table re-render when entering edit mode
- [x] Clean code and prepare for merge

Fixes https://github.com/twentyhq/core-team-issues/issues/1613 that contains other bugs to be fixed before merge

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/utils/getActivityTargetObjectRecords.ts [hunk 1]
```diff
@@ -6,12 +6,13 @@ import { type TaskTarget } from '@/activities/types/TaskTarget';
...
 import { type ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
 import { type ObjectRecord } from '@/object-record/types/ObjectRecord';
+import { type Nullable } from 'twenty-shared/types';
 import { isDefined } from 'twenty-shared/utils';
 
 type GetActivityTargetObjectRecordsProps = {
   activityRecord: Note | Task;
   objectMetadataItems: ObjectMetadataItem[];
-  activityTargets?: NoteTarget[] | TaskTarget[];
+  activityTargets?: Nullable<NoteTarget[] | TaskTarget[]>;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/utils/getActivityTargetObjectRecords.ts:15]: ok :)

File: packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx [hunk 2]
```diff
@@ -41,12 +41,14 @@ const mocks = [
           $orderBy: [MessageOrderByInput]
           $lastCursor: String
           $limit: Int
+          $offset: Int
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx:44]: why this change? looks unrelated to the PR

File: packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecordsWithOffset.ts [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+import { useRecordsFieldVisibleGqlFields } from '@/object-record/record-field/hooks/useRecordsFieldVisibleGqlFields';
+import { useFindManyRecordIndexTableParams } from '@/object-record/record-index/hooks/useFindManyRecordIndexTableParams';
+import { type ObjectRecord } from '@/object-record/types/ObjectRecord';
+
+type UseLazyFindManyRecordsWithOffsetParams = Pick<
+  UseFindManyRecordsParams<ObjectRecord>,
+  'objectNameSingular'
+>;
+
+export const useLazyFindManyRecordsWithOffset = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecordsWithOffset.ts:22]: fileName <> componentName

File: packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckboxPlaceholder.tsx [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+  width: ${RECORD_TABLE_COLUMN_CHECKBOX_WIDTH};
+  padding-right: ${({ theme }) => theme.spacing(1)};
+`;
+
+// TODO: refactor
+const StyledRecordTableTd = styled(RecordTableCellStyleWrapper)`
+  border-left: 1px solid transparent;
+`;
+
+export const RecordTableCellCheckboxPlaceholder = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellCheckboxPlaceholder.tsx:26]: would be nice to uniformize naming Skeleton <> Placeholder

File: packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableRowVirtualizedRouterLevel1.tsx [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+import { RecordTableRowVirtualizedSkeleton } from '@/object-record/record-table/virtualization/components/RecordTableRowVirtualizedSkeleton';
+import { lowDetailsActivatedComponentState } from '@/object-record/record-table/virtualization/states/lowDetailsActivatedComponentState';
+
+import { useRecoilComponentValue } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentValue';
+
+type RecordTableRowVirtualizedRouterLevel1Props = {
+  realIndex: number;
+};
+
+export const RecordTableRowVirtualizedRouterLevel1 = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableRowVirtualizedRouterLevel1.tsx:11]: Router naming is confusing!

File: packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableVirtualizedDataChangedEffect.tsx [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+      !isDefined(lastObjectOperation)
+    ) {
+      return;
+    }
+
+    if (
+      lastObjectOperation?.id !==
+      lastObjectOperationThatResettedVirtualization?.id
+    ) {
+      setLastObjectOperationThatResettedVirtualization(lastObjectOperation);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableVirtualizedDataChangedEffect.tsx:41]: I think we should discuss this, this seems hard to maintain

File: packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableVirtualizedInitialDataLoadEffect.tsx [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+import { isInitializingVirtualTableDataLoadingComponentState } from '@/object-record/record-table/virtualization/states/isInitializingVirtualTableDataLoadingComponentState';
+import { lastContextStoreVirtualizedViewIdComponentState } from '@/object-record/record-table/virtualization/states/lastContextStoreVirtualizedViewIdComponentState';
+import { lastRecordTableQueryIdentifierComponentState } from '@/object-record/record-table/virtualization/states/lastRecordTableQueryIdentifierComponentState';
+import { isFetchingMoreRecordsFamilyState } from '@/object-record/states/isFetchingMoreRecordsFamilyState';
+import { useRecoilComponentState } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentState';
+import { useGetCurrentViewOnly } from '@/views/hooks/useGetCurrentViewOnly';
+import { useEffect } from 'react';
+
+// TODO: see if we can merge the initial and load more processes, to have only one load at scroll index effect
+export const RecordTableVirtualizedInitialDataLoadEffect = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/virtualization/components/RecordTableVirtualizedInitialDataLoadEffect.tsx:16]: that's a lot of effects would be great to see if we can refactor. DevXP is a bit complex regarding data loading, we might want to take a tradeoff to simplify

File: packages/twenty-front/src/modules/object-record/record-table/virtualization/hooks/useAssignRecordsToStore.ts [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+export const useAssignRecordsToStore = () => {
+  const assignRecordsToStore = useRecoilCallback(
+    ({ set, snapshot }) =>
+      <T extends ObjectRecord>({ records }: { records: T[] }) => {
+        for (const record of records) {
+          const currentRecord = snapshot
+            .getLoadable(recordStoreFamilyState(record.id))
+            .getValue();
+
+          if (JSON.stringify(currentRecord) !== JSON.stringify(record)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/virtualization/hooks/useAssignRecordsToStore.ts]: isDeeplyEqual

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-table/virtualization/hooks/useAssignRecordsToStore.ts]: fixed

File: packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecordsWithOffset.ts (hunk 3 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/hooks/useLazyFindManyRecordsWithOffset.ts:22]: fixed

**Review by charlesBochet — APPROVED** [review]
