### PR TITLE
Fixes resetting of scroll position in RecordShowPage due to opening of some dropdowns (#6890)

### LINKED ISSUE #6890: Dropdown render causes parent scroll position to reset
## Bug Description

https://github.com/user-attachments/assets/cfffc128-19f8-4326-a760-57bb7ec0f131

## Expected behavior

Parent scroll should not reset

### PR DESCRIPTION
**Pull request by Faisal-imtiyaz123**
fixes #6890

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx [hunk 1]
```diff
@@ -35,12 +36,15 @@ const StyledInput = styled.input`
...
-      {...{ autoFocus, onChange, placeholder, type, value }}
-      ref={ref}
-    />
-  </StyledDropdownMenuSearchInputContainer>
-));
+>(({ value, onChange, placeholder = 'Search', type }) => {
+  const {inputRef} = useFocus()
+  return (
+    <StyledDropdownMenuSearchInputContainer>
+      <StyledInput
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/ui/layout/dropdown/components/DropdownMenuSearchInput.tsx:43]: Could you try to work on the StyledInput component level ? Ideal solution would be that this useEffect is not an external hook but rather something internal to the input component and we can pass "preventScroll" as a property of this input.

It could be fine to create a new input component if you feel the need.

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau Sure!

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 Your solution works well, I just renamed the component so it's more self-explanatory why we use this instead of autofocus prop.

**Review by lucasbordeau — APPROVED** [review]
I fixed a bug on main from a previously merged PR.
