### PR TITLE
CSV Import translations and dark mode fixes

### LINKED ISSUE #11182: CSV import is ugly when system is in dark mode but app is in light mode
Looks like we still use chakra-ui/rdg tables that must have their own system to detect styling which conflict with ours:

Image

See:
https://github.com/adazzle/react-data-grid/issues/2170

### PR DESCRIPTION
**Pull request by FelixMalfait**
Fixes #11182 and adds missing translations

### CODE REVIEW

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx [hunk 1]
```diff
@@ -275,9 +278,8 @@ export const MatchColumnsStep = <T extends string>({
...
     if (unmatchedRequiredFields.length > 0) {
       enqueueDialog({
-        title: 'Not all columns matched',
-        message:
-          'There are required columns that are not matched or ignored. Do you want to continue?',
+        title: t`Not all columns matched`,
+        message: t`There are required columns that are not matched or ignored. Do you want to continue?`,
         children: (
           <StyledColumnsContainer>
             <StyledColumns>Columns not matched:</StyledColumns>
```
[the remark this answers is not in the document]
Comment (charlesBochet) [reply packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/MatchColumnsStep.tsx:285]: @FelixMalfait greptile gets a point

File: packages/twenty-front/src/modules/spreadsheet-import/components/SpreadsheetImportTable.tsx [hunk 2]
```diff
@@ -133,7 +136,7 @@ export const SpreadsheetImportTable = <Data,>({
       direction={rtl ? 'rtl' : 'ltr'}
       rowHeight={52}
       {...{
-        className,
+        className: `${className || ''} ${themeClassName}`,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/spreadsheet-import/components/SpreadsheetImportTable.tsx:139]: not a fan of this, it's not our usual pattern, can we avoid it?

Comment (charlesBochet) [reply packages/twenty-front/src/modules/spreadsheet-import/components/SpreadsheetImportTable.tsx:139]: ok got it, it's because of react data grid
LGTM

**Review by charlesBochet — APPROVED** [review]

**Review by charlesBochet — APPROVED** [review]
@FelixMalfait LGTM:
- you are missing a translation key (see greptile comment)
- Steps.stories.tsx is failing

Once fixed, you can merge!
