### PR TITLE
Fix: Twenty-website docs same TOC ids #11865

### LINKED ISSUE #11865: Twenty docs same TOC ids
## Bug Description

Same table of content id result in conflicting highlighting

https://github.com/user-attachments/assets/f6aa24e2-c38f-4714-a17b-425c13384bdb

## Expected behavior

Should not be conflicting, need to changes ids

### PR DESCRIPTION
**Pull request by PrajwalDhule**
This PR fixes issue https://github.com/twentyhq/twenty/issues/11865.

The highlight heading logic in TOC was checking the heading text which could be the same for multiple headings.
The ids for these headings were also just the heading texts, leading to conflict in ids too.

Fix:
- Appended index of the heading item from the list of headings to the id of the heading. This fixed conflicting ids.
- Used these unique ids to toggle the highlight style.

Behaviour after the fix:

https://github.com/user-attachments/assets/ab3bc205-0b0e-451d-b9cb-4fa852263efc

Edit:
close #11865

### CODE REVIEW

File: packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx [hunk 1]
```diff
@@ -13,16 +13,16 @@ export const wrapHeadingsWithAnchor = (children: ReactNode): ReactNode => {
...
       isValidElement(child) &&
       typeof child.type === 'string' &&
       ['h1', 'h2', 'h3', 'h4'].includes(child.type)
     ) {
-      const id = child.props.children
+      const id = `${child.props.children
         .toString()
         .replace(/\s+/g, '-')
-        .toLowerCase();
+        .toLowerCase()}-${index}`;
```
Comment (prastoin) [inline packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx:25]: ***Suggestion:*** I feel quite hesitating consuming the index as the 
discriminant here. Tbh I'm not sure of what should the best here. Would instinctively rather think of parent scoping, such as `#some-parent-create-a-project-in-google-cloud`

**Review by prastoin — COMMENTED** [review]
Hey @PrajwalDhule thanks for your contribution !
Your code looks good left one concern regarding the discriminant nature in a comment 
Have a great day !

File: packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx (hunk 1 above)
Comment (PrajwalDhule) [reply packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx:25]: @prastoin 

Since the ID generation is happening for static pages using markdown, using the index method to generate heading IDs should be sufficient as the IDs would be unique and the UI won't change after ID generation.

Another way in line with what you mentioned, is the hierarchy method, which builds IDs by combining the closest parent headings (e.g., docs-installation-linux for an h3: linux, under h2: Installation, and h1: Docs). The method also ensures uniqueness since it could be safe enough to assume the whole hierarchy wont be duplicated. 

However, it can add more complexity and will result in very long IDs.

Can you let me know if this hierarchy method sounds fine to go ahead with and would still be preferred over IDs with index?

Comment (prastoin) [reply packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx:25]: Indeed you're right, as it's deterministic we could.
One other thing I'm concerned about appending/prefixing the index is that any existing anchored link would result in being broken but that's also the case for future addition to the DOM, e.g adding a new element in the tree resulting in incrementing index by one etc etc.
What we could ultimately do is while building the static pages, keep an aggregator, either a map or a set, with of all formatted heading content + a collision counter.
Only on a collision we would add tho the anchor id the current collision counter than increment it for the following page element. This could still break if we add a new identical element to the page ( meaning the collision counter could mutate ) but that's imo acceptable

Comment (prastoin) [reply packages/twenty-website/src/shared-utils/wrapHeadingsWithAnchor.tsx:25]: Exactly

**Review by prastoin — APPROVED** [review]
Hey @PrajwalDhule thanks again for your contribution really good job

**Comment by prastoin** [comment]
@greptile trigger
