### PR TITLE
Fix state mutation serverless action

### LINKED ISSUE #8523: WorkflowEditActionFormServerlessFunction component directly mutates props
The `setNestedValue` function operates on a shallow copy and not a deep copy of the `functionInput`. This is hiding that we mutate props, which is [forbidden with React](https://react.dev/reference/rules/components-and-hooks-must-be-pure#props) as you know.

I would do two things:

1. Call `structuredClone` on the obj in the `setNestedValue` to ensure we never mutate the object references.
2. Synchronously store the state of the form in a `useState`

```ts
export const setNestedValue = (obj: any, path: string[], value: any) => {
  const newObj = structuredClone(obj);
  path.reduce((o, key, index) => {
    if (index === path.length - 1) {
      o[key] = value;
    }
    return o[key] || {};
  }, newObj);
  return newObj;
};
```

Video demo (open it): https://share.cleanshot.com/bJgJTBwD

### PR DESCRIPTION
**Pull request by Devessier**
In this PR:

- Ensure the `setNestedValue` does a deep copy of the provided object and doesn't mutate it directly.
- Store the form's state in a `useState` instead of relying entirely on the backend's state. This makes the form more resilient to slow network connections.
- Ensure the input settings are reset when selecting another function.
- The Inner component now expects the serverless functions data to be resolved before being mounted, so I split it.

Closes https://github.com/twentyhq/twenty/issues/8523

### CODE REVIEW

File: packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx [hunk 1]
```diff
@@ -53,166 +18,17 @@ export const WorkflowEditActionFormServerlessFunction = ({
...
-        fullWidth
-        value={action.settings.input.serverlessFunctionId}
-        options={availableFunctions}
-        emptyOption={{ label: 'None', value: '' }}
-        disabled={actionOptions.readonly}
-        onChange={handleFunctionChange}
-      />
-      {renderFields(functionInput)}
-    </WorkflowEditGenericFormBase>
+    <WorkflowEditActionFormServerlessFunctionInner
```
Comment (thomtrp) [inline packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx:29]: why adding another component here? I feel like the parent does not do a lot. Let's keep everything in the same?

Comment (thomtrp) [inline packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx:29]: if you really want to split the component, we should start grouping components together. Maybe by actions?

**Review by thomtrp — APPROVED** [review]

File: packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx (hunk 1 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/workflow/components/WorkflowEditActionFormServerlessFunction.tsx:29]: According to our discussion, we'll split components in another PR.
