### PR TITLE
fix: adjust padding for icon button in Data model visualizer

### LINKED ISSUE #10958: Icon button in Data model visualizer padding issue
## Bug Description
at Settings / Workspace / Objects / Overview, the close button icon padding seems incorrect

Image

## Expected behavior

Image

figma - 
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34855-566020&t=o571JzLcbvq3mZ2g-0

### PR DESCRIPTION
**Pull request by b9aurav**
Fixes #10958 

image

### CODE REVIEW

**Review by ehconitin — CHANGES_REQUESTED** [review]
@b9aurav Thanks for the PR, we should use `IconButton` for buttons with no title and just icon.
update -- just checked the figma and it seems like it's a `FloatingIconButton`
@Bonapara is this button style updated? not sure if any of FloatingIconButtons or IconButtons variants style would match the figma
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34855-566020&t=0fqroYBOgQt7UcK0-0

File: packages/twenty-front/src/generated-metadata/gql.ts [hunk 1]
```diff
@@ -122,11 +122,11 @@ export function graphql(source: "\n  mutation UpdateOneFieldMetadataItem(\n    $
...
+export function graphql(source: "\n  mutation DeleteOneObjectMetadataItem($idToDelete: UUID!) {\n    deleteOneObject(input: { id: $idToDelete }) {\n      id\n      dataSourceId\n      nameSingular\n      namePlural\n      labelSingular\n      labelPlural\n      description\n      icon\n      isCustom\n      isActive\n      isSearchable\n      createdAt\n      updatedAt\n      labelIdentifierFieldMetadataId\n      imageIdentifierFieldMetadataId\n      isLabelSyncedWithName\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteOneObjectMetadataItem($idToDelete: UUID!) {\n    deleteOneObject(input: { id: $idToDelete }) {\n      id\n      dataSourceId\n      nameSingular\n      namePlural\n      labelSingular\n      labelPlural\n      description\n      icon\n      isCustom\n      isActive\n      isSearchable\n      createdAt\n      updatedAt\n      labelIdentifierFieldMetadataId\n      imageIdentifierFieldMetadataId\n      isLabelSyncedWithName\n    }\n  }\n"];
```
Comment (charlesBochet) [inline packages/twenty-front/src/generated-metadata/gql.ts:129]: not related to this PR, main seems to be outdated

**Review by charlesBochet — APPROVED** [review]
Thanks for opening a PR @b9aurav, I'm simplifying the logic a bit :)

**Comment by charlesBochet** [comment]
@ehconitin I'm merging it with the fix, and I will revisit it with @Bonapara tomorrow
