### PR TITLE
fix the tests

### LINKED ISSUE #1490: Fix the tests (storybook)
The storybook tests are failing due to some recent changes that got merged

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #1490

### CODE REVIEW

File: front/src/testing/graphqlMocks.ts [hunk 1]
```diff
@@ -249,14 +249,14 @@ export const graphqlMocks = [
...
-        objectId: { equals: objectId },
+        viewId: { equals: viewId },
       },
     } = req.variables;
 
     return res(
       ctx.data({
         viewFields:
-          objectId === 'company'
+          viewId === 'e6a2232d-ca6c-42df-b78e-ca0343f545a9'
```
Comment (thaisguigon) [inline front/src/testing/graphqlMocks.ts:259]: Hello, thank you for fixing this!

I suggest we use the `mockedCompanyViews` variable:

```suggestion
          viewId === mockedCompanyViews[0].id
```

Otherwise, LGTM!

**Review by thaisguigon — CHANGES_REQUESTED** [review]

**Comment by charlesBochet** [comment]
THANK YOU!
