### PR TITLE
Fix many bugs on advanced filters for CRUD to work

### LINKED ISSUE #560: Fix advanced filter CRUD
Bugs : 
- saving is prevented due to invalid field type on `positionInViewFilterGroup`
- copying view is prevented due to wrong ids during filter and filter group duplication
- bug with adding a simple filter and advanced filters at the same time

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes many bugs on advanced filters, the goal here was to have CRUD working with other simple filters and sorts.

In order to test this PR you'll have to run a sync metadata.

Fixes https://github.com/twentyhq/core-team-issues/issues/560

## Changed positionInViewFilterGroup field metadata type 

This PR changes the type of positionInViewFilterGroup to NUMERIC instead of POSITION, there certainly was a confusion during the initial development, where POSITION type seemed relevant but it is not for this particular feature because the position in a view filter group is not the position of a record, which is used for displaying and re-ordering purpose in table and kanban views. 

Here the positionInViewFilterGroup is a specific position concept tied to a custom feature, and it is handled by the specific logic of this advanced filter dropdown layout.

## Create new ids when duplicating a view

When we use create view from an existing view, the logic in useCreateViewFromCurrentView will copy over filters, filter groups and sorts. The problem is that it copies it with the same ids, and that if the backend manages somehow to create new ids, the ids that are put in parentViewFilterGroupId are corresponding to the old filter groups not the duplicated new ones.

So we had to create a map of old id => new id so that everything that has to be sent to the backend for creation already has the same mapping of parent id but with new ids generated by the frontend.

## Bug with creating a simple filter

We couldn't create a simple filter when advanced filters were set, this was because of findDuplicateRecordFilterInNonAdvancedRecordFilters which wasn't doing what it's naming tells, it wasn't filtering on simple filters only before looking for duplicates.

## Clean code

- Use lastChildPosition directly from useChildRecordFiltersAndRecordFilterGroups instead of drilling it down
- Refactored AdvancedFilterDropdownButton to extract the code lower where it is really needed in AdvancedFilterChip
- Renamed a few View to Record naming where relevant
- Created a util to abstract view filter and view filter group duplication logic

### CODE REVIEW

File: packages/twenty-server/src/modules/view/standard-objects/view-filter-group.workspace-entity.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export class ViewFilterGroupWorkspaceEntity extends BaseWorkspaceEntity {
 
   @WorkspaceField({
     standardId: VIEW_FILTER_GROUP_STANDARD_FIELD_IDS.positionInViewFilterGroup,
-    type: FieldMetadataType.POSITION,
+    type: FieldMetadataType.NUMERIC,
```
Comment (charlesBochet) [inline packages/twenty-server/src/modules/view/standard-objects/view-filter-group.workspace-entity.ts:88]: use NUMBER here

File: packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts [hunk 2]
```diff
@@ -87,7 +87,7 @@ export class ViewFilterWorkspaceEntity extends BaseWorkspaceEntity {
 
   @WorkspaceField({
     standardId: VIEW_FILTER_STANDARD_FIELD_IDS.positionInViewFilterGroup,
-    type: FieldMetadataType.POSITION,
+    type: FieldMetadataType.NUMERIC,
```
Comment (charlesBochet) [inline packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts:90]: use NUMBER

NUMERIC should not exist and is deprecated (there is a confusion between the Postgres column NUMERIC and the metadata field type NUMBER)

File: packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterAddFilterRuleSelect.tsx [hunk 3]
```diff
@@ -34,6 +33,10 @@ export const AdvancedFilterAddFilterRuleSelect = ({
 
   const { upsertRecordFilter } = useUpsertRecordFilter();
 
+  const { lastChildPosition } = useChildRecordFiltersAndRecordFilterGroups({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/advanced-filter/components/AdvancedFilterAddFilterRuleSelect.tsx:36]: I feel the naming could be improved here: lastChildRecordFilterGroupPosition

 also I'm challenging the usage of a hook here. I feel an util would be better:
 - useRecordFilterGroup({ recordFilterGroupId }) ==> reads from the state
 - getLastChildRecordFilterGroupPosition({ recordGroup })

File: packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts (hunk 2 above)
Comment (charlesBochet) [reply packages/twenty-server/src/modules/view/standard-objects/view-filter.workspace-entity.ts:90]: double check that this won't break anything if we have this code but before sync metadata

File: packages/twenty-front/src/modules/views/components/AdvancedFilterChip.tsx [hunk 4]
```diff
@@ -1,27 +1,62 @@
...
+
+  const advancedRecordFilterIds = currentRecordFilters
+    .filter((recordFilter) => isDefined(recordFilter.recordFilterGroupId))
+    .map((recordFilter) => recordFilter.id);
+
+  const { removeRecordFilter } = useRemoveRecordFilter();
+  const { removeRecordFilterGroup } = useRemoveRecordFilterGroup();
+
+  const handleRemoveClick = () => {
+    if (!advancedRecordFilterIds) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/components/AdvancedFilterChip.tsx:30]: use precise check (.length === 0) or isNonEmptyArray

**Review by charlesBochet — APPROVED** [review]
LGTM, I have tested the behavior on non advanced filters and left a few comments
