### PR TITLE
Fix field metadata creation page

### LINKED ISSUE #11262: Gap on field metadata creation page
No note found

### LINKED ISSUE #11263: Advanced settings orange dot is weird on field creation page
No note found

### PR DESCRIPTION
**Pull request by ijreilly**
in this pr 
1. fixing error helper was no longer showing. unfortunately had to resort to `formConfig.trigger`...
2. closes https://github.com/twentyhq/twenty/issues/11262
3. closes https://github.com/twentyhq/twenty/issues/11263

https://github.com/user-attachments/assets/11f763bb-3098-4b0e-bc96-8a0de3cb3c19

### CODE REVIEW

File: packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx [hunk 1]
```diff
@@ -30,6 +30,8 @@ const StyledInputContainer = styled.div`
   display: flex;
   flex-direction: row;
   position: relative;
+  margin-bottom: ${({ theme }) =>
+    theme.spacing(1)}; // provision for error helper
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx:34]: some alignment issues I found wrt this change
Screenshot 2025-03-31 at 14 48 39

Screenshot 2025-03-31 at 14 49 05

we had a similar regression before which was fixed in https://github.com/twentyhq/twenty/pull/10577

Comment (ijreilly) [reply packages/twenty-front/src/modules/ui/input/components/TextInputV2.tsx:34]: good catch thanks

File: packages/twenty-front/src/modules/settings/components/StyledAdvancedWrapper.tsx [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import styled from '@emotion/styled';
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/settings/components/StyledAdvancedWrapper.tsx:1]: File name should be `AdvancedWrapper`

Comment (bosiraphael) [reply packages/twenty-front/src/modules/settings/components/StyledAdvancedWrapper.tsx:1]: Note: Is it really useful to have a separate file for such a simple component?

File: packages/twenty-front/src/modules/settings/components/StyledDotContainer.tsx [hunk 3]
```diff
@@ -0,0 +1,23 @@
+import styled from '@emotion/styled';
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/settings/components/StyledDotContainer.tsx:1]: Same, file name should never start with 'Styled'.

File: packages/twenty-front/src/modules/settings/components/StyledIconPoint.tsx [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import styled from '@emotion/styled';
+import { IconPoint as IconPointUI } from 'twenty-ui';
+
+const StyledIconPoint = styled(IconPointUI)`
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/settings/components/StyledIconPoint.tsx:4]: Same, you can give it a more specific name `SettingsIconPoint`

File: packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx [hunk 5]
```diff
@@ -207,27 +213,36 @@ export const SettingsDataModelFieldIconLabelForm = ({
...
-                            fillNameFromLabel(label);
-                          }
-                        }}
-                      />
-                    </Card>
+                    <StyledAdvancedWrapper>
+                      <StyledDotContainer dotPosition="centered">
+                        <StyledIconPoint
+                          size={12}
+                          color={MAIN_COLORS.yellow}
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/settings/data-model/fields/forms/components/SettingsDataModelFieldIconLabelForm.tsx:220]: `MAIN_COLORS` are used to define the theme, you shouldn't use them directly, instead use `theme.color.yellow`

**Review by bosiraphael — COMMENTED** [review]
The behavior looks good :) Left a few comments to address before merging.

**Review by bosiraphael — APPROVED** [review]
LGTM
