### PR TITLE
Fix post merge revamp navigation bar

### LINKED ISSUE #6285: Fix post merge Revamp navigation bar
## Scope & Context

After merge of https://github.com/twentyhq/twenty/pull/6031, we have a lot of small fixes and refactors to do. We left them aside to release a working feature.

## Technical inputs

- [x] Use a recoil state instead of useFindRecordCursorFromFindManyCacheRootQuery
- [x] Refactor useRecordIdsFromFindManyCacheRootQuery to be used only if there's a cursor in recoil state
- [x] Refactor useRecordShowPagePagination to be generic with views
- [x] Merge useScrollToPosition and useScrollRestoration if possible, or refactor accordingly
- [x] Refactor RecordIndexContainer => move logic outside, useGeCurrent
- [x] Fix RecordShowPage story (see msw mocks, because requests changed)
- [x] Rename RecordIndexRecordChip to RecordIdentifierChip
- [x] Rename isFieldChipDisplay to isFieldIdentifierDisplay
- [x] Refactor findView and view: any
- [x] Refactor URL building in shared utils
- [x] Refactor ROW_HEIGHT extract

### PR DESCRIPTION
**Pull request by lucasbordeau**
Closes #6285 

@charlesBochet Also added some more utils for our component state v2.

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/cache/utils/getRecordsFromRecordConnection.ts [hunk 1]
```diff
@@ -5,9 +5,11 @@ import { ObjectRecord } from '@/object-record/types/ObjectRecord';
 export const getRecordsFromRecordConnection = <T extends ObjectRecord>({
   recordConnection,
 }: {
-  recordConnection: RecordGqlConnection;
+  recordConnection: RecordGqlConnection | undefined;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/cache/utils/getRecordsFromRecordConnection.ts:8]: I'm not sure I like this change. An undefined connection converted to an empty array, I feel we are losing a lot of information

File: packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts [hunk 2]
```diff
@@ -209,21 +210,30 @@ export const useFetchMoreRecordsWithPagination = <
...
+  const recordConnection = data?.[objectMetadataItem.namePlural];
+
   const records = useMemo(
     () =>
-      data?.[objectMetadataItem.namePlural]
-        ? getRecordsFromRecordConnection<T>({
-            recordConnection: data?.[objectMetadataItem.namePlural],
-          })
-        : ([] as T[]),
+      getRecordsFromRecordConnection<T>({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts:217]: I understand the usage, but I think we should catch it earlier is it possible to have data?.[objectMetadataItem.namePlural] undefined? shouldn't we throw/return earlier in this case instead

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    }),
+  );
+
+  const { filter, orderBy } =
+    useQueryVariablesFromActiveFieldsOfViewOrDefaultView({
+      objectMetadataItem,
+      viewId: currentViewId,
+    });
+
+  const { findCursorInCache } = useFindRecordCursorFromFindManyCacheRootQuery({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts:30]: is this right? what we we have several findMany on the same filters and orderBy?

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+    const cursor = findCursorInCache(recordId);
+
+    const showPageURL = buildShowPageURL(
+      objectMetadataItem.nameSingular,
+      recordId,
+      currentViewId,
+    );
+
+    navigate(showPageURL, {
+      state: {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts:48]: do we need this cursor? I think we could build it from the recordId (it's a relay standard)

File: packages/twenty-front/src/modules/object-record/record-table/states/cursorByRecordFamilyState.ts [hunk 5]
```diff
@@ -0,0 +1,9 @@
+import { createFamilyState } from '@/ui/utilities/state/utils/createFamilyState';
+
+export const cursorByRecordFamilyState = createFamilyState<
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/states/cursorByRecordFamilyState.ts:3]: I think we could remove this if we can rebuild the cursor from the recordId direclty. Would simplify it!

File: packages/twenty-front/src/modules/object-record/record-table/states/tableCursorByRecordComponentStateV2.ts [hunk 6]
```diff
@@ -0,0 +1,11 @@
+import { createComponentFamilyStateV2 } from '@/ui/utilities/state/component-state/utils/createComponentFamilyStateV2';
+import { ViewScopeInternalContext } from '@/views/scopes/scope-internal-context/ViewScopeInternalContext';
+
+// TODO: This is an example that can't be used because the context is not the same between RecordTable and RecordShowPage
+// We should remove it when we have other examples of component family state V2
+export const tableCursorByRecordIdComponentFamilyStateV2 =
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/states/tableCursorByRecordComponentStateV2.ts:6]: that's why I think we should put all this logic into a "navigation-context" module which declares global state if needed, this is not specific to table

File: packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useExtractedComponentFamilyStateV2.ts [hunk 7]
```diff
@@ -0,0 +1,35 @@
+import { useAvailableScopeIdOrThrow } from '@/ui/utilities/recoil-scope/scopes-internal/hooks/useAvailableScopeId';
+import { getScopeIdOrUndefinedFromComponentId } from '@/ui/utilities/recoil-scope/utils/getScopeIdOrUndefinedFromComponentId';
+import { ComponentFamilyState } from '@/ui/utilities/state/component-state/types/ComponentFamilyState';
+import { SerializableParam } from 'recoil';
+
+export const useExtractedComponentFamilyStateV2 = <
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useExtractedComponentFamilyStateV2.ts:6]: why? :p

File: packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useScopeIdFromStateContext.ts [hunk 8]
```diff
@@ -0,0 +1,23 @@
+import { useScopeInternalContext } from '@/ui/utilities/recoil-scope/scopes-internal/hooks/useScopeInternalContext';
+import { ComponentFamilyState } from '@/ui/utilities/state/component-state/types/ComponentFamilyState';
+import { ComponentState } from '@/ui/utilities/state/component-state/types/ComponentState';
+
+export const useScopeIdFromStateContext = (
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useScopeIdFromStateContext.ts:5]: useComponentId!

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useScopeIdFromStateContext.ts (hunk 8 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/ui/utilities/state/component-state/hooks/useScopeIdFromStateContext.ts:5]: It's not componentId it's scopeId, that's not the same, scopeId is prefixed with "-scope-id".

**Comment by lucasbordeau** [comment]
+ infer cursor from id instead of request to get it

**Comment by lucasbordeau** [comment]
Remove unused states

**Review by charlesBochet — COMMENTED** [review]
Follow up:
- infer cursor from recordId (in url)
- introduce "navigation-store" module?

File: packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts (hunk 2 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts:217]: Since in React we try to avoid blocking initial renders where everything is loading and we should just allow the render flow to complete, I think it's preferable here to return [] since it will allow everything to show something and base itself on loading instead on trying to guess whether undefined means loading or error.

In this case there is already an error object that we can watch to handle errors, we shouldn't mix both.

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts (hunk 4 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleIndexIdentifierClick.ts:48]: Not anymore yes

File: packages/twenty-front/src/modules/object-record/cache/utils/getCursorByRecordIdFromRecordConnection.ts [hunk 9]
```diff
@@ -0,0 +1,19 @@
+import { RecordGqlConnection } from '@/object-record/graphql/types/RecordGqlConnection';
+
+export type CursorByRecordId = {
+  cursor: string;
+  recordId: string;
+};
+
+export const getCursorByRecordIdFromRecordConnection = ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/cache/utils/getCursorByRecordIdFromRecordConnection.ts:8]: not used anymore

File: packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts [hunk 10]
```diff
@@ -209,21 +210,31 @@ export const useFetchMoreRecordsWithPagination = <
...
+      }),
+    [recordConnection],
   );
 
   return {
     fetchMoreRecords,
     totalCount,
     records,
     hasNextPage,
+    cursorsByRecordId,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/hooks/useFetchMoreRecordsWithPagination.ts:238]: we should remove all occurences of cursorsByRecordId

**Review by charlesBochet — APPROVED** [review]
