### PR TITLE
Fixed record picker loading flickering

### LINKED ISSUE #12680: Add a debounce on record picker search to avoid flickering

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR solves a flickering effect on record pickers on the different loading state they can be in.

It was designed with @Bonapara to settle on a nice UX feeling.

## Before

With fast network (local) :

https://github.com/user-attachments/assets/58899934-c705-4b44-b7f6-289045032c11

With slow network : 

https://github.com/user-attachments/assets/9fb18d86-9da6-4e5d-a83f-00c810fab2dc

## After

https://github.com/user-attachments/assets/f4abb40f-5d42-4c46-88ab-aaef4f883f7f

Fixes https://github.com/twentyhq/twenty/issues/12680

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItems.tsx [hunk 1]
```diff
@@ -93,56 +86,60 @@ export const SingleRecordPickerMenuItems = ({
...
-      {loading ? (
-        <DropdownMenuSkeletonItem />
+      {emptyLabel && (
+        <SelectableListItem
+          key={'select-none'}
+          itemId={'select-none'}
+          onEnter={() => {
+            setSelectedRecordId(undefined);
+            onRecordSelected();
+          }}
```
Comment (SimonGodefroid) [inline packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/components/SingleRecordPickerMenuItems.tsx:114]: Where possible it's best to create named functions to avoid un-necessary creation of anonymous functions on re-renders.
```tsx
function onEnter(){
  setSelectedRecordId(undefined);
  onRecordSelected();
}
...
onEnter={onEnter}
```

File: packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/states/singleRecordPickerShowSkeletonComponentState.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+import { SingleRecordPickerComponentInstanceContext } from '@/object-record/record-picker/single-record-picker/states/contexts/SingleRecordPickerComponentInstanceContext';
+import { createComponentStateV2 } from '@/ui/utilities/state/component-state/utils/createComponentStateV2';
+
+export const singleRecordPickerShowSkeletonComponentState =
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-picker/single-record-picker/states/singleRecordPickerShowSkeletonComponentState.ts]: singleRecordPickerShouldShowSkeletonComponentState

**Review by charlesBochet — APPROVED** [review]
