### PR TITLE
patch messages in thread

### LINKED ISSUE #12190: Load all messages in thread
## Context

https://github.com/user-attachments/assets/5a0beaf8-1ff3-4e91-a99b-002bb29cece5

Steps to reproduce : 
- from an email tab on person record, click on a thread with more than 20 messages (3 pages in findManyMessages) to arrive on thread tab
- from thread tab, go back to email tab
- from email tab, click on same thread > only two pages are loaded (but all messages are loaded if intermediary messages are unfold)

## Solutions

- In 'theory' - `CommandMenuMessageThreadPage` component has evolved from list with fetching more on scroll to current design : list composed of two first messages displayed / intermediary messages component / last messages. However, `useEmailThreadInCommandMenu` logic should have been updated too : instead of fetching all pages, we should fetch two first messages and last one + fetch all when clicking on intermediary messages.

- In practice ✅ Increase messages fetched by page limit from 10 -> 60. After discussion with Felix, we chose practical solution because it keeps a fluid experience for the majority of threads (the one with less than 60 messages) without impacting experience for long threads (1 calls fetching 60 messages are not very different than 6 calls fetching 10).

### PR DESCRIPTION
**Pull request by etiennejouan**
closes https://github.com/twentyhq/twenty/issues/12190

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export const fetchAllThreadMessagesOperationSignatureFactory: RecordGqlOperation
           receivedAt: 'AscNullsLast',
         },
       ],
-      limit: 10,
+      limit: 30,
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/activities/emails/graphql/operation-signatures/factories/fetchAllThreadMessagesOperationSignatureFactory.ts:18]: Put the maximum authorized by the backend since it is a quick and temporary fix

File: packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx [hunk 2]
```diff
@@ -155,7 +155,7 @@ const mocks = [
         filter: { messageThreadId: { eq: '1' } },
         orderBy: [{ receivedAt: 'AscNullsLast' }],
         lastCursor: undefined,
-        limit: 10,
+        limit: 60,
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/command-menu/pages/message-thread/hooks/__tests__/useEmailThreadInCommandMenu.test.tsx:158]: Isn't there a constant for this? We could create one if there is none

**Review by bosiraphael — APPROVED** [review]
LGTM
