### PR TITLE
Fix latest visited view

### LINKED ISSUE #9772: Not fully created record breaks records tab
**Scenario:**
1. Log in
2. Go to Companies
3. Click "New record" button
4. Go to People
5. Go to Companies

**Actual:** Instead of companies view, there's view of completely different object's records

https://github.com/user-attachments/assets/e511dd96-7f3b-4276-ab70-14460f393551

**Expected:** Companies view must be presented

### PR DESCRIPTION
**Pull request by charlesBochet**
Fixes https://github.com/twentyhq/twenty/issues/9772

In this PR:
- the root cause of the issue that the ContextStoreViewIdEffect was not filtering the views on objectMetadata properly
- I'm also deleting some over complex in the latestVisited view logic
- Duplicated logic between ContextStoreViewIdEffect and ViewBarViewIdEffect, see my comment

### CODE REVIEW

File: packages/twenty-front/src/modules/context-store/components/ContextStoreViewIdEffect.tsx [hunk 1]
```diff
@@ -44,6 +42,9 @@ export const ContextStoreViewIdEffect = ({
   );
 
   useEffect(() => {
+    const viewsOnCurrentObject = views.filter(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/context-store/components/ContextStoreViewIdEffect.tsx:45]: this is the root cause of the issue

File: packages/twenty-front/src/modules/navigation/hooks/useLastVisitedView.ts [hunk 2]
```diff
@@ -48,22 +39,12 @@ export const useLastVisitedView = () => {
     objectNamePlural: string;
     viewId: string;
   }) => {
-    const fallbackObjectMetadataItem =
+    const objectMetadataItem =
       findActiveObjectMetadataItemByNamePlural(objectNamePlural);
 
-    if (isDefined(fallbackObjectMetadataItem)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/navigation/hooks/useLastVisitedView.ts:54]: simplifying as this logic is not useful anymore

File: packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx [hunk 3]
```diff
@@ -1,120 +1,34 @@
...
+export const QueryParamsViewIdEffect = ({
+  objectNamePlural,
+}: {
+  objectNamePlural: string;
+}) => {
   const [currentViewId, setCurrentViewId] = useRecoilComponentStateV2(
     currentViewIdComponentState,
   );
 
-  const { viewsOnCurrentObject } = useGetCurrentView();
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx:26]: this whole logic was duplicated with ContextStoreViewIdEffect. I'm just syncing currentViewId with contextStoreCurrentViewId for now but see TODO comment

File: packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx [hunk 4]
```diff
@@ -35,7 +38,8 @@ export const NavigationDrawerItemForObjectMetadataItem = ({
     objectMetadataItem.id,
   );
 
-  const viewId = lastVisitedViewId ?? objectMetadataViews[0]?.id;
+  const viewId =
+    viewIdQueryParam ?? lastVisitedViewId ?? objectMetadataViews[0]?.id;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx:42]: also fixing the navBar we should trust the url query param viewId first

File: packages/twenty-front/src/modules/context-store/components/ContextStoreViewIdEffect.tsx [hunk 5]
```diff
@@ -38,14 +36,18 @@ export const ContextStoreViewIdEffect = ({
...
-  const setContextStoreCurrentViewId = useSetRecoilComponentStateV2(
-    contextStoreCurrentViewIdComponentState,
-    objectNamePlural,
+  const [contextStoreCurrentViewId, setContextStoreCurrentViewId] =
+    useRecoilComponentStateV2(
+      contextStoreCurrentViewIdComponentState,
+      objectNamePlural,
+    );
+
+  const viewsOnCurrentObject = views.filter(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/context-store/components/ContextStoreViewIdEffect.tsx:45]: root cause of the issue

File: packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx [hunk 6]
```diff
@@ -1,120 +1,34 @@
...
-        setLastVisitedObjectMetadataItem(objectNamePlural);
-      }
-      if (!isDeeplyEqual(viewIdQueryParam, lastVisitedViewId)) {
-        setLastVisitedView({
-          objectNamePlural,
-          viewId: viewIdQueryParam,
-        });
+    if (isDefined(contextStoreCurrentViewId)) {
+      if (currentViewId !== contextStoreCurrentViewId) {
+        console.log('setting currentViewId', contextStoreCurrentViewId);
```
[the remark this answers is not in the document]
Comment (guillim) [reply packages/twenty-front/src/modules/views/components/QueryParamsViewIdEffect.tsx:27]: greptile is probably right on this one @charlesBochet
```suggestion
        console.log('setting currentViewId', contextStoreCurrentViewId);
```

**Review by guillim — APPROVED** [review]

**Review by guillim — COMMENTED** [review]
do not merge I may have found an issue

**Comment by guillim** [comment]
Screenshot 2025-02-12 at 15 47 17

I checked on main the problem does not exit

**Review by guillim — DISMISSED** [review]
found bug on my side when `objectNamePlural` is empty in function `useObjectNameSingularFromPlural`
