### PR TITLE
fix: update settings page for mobile viewport

### LINKED ISSUE #2313: Data Model page needs to be optimised for mobile viewports
## Bug Description

- In settings/Data Model,  the ojects page and Fields page are not optimised for mobile viewports.
- All the data models and columns should scroll for ease of use and future updates within table
- This is a Master issue related to
 #7847 
 #7490

## Current Behaviour

Screenshot 2024-10-30 at 12 36 29 PM

Screenshot 2024-10-30 at 12 36 42 PM

## Expected behavior
Screenshot 2024-10-30 at 12 40 45 PM

Screenshot 2024-10-30 at 12 56 05 PM

https://github.com/user-attachments/assets/6fee3481-dc90-46f5-8357-125e444f9427

### PR DESCRIPTION
**Pull request by harshit078**
## Description

- This PR fixes https://github.com/twentyhq/core-team-issues/issues/2313#issuecomment-4116380772
- Fixes Admin Panel Apps table, Data model table and Roles table
- made data model table scrollable for mobile viewport keeping name column fixed.

## Before

- Roles Table

Screenshot 2026-03-26 at 1 28 30 PM

- Admin Apps table

Screenshot 2026-03-26 at 1 28 12 PM

- Data Model table

https://github.com/user-attachments/assets/c48075c5-56dd-4b76-acd4-76330d6dab94

## After

- Roles Table

Screenshot 2026-03-26 at 1 23 19 PM

- Admin Apps table

Screenshot 2026-03-26 at 1 23 34 PM

- Data model Table

https://github.com/user-attachments/assets/fd44e353-cc7c-44cf-bda0-d2f3cd531f2e

### CODE REVIEW

File: packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx [hunk 1]
```diff
@@ -78,15 +87,12 @@ export const InformationBanner = ({
...
-            <StyledCloseButtonContainer>
-              <IconButton
-                Icon={IconX}
-                size="small"
-                variant="tertiary"
-                onClick={onClose}
-                ariaLabel={t`Close banner`}
-              />
-            </StyledCloseButtonContainer>
+            <StyledCloseButton
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx]: We should use the IconButton here and the we should apply same color as the button above (maybe we are just missing inverted)

File: packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderResizeHandler.tsx [hunk 2]
```diff
@@ -65,14 +60,12 @@ export const RecordTableHeaderResizeHandler = ({
...
-    !columnResizeDisabled && (
-      <StyledResizeHandler
-        className="cursor-col-resize"
-        role="separator"
-        onPointerDown={handlePointerDown}
-        isResizing={isResizing}
-        position={position}
-      />
-    )
+    <StyledResizeHandler
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableHeaderResizeHandler.tsx]: let's keep like it was

File: packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx [hunk 3]
```diff
@@ -9,9 +9,11 @@ import { useSetAtomComponentState } from '@/ui/utilities/state/jotai/hooks/useSe
 
 const StyledScrollWrapper = styled.div<{ autoHeight?: boolean }>`
   &.scroll-wrapper-x-enabled {
+    overflow-x: auto;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/scroll/components/ScrollWrapper.tsx]: we should revert that

**Review by charlesBochet — APPROVED** [review]
Thank you! I have reworked a bit other behaviors on mobile
