### PR TITLE
Consider `null` values as empty values for link fields

### LINKED ISSUE #11844: Record Page - domain url cannot is invisible in company regular view but not when editing
## Bug Description
i don't see the domain I entered creating the record with an API call 
Image

but I see it when editing the domain url
Image

and in the overall company view
Image

this does not happen for all companies of the workspace but it happens for ex if, by mistake, the domain input is domain.com, domain2.com in the same field "domain". So maybe this is bc the domain is not recognized as a domain? the true text is lydia-app.com

### PR DESCRIPTION
**Pull request by Devessier**
This pull request introduces changes to improve handling of nullable values in link-related data structures and simplifies field value generation logic. Key updates include adjustments to type definitions, utility functions, and component logic to support `null` values for links, along with the removal of the `generateDefaultFieldValue` function in favor of `generateEmptyFieldValue`.

There will be a few more follow-up Pull Requests.

---

Closes https://github.com/twentyhq/twenty/issues/11844

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx [hunk 1]
```diff
@@ -19,17 +19,28 @@ export const LinksFieldInput = ({
 }: LinksFieldInputProps) => {
   const { persistLinksField, fieldValue, fieldDefinition } = useLinksField();
 
-  const links = useMemo<{ url: string; label: string }[]>(
+  const links = useMemo<{ url: string; label: string | null }[]>(
     () =>
       [
-        fieldValue.primaryLinkUrl
+        isDefined(fieldValue.primaryLinkUrl)
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/LinksFieldInput.tsx:25]: isNonEmptyString?

**Comment by Devessier** [comment]
A test fails, I must check why.

CleanShot 2025-05-19 at 18 10 27@2x

File: packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx [hunk 2]
```diff
@@ -2,7 +2,7 @@ import { isNonEmptyString } from '@sniptt/guards';
 import { LinkType, RoundedLink, SocialLink } from 'twenty-ui/navigation';
 
 type LinkDisplayProps = {
-  value?: { url: string; label?: string };
+  value?: { url: string | null; label?: string | null };
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx:5]: Fine with me but here, I would force value to be defined and url to be defined too. 
We should cut the tree earlier: if value is not defined or url is not defined, there is no point rendering a LinkDisplay

Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx:5]: (neat)

File: packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx [hunk 3]
```diff
@@ -1,50 +1,43 @@
...
-          return {
-            url: absoluteUrl,
-            label: label || hostname,
-            type: checkUrlType(absoluteUrl),
-          };
-        }),
-    [value?.primaryLinkLabel, value?.primaryLinkUrl, value?.secondaryLinks],
-  );
+  const links = useMemo(() => {
+    if (!isDefined(value)) {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx:20]: this would avoid this

File: packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx [hunk 4]
```diff
@@ -1,50 +1,43 @@
...
 import {
   getAbsoluteUrlOrThrow,
   getUrlHostnameOrThrow,
   isDefined,
 } from 'twenty-shared/utils';
 import { LinkType, RoundedLink, SocialLink } from 'twenty-ui/navigation';
+import { checkUrlType } from '~/utils/checkUrlType';
 
 type LinksDisplayProps = {
   value?: FieldLinksValue;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx:15]: same here, value should be defined
(neat)

File: packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useScopedHotkeyCallback.ts [hunk 5]
```diff
@@ -8,7 +8,7 @@ import { logDebug } from '~/utils/logDebug';
 
 import { internalHotkeysEnabledScopesState } from '../states/internal/internalHotkeysEnabledScopesState';
 
-export const DEBUG_HOTKEY_SCOPE = false;
+export const DEBUG_HOTKEY_SCOPE = true;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useScopedHotkeyCallback.ts:11]: revert :)

**Review by charlesBochet — COMMENTED** [review]
Thank you, LGTM!
Regarding the test, it seems that we are passing the striped quote format somewhere (maybe using the isEmpty check you changed). For the record, defaultValue are string (or object of string for composite) that can be either a function (ex: "now") or a static value (ex: "'my_default'")

Not sure why we call isEmpty there but we should strip the additional single quote earlier (as single quotes are tied to defaultValue logic and not fieldvalue)

File: packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx (hunk 3 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx:20]: I can't make the `value` prop of the `LinksDisplay` component required as it's used in the `LinksFieldDisplay` where the `fieldValue` can be `undefined`.

CleanShot 2025-05-20 at 11 43 32@2x

File: packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx (hunk 2 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx:5]: I made the types stricter 👍

File: packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx (hunk 4 above)
Comment (Devessier) [reply packages/twenty-front/src/modules/ui/field/display/components/LinksDisplay.tsx:15]: As mentioned above, the value property must remain possibly `undefined`. This is also the case for the value of all the other field display components.

For example: 

CleanShot 2025-05-20 at 11 50 08@2x

**Comment by Devessier** [comment]
> Thank you, LGTM! Regarding the test, it seems that we are passing the striped quote format somewhere (maybe using the isEmpty check you changed). For the record, defaultValue are string (or object of string for composite) that can be either a function (ex: "now") or a static value (ex: "'my_default'")
> 
> Not sure why we call isEmpty there but we should strip the additional single quote earlier (as single quotes are tied to defaultValue logic and not fieldvalue)

I'm unsure about where I should move the stripping logic, @charlesBochet. The `isFieldValueEmpty` function is used at many places and I don't know where it's best to move the logic.

**Review by thomtrp — APPROVED** [review]
LGTM. Will let @charlesBochet double check!

**Review by charlesBochet — APPROVED** [review]
