### PR TITLE
Time line activity wrong type

### LINKED ISSUE #874: null id in note and task filters on combinedFindManyRecords
[sentry](https://twenty-v7.sentry.io/issues/6550364611/events/35142f2eb6494af6990fe9686e3c213b/?environment=prod&project=4507072499810304&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=next-event&sort=date&stream_index=18)

```
{
"operationName": "CombinedFindManyRecords",
"query": "query CombinedFindManyRecords($filterTask: TaskFilterInput, $filterNote: NoteFilterInput, $orderByTask: [TaskOrderByInput], $orderByNote: [NoteOrderByInput], $afterTask: String, $beforeTask: String, $firstTask: Int, $lastTask: Int, $afterNote: String, $beforeNote: String, $firstNote: Int, $lastNote: Int, $limitTask: Int, $limitNote: Int) {
  tasks(
    filter: $filterTask
    orderBy: $orderByTask
    after: $afterTask
    before: $beforeTask
    first: $firstTask
    last: $lastTask
    limit: $limitTask
  ) {
    edges {
      node {
        __typename
        id
        title
      }
      cursor
      __typename
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      __typename
    }
    totalCount
    __typename
  }
  notes(
    filter: $filterNote
    orderBy: $orderByNote
    after: $afterNote
    before: $beforeNote
    first: $firstNote
    last: $lastNote
    limit: $limitNote
  ) {
    edges {
      node {
        __typename
        id
        title
      }
      cursor
      __typename
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      __typename
    }
    totalCount
    __typename
  }
}",

"variables": {

"filterNote": {

"id": {

"in": [
null,
null
]
}
},

"filterTask": {

"id": {

"in": [
null,
null
]
}
}
}
}
```

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
Closes https://github.com/twentyhq/core-team-issues/issues/874

`TimeLineActivity` fields `` and `` were typed as required whereas in reality are nullable, resulting in the related sentry error.
Refactored the type then the related components in order to handle nullable use case

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/timeline-activities/hooks/useTimelineActivities.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { useObjectMetadataItem } from '@/object-metadata/hooks/useObjectMetadata
 import { CoreObjectNameSingular } from '@/object-metadata/types/CoreObjectNameSingular';
 import { generateDepthOneRecordGqlFields } from '@/object-record/graphql/utils/generateDepthOneRecordGqlFields';
 import { useFindManyRecords } from '@/object-record/hooks/useFindManyRecords';
+import { isDefined } from 'twenty-shared/utils';
 
 // do we need to test this?
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/activities/timeline-activities/hooks/useTimelineActivities.ts:11]: Indeed

File: packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts [hunk 2]
```diff
@@ -10,7 +11,17 @@ export type TimelineActivity = {
   properties: any;
   name: string;
   linkedRecordCachedName: string;
-  linkedRecordId: string;
-  linkedObjectMetadataId: string;
+  linkedRecordId: string | null;
+  linkedObjectMetadataId: string | null;
   __typename: 'TimelineActivity';
 } & Record<string, any>;
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts:17]: Unfortunalety I know, out of scope here

**Comment by prastoin** [comment]
> Inconsistent error handling in /packages/twenty-front/src/modules/activities/timeline-activities/rows/activity/components/EventRowActivity.tsx - throws error for null linkedRecordId before type guard

Love you

**Comment by prastoin** [comment]
@greptileai trigger

File: packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts [hunk 3]
```diff
@@ -10,7 +11,17 @@ export type TimelineActivity = {
...
+
+export type TimelineActivityWithRecord = TimelineActivity & {
+  linkedRecordId: string;
+  linkedObjectMetadataId: string;
+};
+
+export const isTimelineActivityWithRecord = (
+  el: TimelineActivity,
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts:25]: nit but I think we are avoiding shorthands such as `el`

File: packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts [hunk 4]
```diff
@@ -10,7 +11,17 @@ export type TimelineActivity = {
...
+  linkedObjectMetadataId: string | null;
   __typename: 'TimelineActivity';
 } & Record<string, any>;
+
+export type TimelineActivityWithRecord = TimelineActivity & {
+  linkedRecordId: string;
+  linkedObjectMetadataId: string;
+};
+
+export const isTimelineActivityWithRecord = (
```
Comment (ijreilly) [inline packages/twenty-front/src/modules/activities/timeline-activities/types/TimelineActivity.ts:24]: Nit: `hasLinkedRecord`? 
WithRecord is not very explicit when reading it the first time

**Review by ijreilly — APPROVED** [review]
code makes sense but I would like to understand where this is called in the product so we can test it is fixed !

**Comment by prastoin** [comment]
Unfortunately I'm unable to reproduce as this morning :(
[seeing](https://twenty-v7.sentry.io/issues/6550364611/events/35142f2eb6494af6990fe9686e3c213b/replays/?project=4507072499810304&selected_replay_index=2)

The error would come from `timelineActivity` note and task related that would not have any associated record

File: packages/twenty-front/src/modules/activities/timeline-activities/hooks/useTimelineActivities.ts [hunk 5]
```diff
@@ -41,7 +42,8 @@ export const useTimelineActivities = (
 
   const activityIds = timelineActivities
     .filter((timelineActivity) => timelineActivity.name.match(/note|task/i))
-    .map((timelineActivity) => timelineActivity.linkedRecordId);
+    .map((timelineActivity) => timelineActivity.linkedRecordId)
+    .filter(isDefined);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/activities/timeline-activities/hooks/useTimelineActivities.ts:46]: That's the fix
