### PR TITLE
Fix duplicated calendar events

### LINKED ISSUE #5159: Duplicated calendar events
# Current behavior

It appears that some events are getting duplicated when they're in different team members' calendars.

CleanShot 2024-04-24 at 22 19 42

The second event side panel is empty:

CleanShot 2024-04-24 at 22 19 13

# Desired Behavior

Have one event only! 

@Weiko any idea? Great for Experienced contributors?

### PR DESCRIPTION
**Pull request by bosiraphael**
Fix duplicated calendar events when two workspace members participate to the same event.

### CODE REVIEW

File: packages/twenty-server/src/modules/calendar/repositories/calendar-event.repository.ts [hunk 1]
```diff
@@ -97,8 +117,8 @@ export class CalendarEventRepository {
           iCalUID: string;
         }[]
       | undefined = await this.workspaceDataSourceService.executeRawQuery(
-      `SELECT id, "iCalUID" FROM ${dataSourceSchema}."calendarEvent" WHERE "id" = ANY($1)`,
-      [calendarEventIds],
+      `SELECT id, "iCalUID" FROM ${dataSourceSchema}."calendarEvent" WHERE "iCalUID" = ANY($1)`,
+      [iCalUIDs],
```
Comment (Weiko) [inline packages/twenty-server/src/modules/calendar/repositories/calendar-event.repository.ts:121]: LGTM but keep in mind that we can't make sure this is unique from the DB as of today 👍 (compared to calendarEventIds)

**Review by Weiko — APPROVED** [review]
