### PR TITLE
Fix webhook pages in Settings

### LINKED ISSUE #10822: "Invalid URL" on webhooks/api page
If you have an invalid webhook URL then the webhook/api page becomes completely unaccessible.

It seems legacy users have invalid webhook urls, and that it's still possible to create a webhook with an empty url (which is invalid)

### PR DESCRIPTION
**Pull request by charlesBochet**
## Context

Some users were able to set an empty URL as webhook targetUrl, which was breaking the Webhook List and Detail pages

## Fix
- Making sure to protect getHostNameOrThrow by isValidUrl
- rework webhook form to prevent creation of invalid webhooks

Fixes https://github.com/twentyhq/twenty/issues/10822

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/developers/hooks/useWebhookUpdateForm.ts [hunk 1]
```diff
@@ -35,7 +35,12 @@ export const useWebhookUpdateForm = ({
   const [formData, setFormData] = useState<WebhookFormData>({
     targetUrl: '',
     description: '',
-    operations: [],
+    operations: [
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/developers/hooks/useWebhookUpdateForm.ts:38]: adding a default for creation page too

**Review by Weiko — APPROVED** [review]
