### PR TITLE
fix: Minor bug in column scroll in mobile viewport 

### LINKED ISSUE #7447: Minor bug in column scroll in mobile viewport
## Bug Description

- When scrolling across the columns, the first letter of the input often gets displayed which hinders the design.
- Text input container when clicked outside and opened again in right Drawer makes the text  in ellipsis fashion even when text is small.

## Current Behaviour

https://github.com/user-attachments/assets/8ad1fa47-07a8-4dd5-8431-6246e7ad932d

https://github.com/user-attachments/assets/d5e947d6-b7d7-40a0-af85-9854a094c7bd

## Expected behavior

https://github.com/user-attachments/assets/94f113e1-dbf2-4551-b243-a25d6844c132

https://github.com/user-attachments/assets/791b83c1-9a12-4937-a11e-5f45dab1bcf6

### PR DESCRIPTION
**Pull request by harshit078**
> [!Note]
> - This PR fixes #7447

### CODE REVIEW

**Comment by charlesBochet** [comment]
@harshit078 Thanks for the issue AND the PR

I have some feedbacks / questions:
- Regarding the issue on the RecordTable, your fix works but the ideal fix would be to display the first column chip itself in a "compact mode" where we only see the icon. I would add a prop on top of the AvatarChip (isCompact), add a property to the  FieldContext isCompactDisplay and set it to true in the case of isMobile
- Regarding the other issue on the RightDrawer, I managed to reproduce it but I'm not sure to understand how it's happening (looks like the margin is still applied and mess with the design) but I'm not sure your fix is correct as it might break other behaviors, I'm double checking

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ const StyledInlineCellEditModeContainer = styled.div`
   display: flex;
   height: 24px;
 
-  margin-left: -${({ theme }) => theme.spacing(1)};
+  margin-left: ${({ theme }) => theme.spacing(1)};
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx:14]: changing it might break the alignment for other inline edit input

**Comment by charlesBochet** [comment]
Regarding my second point, it's indeed breaking the alignment of the inplace input:
image

(the placeholder of the edit input should be in the exact same spot as the display text)

I think there is something very wrong with the current implementation, I'm making a proposal in your PR

File: packages/twenty-front/src/loading/components/__stories__/PrefetchLoading.stories.tsx [hunk 2]
```diff
@@ -38,6 +38,6 @@ export const Default: Story = {
     await canvas.findByText('Tasks');
     await canvas.findByText('People');
     await canvas.findByText('Opportunities');
-    await canvas.findByText('My Customs');
+    await canvas.findByText('Rockets');
```
Comment (charlesBochet) [inline packages/twenty-front/src/loading/components/__stories__/PrefetchLoading.stories.tsx:41]: Fixing an unrelated story

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx [hunk 3]
```diff
@@ -24,15 +24,13 @@ import {
 type RecordInlineCellProps = {
   readonly?: boolean;
   loading?: boolean;
-  isCentered?: boolean;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx:27]: no need to drilldown props as we already have it from the context

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx [hunk 4]
```diff
@@ -1,17 +1,16 @@
...
 import { useContext } from 'react';
 import { createPortal } from 'react-dom';
 
-import { FieldContext } from '@/object-record/record-field/contexts/FieldContext';
-
 const StyledInlineCellEditModeContainer = styled.div`
   align-items: center;
 
   display: flex;
+  width: 100%;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx:11]: this is correct and ease positioning

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx [hunk 5]
```diff
@@ -34,21 +33,21 @@ type RecordInlineCellEditModeProps = {
...
 
   const { refs, floatingStyles } = useFloating({
-    placement: isCentered ? undefined : 'right-start',
+    placement: isCentered ? 'bottom' : 'bottom-start',
     middleware: [
       flip(),
       offset(
         isCentered
           ? {
-              mainAxis: -32,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellEditMode.tsx:46]: this was non sense :p

File: packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/__stories__/EventRowMainObjectUpdated.stories.tsx [hunk 6]
```diff
@@ -36,7 +36,7 @@ const meta: Meta<typeof EventRowMainObjectUpdated> = {
       },
     } as TimelineActivity,
     mainObjectMetadataItem: generatedMockObjectMetadataItems.find(
-      (item) => item.namePlural === 'person',
+      (item) => item.nameSingular === 'person',
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/activities/timelineActivities/rows/main-object/components/__stories__/EventRowMainObjectUpdated.stories.tsx:39]: non related too

**Review by charlesBochet — APPROVED** [review]
I will actually approve it as it looks not so bad regarding the table too! I still think we could implement something more robust but it still a good step forward

Thank you @harshit078 :)

**Comment by harshit078** [comment]
@charlesBochet The whole misalignment of RecordInline cell container started from #6899 where it was decided to reduce the width of container  which led to their current looking state.

**Comment by harshit078** [comment]
One more feature to work on would be to improve the overall snap and scroll behaviour for ismobile when scrolling across the table.

https://github.com/user-attachments/assets/aa36ca3e-830b-4493-a80a-cb0f95d1e86b

**Comment by charlesBochet** [comment]
> @charlesBochet The whole misalignment of RecordInline cell container started from #6899 where it was decided to reduce the width of container which led to their current looking state.

Yes but the issue was that the editModeContainer was a 0px container putted right before the displayMode which made very hard to properly align the floating inplace input. I have changed it to be absolutely positioned on top which give us more control!

Yes the we can do better regarding the snap, maybe some animation?

**Comment by harshit078** [comment]
Yes, I agree to your point on giving `position:absolute `to gain more control on cell container. Could we do` transition-  ease-in-out, scroll-behavior- smooth` or maybe something in the same direction. Whats your take @charlesBochet ?
