### PR TITLE
fix: relation and record chip height

### LINKED ISSUE #6756: Adjust relation chip height
# Current behavior

The height of the relation chips is 24px everywhere

CleanShot 2024-08-28 at 10 52 42

CleanShot 2024-08-28 at 11 28 01

# Desired Behavior

All relation chips height should be 20px

c1345a3d934e4ea201e496e275518d8be8796beaf52171372f87d1b88ff7be79

### PR DESCRIPTION
**Pull request by Nabhag8848**
# ISSUE 
- Closes #6756 

After Changes: 

https://github.com/user-attachments/assets/1885be11-b50a-4b05-afae-d2f02a403ad6

https://github.com/user-attachments/assets/edc6a913-95a6-4c75-8ec2-83e2c27fddb0

### CODE REVIEW

**Comment by Nabhag8848** [comment]
@Bonapara ready for review.

File: packages/twenty-ui/src/display/chip/components/Chip.tsx [hunk 1]
```diff
@@ -111,6 +111,10 @@ const StyledContainer = withTheme(styled.div<
 
   border-radius: ${({ theme, variant }) =>
     variant === ChipVariant.Rounded ? '50px' : theme.border.radius.sm};
+
+  &.relation-chip {
+    height: ${({ theme }) => theme.spacing(3)};
```
Comment (lucasbordeau) [inline packages/twenty-ui/src/display/chip/components/Chip.tsx:116]: Let's just modify the Chip component to `height: ${({ theme }) => theme.spacing(4)};` for all use cases.

Also for information, this pattern you used, using a class to modify the default behavior is not standard in Twenty, we prefer adding a prop like 'small' | 'big' and then convert this into the relevant CSS. 

But since here we just want to modify the Chip component we don't need it.

Comment (Nabhag8848) [reply packages/twenty-ui/src/display/chip/components/Chip.tsx:116]: Thanks, making changes, In Issue it was mentioned just relation chips that made me do changes conditionally as Chip Component is being used beyond that.

**Review by lucasbordeau — APPROVED** [review]
