### PR TITLE
Fix auth modal closing hotkey scopes

### LINKED ISSUE #1052: Hotkey scops aren't properly set when you come from the login screen
If you login and then try to use cmd+k directly it doesn't work. But if you refresh, it does.

Probably linked to the recenter refactoring where I made more things asynchronous in the app
@bosiraphael would be great if you can handle it since you know this area well. Thanks a lot!

### PR DESCRIPTION
**Pull request by bosiraphael**
The auth modal is a particular modal because it is the only one that is opened in an effect (because its opening depends on the location).

After the hotkey scopes and the modal refactoring, we are now force to call `openModal` and `closeModal` to open and close the modals. Here, the `closeModal` wasn't called, but the modal was simply unmounted. The global hotkeys were then disabled because the modal was still in the focus stack.

Fixes [#1052](https://github.com/twentyhq/core-team-issues/issues/1052#event-17916955590)

### CODE REVIEW

File: packages/twenty-front/src/modules/auth/components/AuthModalMountEffect.tsx [hunk 1]
```diff
@@ -4,11 +4,15 @@ import { useEffect } from 'react';
...
 export const AuthModalMountEffect = () => {
-  const { openModal } = useModal();
+  const { openModal, closeModal } = useModal();
 
   useEffect(() => {
     openModal(AUTH_MODAL_ID);
-  }, [openModal]);
+
+    return () => {
+      closeModal(AUTH_MODAL_ID);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/components/AuthModalMountEffect.tsx:14]: add TODO to explain we should not do that

**Review by charlesBochet — APPROVED** [review]
