### PR TITLE
Refacto views

### LINKED ISSUE #10253: [BUG] Infinite loop when creating a view from a filtered view
## Bug Description

When creating a view from an already filtered one makes the browser crash

## Expected behavior

It should create a new view

### PR DESCRIPTION
**Pull request by charlesBochet**
In this huge (sorry!) PR:
- introducing objectMetadataItem in contextStore instead of objectMetadataId which is more convenient
- splitting some big hooks into smaller parts to avoid re-renders
- removing Effects to avoid re-renders (especially onViewChange)
- making the view prefetch separate from favorites to avoid re-renders
- making the view prefetch load a state and add selectors on top of it to avoir re-renders

As a result, the performance is WAY better (I suspect the favorite implementation to trigger a lot of re-renders unfortunately). 
However, we are still facing a random app freeze on view creation. I could not investigate the root cause. As this seems to be already there in the precedent release, we can move forward but this seems a urgent follow up to me ==> EDIT: I've found the root cause after a few ours of deep dive... an infinite loop in RecordTableNoRecordGroupBodyEffect...

prastoin edit: close https://github.com/twentyhq/twenty/issues/10253

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerGater.tsx [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+import { useRecoilCallback, useRecoilValue } from 'recoil';
+import { capitalize } from 'twenty-shared';
+
+const StyledIndexContainer = styled.div`
+  display: flex;
+  height: 100%;
+  width: 100%;
+`;
+
+export const RecordIndexContainerGater = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexContainerGater.tsx:29]: Adding this "Gater" to introduce an intermediate level to avoid re-renders

File: packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexLoadBaseOnContextStoreEffect.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import { contextStoreCurrentViewIdComponentState } from '@/context-store/states/contextStoreCurrentViewIdComponentState';
+import { useLoadRecordIndexStates } from '@/object-record/record-index/hooks/useLoadRecordIndexStates';
+import { prefetchViewFromViewIdFamilySelector } from '@/prefetch/states/selector/prefetchViewFromViewIdFamilySelector';
+import { useRecoilComponentValueV2 } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentValueV2';
+import { useEffect, useState } from 'react';
+import { useRecoilValue } from 'recoil';
+import { isDefined } from 'twenty-shared';
+
+export const RecordIndexLoadBaseOnContextStoreEffect = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexLoadBaseOnContextStoreEffect.tsx:9]: I have introduced this effect for now but I have voluntarily put everything into a loadRecordIndexStates hook. I think we would like to load this from the PageChangeEffect at some point. open to discussion

File: packages/twenty-front/src/modules/object-record/record-table/hooks/useSetTableColumns.ts [hunk 3]
```diff
@@ -0,0 +1,33 @@
+import { FieldMetadata } from '@/object-record/record-field/types/FieldMetadata';
+import { tableColumnsComponentState } from '@/object-record/record-table/states/tableColumnsComponentState';
+import { ColumnDefinition } from '@/object-record/record-table/types/ColumnDefinition';
+import { getSnapshotValue } from '@/ui/utilities/state/utils/getSnapshotValue';
+import { useRecoilCallback } from 'recoil';
+import { isDeeplyEqual } from '~/utils/isDeeplyEqual';
+
+export const useSetTableColumns = () => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/hooks/useSetTableColumns.ts:8]: moved from useRecordTable

File: packages/twenty-front/src/modules/prefetch/constants/PrefetchConfig.ts [hunk 4]
```diff
@@ -12,10 +11,6 @@ export const PREFETCH_CONFIG: Record<
     operationSignatureFactory: RecordGqlOperationSignatureFactory;
   }
 > = {
-  ALL_VIEWS: {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/prefetch/constants/PrefetchConfig.ts:15]: removing ALL Views from here. Prefetch was a bad idea overall

File: packages/twenty-front/src/modules/favorites/states/selectors/favoriteViewsWithMinimalDataSelector.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
+import { prefetchViewsState } from '@/prefetch/states/prefetchViewsState';
+import { View } from '@/views/types/View';
+import { selector } from 'recoil';
+
+export const favoriteViewsWithMinimalDataSelector = selector<
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/favorites/states/selectors/favoriteViewsWithMinimalDataSelector.ts:5]: selector designed for favorites that need to have minimal info on views (to avoid re-renders too)

**Comment by charlesBochet** [comment]
image

File: packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx [hunk 6]
```diff
@@ -26,8 +25,8 @@ export const RecordShowActionMenu = ({
   objectNameSingular: string;
   handleFavoriteButtonClick: () => void;
 }) => {
-  const contextStoreCurrentObjectMetadataId = useRecoilComponentValueV2(
-    contextStoreCurrentObjectMetadataIdComponentState,
+  const contextStoreCurrentObjectMetadataItem = useRecoilComponentValueV2(
+    contextStoreCurrentObjectMetadataItemComponentState,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx:29]: ***Question:*** Went from an atomic ID listener to the whole objectMetadataItem ?

File: packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx [hunk 7]
```diff
@@ -42,7 +41,7 @@ export const RecordShowActionMenu = ({
 
   return (
     <>
-      {contextStoreCurrentObjectMetadataId && (
+      {contextStoreCurrentObjectMetadataItem && (
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx:44]: False positive

File: packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+export const prefetchViewsFromObjectMetadataItemFamilySelector = selectorFamily<
+  View[],
+  { objectMetadataItemId: string }
+>({
+  key: 'prefetchViewsFromObjectMetadataItemFamilySelector',
+  get:
+    ({ objectMetadataItemId }) =>
+    ({ get }) => {
+      const views = get(prefetchViewsState);
+      return views.filter(
```
Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts:14]: ***Remark:*** Unless I'm mistaken we should be using find here ? Here "falsy" value would be empty array which can be misleading to the `prefetchViewsFromObjectMetadataItemFamilySelector` consumer

Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts:14]: ***Remark:*** Might return empty array in case no matching objectMetadata is found within `prefetchViewsState`

File: packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts [hunk 9]
```diff
@@ -0,0 +1,15 @@
...
+
+export const prefetchViewIdsFromObjectMetadataItemFamilySelector =
+  selectorFamily<string[], { objectMetadataItemId: string }>({
+    key: 'prefetchViewIdsFromObjectMetadataItemFamilySelector',
+    get:
+      ({ objectMetadataItemId }) =>
+      ({ get }) => {
+        const views = get(prefetchViewsState);
+        return views
+          .filter((view) => view.objectMetadataId === objectMetadataItemId)
```
Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts:12]: ***Recoil newbie question:*** Could we and is it recommended to use nested recoil selectors ? ( in this case overkill but could have used `prefetchViewsFromObjectMetadataItemFamilySelector`)

Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts:12]: ***Recoil newbie question:*** Could we and is it recommended to use nested recoil selectors ? ( in this case overkill but could have used `prefetchViewsFromObjectMetadataItemFamilySelector`)

File: packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx [hunk 10]
```diff
@@ -2,25 +2,17 @@ import { RegisterRecordActionEffect } from '@/action-menu/actions/record-actions
...
 export const RecordActionMenuEntriesSetter = () => {
-  const contextStoreCurrentObjectMetadataId = useRecoilComponentValueV2(
-    contextStoreCurrentObjectMetadataIdComponentState,
-  );
-
-  const objectMetadataItems = useRecoilValue(objectMetadataItemsState);
-
-  const objectMetadataItem = objectMetadataItems.find(
-    (item) => item.id === contextStoreCurrentObjectMetadataId,
+  const contextStoreCurrentObjectMetadataItem = useRecoilComponentValueV2(
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx:14]: Is there any risk that this state get desynchronized from the objectMetadataItems state ? Could this be a component selector instead ? Based on the id ?

File: packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+
+  const { objectMetadataItems } = useObjectMetadataItems();
+
+  const findAllViewsOperationSignature = findAllViewsOperationSignatureFactory({
+    objectMetadataItem: objectMetadataItems.find(
+      (item) => item.nameSingular === CoreObjectNameSingular.View,
+    ),
+  });
+
+  const { records } = useFindManyRecords({
```
Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx:29]: ***Suggestion:*** passing `View` predicate to `useFindManyRecords` would avoid force casting in below useEffect
```ts
  const { records } = useFindManyRecords<View>({
  //...
  useEffect(() => {
    if (isDefined(views) && !isPersistingViewFields) {
      setPrefetchViewsState(views);
    }
  }, [isPersistingViewFields, records, setPrefetchViewsState]);
```

File: packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+  });
+
+  const setPrefetchViewsState = useRecoilCallback(
+    ({ set, snapshot }) =>
+      (views: View[]) => {
+        const existingViews = snapshot
+          .getLoadable(prefetchViewsState)
+          .getValue();
+
+        if (!isDeeplyEqual(existingViews, views)) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx:43]: ***Huge nitpick:*** Inconsistent early return check ( looking `useSetTableColumns` )

File: packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx (hunk 10 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/action-menu/actions/record-actions/components/RecordActionMenuEntriesSetter.tsx:14]: good idea!

File: packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx (hunk 6 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/action-menu/components/RecordShowActionMenu.tsx:29]: yes, because the DevXP was painful (always have to find the objectMetadataItem from the Id). Another possibility is to create a hook or a selector on top of that. Which would actually be better I believe

File: packages/twenty-front/src/modules/context-store/components/MainContextStoreProvider.tsx [hunk 13]
```diff
@@ -48,29 +46,27 @@ export const MainContextStoreProvider = () => {
...
   const { getLastVisitedViewIdFromObjectNamePlural } = useLastVisitedView();
 
   const lastVisitedViewId = getLastVisitedViewIdFromObjectNamePlural(
     objectMetadataItem?.namePlural ?? '',
   );
 
-  const viewsOnCurrentObject = views.filter(
-    (view) => view.objectMetadataId === objectMetadataItem?.id,
+  const indexViewId = useRecoilValue(
+    prefetchIndexViewIdFromObjectMetadataItemFamilySelector({
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/context-store/components/MainContextStoreProvider.tsx:64]: prefetched ?

File: packages/twenty-front/src/modules/context-store/hooks/useContextStoreObjectMetadataItemOrThrow.ts [hunk 14]
```diff
@@ -0,0 +1,17 @@
+import { contextStoreCurrentObjectMetadataItemComponentState } from '@/context-store/states/contextStoreCurrentObjectMetadataItemComponentState';
+import { useRecoilComponentValueV2 } from '@/ui/utilities/state/component-state/hooks/useRecoilComponentValueV2';
+
+export const useContextStoreObjectMetadataItemOrThrow = (
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/context-store/hooks/useContextStoreObjectMetadataItemOrThrow.ts:4]: I really think that should be a convention to add "OrThrow" as a suffix because throwing in React is not conventionnal, it should be reminded in the naming.

File: packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts [hunk 15]
```diff
@@ -36,12 +33,13 @@ export const useFindManyRecordsSelectedInContextStore = ({
   const queryFilter = computeContextStoreFilters(
     contextStoreTargetedRecordsRule,
     contextStoreFilters,
-    objectMetadataItem,
+    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+    objectMetadataItem!,
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts:37]: We should never resort to non-null assertion, it's like using any.

Comment (charlesBochet) [reply packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts:37]: yes sorry, I was testing stuff and forgot about it!
I have introduced another tooling since

File: packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts [hunk 16]
```diff
@@ -14,12 +13,10 @@ export const useFindManyRecordsSelectedInContextStore = ({
   instanceId?: string;
   limit?: number;
 }) => {
-  const objectMetadataId =
-    useContextStoreCurrentObjectMetadataIdOrThrow(instanceId);
-
-  const { objectMetadataItem } = useObjectMetadataItemById({
-    objectId: objectMetadataId,
-  });
+  const objectMetadataItem = useRecoilComponentValueV2(
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/context-store/hooks/useFindManyRecordsSelectedInContextStore.ts:16]: Can't we use useContextStoreObjectMetadataItemOrThrow here ? 

Or else, how can we handle the fact that objectMetadataItem is undefined, let's imagine that this hook renders somewhere `contextStoreCurrentObjectMetadataItemComponentState` isn't initialized yet.

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts [hunk 17]
```diff
@@ -22,16 +22,23 @@ export const sortFavorites = (
     objectNameSingular: string,
   ) => ObjectRecordIdentifier,
   hasLinkToShowPage: boolean,
-  views: View[],
+  views: Pick<View, 'id' | 'name' | 'objectMetadataId' | 'icon'>[],
```
Comment (prastoin) [inline packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:25]: ***Suggestion:*** Would create an explicit type
Should also keep in mind that `id` here is typed as any for the moment due to Scarlars permissive definition

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts [hunk 18]
```diff
@@ -22,16 +22,23 @@ export const sortFavorites = (
...
     .map((favorite) => {
       if (isDefined(favorite.viewId) && isDefined(favorite.workspaceMemberId)) {
-        const { labelPlural, view } = getObjectMetadataLabelPluralFromViewId(
-          views,
+        const view = views.find((view) => view.id === favorite.viewId);
+
+        if (!isDefined(view)) {
+          return {
+            ...favorite,
+          } as ProcessedFavorite;
```
Comment (prastoin) [inline packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:36]: ***Question:*** Why force casting to `ProcessedFavorite` here ? Unless I'm mistaken it has not overlap with `Favorite`

File: packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts [hunk 19]
```diff
@@ -1,19 +1,19 @@
...
-import { View } from '@/views/types/View';
 import { useMemo } from 'react';
 import { useRecoilValue } from 'recoil';
 import { FieldMetadataType } from '~/generated-metadata/graphql';
 import { usePrefetchedFavoritesData } from './usePrefetchedFavoritesData';
 
 export const useFavorites = () => {
   const { favorites } = usePrefetchedFavoritesData();
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
+  const favoriteViewsWithMinimalData = useRecoilValue(
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/favorites/hooks/useFavorites.ts:14]: MinimalData seems too vague as a naming, can't we have something more self-explanatory ?

File: packages/twenty-front/src/modules/favorites/hooks/useFavoritesByFolder.ts [hunk 20]
```diff
@@ -7,12 +9,13 @@ export const useFavoritesByFolder = () => {
   const { favorites } = usePrefetchedFavoritesData();
   const { favoriteFolders } = usePrefetchedFavoritesFoldersData();
   const {
-    views,
     objectMetadataItems,
     getObjectRecordIdentifierByNameSingular,
     favoriteRelationFields,
   } = useFavoritesMetadata();
 
+  const prefetchViews = useRecoilValue(prefetchViewsState);
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/favorites/hooks/useFavoritesByFolder.ts:17]: prefetched ? otherwise seems like a function naming

File: packages/twenty-front/src/modules/favorites/hooks/useSortedFavorites.ts [hunk 21]
```diff
@@ -1,32 +1,35 @@
...
 export const useSortedFavorites = () => {
   const { favorites, workspaceFavorites } = usePrefetchedFavoritesData();
   const {
-    views,
     objectMetadataItems,
     getObjectRecordIdentifierByNameSingular,
     favoriteRelationFields,
   } = useFavoritesMetadata();
 
+  const prefetchViews = useRecoilValue(prefetchViewsState);
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/favorites/hooks/useSortedFavorites.ts:16]: Same

File: packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts [hunk 22]
```diff
@@ -4,18 +4,15 @@ import { useGetObjectRecordIdentifierByNameSingular } from '@/object-metadata/ho
...
 import { useMemo } from 'react';
 import { useRecoilValue } from 'recoil';
 import { FieldMetadataType } from '~/generated-metadata/graphql';
 import { usePrefetchedFavoritesData } from './usePrefetchedFavoritesData';
 
 export const useWorkspaceFavorites = () => {
   const { workspaceFavorites } = usePrefetchedFavoritesData();
-
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
+  const prefetchViews = useRecoilValue(prefetchViewsState);
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/favorites/hooks/useWorkspaceFavorites.ts:15]: Same

File: packages/twenty-front/src/modules/favorites/states/selectors/favoriteViewsWithMinimalDataSelector.ts (hunk 5 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/favorites/states/selectors/favoriteViewsWithMinimalDataSelector.ts:5]: Could we use viewsForMenuItem or something that tells us what the props curation is for ?

File: packages/twenty-front/src/modules/favorites/utils/getObjectMetadataLabelPluralFromViewId.ts [hunk 23]
```diff
@@ -4,23 +4,13 @@ import { isDefined } from 'twenty-shared';
 
 type ReturnType = {
   labelPlural: string;
-  view: View | null;
+  view: Pick<View, 'id' | 'name' | 'objectMetadataId'>;
 };
 
 export const getObjectMetadataLabelPluralFromViewId = (
-  views: View[],
+  view: Pick<View, 'id' | 'name' | 'objectMetadataId'>,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/favorites/utils/getObjectMetadataLabelPluralFromViewId.ts:11]: ***Question:*** Seems to be missing Icon here ? would extend to Omit icon from a reusable type `FavoriteMinimalView`

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts (hunk 17 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:25]: Agree, with the same idea for naming, ViewForMenuItem or something similar

File: packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts [hunk 24]
```diff
@@ -15,7 +13,7 @@ export const useDefaultHomePagePath = () => {
   const currentUser = useRecoilValue(currentUserState);
   const { activeObjectMetadataItems, alphaSortedActiveObjectMetadataItems } =
     useFilteredObjectMetadataItems();
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
+  const prefetchViews = useRecoilValue(prefetchViewsState);
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/navigation/hooks/useDefaultHomePagePath.ts:16]: prefetched

File: packages/twenty-front/src/modules/navigation/hooks/useSetLastVisitedViewForObjectMetadataNamePlural.ts [hunk 25]
```diff
@@ -20,7 +15,7 @@ export const useSetLastVisitedViewForObjectMetadataNamePlural = () => {
         objectNamePlural: string;
         viewId: string;
       }) => {
-        await findManyRecords();
+        const views = snapshot.getLoadable(prefetchViewsState).getValue();
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/navigation/hooks/useSetLastVisitedViewForObjectMetadataNamePlural.ts:18]: Same

File: packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useDeleteCombinedViewFilterGroup.ts [hunk 26]
```diff
@@ -24,11 +24,10 @@ export const useDeleteCombinedViewFilterGroup = (
     );
 
   const currentViewIdCallbackState = useRecoilComponentCallbackStateV2(
-    currentViewIdComponentState,
-    viewBarComponentId,
+    contextStoreCurrentViewIdComponentState,
   );
 
-  const { getViewFromCache } = useGetViewFromCache();
+  const { getViewFromPrefetchState } = useGetViewFromPrefetchState();
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useDeleteCombinedViewFilterGroup.ts:30]: useGetPrefetchedView ?

Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useDeleteCombinedViewFilterGroup.ts:30]: State should be avoiding in naming other than for state naming.

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts [hunk 27]
```diff
@@ -0,0 +1,281 @@
...
+
+        const filterableFieldMetadataItems = snapshot
+          .getLoadable(
+            availableFieldMetadataItemsForFilterFamilySelector({
+              objectMetadataItemId: objectMetadataItem.id,
+            }),
+          )
+          .getValue();
+
+        onViewFieldsChange(view.viewFields, objectMetadataItem, recordIndexId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts:195]: ***Concerns:*** passing `view.viewFields` typed as `ViewFields[]` to `onViewFieldsChange` that expects `ViewGroup[]`

Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts:195]: That hook is doing too much and those handlers shouldn't be called like that, seems like a complexity zone that could be refactored, if it works for now let's keep it like that but let's think about how we could break this down.

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts [hunk 28]
```diff
@@ -0,0 +1,281 @@
...
+            instanceId: recordIndexId,
+          }),
+          mapViewSortsToSorts(view.viewSorts, sortDefinitions),
+        );
+        setRecordIndexSorts(
+          mapViewSortsToSorts(view.viewSorts, sortDefinitions),
+        );
+        setRecordIndexViewType(view.type);
+        setRecordIndexViewKanbanFieldMetadataIdState(
+          view.kanbanFieldMetadataId,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexStates.ts:246]: ***Remark:*** `view.kanbanFieldMetadataId` is maked as deprecated

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts [hunk 29]
```diff
@@ -22,16 +22,23 @@ export const sortFavorites = (
     objectNameSingular: string,
   ) => ObjectRecordIdentifier,
   hasLinkToShowPage: boolean,
-  views: View[],
+  views: Pick<View, 'id' | 'name' | 'objectMetadataId' | 'icon'>[],
   objectMetadataItems: ObjectMetadataItem[],
```
Comment (prastoin) [inline packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:26]: ***Reminder:*** Should refactor `sortFavorites` arg signature to use record instead of args list

File: packages/twenty-front/src/modules/object-record/record-table/hooks/useSetTableColumns.ts [hunk 30]
```diff
@@ -0,0 +1,33 @@
...
+  const setTableColumns = useRecoilCallback(
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-table/hooks/useSetTableColumns.ts:9]: This should be refactored after advanced filters, good point for extracting in a separate hook.

File: packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableNoRecordGroupBodyEffect.tsx [hunk 31]
```diff
@@ -141,8 +143,11 @@ export const RecordTableNoRecordGroupBodyEffect = () => {
       return;
     }
 
-    findManyRecords();
-  }, [currentWorkspaceMember, findManyRecords]);
+    if (!hasInitialized) {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableNoRecordGroupBodyEffect.tsx:146]: Nice

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts (hunk 29 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:26]: This function has a weird typing overall
ReturnType is only based on force cast of `ProcessedFavorite`

File: packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx [hunk 32]
```diff
@@ -0,0 +1,59 @@
...
+  });
+
+  const { records } = useFindManyRecords({
+    objectNameSingular: CoreObjectNameSingular.View,
+    filter: findAllViewsOperationSignature.variables.filter,
+    recordGqlFields: findAllViewsOperationSignature.fields,
+    skip: !currentUser || isWorkspaceSuspended,
+  });
+
+  const setPrefetchViewsState = useRecoilCallback(
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/prefetch/components/PrefetchRunViewQueryEffect.tsx:36]: We should avoid using the suffix state, it's like using Type for naming a type, it's redundant.

File: packages/twenty-front/src/testing/jest/JestContextStoreSetter.tsx [hunk 33]
```diff
@@ -55,20 +55,21 @@ export const JestContextStoreSetter = ({
...
     setContextStoreNumberOfSelectedRecords(contextStoreNumberOfSelectedRecords);
     setcontextStoreFiltersComponentState(contextStoreFilters);
 
     setIsLoaded(true);
   }, [
     setContextStoreTargetedRecordsRule,
-    setContextStoreCurrentObjectMetadataId,
+    setContextStoreCurrentObjectMetadataItem,
     contextStoreTargetedRecordsRule,
     contextStoreCurrentObjectMetadataId,
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/testing/jest/JestContextStoreSetter.tsx:67]: Good bot
Not wrong but out of scope a little bit

File: packages/twenty-front/src/testing/decorators/PrefetchLoadedDecorator.tsx [hunk 34]
```diff
@@ -5,17 +5,13 @@ import { prefetchIsLoadedFamilyState } from '@/prefetch/states/prefetchIsLoadedF
 import { PrefetchKey } from '@/prefetch/types/PrefetchKey';
 
 export const PrefetchLoadedDecorator: Decorator = (Story) => {
-  const setAreViewsPrefetched = useSetRecoilState(
```
Comment (prastoin) [inline packages/twenty-front/src/testing/decorators/PrefetchLoadedDecorator.tsx:8]: ***Question:*** Maybe we should create a new decorator for tests that needs to pre-set views state ?

File: packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts (hunk 8 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts:14]: Is this a problem ? We should allow React to render without blocking or throwing because some data may be loading or fetching and the app should be allowed to render multiple times with empty arrays, undefined values, etc.

File: packages/twenty-front/src/modules/views/view-picker/components/ViewPickerFavoriteFoldersDropdown.tsx [hunk 35]
```diff
@@ -1,21 +1,23 @@
...
 export const ViewPickerFavoriteFoldersDropdown = () => {
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
   const [viewPickerReferenceViewId] = useRecoilComponentStateV2(
     viewPickerReferenceViewIdComponentState,
   );
 
-  const view = views.find((view) => view.id === viewPickerReferenceViewId);
+  const view = useRecoilValue(
+    prefetchViewFromViewIdFamilySelector({
+      viewId: viewPickerReferenceViewId ?? '',
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/view-picker/components/ViewPickerFavoriteFoldersDropdown.tsx:18]: ***Remark:*** Not the first occurence of passing an empty string to this selector
Maybe we should create a specific one that could explicitly accept `nullish` `viewId` ?

File: packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts (hunk 18 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/favorites/utils/sortFavorites.ts:36]: who knows? :D

File: packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx [hunk 36]
```diff
@@ -15,7 +13,7 @@ type BooleanDisplayProps = {
 };
 
 export const BooleanDisplay = ({ value }: BooleanDisplayProps) => {
-  if (!isDefined(value)) {
+  if (value === null || value === undefined) {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx:16]: Why ? Is it different than !isDefined ?

File: packages/twenty-front/src/modules/views/view-picker/components/ViewPickerFavoriteFoldersDropdown.tsx (hunk 35 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/views/view-picker/components/ViewPickerFavoriteFoldersDropdown.tsx:18]: I think I would prefer introduce a hook useContextStoreViewIdOrThrow to force the caller to take a decision

File: packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts [hunk 37]
```diff
@@ -1,45 +1,31 @@
...
-    closeTypeDropdown();
-    closeViewPickerDropdown();
-  }, [
-    closeKanbanFieldDropdown,
-    closeTypeDropdown,
-    closeViewPickerDropdown,
-    setViewPickerIsPersisting,
-    setViewPickerMode,
-  ]);
+    closeDropdown(VIEW_PICKER_KANBAN_FIELD_DROPDOWN_ID);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts:25]: ***Note:*** We should strictly typed as much as possible any static occurences of `specificComponentId`, as I guess there're also dynamic dropdown ids

File: packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx (hunk 36 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx:16]: because of storybook build failing:
BooleanDisplay is in vyw + using twenty-shared, this seems to be an issue currently. We should investigate but I'm protecting the devXP

File: packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts (hunk 37 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts:25]: we don't want to type from the inside as the dropdown is a lower layer component that should not take dependency on the app.
In this case we could introduce an enum
ViewDropdownsInstanceId to help the devXp

File: packages/twenty-front/src/modules/views/hooks/useGetViewFromPrefetchState.ts [hunk 38]
```diff
@@ -0,0 +1,24 @@
+import { prefetchViewFromViewIdFamilySelector } from '@/prefetch/states/selector/prefetchViewFromViewIdFamilySelector';
+import { useRecoilCallback } from 'recoil';
+
+export const useGetViewFromPrefetchState = () => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/views/hooks/useGetViewFromPrefetchState.ts:4]: useGetPrefectedView ?

File: packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts (hunk 37 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/views/view-picker/hooks/useCloseAndResetViewPicker.ts:25]: > we don't want to type from the inside as the dropdown is a lower layer component that should not take dependency on the app.

We could add an abstraction layer over it scoped to the app or add a TypeScript generic to the `closeDropdown` to make it generic as possible

File: packages/twenty-front/src/modules/views/utils/mapViewFiltersToFilters.ts [hunk 39]
```diff
@@ -18,9 +18,8 @@ export const mapViewFiltersToFilters = (
       );
 
       if (!isDefined(availableFieldMetadataItem)) {
-        throw new Error(
-          `Field metadata item not found for view filter ${viewFilter.id} and field metadata id ${viewFilter.fieldMetadataId}`,
-        );
+        // Todo: we we don't throw an error yet as we have race condition on view change
```
[the remark this answers is not in the document]
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/views/utils/mapViewFiltersToFilters.ts:21]: Ok

File: packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts (hunk 8 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewsFromObjectMetadataItemFamilySelector.ts:14]: Not a problem ! Was wondering if we could return `null/undefined` instead of an empty array to explicitly tell the consumer that this function "could fail", but you're right I think it's up to the caller to handle an empty array return value.

Anyway will always prefer simplifying typing by having an empty array instead of undefined so my remark was dumb !

File: packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts (hunk 9 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/prefetch/states/selector/prefetchViewIdsFromObjectMetadataItemFamilySelector.ts:12]: Would it make sense here to use the `prefetchViewsFromObjectMetadataItemFamilySelector` selector in order to retrieve objectMetadaItem views ? I feel like it's redundant states access even if very cheap to perform

File: packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx (hunk 36 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/ui/field/display/components/BooleanDisplay.tsx:16]: What kind of error had you when building over this ? Emotion.styled is not a function one ?

**Review by lucasbordeau — COMMENTED** [review]
For naming I would suggest : 
- Prefetched when we talk about values 
- Removing state suffix

File: packages/twenty-front/src/modules/views/hooks/useUpsertCombinedViewSorts.ts [hunk 40]
```diff
@@ -53,7 +52,7 @@ export const useUpsertCombinedViewSorts = (viewBarComponentId?: string) => {
           return;
         }
 
-        const currentView = await getViewFromCache(currentViewId);
+        const currentView = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useUpsertCombinedViewSorts.ts:55]: ***Nitpick:*** Useless `await`

File: packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewGroups.ts [hunk 41]
```diff
@@ -31,7 +31,7 @@ export const useSaveCurrentViewGroups = (viewBarComponentId?: string) => {
           return;
         }
 
-        const view = await getViewFromCache(currentViewId);
+        const view = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewGroups.ts:34]: ***Nitpick:*** useless `await`

File: packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewGroups.ts [hunk 42]
```diff
@@ -31,7 +31,7 @@ export const useSaveCurrentViewGroups = (viewBarComponentId?: string) => {
...
 
         if (isUndefinedOrNull(view)) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewGroups.ts:36]: ***Nitpick:*** Could now become `isDefined`

File: packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFiltersAndSorts.ts [hunk 43]
```diff
@@ -77,7 +77,7 @@ export const useSaveCurrentViewFiltersAndSorts = (
           unsavedToUpsertViewSortsCallbackState({ viewId }),
         );
 
-        const view = await getViewFromCache(viewId);
+        const view = await getViewFromPrefetchState(viewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFiltersAndSorts.ts:80]: ***Nitpick:*** useless await

File: packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFiltersAndSorts.ts [hunk 44]
```diff
@@ -123,7 +123,7 @@ export const useSaveCurrentViewFiltersAndSorts = (
           unsavedToUpsertViewFilterGroupsCallbackState({ viewId }),
         );
 
-        const view = await getViewFromCache(viewId);
+        const view = await getViewFromPrefetchState(viewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFiltersAndSorts.ts:126]: ***Nitpick:*** useless await

File: packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFields.ts [hunk 45]
```diff
@@ -37,9 +31,9 @@ export const useSaveCurrentViewFields = (viewBarComponentId?: string) => {
           return;
         }
 
-        set(isPersistingViewFieldsCallbackState, true);
+        set(isPersistingViewFieldsState, true);
 
-        const view = await getViewFromCache(currentViewId);
+        const view = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useSaveCurrentViewFields.ts:36]: ***Nitpick:*** useless await

File: packages/twenty-front/src/modules/views/hooks/useGetCurrentView.ts [hunk 46]
```diff
@@ -29,42 +29,46 @@ export const useGetCurrentView = (viewBarInstanceId?: string) => {
...
-    instanceId,
+    contextStoreCurrentViewIdComponentState,
   );
 
-  const viewObjectMetadataId = useRecoilComponentValueV2(
-    viewObjectMetadataIdComponentState,
-    instanceId,
+  const indexViewId = useRecoilValue(
+    prefetchIndexViewIdFromObjectMetadataItemFamilySelector({
+      objectMetadataItemId: objectMetadataItem.id,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useGetCurrentView.ts:40]: same

File: packages/twenty-front/src/modules/views/hooks/useDeleteCombinedViewFilters.ts [hunk 47]
```diff
@@ -50,7 +50,7 @@ export const useDeleteCombinedViewFilters = (viewBarComponentId?: string) => {
           return;
         }
 
-        const currentView = await getViewFromCache(currentViewId);
+        const currentView = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useDeleteCombinedViewFilters.ts:53]: ***Nitpick:*** Useless await

File: packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts [hunk 48]
```diff
@@ -169,21 +173,21 @@ export const useCreateViewFromCurrentView = (viewBarComponentId?: string) => {
...
       createOneRecord,
       createViewFieldRecords,
-      getViewSortsCombined,
-      getViewFiltersCombined,
-      getViewFilterGroupsCombined,
-      currentViewIdCallbackState,
-      getViewFromCache,
-      isPersistingViewFieldsCallbackState,
+      findManyRecords,
+      objectMetadataItem?.fields,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useCreateViewFromCurrentView.ts:184]: ***React newbie concerns:*** this

File: packages/twenty-front/src/modules/navigation/hooks/useSetLastVisitedViewForObjectMetadataNamePlural.ts [hunk 49]
```diff
@@ -54,7 +49,7 @@ export const useSetLastVisitedViewForObjectMetadataNamePlural = () => {
           });
         }
       },
-    [findManyRecords, views],
+    [],
```
Comment (prastoin) [inline packages/twenty-front/src/modules/navigation/hooks/useSetLastVisitedViewForObjectMetadataNamePlural.ts:52]: ***praise:*** yummy

File: packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx [hunk 50]
```diff
@@ -24,11 +21,10 @@ export type NavigationDrawerItemForObjectMetadataItemProps = {
...
   objectMetadataItem,
 }: NavigationDrawerItemForObjectMetadataItemProps) => {
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
-
-  const objectMetadataViews = getObjectMetadataItemViews(
-    objectMetadataItem.id,
-    views,
+  const views = useRecoilValue(
+    prefetchViewsFromObjectMetadataItemFamilySelector({
+      objectMetadataItemId: objectMetadataItem.id,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx:26]: ***Nitpick:*** typed as `any` would `?? ''`

File: packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useDeleteCombinedViewFilterGroup.ts [hunk 51]
```diff
@@ -56,7 +55,7 @@ export const useDeleteCombinedViewFilterGroup = (
           return;
         }
 
-        const currentView = await getViewFromCache(currentViewId);
+        const currentView = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/advanced-filter/hooks/useDeleteCombinedViewFilterGroup.ts:58]: ***Nitpick:*** useless await

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts [hunk 52]
```diff
@@ -120,7 +113,7 @@ export const useHandleRecordGroupField = ({
           return;
         }
 
-        const view = await getViewFromCache(currentViewId);
+        const view = await getViewFromPrefetchState(currentViewId);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleRecordGroupField.ts:116]: ***Nitpick:*** useless await

File: packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx [hunk 53]
```diff
@@ -123,12 +121,10 @@ export const RecordDetailRelationSection = ({
...
 
-  const { records: views } = usePrefetchedData<View>(PrefetchKey.AllViews);
-
-  const indexView = views.find(
-    (view) =>
-      view.key === 'INDEX' &&
-      view.objectMetadataId === relationObjectMetadataItem.id,
+  const indexViewId = useRecoilValue(
+    prefetchIndexViewIdFromObjectMetadataItemFamilySelector({
+      objectMetadataItemId: relationObjectMetadataItem.id,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-show/record-detail-section/components/RecordDetailRelationSection.tsx:126]: ***praise:*** nice

**Review by prastoin — COMMENTED** [review]
Gg a lot of work, re-rendering master !
I think we should merge this after fixing critical points raised by reviews, and handle nitpicks afterwards to avoid any conflicts and friction due to the PR size

**Review by prastoin — APPROVED** [review]
Stamping this to get to the release ! We will handle nitpicks and non-critical feedbacks afterwards
<image src="https://github.com/user-attachments/assets/b467c2eb-fe90-4420-a8aa-6363916749f0" width=300 height=300 />
