### PR TITLE
fix: navigation drawer clip while making folder in favorites

### LINKED ISSUE #8606: Navigation drawer clip while making folder in favorites
### This is specific to Chromium-based browser on Linux
The navigation drawer overflows from the screen when a favourite folder input is active. 

Image

https://github.com/user-attachments/assets/c33c8dc8-7f51-4958-8c44-5e96d10b991b

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #8606 

**Reason for the issue:** 

The issue was caused by the padding in `TEXT_INPUT_STYLE`, which was being applied to the `StyledTextInput` component used in `NavigationDrawerInput`. 

**Changes**

- Overrode the padding in `StyledTextInput` with a value of 0.
- Added padding-right: 8px to the `Icon`. This ensures consistent spacing between the Icon and the input value, maintaining the same visual alignment as before.

[Screencast from 2024-11-20 23-32-24.webm](https://github.com/user-attachments/assets/f20058bc-cb89-4077-bab1-27c30088779a)

### CODE REVIEW

File: packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPickerFooter.tsx [hunk 1]
```diff
@@ -27,6 +31,7 @@ export const FavoriteFolderPickerFooter = () => {
         <MenuItem
           className="add-folder"
           onClick={() => {
+            setIsNavigationDrawerExpanded(true);
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/favorites/favorite-folder-picker/components/FavoriteFolderPickerFooter.tsx:34]: @martmull How about this? I missed this earlier and added it here -- not related to the issue.

**Review by martmull — COMMENTED** [review]
Hey, nice one thank you. One comment

**Review by martmull — APPROVED** [review]
LGTM thank you guys
