### PR TITLE
Fix issue 2130: text overflow on setting member page

### LINKED ISSUE #2130: On Settings > Member page, if a member has a long name, it causes a text overflow
## Bug Description

On /settings/workspace-members, if a member name is very long, it is overflowing its container.
image

## Expected behavior

In case of long names, the name should be truncated with ellipsis.

## Technical inputs

Ideal would be to use OverflowingTextWithTooltip component

### PR DESCRIPTION
**Pull request by ttlpta**
Fixes https://github.com/twentyhq/twenty/issues/2130

### CODE REVIEW

File: front/src/modules/workspace/components/WorkspaceMemberCard.tsx [hunk 1]
```diff
@@ -53,7 +51,7 @@ export const WorkspaceMemberCard = ({
       size="xl"
     />
     <StyledContent>
-      <StyledNameText>{workspaceMember.user.displayName}</StyledNameText>
+      <OverflowingTextWithTooltip text={workspaceMember.user.displayName} />
```
Comment (IbrahimBagalwa) [inline front/src/modules/workspace/components/WorkspaceMemberCard.tsx:54]: LGTM 👍

**Review by IbrahimBagalwa — COMMENTED** [review]
LGTM 👍

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you!
