### PR TITLE
Error invalid link

### LINKED ISSUE #9778: No error when adding wrong link in record details
**Scenario:**
1. Log in
2. Go to Companies
3. Check details of any record
4. Add wrongly formatted link like `a.a` or email like `a@a.a`

**Actual:** While wrongly formatted link isn't added, there's no error nor red border informing about wrong data

https://github.com/user-attachments/assets/ed0773c3-c7df-4858-ab9a-918d3718262b

**Expected:** There should be an indicator when user tries to add wrongly formatted data

### PR DESCRIPTION
**Pull request by etiennejouan**
Don't have access to push on https://github.com/twentyhq/twenty/pull/9942, so close it and open new PR here

Screenshot 2025-02-18 at 11 09 39
Screenshot 2025-02-18 at 11 09 51

Ok for RecordInlineCell / RecordTableCell and EmailsFieldInput / LinksFieldInput.
I think it's too complex for a so small issue (agree with you khuddite)

closes https://github.com/twentyhq/twenty/issues/9778
on top of https://github.com/twentyhq/twenty/pull/9942 from @khuddite

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx [hunk 1]
```diff
@@ -54,6 +54,7 @@ type FieldInputProps = {
   onEscape?: FieldInputEvent;
   onTab?: FieldInputEvent;
   onShiftTab?: FieldInputEvent;
+  onError?: (hasError: boolean, hasItem: boolean) => void;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx:57]: not sure to understand the "hasItem" parameter

Comment (charlesBochet) [reply packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx:57]: To expand more:
- it feels that we are trying to make the lower component provide information that is useful to the parent in a way that the parent can only know: maybe the parent wants more than knowing "hasItem", maybe he will want to have all items to take decisions based on that
- this onError signature does not seem to be compatible with other FieldInput

=> I would do (hasError, value) (which it case of multiItem would be an array of items

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx [hunk 2]
```diff
@@ -33,6 +34,13 @@ type RecordInlineCellProps = {
 export const RecordInlineCell = ({ loading }: RecordInlineCellProps) => {
   const { fieldDefinition, recordId, isCentered, isDisplayModeFixHeight } =
     useContext(FieldContext);
+
+  const setHasRecordInlineCellDangerBorder = useSetRecoilState(
+    hasRecordInlineCellDangerBorderScopedState(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCell.tsx:39]: that's the old way of doing it, we should be using ComponentStates now!

File: packages/twenty-front/src/modules/object-record/record-inline-cell/states/hasRecordInlineCellDangerBorderScopedState.ts [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import { createFamilyState } from '@/ui/utilities/state/utils/createFamilyState';
+
+export const hasRecordInlineCellDangerBorderScopedState = createFamilyState<
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/states/hasRecordInlineCellDangerBorderScopedState.ts:3]: use createComponentStateV2 here

**Review by charlesBochet — COMMENTED** [review]
I have left comment and rebased on main

File: packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx (hunk 1 above)
Comment (etiennejouan) [reply packages/twenty-front/src/modules/object-record/record-field/components/FieldInput.tsx]: I modify to (hasError:boolean, value:any) but not very satisfied of value 'any' type.

not sure to understand your second comment. I should provide onError prop to all other FieldInput component ?

**Comment by lucasbordeau** [comment]
I know it's a bit late but adding an onError feels like a code smell here, I would suggest that we instead create a state that says if a generic field input is in error, and then deriving it in record inline cell and record table cell.

**Comment by lucasbordeau** [comment]
Thus allowing particular field inputs to set this state to true without the parent having to drill down even handlers for a validation logic it shouldn't know about.

**Comment by etiennejouan** [comment]
@lucasbordeau @charlesBochet 
I've added the changes you recommend.
Charles, I had to lift up the RecordFieldComponentInstanceContext you provide in FieldInput, in order to access state value in RecordInline and RecordTable components.

**Review by charlesBochet — APPROVED** [review]
