### PR TITLE
Fix: Editing a task assignee relation from the list opens both the command menu and the multi item picker

### LINKED ISSUE #12129: Editing a task assignee relation from the list opens both the command menu and the multi item picker
https://github.com/user-attachments/assets/0ff2b127-a675-4348-8ecb-b5b014bc0605

### PR DESCRIPTION
**Pull request by Weiko**
Fixes https://github.com/twentyhq/twenty/issues/12129

To fix this, we need to stop the click event from propagating up from the ActivityTargetsInlineCell

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx [hunk 1]
```diff
@@ -124,13 +128,19 @@ export const TaskRow = ({ task }: { task: Task }) => {
...
           >
-            <ActivityTargetsInlineCell
-              activityObjectNameSingular={CoreObjectNameSingular.Task}
-              activityRecordId={task.id}
-              showLabel={false}
-              maxWidth={200}
-              componentInstanceId={`task-row-targets-${task.id}`}
-            />
+            <StyledActivityTargetsInlineCellContainer
+              onClick={(e) => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx:132]: Works but we might find a better solution, let's merge like that.

**Review by lucasbordeau — APPROVED** [review]
LGTM

File: packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx (hunk 1 above)
Comment (Weiko) [reply packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx:132]: Yes, agree! It seems we did the same for checkbox click above in this component so we should change that as well @lucasbordeau

Comment (charlesBochet) [reply packages/twenty-front/src/modules/activities/tasks/components/TaskRow.tsx:132]: use StopPropagationContainer

**Review by lucasbordeau — APPROVED** [review]
Better LGTM
