### PR TITLE
Fix safari broken table

### LINKED ISSUE #11254: Broken table scroll on Safari
## Bug Description

Having a huge table brokes scroll on Safari, rows are not displayed

https://github.com/user-attachments/assets/3ec2a2f7-77fb-4aa2-b226-dedc5c457d98

## Expected behavior

It should display rows

## Technical inputs

It remembers me an other related issue that I'm about to search for
I'm sure @charlesBochet knows what I'm talking about

### PR DESCRIPTION
**Pull request by charlesBochet**
In this PR:
- deprecate usage of useInView (react-intersection-observer) for record table
- fixes #11254

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyLoading.tsx [hunk 1]
```diff
@@ -33,6 +33,8 @@ export const RecordTableBodyLoading = () => {
             }}
           >
             <RecordTableTr
+              recordId={`${rowIndex}`}
```
Comment (Weiko) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-body/components/RecordTableBodyLoading.tsx:36]: template literals not needed here?

**Review by Weiko — APPROVED** [review]
