### PR TITLE
Throw 400 for webhook triggering deleted workspaces + enqueue workflows by batches

### LINKED ISSUE #16824: QUERY_MAX_RECORDS makes it impossible to enque larger chunks of workflowrun
the constant `QUERY_MAX_RECORDS` is set to 200 and combined with a higher WORKFLOW_EXEC_SOFT_THROTTLE_LIMIT (1000 in my case)  makes it impossible to enqueue workflow run

```
[Nest] 34  - 12/27/2025, 2:00:53 AM   ERROR [WorkflowRunEnqueueWorkspaceService] Failed to enqueue workflow runs for workspace: f86f4df7-aab6-4992-baf2-a0a02053a635
[Nest] 34  - 12/27/2025, 2:00:53 AM   ERROR [WorkflowRunEnqueueWorkspaceService] TwentyORMException [Error]: Cannot update more than 200 records at once
    at WorkspaceUpdateQueryBuilder.execute (/app/packages/twenty-server/dist/engine/twenty-orm/repository/workspace-update-query-builder.js:58:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async /app/packages/twenty-server/dist/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.js:88:17
    at async WorkflowRunEnqueueWorkspaceService.enqueueRunsForWorkspace (/app/packages/twenty-server/dist/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.js:53:13)
    at async WorkflowRunEnqueueJob.handle (/app/packages/twenty-server/dist/modules/workflow/workflow-runner/workflow-run-queue/jobs/workflow-run-enqueue.job.js:27:9)
    at async MessageQueueExplorer.invokeProcessMethods (/app/packages/twenty-server/dist/engine/core-modules/message-queue/message-queue.explorer.js:113:17)
    at async MessageQueueExplorer.handleProcessor (/app/packages/twenty-server/dist/engine/core-modules/message-queue/message-queue.explorer.js:104:13)
    at async /app/packages/twenty-server/dist/engine/core-modules/message-queue/message-queue.explorer.js:79:17
    at async Worker.processFn (/app/packages/twenty-server/dist/engine/core-modules/message-queue/drivers/bullmq.driver.js:46:13)
    at async /app/node_modules/bullmq/dist/cjs/classes/worker.js:520:32 {
  code: 'TOO_MANY_RECORDS_TO_UPDATE',
  userFriendlyMessage: {
    id: '4ysDL0',
    message: 'You can only update up to {QUERY_MAX_RECORDS} records at once.',
    values: {
      QUERY_MAX_RECORDS: 200
    }
  }
}

```

 i've ran through the discord and github  issues and increasing the constant limit was discussed, but never implemented in a favor of batching.
either batching in enqueueing mechanism should be implemented or the constant moved to config, so it can be adjusted accordingly

### PR DESCRIPTION
**Pull request by thomtrp**
Fixes https://github.com/twentyhq/twenty/issues/17027

Fixes https://github.com/twentyhq/twenty/issues/16824

### CODE REVIEW

File: packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts [hunk 1]
```diff
@@ -39,6 +42,8 @@ export class WorkflowTriggerController {
   constructor(
     private readonly globalWorkspaceOrmManager: GlobalWorkspaceOrmManager,
     private readonly workflowTriggerWorkspaceService: WorkflowTriggerWorkspaceService,
+    @InjectRepository(WorkspaceEntity)
+    protected readonly workspaceRepository: Repository<WorkspaceEntity>,
```
Comment (Weiko) [inline packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts:46]: Not super critical but we usually avoid using repositories directly in controllers and prefer to delegate this to services

File: packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts [hunk 2]
```diff
@@ -73,6 +78,17 @@ export class WorkflowTriggerController {
     payload?: object;
     workspaceId: string;
   }) {
+    const workspaceExists = await this.workspaceRepository.existsBy({
```
Comment (Weiko) [inline packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts:81]: Note: we could implement a WorkspaceExistsGuard guard for that. Not sure this is worth now if it's the only place but just so you know.

File: packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts [hunk 3]
```diff
@@ -106,17 +113,38 @@ export class WorkflowRunEnqueueWorkspaceService {
...
+            const batchIds = batchRuns.map(
+              (workflowRun: WorkflowRunWorkspaceEntity) => workflowRun.id,
             );
+
+            await workflowRunRepository.update(batchIds, {
+              enqueuedAt: new Date().toISOString(),
+              status: WorkflowRunStatus.ENQUEUED,
+            });
+
+            for (const workflowRunId of batchIds) {
```
Comment (Weiko) [inline packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts:127]: Note: the status update is in batch but the enqueue is not. If at some point it fails after the update, some workflows could stay in "enqueued" status forever, right?

File: packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts [hunk 4]
```diff
@@ -106,17 +113,38 @@ export class WorkflowRunEnqueueWorkspaceService {
...
+              await this.messageQueueService.add<RunWorkflowJobData>(
+                RunWorkflowJob.name,
+                {
+                  workflowRunId,
+                  workspaceId,
+                },
+              );
+            }
+
+            alreadyEnqueuedIds.push(...batchIds);
```
Comment (Weiko) [inline packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts]: I feel like alreadyEnqueuedIds is redundant here. You are pushing the workflows that you've updated with "ENQUEUED" status in an array then do `id: Not(In(alreadyEnqueuedIds))` in a SELECT query that already excludes rows with status <> WorkflowRunStatus.NOT_STARTED.
Or am I missing something?

**Review by Weiko — COMMENTED** [review]
Left some comments @thomtrp

**Review by etiennejouan — APPROVED** [review]
LGTM 🚀

File: packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts (hunk 3 above)
Comment (thomtrp) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts:127]: We do not enqueue by batch indeed but this needs to be done separately from status update anyway so not sure what that would bring?
If a workflow is stuck in enqueue status we have a cron that will set it back to not started

File: packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts (hunk 1 above)
Comment (thomtrp) [reply packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts:46]: what's the reason behind?

File: packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts (hunk 2 above)
Comment (thomtrp) [reply packages/twenty-server/src/engine/core-modules/workflow/controllers/workflow-trigger.controller.ts:81]: This is the only place for now but I will keep this in mind

File: packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts (hunk 3 above)
Comment (Weiko) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts:127]: "If a workflow is stuck in enqueue status we have a cron that will set it back to not started" yes that's what I wanted to know, perfect 👍

File: packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts (hunk 4 above)
Comment (thomtrp) [reply packages/twenty-server/src/modules/workflow/workflow-runner/workflow-run-queue/workspace-services/workflow-run-enqueue.workspace-service.ts]: yes you're right! Maybe at some point we'll have eventual writes 🙈 
Thank you
