### PR TITLE
Fix bug bypassing verification in confirmation modal when pressing Enter

### LINKED ISSUE #6663: Missing verification when deleting the account
# Do not try to repeat this on paid version!

**Scenario:**
1. Log in
2. Go to Settings > Profile
3. Click "Delete account" button
4. Type anything and press Enter

**Actual:** User is deleted and if that's the only member of workspace, the workspace is also deleted

**Expected:** User should be deleted ONLY IF the user's email was typed correctly (and maybe the button was pressed instead of pressing Enter key but that's up to decide)

**Note:** Reproduced on demo

### PR DESCRIPTION
**Pull request by bachtly**
# Description
Fix bug bypassing verification in the confirmation modal when pressing Enter

# Demo
Tested for webhook case (similar to other cases):
1. Press Enter when invalid verification => not delete webhook
2. Press Enter when valid verification => delete webhook

https://github.com/user-attachments/assets/81aa0aaa-7361-4584-b7ae-b29525f33664

# Ref
Fixes #6663

### CODE REVIEW

**Comment by bachtly** [comment]
Hi @Bonapara and @charlesBochet, I don't know how to add you as reviewers so I put a comment here. Please help have a look, the PR is simple. Thank you!

**Comment by Bonapara** [comment]
@lucasbordeau ;)

File: packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export const ConfirmationModal = ({
                 setIsOpen(false);
               }
             }}
-            onEnter={onConfirmClick}
+            onEnter={!isValidValue ? undefined : onConfirmClick}
```
Comment (Weiko) [inline packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx:96]: nit: I feel like this is easier to read
```typescript
onEnter={isValidValue ? onConfirmClick : undefined}
```

**Review by Weiko — APPROVED** [review]
LGTM thank you @bachtly

File: packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx (hunk 1 above)
Comment (bachtly) [reply packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx:96]: Thanks for your suggestion!
