### PR TITLE
fix: Close the email side panel upon clicking an open email thread

### LINKED ISSUE #4205: Close the email side panel upon clicking an open email thread
# Current Behavior

When attempting to close the side panel (without utilizing the 'x' button icon), users must click away from the email list.

https://github.com/twentyhq/twenty/assets/19412894/71f0ff27-2820-44f2-9e5f-acf864a59fe4

# Desired Behavior

The side panel should close when a user clicks on an already-opened email.

### PR DESCRIPTION
**Pull request by sooster910**
This PR addresses an issue ( closes #4205) where the right drawer, which displays the email thread, did not close as expected when clicking on an already opened email thread from the EmailThread component. 

## Describe 

Whenever you click outside the right-drawer, the `closeRightDrawer()` gets triggered. 
This also happens when clicking on any email thread, which complicates tracking the `isRightDrawerOpen` state changes.

https://github.com/twentyhq/twenty/blob/b2210bd418af1a881dca949a928ca3aecd11595d/packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx#L112

https://github.com/twentyhq/twenty/blob/b2210bd418af1a881dca949a928ca3aecd11595d/packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx#L59-L77

Given that `isRightDrawerOpen` is a straightforward state name that helps any developer determine whether the right drawer should be closed or not, I needed to figure out a way to keep tabs on the final state of isRightDrawerOpen.

In this case, useEffect reacts to changes in the global state `isRightDrawerOpen` and allows for the conditional execution of logic, taking into account both this global state and a component-specific state `isDrawerActive`.

Any suggestions or missed cases would be appreciated!

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hi @sooster910, please implement an additional useListenClickoutside callback.

You can find an example in `ActivityEditorEffect.tsx`

```tsx
useRegisterClickOutsideListenerCallback({
  callbackId: 'activity-editor',
  callbackFunction: upsertActivityCallback,
});
```

File: packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts [hunk 1]
```diff
@@ -1,22 +1,37 @@
...
+  useEffect(() => {
+    if (isRightDrawerOpen) {
+      setIsDrawerActive(true);
+      return;
+    }
+    setIsDrawerActive(false);
+  }, [isRightDrawerOpen]);
 
   const openEmailThread = (threadId: string) => {
+    if (viewableEmailThreadId === threadId && isDrawerActive) {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts:27]: Why not using directly isRightDrawerOpen ?

**Comment by lucasbordeau** [comment]
The approach seems ok for now. Let's see if we need more in the future.

Although not sure if we need a useEffect here ?

File: packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts (hunk 1 above)
Comment (sooster910) [reply packages/twenty-front/src/modules/activities/emails/hooks/useEmailThread.ts:27]: Yeah you are right. When we click on an emailThread element and exclude it from the event listener in `useListenClickOutside`, it makes the isRightClose state clearer. This way, we can easily use isRightDrawOpened. I didn't realize this at first. I changed the code as you suggested. Thanks for your guidance and helping me understand the situation better.
```suggestion
     const toggleEmailThread = useRecoilCallback(
    ({ snapshot }) =>
      async (threadId: string) => {
        const isRightDrawerOpen = snapshot
          .getLoadable(isRightDrawerOpenState)
          .getValue();

        if (isRightDrawerOpen && viewableEmailThreadId === threadId) {
          setViewableEmailThreadId(null);
          closeRightDrawer();
        } else {
          setViewableEmailThreadId(threadId);
          openEmailThredRightDrawer();
        }
      },
  );
```

**Comment by sooster910** [comment]
> The approach seems ok for now. Let's see if we need more in the future.
> 
> Although not sure if we need a useEffect here ?

I also think we don't have to use useEffect. my bad. 
I initially used useEffect because of the issue. The email thread element is also targeted by useListenClickOutside. When I tried to close the rightDrawer by clicking the email thread again, the isRightOpenDrawerOpen status was already false since useListenClickOutside got triggered first. So, the drawer never closed

https://github.com/twentyhq/twenty/blob/b2210bd418af1a881dca949a928ca3aecd11595d/packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx#L59-L65

Can we use `useListenClickOutsideByClassName ` instead of `useListenClickOutside`?
This code satisfies the following conditions:
1.  It toggles if the same emailId is clicked.
2.  It changes content without closing when a different item is clicked.
3.  It closes the drawer when a click occurs outside of it.

```suggestion
  useListenClickOutsideByClassName({
    classNames: ['rightDrawerWrapper'],
    excludeClassNames: ['emailThreadRow'],
    callback: () => {
      closeCallback();
    },
  });
  ```
  
  Thanks.

**Comment by lucasbordeau** [comment]
That's not an easy problem.

We want the right drawer useListenClickOutside to stay decoupled ideally.

From what I understand, useListenClickOutside gets triggered first then after emailThreadRow click gets triggered.

useRecoilCallback should commit before the second click handler gets triggered, so what we could do to help you is to refactor closeCallback() by using useRecoilCallback instead of useRecoilState, would you be willing to try that ? 

If that feels too much on your plate we could create an issue for this.

**Comment by lucasbordeau** [comment]
@sooster910 I'll handle this mini refactor as it is a bit tricky

**Comment by sooster910** [comment]
> @sooster910 I'll handle this mini refactor as it is a bit tricky

@lucasbordeau  Okay. Thanks a lot.

**Comment by lucasbordeau** [comment]
@sooster910 Here's what I did for reference : 

# Context 

1- The generic click outside listener of the right drawer fires first.

2- The click handler of the email thread list item fires after.

# Problem 

We want to know if the email thread list item we clicked on is the same as the thread in the right drawer that has just been closed. 

So we can prevent opening it again.

# Solution

- Registered a custom click outside callback on `RightDrawerEmailThread` component that will set an atom `emailThreadIdWhenEmailThreadWasClosedState`, containing the thread id on right drawer, on close. Since we're using useRecoilCallback, the state modification will be committed in the Recoil store BEFORE the second click handler gets triggered.
- Created a util function in useRightDrawer to check `isSameEventThanRightDrawerClose`
- Created a `canOpen` predicate to know if we can call `openEmailThread` to open email thread right drawer.

**Review by lucasbordeau — APPROVED** [review]
