### PR TITLE
fix: allow access to the Update View button when a table column can be persisted

### LINKED ISSUE #1432: Bug: Open the Sort and Filter bar when a column can be persisted
### Context

Currently, the Company/People table's "Filter and Sort" bar only opens if a filter or sort has been selected. But we need to show it when a column has been resized and/or shown/hidden as well, so the "Update view" button is displayed and the view can be updated.

### Expected behavior

**Scenario: Resize a column**

**GIVEN** I am on the Companies/People page
**WHEN** I resize a table column
**THEN** I see the "Update view" button in the "Filter and Sort" bar

**Scenario: Change a column's visibility**

**GIVEN** I am on the Companies/People page
**WHEN** I change a column's visibility
**THEN** I see the "Update view" button in the "Filter and Sort" bar

### PR DESCRIPTION
**Pull request by thaisguigon**
Closes #1432

### CODE REVIEW

File: front/src/modules/ui/filter-n-sort/components/SortAndFilterBar.tsx [hunk 1]
```diff
@@ -136,7 +138,7 @@ function SortAndFilterBar<SortField>({
   }
 
   if (
-    (!filtersWithDefinition.length && !sorts.length) ||
+    (!canToggle && !filtersWithDefinition.length && !sorts.length) ||
```
Comment (charlesBochet) [inline front/src/modules/ui/filter-n-sort/components/SortAndFilterBar.tsx:141]: Ok as it fixes the issue but I feel we might need to re-think this "SortAndFilterBar" to actually be a "ViewBar" that would be aware of everything: filters, sorts and views and that would force toggle itself based on filters, views and sorts. Looks too ambitious for the release so what you are doing is the way to go for now :)

**Review by charlesBochet — APPROVED** [review]
