### PR TITLE
608 fix hotkey scope and dropdown issues in the command menu

### LINKED ISSUE #608: [Timebox] Fix hotkey scope and dropdown issues in the command menu
The hotkey scopes are not reset correctly for some components inside the command menu, for instance the `MultipleRecordPicker` or the `BlockEditor` do not correctly go back to the previous hotkey scope causing shortcuts and click outside listeners not to be triggered.
Also some dropdowns are not closed when we close the command menu.

### PR DESCRIPTION
**Pull request by bosiraphael**
Closes https://github.com/twentyhq/core-team-issues/issues/608

- Introduces a new hotkey scope `CommandMenuFocused`
- Fixes hotkey scopes issues in the side panel

### CODE REVIEW

File: packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx [hunk 1]
```diff
@@ -59,6 +62,12 @@ export const RecordShowRightDrawerOpenRecordButton = ({
 
   const navigate = useNavigateApp();
 
+  const actionMenuId = useComponentInstanceStateContext(
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/action-menu/components/RecordShowRightDrawerOpenRecordButton.tsx:65]: useAvailalbleComponentInstanceIdOrThrow

**Review by charlesBochet — APPROVED** [review]
