### PR TITLE
fix: attachment scroll issue in preview modal

### LINKED ISSUE #10919: Preview can't be scrolled horizontally
**Scenario:**
1. Log in
2. Go to People
3. Check details of any record
4. Go to Files and import [company (24).csv](https://github.com/user-attachments/files/19262386/company.24.csv)
5. Check preview of this file

**Actual:** Preview can't be scrolled horizontally

Image

**Expected:** Preview can be scrolled horizontally

### PR DESCRIPTION
**Pull request by anoopw3bdev**
Fixes #10919

### CODE REVIEW

File: packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx [hunk 1]
```diff
@@ -94,6 +94,7 @@ const StyledModalHeader = styled(Modal.Header)`
 `;
 
 const StyledModalContent = styled(Modal.Content)`
+  overflow: auto;
```
Comment (ehconitin) [inline packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx:97]: We should use ScrollWrapper. I remember AuthModal having the same issue, which was dealt with by adding a ScrollWrapper. Could you check how it's done in AuthModal?

**Review by ehconitin — CHANGES_REQUESTED** [review]
Left a comment

File: packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx (hunk 1 above)
Comment (anoopw3bdev) [reply packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx:97]: Thanks for the review @ehconitin, when I implemented with ScrollWrapper, there is a scrollbar even though the content is not overflowing (as you can see in the screenshot attached), maybe something have to handle within the **ScrollWrapper**

I can push the commit if this is fine.

Screenshot 2025-03-17 at 7 13 49 PM

Comment (anoopw3bdev) [reply packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx:97]: I am wrapping the StyledModalContent as below 
```
<ScrollWrapper
  contextProviderName="modalContent"
  componentInstanceId="scroll-wrapper-modal-content"
>
  <StyledModalContent />
</ScrollWrapper>
```

Comment (ehconitin) [reply packages/twenty-front/src/modules/activities/files/components/AttachmentList.tsx]: It was because of the total height.
I made some changes in modal paddings and gaps to match figma https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=56165-105671&t=WAwuuEPlUp4Z2Y3D-0

**Review by ehconitin — APPROVED** [review]
LGTM! thanks @anoopw3bdev
