### PR TITLE
Fix total count in show page

### LINKED ISSUE #6405: Fix total count in show page navigation bar when total count = 1
## Bug Description

Total count is displayed as 0 if it is 1.

image

## Expected behavior

Total count should be 1 if total count is 1.

## Technical inputs

See related issue : https://github.com/twentyhq/twenty/issues/6325

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #6405 

We need to take into account both the totalCount of **before cursor** results and **after cursor** results.

### CODE REVIEW

**Comment by prateekj117** [comment]
@charlesBochet Can help with a review on this?

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts [hunk 1]
```diff
@@ -147,6 +148,19 @@ export const useRecordShowPagePagination = (
 
   const objectLabel = capitalize(objectMetadataItem.namePlural);
 
+  let totalCount = 0;
+
+  if (totalCountBefore !== 0 && totalCountAfter !== 0) {
+    totalCount = Math.max(totalCountBefore, totalCountAfter);
+  } else {
+    totalCount =
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:156]: totalCount = (totalCountBefore === 0 && totalCountAfter === 0) ? 1 : Math.max(totalCountBefore, totalCountAfter)
I believe this should work?

Comment (prateekj117) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:156]: Yup. That's a better way to write it. Let me correct this.

**Comment by prateekj117** [comment]
@charlesBochet Ready for another round of review.

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts [hunk 2]
```diff
@@ -147,6 +148,11 @@ export const useRecordShowPagePagination = (
 
   const objectLabel = capitalize(objectMetadataItem.namePlural);
 
+  const totalCount =
+    totalCountBefore === 0 && totalCountAfter === 0
```
Comment (Weiko) [inline packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowPagePagination.ts:152]: Could be even shorter
```typescript
const totalCount = Math.max(1, totalCountBefore, totalCountAfter)
```

**Review by charlesBochet — APPROVED** [review]
LGTM!
