### PR TITLE
[BUG] Record settings not saved

### LINKED ISSUE #9381: Data Model Record Label identifier is not persisted
# Current Behavior

Image

I can edit the value, but it doesn't persist.

# Desired Behavior

Save the user preference when they change the record label identifier.

### PR DESCRIPTION
**Pull request by prastoin**
# Introduction
By initially fixing this Fixes #9381, discovered other behavior that have been fix.
Overall we encountered a bug that corrupts a workspace and make the browser + api crash
This issue https://github.com/twentyhq/core-team-issues/issues/25 suggests a refactor that has final save button instead of auto-save

## `labelIdentifierFieldMetadataId` form default value
The default value resulted in being undefined, resulting in react hook form `labelIdentifierFieldMetadataId` is required field error.

### Fix
Setting default value fallback to `null`  as field is `nullable`

## `SettingsDataModelObjectSettingsFormCard` never triggers form
Unless I'm mistaken in production touching any fields within `SettingsDataModelObjectSettingsFormCard` would never trigger form submission until you also modify `SettingsDataModelObjectAboutForm` fields

### Fix
Provide and apply `onblur` that triggers the form on both `SettingsDataModelObjectSettingsFormCard` inputs

## Wrong default `labelIdentifierFieldMetadataItem` on first page render
When landing on the page for the first time, if a custom `labelIdentifierFieldMetadataItem` has been set it won't be computed within the `PreviewCard`.
Occurs when `labelIdentifierFieldMetadataId` form default value is undefined, due to `any` injection.

### Fix
In the `getLabelIdentifierFieldMetadataItem` check the `labelIdentifierFieldMetadataIdFormValue` definition, if undefined fallback to current `objectMetadata` identifier

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 1]
```diff
@@ -65,41 +71,37 @@ export const SettingsDataModelObjectIdentifiersForm = ({
       {[
         {
           label: 'Record label',
-          fieldName: 'labelIdentifierFieldMetadataId' as const,
+          fieldName: LABEL_IDENTIFIER_FIELD_METADATA_ID,
           options: labelIdentifierFieldOptions,
+          defaultValue:
+            objectMetadataItem[LABEL_IDENTIFIER_FIELD_METADATA_ID] ??
+            defaultLabelIdentifierFieldMetadataId, // defaultLabelIdentifierFieldMetadataId could be undefined as it's injected as any
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:78]: // defaultLabelIdentifierFieldMetadataId could be undefined as it's injected as any

**Comment by prastoin** [comment]
Just linking this issue with this PR https://github.com/twentyhq/core-team-issues/issues/25, this issue seems to suggest to refactor the `About` section as whole save instead of auto-save `onBlur`

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 2]
```diff
@@ -19,11 +19,17 @@ export const settingsDataModelObjectIdentifiersFormSchema =
 export type SettingsDataModelObjectIdentifiersFormValues = z.infer<
   typeof settingsDataModelObjectIdentifiersFormSchema
 >;
-
+export type SettingsDataModelObjectIdentifiers =
+  keyof SettingsDataModelObjectIdentifiersFormValues;
 type SettingsDataModelObjectIdentifiersFormProps = {
   objectMetadataItem: ObjectMetadataItem;
-  defaultLabelIdentifierFieldMetadataId: string;
+  defaultLabelIdentifierFieldMetadataId: string | undefined;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:26]: remove from props

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 3]
```diff
@@ -65,41 +71,37 @@ export const SettingsDataModelObjectIdentifiersForm = ({
       {[
         {
           label: 'Record label',
-          fieldName: 'labelIdentifierFieldMetadataId' as const,
+          fieldName: LABEL_IDENTIFIER_FIELD_METADATA_ID,
           options: labelIdentifierFieldOptions,
+          defaultValue:
+            objectMetadataItem[LABEL_IDENTIFIER_FIELD_METADATA_ID] ??
+            defaultLabelIdentifierFieldMetadataId,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:78]: this should throw an error if we don't have a default

**Comment by prastoin** [comment]
@greptileai

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectSettingsFormCard.tsx [hunk 4]
```diff
@@ -80,6 +85,7 @@ export const SettingsDataModelObjectSettingsFormCard = ({
       <CardContent>
         <SettingsDataModelObjectIdentifiersForm
           objectMetadataItem={objectMetadataItem}
+          onBlur={onBlur}
           defaultLabelIdentifierFieldMetadataId={
             labelIdentifierFieldMetadataItem?.id
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectSettingsFormCard.tsx]: refactored

**Comment by prastoin** [comment]
# Refactor comments
Refactored the integration to avoid consuming the form values but rather the `objectMetadaItem` instance whom `labelIdentifierFieldMetadataId` is always defined as strictly typed as string.
This type mutation has several side effect in the codebase, especially in mappers where I've for the moment force cast as string only. Those files would be stable if we could mutate the `packages/twenty-front/src/generated-metadata/graphql.ts` `ObjectMetadataItem` exported type
Please let me know your thoughts on all of that @charlesBochet

File: packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts [hunk 5]
```diff
@@ -20,7 +20,7 @@ export const objectMetadataItemSchema = z.object({
   isCustom: z.boolean(),
   isRemote: z.boolean(),
   isSystem: z.boolean(),
-  labelIdentifierFieldMetadataId: z.string().uuid().nullable(),
+  labelIdentifierFieldMetadataId: z.string().uuid(),
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/object-metadata/validation-schemas/objectMetadataItemSchema.ts:23]: The nullfallback referenced the React hook form state

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 6]
```diff
@@ -32,12 +37,13 @@ const StyledContainer = styled.div`
...
 export const SettingsDataModelObjectIdentifiersForm = ({
   objectMetadataItem,
-  defaultLabelIdentifierFieldMetadataId,
+  onBlur,
 }: SettingsDataModelObjectIdentifiersFormProps) => {
-  const { control } =
+  const { control, watch } =
     useFormContext<SettingsDataModelObjectIdentifiersFormValues>();
+  watch(LABEL_IDENTIFIER_FIELD_METADATA_ID);
+  watch(IMAGE_IDENTIFIER_FIELD_METADATA_ID);
```
[the remark this answers is not in the document]
Comment (prastoin) [reply packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:45]: You're a good bot, it triggers component re-render

File: packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts [hunk 7]
```diff
@@ -11,6 +10,8 @@ export const mapPaginatedObjectMetadataItemsToObjectMetadataItems = ({
     pagedObjectMetadataItems?.objects.edges.map((object) => ({
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts:10]: if (!isString(object.node
        .labelIdentifierFieldMetadataId) { throw / continue }

File: packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts [hunk 8]
```diff
@@ -18,6 +18,7 @@ const objectMetadataItem: ObjectMetadataItem = {
   updatedAt: '2021-01-01',
   nameSingular: 'object1',
   namePlural: 'object1s',
+  labelIdentifierFieldMetadataId: '',
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/object-sort-dropdown/utils/__tests__/turnSortsIntoOrderBy.test.ts:21]: 20202020-72ba-4e11-a36d-e17b544541e1

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 9]
```diff
@@ -65,41 +71,35 @@ export const SettingsDataModelObjectIdentifiersForm = ({
       {[
         {
           label: 'Record label',
-          fieldName: 'labelIdentifierFieldMetadataId' as const,
+          fieldName: LABEL_IDENTIFIER_FIELD_METADATA_ID,
           options: labelIdentifierFieldOptions,
+          defaultValue: objectMetadataItem.labelIdentifierFieldMetadataId,
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:76]: defaultValue: watch(LABEL_IDENTIFIER_FIELD_METADATA_ID) ?? objectMetadataItem.labelIdentifierFieldMetadataId

File: packages/twenty-front/src/modules/settings/data-model/object-details/components/tabs/ObjectSettings.tsx [hunk 10]
```diff
@@ -71,6 +70,8 @@ export const ObjectSettings = ({ objectMetadataItem }: ObjectSettingsProps) => {
     resolver: zodResolver(objectEditFormSchema),
   });
 
+  const { isDirty } = formConfig.formState;
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/object-details/components/tabs/ObjectSettings.tsx:73]: ***Remark:*** While peer debugging with @charlesBochet, we've landed on two mains issues, one being just above:
- formConfig.formState is not reactive, we need extract it within the component for it to become

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx [hunk 11]
```diff
@@ -65,41 +71,37 @@ export const SettingsDataModelObjectIdentifiersForm = ({
...
+          render={({ field: { onChange, value } }) => (
+            <Select
+              label={label}
+              disabled={!objectMetadataItem.isCustom || !options.length}
+              fullWidth
+              dropdownId={`${fieldName}-select`}
+              emptyOption={emptyOption}
+              options={options}
+              value={value}
+              onChange={(value) => {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx:99]: ***Remark:*** While peer debugging with @charlesBochet we landed on two main issues, one just here:
- there was a race condition between the onBlur and the onChange, fix -> make them sync

File: packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts [hunk 12]
```diff
@@ -28,6 +28,7 @@ export const useFieldPreviewValue = ({
     relationObjectMetadataItem: relationObjectMetadataItem ?? {
       fields: [],
       labelSingular: '',
+      labelIdentifierFieldMetadataId: '',
```
Comment (prastoin) [inline packages/twenty-front/src/modules/settings/data-model/fields/preview/hooks/useFieldPreviewValue.ts:31]: @charlesBochet what about this one ?

File: packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx (hunk 2 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/settings/data-model/objects/forms/components/SettingsDataModelObjectIdentifiersForm.tsx]: done

File: packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts (hunk 7 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-metadata/utils/mapPaginatedObjectMetadataItemsToObjectMetadataItems.ts]: put in place zod validation schema inferred from the `objectMetadataItem` zod object

File: packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts [hunk 13]
```diff
@@ -1,14 +1,23 @@
 import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
+import { objectMetadataItemSchema } from '@/object-metadata/validation-schemas/objectMetadataItemSchema';
```
Comment (prastoin) [inline packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts:2]: ***Remark:*** we should re-generate this file, as it contains `labelIdentifier` nullable occurrences

Comment (prastoin) [reply packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts:2]: We decided to manually fix it as it has only occurrence and as it seems to be always a mess re-generating it from the seeds

File: packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts [hunk 14]
```diff
@@ -1,13 +1,13 @@
 import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
-import { objectMetadataItemSchema } from '@/object-metadata/validation-schemas/objectMetadataItemSchema';
```
Comment (prastoin) [inline packages/twenty-front/src/testing/mock-data/generatedMockObjectMetadataItems.ts]: ***Remark:*** This introduces a circular dep https://github.com/twentyhq/twenty/actions/runs/12905554388/job/35985011969.
Duplicating labelIdentifier schema is not clean

**Review by charlesBochet — APPROVED** [review]
