### PR TITLE
Table small fixes

### LINKED ISSUE #14573: "No records" is not centred properly when view has many view fields
## Bug Description

Image

## Expected behavior

Should be centred properly regardless of the number of displayed view fields

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR brings more UX fixes for table.

Fixes in https://github.com/twentyhq/core-team-issues/issues/1490 : 
- Fix any field filter chip formatting
- Empty placeholder should be centered on screenwidth and not scrollable width on table
- First cell is automatically active on table but we can't move => We now allow focus position to be null as it is a portal

Fixes https://github.com/twentyhq/twenty/issues/14573

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx [hunk 1]
```diff
@@ -14,6 +17,18 @@ import {
   type AnimatedPlaceholderType,
 } from 'twenty-ui/layout';
 
+const StyledEmptyPlaceholderOuterContainer = styled(
+  AnimatedPlaceholderEmptyContainer,
+)`
+  align-items: flex-start;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx:23]: I feel we should avoid styling from the outside, can't we fix the AnimatedPlaceholderEmptyContainer itself? 

this will lead to inconsitencies

**Review by charlesBochet — APPROVED** [review]

File: packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx (hunk 1 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/record-table/empty-state/components/RecordTableEmptyStateDisplay.tsx:23]: We would have to adapt all the callers of this component. And I'm not sure that this constraint is present on other callers, so I think it's a good trade-off.
