### PR TITLE
Fix frontend bug when filtering with special character

### LINKED ISSUE #8767: Filter is interepreted as a regex
I added a filter on the email field, looking for emails containing +1 but then when I navigated to a record page and tried to update that record's 
name it triggered the following error:

Image

It seems like the filter is incorrectly interpreted as a regex and not just a string

### PR DESCRIPTION
**Pull request by FelixMalfait**
Fixes #8767

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts [hunk 1]
```diff
@@ -21,7 +21,11 @@ export const isMatchingStringFilter = ({
       return regexCaseSensitive.test(value);
     }
     case stringFilter.ilike !== undefined: {
-      const regexPattern = stringFilter.ilike.replace(/%/g, '.*');
+      const escapedPattern = stringFilter.ilike.replace(
+        /[.*+?^${}()|[\]\\]/g,
+        '\\$&',
+      );
+      const regexPattern = escapedPattern.replace(/%/g, '.*');
```
Comment (magrinj) [inline packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts:28]: I think we can use [escapeRegExp](https://www.geeksforgeeks.org/lodash-_-escaperegexp-method/) from lodash instead of a custom one

File: packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts [hunk 2]
```diff
@@ -21,7 +21,11 @@ export const isMatchingStringFilter = ({
       return regexCaseSensitive.test(value);
     }
     case stringFilter.ilike !== undefined: {
```
Comment (magrinj) [inline packages/twenty-front/src/modules/object-record/record-filter/utils/isMatchingStringFilter.ts:23]: Don't you think we need to add the same check for the `like` ?

**Comment by FelixMalfait** [comment]
Thanks @magrinj good points, I made the changes! I'll merge
