### PR TITLE
Fix issue 2151: Dropdown menu of header table does not close after hide column

### LINKED ISSUE #2151: Dropdown menu of header table does not close after hide column.
## Bug Description
- Click header of table to show dropdown then select option hide.
- Click button Plus in header of the last column of the table, and select column which has just hidden.
- The column show with the dropdown menu.
image

## Expected behavior

- The dropdown menu of the header also close when this column hidden.

## Technical inputs
- N/A

### PR DESCRIPTION
**Pull request by ttlpta**
Fixes [2151](https://github.com/twentyhq/twenty/issues/2151)

### CODE REVIEW

File: front/src/modules/ui/data/data-table/components/DataTableColumnDropdownMenu.tsx [hunk 1]
```diff
@@ -14,19 +13,21 @@ export type DataTableColumnDropdownMenuProps = {
...
   isFirstColumn,
   isLastColumn,
   primaryColumnKey,
+  dropdownScopeId,
 }: DataTableColumnDropdownMenuProps) => {
   const { handleColumnVisibilityChange, handleMoveTableColumn } =
     useTableColumns();
 
   const { closeDropdown } = useDropdown({
-    dropdownScopeId: ColumnHeadDropdownId,
```
Comment (charlesBochet) [inline front/src/modules/ui/data/data-table/components/DataTableColumnDropdownMenu.tsx:29]: as this code is called from within DropdownScope it should not be needed. useDropdown will find it by itself

**Review by charlesBochet — APPROVED** [review]
Thank you!
