### PR TITLE
4902 bug fix fix api filter for enum

### LINKED ISSUE #4902: [Bug Fix] Fix api filter for enum
https://discord.com/channels/1130383047699738754/1225115274890706945

### PR DESCRIPTION
**Pull request by martmull**
- Handle NUMERIC, SELECT, PROBABILITY, RATING FieldMetadataTypes

Those filters now works:
- http://localhost:3000/rest/opportunities?filter=stage[eq]:MEETING
- http://localhost:3000/rest/opportunities?filter=stage[in]:[MEETING,NEW]

When providing wrong enum values, the following error messages are returned:
- http://localhost:3000/rest/opportunities?filter=stage[eq]:MEETINGG
> BadRequestException: 'filter' enum value 'MEETINGG' not available in 'stage' enum. Available enum values are ['NEW', 'SCREENING', 'MEETING', 'PROPOSAL', 'CUSTOMER']
- http://localhost:3000/rest/opportunities?filter=stage[in]:[MEETING,NEWW]
> BadRequestException: 'filter' enum value 'NEWW' not available in 'stage' enum. Available enum values are ['NEW', 'SCREENING', 'MEETING', 'PROPOSAL', 'CUSTOMER']

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
@martmull We do not support PROBABILITY actually. We should remove them from the codebase. It's legacy stuff. NUMERIC should not be exported either, it's only part of CurrencyComposite field

File: packages/twenty-server/src/engine/api/rest/api-rest-query-builder/factories/input-factories/filter-utils/check-filter-enum-values.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
+import { BadRequestException } from '@nestjs/common';
+
+import { ObjectMetadataInterface } from 'src/engine/metadata-modules/field-metadata/interfaces/object-metadata.interface';
+
+import { FieldMetadataType } from 'src/engine/metadata-modules/field-metadata/field-metadata.entity';
+
+export const checkFilterEnumValues = (
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/api/rest/api-rest-query-builder/factories/input-factories/filter-utils/check-filter-enum-values.ts:7]: check-filter-enum-values-or-throw if we throw. Do we actually want to throw here? we could return a boolean instead and leave it to the code calling the util to throw. I always feel it's not the util responsibiltiy to throw as depending on the context you only want to log (which forces a try catch) or to throw

**Review by charlesBochet — APPROVED** [review]
LGTM as the discussed pattern is already there
