### PR TITLE
Permission table fixes

### LINKED ISSUE #13865: field permissions table fixes
# Current behavior

Image

# Desired Behavior

remove the eye icon from the "see" label
Align label & checkbox to the left

Image

### PR DESCRIPTION
**Pull request by BKM14**
Closes #13865 
`IconEye` has been removed as specified in the issue. There was also a `PencilIcon` for the `Edit` section, which has been removed. The alignment issue was caused due to the `See` label being aligned to `center`, which has now been removed. An optional parameter `gridColumns` has been added to `StyledObjectFieldTableRow`. 

Adding a screenshot for reference:
image

### CODE REVIEW

File: packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx [hunk 1]
```diff
@@ -38,8 +38,11 @@ type SettingsObjectFieldItemTableRowProps = {
   mode: 'view' | 'new-field';
 };
 
-export const StyledObjectFieldTableRow = styled(TableRow)`
-  grid-auto-columns: 180px 148px 148px 36px;
+export const StyledObjectFieldTableRow = styled(TableRow)<{
```
Comment (FelixMalfait) [inline packages/twenty-front/src/modules/settings/data-model/object-details/components/SettingsObjectFieldItemTableRow.tsx]: This isn't very clean imo (mix of default + passed value, component seems internal to a file but exported). 
Let's not introduce `$gridColumns`, do two components if we need to, and potentially extract it into a file if it's used in multiple places

**Review by FelixMalfait — COMMENTED** [review]
Thank you! Almost there, one small comment

**Comment by BKM14** [comment]
@FelixMalfait, have made the changes, created another component in the same file as the table and removed `$gridColumns`

**Review by FelixMalfait — APPROVED** [review]
