### PR TITLE
Fix: keep the filter edition open if it is empty

### LINKED ISSUE #2967: Keep the filter edition open if it is empty
## Scope & Context

Filter dropdown input

## Current behavior

If we empty the filter input, it will delete the filter, and it's a problem because we might want to clear the input to type in something else without having to open it again.

https://github.com/twentyhq/twenty/assets/26528466/a1713f2e-04f4-45f1-ace1-30365a885ef1

## Expected behavior

We would like the filter dropdown to stay open if the input is empty, and trigger the filter reset only if we close the dropdown (by clicking outside) with an empty input.

It should work on every filter dropdown.

### PR DESCRIPTION
**Pull request by CzhCN0**
Closes #2967

### CODE REVIEW

File: packages/twenty-front/src/modules/views/hooks/internal/useViewFilters.ts [hunk 1]
```diff
@@ -209,10 +209,11 @@ export const useViewFilters = (viewScopeId: string) => {
               return filtersDraft;
             }
 
-            if (filterToUpsert.value === '') {
-              filtersDraft.splice(existingFilterIndex, 1);
-              return filtersDraft;
-            }
+            // Fixes #2967: Keep the filter edition open if it is empty
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/views/hooks/internal/useViewFilters.ts:212]: Using this kind of comment is generally considered a bad practice because git is already doing that job for us with blaming and proper commit messages. 

We can remove this code.

File: packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx [hunk 2]
```diff
@@ -61,6 +61,13 @@ export const EditableFilterDropdownButton = ({
     removeViewFilter(viewFilter.fieldMetadataId);
   };
 
+  const onClickOutside = useCallback(() => {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/views/components/EditableFilterDropdownButton.tsx:64]: Our handlers are always named with handleXYZ, so in this case it would be handleDropdownClickOutside.

**Review by lucasbordeau — DISMISSED** [review]

**Review by charlesBochet — APPROVED** [review]
It's looking good! Thanks for the help, it's much appreciated :)
