### PR TITLE
fix - newly added object not visible in left menu

### LINKED ISSUE #14190: Newly added object isn't visible in left menu
**Scenario**:
1. Log in
2. Go to Settings > Data model
3. Create new object
4. Go back to main menu

**Actual:** Newly added object isn't immediately visible

https://github.com/user-attachments/assets/2e66e9ed-49da-4009-b309-45e6372bc558

**Expected:** Newly added object is visible

**Workaround:** Refresh page

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #14190 

added refreshCoreViews() call after object creation to immediately update core views state, ensuring new objects appear in the navigation drawer without requiring a refresh

### CODE REVIEW

File: packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts [hunk 1]
```diff
@@ -132,6 +138,9 @@ export const DELETE_ONE_FIELD_METADATA_ITEM = gql`
       createdAt
       updatedAt
       settings
+      object {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-metadata/graphql/mutations.ts:141]: ***Remark:*** not necessary but agreed for consistency matters

**Review by prastoin — APPROVED** [review]
Really nice work !

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/__tests__/field-metadata-related-records.spec.ts [hunk 2]
```diff
@@ -21,11 +25,20 @@ type GetOptionsDifferencesTestContext = EachTestingContext<{
 describe('FieldMetadataRelatedRecordsService', () => {
   describe('getOptionsDifferences', () => {
     let service: FieldMetadataRelatedRecordsService;
-    let twentyORMGlobalManager: TwentyORMGlobalManager;
+    let viewService: ViewService = {} as ViewService;
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/__tests__/field-metadata-related-records.spec.ts:27]: ***Polish:*** could use real mock

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 3]
```diff
@@ -37,7 +35,11 @@ type GetOptionsDifferences = Differences<
 @Injectable()
 export class FieldMetadataRelatedRecordsService {
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts:37]: ***Remark:*** Unless I'm mistaken this file will get deprecated once introducing view in workspace migration v2

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 4]
```diff
@@ -306,97 +299,54 @@ export class FieldMetadataRelatedRecordsService {
...
+          (existingViewField) =>
+            existingViewField.fieldMetadataId === createdFieldMetadata.id,
         );
 
-        for (const createdFieldMetadata of createdFieldMetadatas) {
-          const views = await viewsRepository.find({
-            where: {
-              objectMetadataId: createdFieldMetadata.objectMetadataId,
-            },
+        if (!createdFieldIsAlreadyInView) {
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts]: ***Polish:*** early return/continue

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 5]
```diff
@@ -306,97 +299,54 @@ export class FieldMetadataRelatedRecordsService {
...
+      return;
+    }
 
-        const viewFieldsRepository = workspaceEntityManager.getRepository(
-          'viewField',
-          {
-            shouldBypassPermissionChecks: true,
-          },
+    for (const view of views) {
+      for (const createdFieldMetadata of createdFieldMetadatas) {
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts]: ***Remark:*** Iterating over all views instead of previously only one ? not same result

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts [hunk 6]
```diff
@@ -607,11 +605,6 @@ export class FieldMetadataService extends TypeOrmQueryService<FieldMetadataEntit
 
       await queryRunner.commitTransaction();
 
-      await this.viewService.resetKanbanAggregateOperationByFieldMetadataId({
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts:610]: ***Question:*** Cannot challenge motivations

Comment (prastoin) [reply packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata.service.ts:610]: From my understanding this should be called somewhere else

File: packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts [hunk 7]
```diff
@@ -17,20 +28,91 @@ export const useRefreshCoreViewsByObjectMetadataId = () => {
           fetchPolicy: 'network-only',
         });
 
+        const objectMetadataItems = snapshot
+          .getLoadable(objectMetadataItemsState)
+          .getValue();
+
+        const objectMetadataItem = objectMetadataItems.find(
+          (o) => o.id === objectMetadataId,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts]: ***Polish:*** naming

File: packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts [hunk 8]
```diff
@@ -17,20 +28,91 @@ export const useRefreshCoreViewsByObjectMetadataId = () => {
...
+          return;
+        }
+
         const coreViewsForObjectMetadataId = snapshot
           .getLoadable(
             coreViewsByObjectMetadataIdFamilySelector(objectMetadataId),
           )
           .getValue();
 
+        if (!isDefined(result.data?.getCoreViews)) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts]: ***Polish:*** Could be done higher in order to avoid un-necessary code flow

File: packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts [hunk 9]
```diff
@@ -17,20 +28,91 @@ export const useRefreshCoreViewsByObjectMetadataId = () => {
...
+            set(
+              currentRecordFieldsComponentState.atomFamily({
+                instanceId: getRecordIndexIdFromObjectNamePluralAndViewId(
+                  objectMetadataItem.namePlural,
+                  view.id,
+                ),
+              }),
+              view.viewFields
+                .filter(isDefined)
+                .map((v) => mapViewFieldToRecordField(v)),
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/useRefreshCoreViewsByObjectMetadataId.ts]: ***Nit:*** could pass method directly without having to pass arrow function

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 10]
```diff
@@ -37,7 +36,11 @@ type GetOptionsDifferences = Differences<
 @Injectable()
 export class FieldMetadataRelatedRecordsService {
   constructor(
-    private readonly twentyORMGlobalManager: TwentyORMGlobalManager,
+    private readonly viewService: ViewService,
+    private readonly viewFieldService: ViewFieldService,
+    private readonly viewSortService: ViewSortService,
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts]: ***Nit:*** unused

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 11]
```diff
@@ -306,97 +300,59 @@ export class FieldMetadataRelatedRecordsService {
...
+      return;
+    }
 
-        const viewFieldsRepository = workspaceEntityManager.getRepository(
-          'viewField',
-          {
-            shouldBypassPermissionChecks: true,
-          },
-        );
+    const view = views.find((view) => view.key === ViewKey.INDEX);
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts]: cool

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 12]
```diff
@@ -306,97 +300,59 @@ export class FieldMetadataRelatedRecordsService {
...
     createdFieldMetadatas: FieldMetadataEntity[],
     workspaceId: string,
   ) {
-    const workspaceDataSource =
-      await this.twentyORMGlobalManager.getDataSourceForWorkspace({
-        workspaceId,
-      });
+    const views = await this.viewService.findByObjectMetadataId(
+      workspaceId,
+      createdFieldMetadatas[0].objectMetadataId,
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts]: ***Remark:*** This assumes that we have at least one element in our array, also in case of in case of a morph of a relation field we would iterate over each object metadata id

**Review by prastoin — COMMENTED** [review]
Regression on created object metadata which now only runs on first created instead of all

**Comment by charlesBochet** [comment]
@vinaybadgujar102 Thanks a lot for opening a PR. While reviewing, I've noticed that the problem was way larger that the original scope and used it as an occasion to treat the whole problem.

1) The optimistic rendering issue was larger than the object creation case: we also need to take care of field update / delete / create
2) The optimistic rendering logic on field side was broken. it's still very fragile but we've discussed it internally and we will revisit this soon with a more long term plan
3) the backend logic to update views on object / field change was not robust: we were updating a legacy system of workspace views and syncing the new core view system of top of it. I have removed it and re-coded the logic
4) Also fixed a few minor design issues on viewFilters.value
5) Rework the duplicate viewField error message to add userFriendlyMessage

**Comment by charlesBochet** [comment]
Regarding QA, I've tested it:
- adding / updating / deleting object
- adding / updating / deleting fields x viewFilter / viewSort / viewGroup / KanbanAggregate x types (SELECT | RELATION | TEXT | MULTISELECT)

**Comment by vinaybadgujar102** [comment]
> @vinaybadgujar102 Thanks a lot for opening a PR. While reviewing, I've noticed that the problem was way larger that the original scope and used it as an occasion to treat the whole problem.

@charlesBochet thanks for the response! This was my first time making changes in this codebase so I had very little context. I knew my solution wasn’t optimal, but I wanted to give it a try and learn from the feedback

File: packages/twenty-server/src/engine/core-modules/view/services/view-field.service.ts [hunk 13]
```diff
@@ -107,9 +107,29 @@ export class ViewFieldService {
...
-    const viewField = this.viewFieldRepository.create(viewFieldData);
-
-    return this.viewFieldRepository.save(viewField);
+    try {
+      const viewField = this.viewFieldRepository.create(viewFieldData);
+
+      return await this.viewFieldRepository.save(viewField);
+    } catch (error) {
+      if (
+        error.message.includes('duplicate key value violates unique constraint')
```
Comment (prastoin) [inline packages/twenty-server/src/engine/core-modules/view/services/view-field.service.ts:116]: ***Nitpick:*** IMO Not very reliable. Could involved any others column depending on existing constraint in addition of the primary key one.
Would recommend checking if colliding row with same id exists before, we can ignore this in this PR as this will be way easier and cheaper to be done through viewMaps cache read interaction added by upcoming Coco's refactor

File: packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts [hunk 14]
```diff
@@ -22,6 +29,20 @@ export const getRecordFilterLabelValue = (recordFilter: RecordFilter) => {
         return `${operandLabelShort} ${recordFilter.displayValue}`;
     }
   }
+  if (recordFilter.type === 'SELECT' || recordFilter.type === 'MULTI_SELECT') {
+    const valueArray = JSON.parse(recordFilter.value);
+
+    if (!Array.isArray(valueArray)) {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts:35]: ***Question:*** Unless I'm mistaken this is paradoxical with `recordFilter.type === 'SELECT'` ? From my understanding a select filter value is not an array but an atomic option value ?

File: packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts [hunk 15]
```diff
@@ -22,6 +29,20 @@ export const getRecordFilterLabelValue = (recordFilter: RecordFilter) => {
         return `${operandLabelShort} ${recordFilter.displayValue}`;
     }
   }
+  if (recordFilter.type === 'SELECT' || recordFilter.type === 'MULTI_SELECT') {
+    const valueArray = JSON.parse(recordFilter.value);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts:33]: ***Nitpick:*** Unless I'm mistaken we should user safe `parseJson` here, also passing a generic

File: packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts [hunk 16]
```diff
@@ -22,6 +29,20 @@ export const getRecordFilterLabelValue = (recordFilter: RecordFilter) => {
         return `${operandLabelShort} ${recordFilter.displayValue}`;
     }
   }
+  if (recordFilter.type === 'SELECT' || recordFilter.type === 'MULTI_SELECT') {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/utils/getRecordFilterLabelValue.ts:32]: ***Nitpick:*** Unless I'm mistaken we could add intersection on `isDefined(fieldMetadataOptions) && fieldMetadataOptions.length > 0`

File: packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts [hunk 17]
```diff
@@ -86,7 +86,7 @@ export const usePersistViewFilterRecords = () => {
             variables: {
               id: viewFilter.id,
               input: {
-                value: viewFilter.value,
+                value: parseJson(viewFilter.value),
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts:89]: ***Remark:*** We should definitly refactor the Scalars primitives entries not to be any

File: packages/twenty-front/src/modules/views/components/EditableFilterChip.tsx [hunk 18]
```diff
@@ -44,7 +44,10 @@ export const EditableFilterChip = ({
     : recordFilter.label;
 
   const labelKey = `${fieldNameLabel}`;
-  const labelValue = getRecordFilterLabelValue(recordFilter);
+  const labelValue = getRecordFilterLabelValue({
+    recordFilter,
+    fieldMetadataOptions: fieldMetadataItem.options ?? [],
```
Comment (prastoin) [inline packages/twenty-front/src/modules/views/components/EditableFilterChip.tsx:49]: ***Question:*** Shouldn't this fallback on undefined ?

File: packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts [hunk 19]
```diff
@@ -156,29 +175,29 @@ export class FieldMetadataRelatedRecordsService {
...
+
+        if (!isDefined(parsedValue) || !Array.isArray(parsedValue)) {
           throw new FieldMetadataException(
             `Unexpected invalid view filter value for filter ${viewFilter.id}`,
             FieldMetadataExceptionCode.INTERNAL_SERVER_ERROR,
           );
         }
 
-        const viewFilterOptions = viewFilterValue
+        const viewFilterOptions = parsedValue
```
Comment (prastoin) [inline packages/twenty-server/src/engine/metadata-modules/field-metadata/services/field-metadata-related-records.service.ts:200]: ***Remark:*** any[]

File: packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts [hunk 20]
```diff
@@ -278,41 +253,31 @@ describe('update-one-field-metadata-related-record', () => {
...
         }
         expect(updatedOptions.map((option) => option.value)).toEqual(
-          expect.arrayContaining(parsedViewFilterValues),
+          expect.arrayContaining(updatedViewFilter.value as string[]),
         );
 
-        expect(findResponse).toMatchSnapshot({
-          id: expect.any(String),
-        });
+        expect(updatedViewFilter.value).toMatchSnapshot();
```
Comment (prastoin) [inline packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts:280]: ***Polish:*** Would include the whole filter in the snapshot

**Review by prastoin — APPROVED** [review]
Left several comments but nothing blocking IMO !
Well done !!

File: packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts (hunk 20 above)
Comment (charlesBochet) [reply packages/twenty-server/test/integration/metadata/suites/field-metadata/update-one-field-metadata-related-record.integration-spec.ts:280]: the new API is retruning relations even if you don't ask for them (rest), maybe we should check a subset of the fields (value + fieldMetadataId + operand is what matters actualy)

File: packages/twenty-server/test/integration/graphql/suites/view/view-filter-group-resolver.integration-spec.ts [hunk 21]
```diff
@@ -41,10 +41,10 @@ describe('View Filter Group Resolver', () => {
...
       input: {
-        nameSingular: 'myTestObject',
-        namePlural: 'myTestObjects',
-        labelSingular: 'My Test Object',
-        labelPlural: 'My Test Objects',
+        nameSingular: 'myFilterGroupTestObject',
+        namePlural: 'myFilterGroupTestObjects',
+        labelSingular: 'My Filter Group Test Object',
+        labelPlural: 'My Filter Group Test Objects',
         icon: 'Icon123',
```
Comment (prastoin) [inline packages/twenty-server/test/integration/graphql/suites/view/view-filter-group-resolver.integration-spec.ts:48]: ***Remark:*** I We can pass `expectToFail: false` when using fetchers in jest hooks, so the test suite would error if the required steps fails to be done

File: packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts (hunk 17 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts:89]: regression :(

Comment (prastoin) [reply packages/twenty-front/src/modules/views/hooks/internal/usePersistViewFilterRecords.ts:89]: Which one exactly ? @charlesBochet 
Are you working on main right now ?
