### PR TITLE
Fixes date filter chip bugs

### LINKED ISSUE #12778: Selecting relative date filter is crashing the page
When selecting the "relative" operand for a date filter, the page crashes.

Image

### PR DESCRIPTION
**Pull request by lucasbordeau**
This PR fixes a bug that occurs during filter operand changes.

As a date filter can contain values that have a different shape, mainly date ISO string and hard-coded relative dates, changing the operand without resetting the value to its default was causing a crash.

This PR also extracts the logic that computes the right part of a filter chip into a util instead of a difficult to understand ternary, thus solving small bugs in the value displayed also.

Fixes https://github.com/twentyhq/twenty/issues/12778

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useApplyObjectFilterDropdownOperand.ts [hunk 1]
```diff
@@ -62,12 +63,40 @@ export const useApplyObjectFilterDropdownOperand = () => {
...
+    if (
+      isDefined(recordFilterToUpsert) &&
+      (recordFilterToUpsert.type === 'DATE' ||
+        recordFilterToUpsert.type === 'DATE_TIME')
+    ) {
+      if (
+        recordFilterToUpsert.operand === RecordFilterOperand.Is ||
+        recordFilterToUpsert.operand === RecordFilterOperand.IsNot ||
+        recordFilterToUpsert.operand === RecordFilterOperand.IsAfter ||
+        recordFilterToUpsert.operand === RecordFilterOperand.IsBefore
```
Comment (bosiraphael) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/hooks/useApplyObjectFilterDropdownOperand.ts]: Maybe we could create a constant with this value to improve readability

**Review by bosiraphael — APPROVED** [review]
LGTM, left a comment
