### PR TITLE
Fix spacing issue on show page

### LINKED ISSUE #607: Spacing issue - Page details
Spacing (gap) is 8px instead of 2px

# Online
Image

# Figma
Image

### PR DESCRIPTION
**Pull request by FelixMalfait**
Fixes : https://github.com/twentyhq/twenty/issues/607

Screenshot 2023-07-12 at 09 44 14

### CODE REVIEW

File: front/src/modules/ui/components/property-box/PropertyBox.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ const StyledPropertyBoxContainer = styled.div`
   border-radius: ${({ theme }) => theme.border.radius.sm};
   display: flex;
   flex-direction: column;
-  gap: ${({ theme }) => theme.spacing(2)};
+  gap: ${({ theme }) => theme.spacing(0.5)};
```
Comment (charlesBochet) [inline front/src/modules/ui/components/property-box/PropertyBox.tsx:10]: I'm approving this PR but we need to have a discussion with Thomas on spacing between. The goal of the spacing function is to enforce spacing to be a multiple of 4px. Here we are hacking it to get 2px.
So should the step be 2px? Is this an exception for spacing between vertical elements?

**Review by charlesBochet — APPROVED** [review]
