### PR TITLE
Fix last row disappearing when dragging a row in the table

### LINKED ISSUE #836: Tables - when drag and drop record on table, last one is disappearing
as you can see in the video, it's only when hovering the table with the selected record. maybe the "empty line space" added by the library should be take in into account when creating the table height.

https://github.com/user-attachments/assets/230ba5f8-d1cf-4a20-9fc4-06b320a39562

### PR DESCRIPTION
**Pull request by bosiraphael**
# Fix last row disappearing when dragging a row in the table

Fixes https://github.com/twentyhq/core-team-issues/issues/836

The issue came from the fact that the provided placeholder was not mounted at the right place (after the footer when it should be mounted before it).

I created a context to which we can pass the placeholder. We can use this placeholder anywhere inside the table by using `RecordTableBodyDroppablePlaceholder`.

## Before

https://github.com/user-attachments/assets/39a2e45b-6d97-4450-bfee-12135a873a1d

## After

https://github.com/user-attachments/assets/ca126819-67f2-4358-b644-85172fef3b8f

### CODE REVIEW

File: packages/twenty-ui/src/utilities/index.ts [hunk 1]
```diff
@@ -24,5 +24,6 @@ export { isModifiedEvent } from './events/isModifiedEvent';
 export { useIsMobile } from './responsive/hooks/useIsMobile';
 export { useScreenSize } from './screen-size/hooks/useScreenSize';
 export { createState } from './state/utils/createState';
+export type { ClickOutsideAttributes } from './types/ClickOutsideAttributes';
```
Comment (bosiraphael) [inline packages/twenty-ui/src/utilities/index.ts:27]: This is because I forgot to commit it inside my previous PR

**Review by etiennejouan — APPROVED** [review]
Nice !👏  
(Tested on RecordGroup and NoRecordGroup)

File: packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx [hunk 2]
```diff
@@ -57,6 +58,7 @@ export const RecordTableRecordGroupRows = () => {
       })}
       <RecordTableRecordGroupSectionLoadMore />
       <RecordTableRecordGroupSectionAddNew />
+      <RecordTableBodyDroppablePlaceholder />
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/object-record/record-table/components/RecordTableRecordGroupRows.tsx:61]:
```suggestion
      <RecordTableBodyDroppablePlaceholder />
      <RecordTableRecordGroupSectionLoadMore />
      <RecordTableRecordGroupSectionAddNew />
```
