### PR TITLE
fix(admin-panel): prevent layout shift when toggling feature flags

### LINKED ISSUE #12571: Updating a feature flag breaks admin panel design
## Bug Description

https://github.com/user-attachments/assets/67a377f2-0401-48c3-9d7c-7a45ed740360

## Expected behavior

Updating a feature flag should preserves current design

### PR DESCRIPTION
**Pull request by ehconitin**
Closes #12571
~~## What’s broken?~~
~~Toggling a feature flag in the admin panel re-renders the entire table and uses a Framer Motion slide animation for the knob. Each animation frame forces a layout recalculation all the way up, causing the page to “jump.”~~

~~## What’s the fix?~~
~~Swap out the Framer Motion toggle for a pure-CSS version:~~
~~- Container is position: relative~~
~~- Knob is position: absolute and moves via left~~
~~- A transition: left 0.3s ease + will-change: left hint runs on the compositor layer~~

~~This keeps the smooth slide effect but never triggers parent layout reflows.~~

~~No changes to the public <Toggle> API or behavior.~~

~~TODO: test all toggles in app and stories if any~~

### CODE REVIEW

**Comment by ehconitin** [comment]
The question is -- why now though?
The last commit on toggle seems to be 7 months old. 
Which makes me believe it was working fine with framer before?

TODO: find what changed :)

**Review by charlesBochet — COMMENTED** [review]
TY @ehconitin, I'm not sure to understand how the toggle animation can have such impacts on the whole page

**Comment by charlesBochet** [comment]
> TY @ehconitin, I'm not sure to understand how the toggle animation can have such impacts on the whole page

Super weird behavior, I can reproduce locally but I don't get it!

**Review by charlesBochet — CHANGES_REQUESTED** [review]
I'm not entirely sure why but it seems that animations are breaking the flex display and making everything to shift up like if there was not enough space.

This can be solved by making sure what's animated is in position absolute and doesn't interfere with flexbox.
- you should achieve the same result without removing framer motion by just adding a position: relative to Toggle StlyedContainer and position: absolute to StyledCircle

**Comment by ehconitin** [comment]
@charlesBochet Agree!
This was very hard to debug.
Added stories for the toggle. Thanks!

File: packages/twenty-ui/src/input/components/Toggle.tsx [hunk 1]
```diff
@@ -12,29 +12,34 @@ type ContainerProps = {
...
-  display: block;
   background-color: ${({ theme }) => theme.background.primary};
   border-radius: 50%;
+  display: block;
   height: ${({ size }) => (size === 'small' ? 12 : 16)}px;
+  left: 0;
+  position: absolute;
+  top: 50%;
   width: ${({ size }) => (size === 'small' ? 12 : 16)}px;
+  will-change: transform;
```
Comment (charlesBochet) [inline packages/twenty-ui/src/input/components/Toggle.tsx]: is this useful?

File: packages/twenty-ui/src/input/components/Toggle.tsx [hunk 2]
```diff
@@ -57,8 +62,8 @@ export const Toggle = ({
   disabled,
 }: ToggleProps) => {
   const circleVariants = {
-    on: { x: toggleSize === 'small' ? 10 : 14 },
-    off: { x: 2 },
+    on: { x: toggleSize === 'small' ? 10 : 14, y: '-50%' },
+    off: { x: 2, y: '-50%' },
```
Comment (charlesBochet) [inline packages/twenty-ui/src/input/components/Toggle.tsx]: is this useful too?

**Review by charlesBochet — APPROVED** [review]
Looks to be working fine with me without adding extra top: 50%
