### PR TITLE
fix incorrect data in sample export

### LINKED ISSUE #14928: Sample import files contain incorrect data
**Scenario:**
1. Log in
2. Go to e.g. People
3. Open command menu (by pressing CMD/Ctrl + K)
4. Select Import records option
5. Download sample file and open it in Excel or any csv editor

**Actual:** Sample file contains incorrect data (invalid UUID as record's ID, [Object object] as Additional links, etc.)

[people-sample.csv](https://github.com/user-attachments/files/22736438/people-sample.csv)

**Expected:** Sample file should contain correct data to show users how to correctly import data

### PR DESCRIPTION
**Pull request by etiennejouan**
fixes https://github.com/twentyhq/twenty/issues/14928
introduced by https://github.com/twentyhq/twenty/pull/14347

### CODE REVIEW

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts [hunk 1]
```diff
@@ -123,9 +123,11 @@ export const useDownloadFakeRecords = () => {
...
-        formatValueForCSV(sanitizeValueForCSVExport(value)),
-      );
+      return row.map((value) => {
+        const stringifiedValue =
+          typeof value === 'string' ? value : JSON.stringify(value);
+        return formatValueForCSV(sanitizeValueForCSVExport(stringifiedValue));
+      });
     });
 
     const csvContent = [...escapedRows.map((row) => row.join(','))].join('\n');
```
Comment (Weiko) [inline packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts]: array spread seems redundant and intermediate variable seems unnecessary.

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts [hunk 2]
```diff
@@ -123,9 +123,11 @@ export const useDownloadFakeRecords = () => {
 
   const formatToCsvContent = (rows: string[][]) => {
     const escapedRows = rows.map((row) => {
-      return row.map((value) =>
-        formatValueForCSV(sanitizeValueForCSVExport(value)),
-      );
+      return row.map((value) => {
+        const stringifiedValue =
```
Comment (Weiko) [inline packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts:127]: Interesting, it seems the function parameter is wrong then 🤔 (string[][]). Do we expect other non-string primitives such as number, bool, etc?

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts [hunk 3]
```diff
@@ -123,9 +123,11 @@ export const useDownloadFakeRecords = () => {
...
+          typeof value === 'string' ? value : JSON.stringify(value);
```
Comment (Weiko) [inline packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts:128]: We are calling stringify on everything that is not a string, is it expected or do we only want to call it on objects?

**Review by Weiko — APPROVED** [review]
Left some comments otherwise LGTM! @etiennejouan

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts (hunk 2 above)
Comment (etiennejouan) [reply packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts:127]: Only string, JSON or string[] (from exampleValues prop on `SETTINGS_COMPOSITE_FIELD_TYPE_CONFIGS` constant)

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts (hunk 3 above)
Comment (etiennejouan) [reply packages/twenty-front/src/modules/spreadsheet-import/steps/components/UploadStep/hooks/useDownloadFakeRecords.ts:128]: I correct input typing : string, JSON or string[]
