### PR TITLE
fix: improve full name editable fields in Person Show page

### LINKED ISSUE #910: Update show title edition style
# Actual behavior

https://github.com/twentyhq/twenty/assets/19412894/aad96d43-2a57-4aba-af49-de08e044bddc

# Desired behavior

Keep the edition in place (Don't add an input above when clicking to edit). Add a Transparent light background behind the editable fields. Resize automatically (hug content) and maintain centered the two fields in the medium of the column (even while editing)

Using tab should switch from First name to last name. 

https://github.com/twentyhq/twenty/assets/19412894/c53a309a-8279-4704-9208-53bb224510e3

### PR DESCRIPTION
**Pull request by thaisguigon**
+ autoresize inputs according to their content
+ use "Empty" as placeholder
+ improve hover style

Closes #910

### CODE REVIEW

File: front/src/modules/ui/input/double-text/components/DoubleTextInputEdit.tsx [hunk 1]
```diff
@@ -33,24 +41,34 @@ export function DoubleTextInputEdit({
...
-      <StyledNameInput
-        size={secondValue.length}
-        autoComplete="off"
-        placeholder={secondValuePlaceholder}
-        value={secondValue}
-        onChange={(event: ChangeEvent<HTMLInputElement>) => {
-          onChange(firstValue, event.target.value);
-        }}
-      />
+      <TemplateDimensionsEffect template={firstValue || firstValuePlaceholder}>
```
Comment (charlesBochet) [inline front/src/modules/ui/input/double-text/components/DoubleTextInputEdit.tsx:44]: I like the API but I think that "Template" keyword is not clear
What about: `ComputeNodeDimensions` and `node`?

**Review by charlesBochet — APPROVED** [review]
I really like the API you are proposing! Nice one

**Review by Weiko — APPROVED** [review]
