### PR TITLE
fix: On Sign Out > Sign In, States are not loaded properly

### LINKED ISSUE #3026: On Sign Out > Sign In, States are not loaded properly
## Bug Description

I have noticed that if, as a logged in user, you sign out. All recoil states are erased. This is causing multiple issues:
- ClientConfig is not properly loaded anymore (so Google SSO button disappears for example)
- If you sign in again, Icons are missing
image

## Technical inputs

I think it is related to the `handleSignOut` function in `useAuth` and especially:
`goToRecoilSnapshot(snapshot_UNSTABLE());`

What we want is to reset all recoil states except: clientConfigState + iconsState

### PR DESCRIPTION
**Pull request by a-kud**
FIxes #3026 
Before:
imagen

After:
imagen

### CODE REVIEW

File: packages/twenty-front/src/modules/auth/hooks/useAuth.ts [hunk 1]
```diff
@@ -126,13 +125,23 @@ export const useAuth = () => {
   );
 
   const handleSignOut = useCallback(() => {
-    goToRecoilSnapshot(snapshot_UNSTABLE());
     setTokenPair(null);
     setCurrentUser(null);
+    setCurrentWorkspaceMember(null);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/hooks/useAuth.ts:130]: @a-kud we actually would like to keep removing all recoil states (table contents, favorites, ...) but keep the iconsState + clientConfigState.

can we try to transform handleSignOut into a useRecoilCallback() and to keep goToRecoilSnapshot(snapshot_UNSTABLE()) but get the content if iconsState and clientConfigState before (from snapshot to avoid re-renders, that's the point of using a useRecoilCallback) an re-set it after?

Comment (a-kud) [reply packages/twenty-front/src/modules/auth/hooks/useAuth.ts:130]: can you elaborate, please?
should it look like something like this?
```const handleSignOut = useRecoilCallback(
  ({ snapshot, reset, set }) => async () => {

    const iconsValue = snapshot.getLoadable(iconsState).contents;
    const clientConfigValue = snapshot.getLoadable(clientConfigState).contents;

    reset(currentUserState);
    reset(currentWorkspaceMemberState);
    reset(currentWorkspaceState);
    reset(isVerifyPendingState);
    reset(tokenPairState);
    
    await client.clearStore();
    sessionStorage.clear();

    set(iconsState, iconsValue);
    set(clientConfigState, clientConfigValue);
  },
  [],
);```

Comment (charlesBochet) [reply packages/twenty-front/src/modules/auth/hooks/useAuth.ts:130]: Yes, exactly!

**Comment by charlesBochet** [comment]
@a-kud Let me know if you need more help on this one!

File: packages/twenty-front/src/modules/auth/hooks/useAuth.ts (hunk 1 above)
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/auth/hooks/useAuth.ts:130]: A clean way of doing it would to craft the initial snapshot we want by using .map() like this : 

```typescript
const emptySnapshot = snapshot_UNSTABLE()

const initialSnapshot = emptySnapshot.map(({ set }) => {
  set(iconsState, iconsValue);
  set(clientConfigState, clientConfigValue);
});

goToRecoilSnapshot(initialSnapshot)
```

Then to obtain `iconsValue` and `clientConfigValue` we can either use a useRecoilCallback that will just read those two states or directly using `useRecoilValue`.

**Comment by a-kud** [comment]
> @a-kud Let me know if you need more help on this one!

there's no `clientConfigState` how do I retrieve it?

**Comment by charlesBochet** [comment]
You are right, we actually have 6 states to maintain (all located in packages/twenty-front/src/modules/client-config/states)

**Comment by a-kud** [comment]
@charlesBochet @lucasbordeau ready for review

**Review by charlesBochet — APPROVED** [review]
@a-kud Looks good! I've merged main into your branch, just waiting for the tests to pass and we merge it!
