### PR TITLE
Import - fixes

### LINKED ISSUE #11623: When importing Companies as .xlsx with multiple sheets, the "Select header row" dialog does not accept clicks?
## Bug Description

When I try to import Companies from an .xlsx spreadsheet with multiple sheets, I am firs asked what sheet to import from. I select one and click Next. Then I am asked to select the header row in the dialog shown below. 
In this dialog, I am unable to select the first row (the header). It does not seem to accept my click.
Probably the first row should be preselected as the first row is likely the header row in at least 9 out of 10 cases. 

Browser is Safari.

Image

## Expected behavior

When I click the Checkbox next to first row or the row itself, the specified row should be selected.

 
## Technical inputs

Twenty v0.51.1

Deployed on Linux host using containers.

Client details: 
OS: MacOS Seqouia
Browser: Safari

### PR DESCRIPTION
**Pull request by etiennejouan**
- Fixes : https://github.com/twentyhq/twenty/issues/11623
- Design fix : https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=61976-118483&t=z12YCJg7W7PFMcmg-4

After
Screenshot 2025-07-08 at 11 52 26

Before
Screenshot 2025-07-08 at 11 23 08

### CODE REVIEW

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx [hunk 1]
```diff
@@ -27,8 +27,8 @@ export const SelectHeaderTable = ({
       rowKeyGetter={(row: any) => importedRows.indexOf(row)}
       rows={importedRows}
       columns={columns}
-      selectedRowIndexes={selectedRowIndexes}
-      onSelectedRowIndexesChange={(newRowIndexes: number[]) => {
+      selectedRows={selectedRowIndexes}
```
Comment (Weiko) [inline packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx:30]: Why this change? Should we rename the props as well then?

**Review by Weiko — APPROVED** [review]
LGTM

File: packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx (hunk 1 above)
Comment (charlesBochet) [reply packages/twenty-front/src/modules/spreadsheet-import/steps/components/SelectHeaderStep/components/SelectHeaderTable.tsx:30]: I took a look: typing was very bad because react-data-grid is not exposing proper type and there was a type ignore in SpreadsheetImportTable.
As a result, these selectedRowIndexes do not exist on SpreadsheetImportTable and no ts error was raised
See my changes here (I'm using Pick to make sure ts understands issues

**Review by charlesBochet — APPROVED** [review]
