### PR TITLE
fix: Display multipicker on Created By source filter

### LINKED ISSUE #9674: Display multipicker on "Created By" source filter
# Current behavior

https://github.com/user-attachments/assets/e55b9c47-2324-45ce-adaa-2205ef82e8d4

# Desired Behavior

Image

### PR DESCRIPTION
**Pull request by Paribesh01**
fix: #9674 

When the selected filter is Is and the field type is ACTOR, we now show ObjectFilterDropdownSourceSelect instead of a text input. This ensures proper selection for actor-based filters. Also previously, when a user changed the selected option, all default values were getting wiped out so i have made some changes in updatedSelectedItems

Loom video: https://www.loom.com/share/8b80a78d5e8c4a5192d69cab96f0c838?sid=5bd76fff-7cd4-4e3c-8c48-d1c9e4e95651

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hi @Paribesh01 thank you for contributing, this works well.

Could you please see those other associated problems ?

The operator list is still not correct : 

image

image

The filter from table column is still not correct : 

image


image

**Comment by Paribesh01** [comment]
@lucasbordeau fixed the operator list, but for the header part should I create a submenu to select

**Comment by Paribesh01** [comment]
@lucasbordeau done with the filter 
https://www.loom.com/share/32040a5ac4034b5aba00dc86b8309313?sid=a67298a4-679c-4cf0-8553-c80f86888f81

File: packages/twenty-front/src/modules/object-record/record-filter/utils/getRecordFilterOperands.ts [hunk 1]
```diff
@@ -78,11 +78,7 @@ export const getRecordFilterOperands = ({
       ];
     case 'ACTOR': {
       if (isFilterOnActorSourceSubField(subFieldName)) {
-        return [
-          RecordFilterOperand.Is,
-          RecordFilterOperand.IsNot,
-          ...emptyOperands,
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-filter/utils/getRecordFilterOperands.ts:84]: ***Remark:*** Unless I'm mistaken an Actor can be empty

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx [hunk 2]
```diff
@@ -62,10 +62,20 @@ export const ObjectFilterDropdownSourceSelect = ({
   const sourceTypes = getActorSourceMultiSelectOptions(
     objectFilterDropdownSelectedRecordIds,
   );
-
-  const filteredSelectedItems = sourceTypes.filter((option) =>
-    objectFilterDropdownSelectedRecordIds.includes(option.id),
-  );
+  const selectedFilterValues = Array.isArray(selectedFilter?.value)
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:65]: ***Suggestion:*** We should not make assertion at runtime on the current data like, we should determine its integrity using a discriminated union.
If there's no other solution then we should break this ternary into several human readable statements.

***Change:*** `selectedFilterValues` is atm typed as any

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx [hunk 3]
```diff
@@ -62,10 +62,20 @@ export const ObjectFilterDropdownSourceSelect = ({
...
+    ? selectedFilter.value
+    : isDefined(selectedFilter?.value) &&
+        typeof selectedFilter.value === 'string' &&
+        selectedFilter.value.trim() !== ''
+      ? JSON.parse(selectedFilter.value)
+      : [];
+
+  const filteredSelectedItems = sourceTypes
+    .filter((option) => selectedFilterValues.includes(option.id))
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:74]: ***Change:*** Unless I'm mistaken we never transpile `selectedFilterValues` from `RecordFilter[]` to `string[]`. Then the includes here by definition cannot work
TypeScript not throwing an error as inferred as `any` due to nested ternary and so on

File: packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadDropdownMenu.tsx [hunk 4]
```diff
@@ -77,58 +96,85 @@ export const RecordTableColumnHeadDropdownMenu = ({
...
-  };
-
   const isSortable = column.isSortable === true;
   const isFilterable = column.isFilterable === true;
   const showSeparator =
     (isFilterable || isSortable) && column.isLabelIdentifier !== true;
   const canHide = column.isLabelIdentifier !== true;
 
+  const handleFilterClick = () => {
+    if (column.type === 'ACTOR') {
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadDropdownMenu.tsx:109]: ***Nitpick:*** Use enum

File: packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadWithDropdown.tsx [hunk 5]
```diff
@@ -23,6 +24,8 @@ export const RecordTableColumnHeadWithDropdown = ({
   const { toggleScrollXWrapper, toggleScrollYWrapper } =
     useToggleScrollWrapper();
 
+  const filterDropdownId = 'view-filter';
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/record-table/record-table-header/components/RecordTableColumnHeadWithDropdown.tsx:27]: ***Suggestion:*** Could less generic

**Review by prastoin — CHANGES_REQUESTED** [review]
Hello there ! Thanks @Paribesh01 for your contribution
First review here ! about to dig deeper in local
Overall my first and very subjective feeling is that it seems like quite hacky and bring a double reading to the existing filters, might be interesting to create a dedicated abstraction to handle classic filters and relations filters

### Notes
Rebased, fixed conflicts lints and tsc errors on your branch.
Also refactored few nitpicks

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelectCompositeFieldSubMenu.tsx [hunk 6]
```diff
@@ -21,11 +21,17 @@ import { DropdownMenuItemsContainer } from '@/ui/layout/dropdown/components/Drop
...
 import { useSetRecoilComponentStateV2 } from '@/ui/utilities/state/component-state/hooks/useSetRecoilComponentStateV2';
+import { ViewFilterOperand } from '@/views/types/ViewFilterOperand';
 import { useState } from 'react';
-import { IconApps, IconChevronLeft, MenuItem, useIcons } from 'twenty-ui';
 import { isDefined } from 'twenty-shared/utils';
+import { IconApps, IconChevronLeft, MenuItem, useIcons } from 'twenty-ui';
 
-export const ObjectFilterDropdownFilterSelectCompositeFieldSubMenu = () => {
+type ObjectFilterDropdownFilterSelectCompositeFieldSubMenuProps = {
+  handelAddFilterForActor: (id: string, operand?: ViewFilterOperand) => void;
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterSelectCompositeFieldSubMenu.tsx:30]: ***Remark:*** Unless I'm mistaken should be optional, atm raising ts errors to existing `ObjectFilterDropdownFilterSelectCompositeFieldSubMenuProps` invokations

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx (hunk 2 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:65]: `selectedFilter?.value` should never be an array

Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx]: Refactored

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx (hunk 3 above)
Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:67]: Refactored

**Comment by prastoin** [comment]
***Bug/Feat:*** It seems like un-checking filters does not "reset" the filters

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx [hunk 7]
```diff
@@ -70,12 +70,20 @@ export const ObjectFilterDropdownFilterInput = ({
     subFieldNameUsedInDropdown,
   );
 
+  const isActorAndIsOperand =
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownFilterInput.tsx:73]: ***Nitpick:*** Could be factorized

File: packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx [hunk 8]
```diff
@@ -79,21 +82,30 @@ export const ObjectFilterDropdownSourceSelect = ({
...
+        recordFilter.fieldMetadataId ===
+        fieldMetadataItemUsedInFilterDropdown.id,
+    );
+
+    const filterId = recordFilter?.id ?? fieldId;
+    const recordFilterId = selectedFilter?.id ? selectedFilter.id : filterId;
+
     if (newSelectedItemIds.length === 0) {
       emptyRecordFilter();
-      removeRecordFilter(fieldMetadataItemUsedInFilterDropdown.id);
```
Comment (prastoin) [inline packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:96]: ***Bug:*** This is a know issue, please refer to https://github.com/twentyhq/core-team-issues/issues/445
This is not the first I find a bug due to `Scalars` `any` inference. In my opinion this more `critical` bug type than `high` as it hides several undetermined behavior

Comment (prastoin) [reply packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownSourceSelect.tsx:96]: ***Question:*** we might not want to remove the filter on an empty selection but trigger it with none ?

**Review by prastoin — COMMENTED** [review]
Hello there, unless I'm mistaken this should now be ready to be reviewed.
Last point about record filter deletion on all filters value de-selection to determine + UX concerns on checked filters sort order
Please let me know !
@FelixMalfait @lucasbordeau

**Comment by lucasbordeau** [comment]
Thank you for this review, I'll take over this PR, and add the last changes.

**Comment by lucasbordeau** [comment]
I reverted most of the initial changes because they were not aligned with our code guidelines. 

This area of the code is complex and contains different legacy code versions mixed together, that requires an historical context on the codebase to be handled properly, which cannot be expected from an open source contributor.

Plus I'm in the process of refactoring and implementing what's missing for handling sub field filtering in this area, so it wasn't really useful to go further away than fixing this precise issue for the source sub field.

The key here was to rely on the less than ideal EditableFilterDropdownButtonEffect component (which hopefully will be removed soon) that synchronizes the dropdown states with the record filter it is related to, I just added the missing states that were not synchronized.

**Review by lucasbordeau — APPROVED** [review]

**Review by prastoin — APPROVED** [review]
Nice job !
