### PR TITLE
fix: Auto Reset Opportunity Creation Search Field

### LINKED ISSUE #4923: Auto-Reset for Opportunity Creation Search Field
# Current Behavior

The search field retains the previous company name when creating a new opportunity.

https://github.com/twentyhq/twenty/assets/19412894/d9b7fb77-fca4-47ce-b96e-c2448c426768

# Desired Behavior

The search field should reset to blank each time the opportunity creation picker is opened.

### PR DESCRIPTION
**Pull request by agupta0001**
## Description

In the previous implementation, we saved the user's search field input. However, I have introduced a new prop called `clearOnOpen`, which allows us to reset the search field upon loading.

Closes: #4923 

https://github.com/twentyhq/twenty/assets/95065270/dd2cab30-ea47-444e-b356-d5c98087bcc6

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx [hunk 1]
```diff
@@ -36,11 +39,24 @@ export const SingleEntitySelectMenuItemsWithSearch = ({
...
+  const {
+    searchFilter,
+    searchQuery,
+    handleSearchFilterChange,
+    resetSearchFilterChange,
+  } = useEntitySelectSearch({
+    relationPickerScopeId,
+  });
+
+  useEffect(() => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:53]: We avoid this pattern:
1) instead of using a useEffect, we prefer perform the action (here reset the search filter) sequentially when needed. For example, on onSubmit or on onCancel. This avoids creating side effects that are difficult to debug and also creating re-renders
2) here you are hacking the useEffect dependency array to avoid re-renders which is a symptom of the problem above

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx [hunk 2]
```diff
@@ -16,6 +18,7 @@ export type SingleEntitySelectMenuItemsWithSearchProps = {
   relationObjectNameSingular: string;
   relationPickerScopeId?: string;
   selectedRelationRecordIds: string[];
+  clearOnOpen?: boolean;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx:21]: I think the behavior we want is:
- onSubmit or onCancel => reset to ''
- be able to programatically set a defaultValue in the Search (I don't think it's needed for now, we can let it for later)

**Review by charlesBochet — COMMENTED** [review]
@agupta0001 Thanks a lot for you PR, I've left comments :)

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx (hunk 1 above)
Comment (agupta0001) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx]: hey @charlesBochet, Thanks for the Review, I've made changes so that we will reset the field when `onCancel` is triggered or an entity is selected

File: packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx (hunk 2 above)
Comment (agupta0001) [reply packages/twenty-front/src/modules/object-record/relation-picker/components/SingleEntitySelectMenuItemsWithSearch.tsx]: Remove this field

**Comment by charlesBochet** [comment]
@agupta0001 LGTM, I have made a change to avoid some re-renders but unrelated to your work, thank you!

**Review by charlesBochet — APPROVED** [review]
