### PR TITLE
RICH_TEXT_V2 frontend

### LINKED ISSUE #10084: GraphQLError: Unexpected token R in JSON at position 0
Sentry Issue: [TWENTY-SERVER-9S](https://twenty-v7.sentry.io/issues/5343675393/?referrer=github_integration)

```
GraphQLError: Unexpected token R in JSON at position 0
  File "/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/handlers/activity-query-result-getter.handler.js", line 19, in ActivityQueryResultGetterHandler.handle
    const blocknote = JSON.parse(blocknoteJson);
  File "/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js", line 107, in QueryResultGettersFactory.processRecord
    const objectRecordProcessedWithoutRelationFields = await handler.handle(record, workspaceId);
  File "/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js", line 65
    node: await this.processRecord(edge.node, objectMetadataItemId, objectMetadataMaps, workspaceId)
  File "/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js", line 63, in QueryResultGettersFactory.processConnection
    edges: await Promise.all(connection.edges.map(async (edge)=>({
  File "/app/packages/twenty-server/dist/src/engine/api/graphql/workspace-query-runner/factories/query-result-getters/query-result-getters.factory.js", line 116, in QueryResultGettersFactory.processQueryResultField
    return await this.processConnection(queryResultField, objectMetadataItemId, objectMetadataMaps, workspaceId);
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by eliasylonen**
Adds task and note support for the new `bodyV2` field. (Field metadata type of `bodyV2` is `RICH_TEXT_V2`.)

Related to issue https://github.com/twentyhq/twenty/issues/7613

Upgrade commands will be in separate PRs.

Fixes https://github.com/twentyhq/twenty/issues/10084

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const CardComponents: Record<CardType, CardComponentType> = {
     </StyledGreyBox>
   ),
 
-  [CardType.RichTextCard]: ({ targetableObject }) => (
+  [CardType.RichTextV2Card]: ({ targetableObject }) => (
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx:56]: Shouldn't we keep both ?

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts [hunk 2]
```diff
@@ -36,11 +36,11 @@ export const useRecordShowContainerTabs = (
   > = {
     [CoreObjectNameSingular.Note]: {
       tabs: {
-        richText: {
+        richTextV2: {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts:39]: Shouldn't we keep both types ?

File: packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts [hunk 3]
```diff
@@ -10,5 +10,5 @@ export enum CardType {
   WorkflowVersionCard = 'WorkflowVersionCard',
   WorkflowRunCard = 'WorkflowRunCard',
   WorkflowRunOutputCard = 'WorkflowRunOutputCard',
-  RichTextCard = 'RichTextCard',
+  RichTextV2Card = 'RichTextV2Card',
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts:13]: Shouldn't we keep both types ?

File: packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts [hunk 4]
```diff
@@ -158,6 +160,24 @@ export const buildRecordFromImportedStructuredRow = (
         }
         break;
       }
+      case FieldMetadataType.RICH_TEXT_V2: {
+        if (
+          isDefined(
+            importedStructuredRow[`${blocknoteLabel} (${field.name})`] ||
+              importedStructuredRow[`${markdownLabel} (${field.name})`],
+          )
+        ) {
```
[the remark this answers is not in the document]
Comment (lucasbordeau) [reply packages/twenty-front/src/modules/object-record/spreadsheet-import/utils/buildRecordFromImportedStructuredRow.ts:169]: Good point

File: packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts [hunk 5]
```diff
@@ -122,12 +120,6 @@ export const SETTINGS_NON_COMPOSITE_FIELD_TYPE_CONFIGS: SettingsNonCompositeFiel
       exampleValue: { key: 'value' },
       category: 'Advanced',
     } as const satisfies SettingsFieldTypeConfig<FieldJsonValue>,
-    [FieldMetadataType.RICH_TEXT]: {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts:125]: Shouldn't we keep this ? We're not yet removing the old type

**Comment by lucasbordeau** [comment]
@eliasylonen could you fix the bug we have because of this line `const blocknote: RichTextBody = JSON.parse(blocknoteJson);` in `ActivityQueryResultGetterHandler` ? Because it might be in production right now. And even if it doesn't prevent displaying the note, it show an error message which is annoying. 

A simple try / catch and returning something appropriate could fix it what do you think ?

**Comment by lucasbordeau** [comment]
We should put some effort to have body V1 not so buggy before rolling out V2.

**Comment by lucasbordeau** [comment]
Also maybe we could prevent importing into body V1 in this PR already ?

**Comment by lucasbordeau** [comment]
I feel like this PR should at least harden everything for body v1 to prevent any more bug on notes and tasks, because it's a critical part of Twenty used by users right now.

File: packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts (hunk 2 above)
Comment (eliasylonen) [reply packages/twenty-front/src/modules/object-record/record-show/hooks/useRecordShowContainerTabs.ts:39]: The renaming seems unnecessary, nothing v2-specific here, reverting

File: packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts (hunk 3 above)
Comment (eliasylonen) [reply packages/twenty-front/src/modules/object-record/record-show/types/CardType.ts:13]: Also nothing v2-specific here, reverting

File: packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx (hunk 1 above)
Comment (eliasylonen) [reply packages/twenty-front/src/modules/object-record/record-show/components/CardComponents.tsx]: Unnecessarily renamed

File: packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts (hunk 5 above)
Comment (eliasylonen) [reply packages/twenty-front/src/modules/settings/data-model/constants/SettingsNonCompositeFieldTypeConfigs.ts:125]: `RICH_TEXT` is excluded from the settings in `SettingsExcludedFieldType.ts` so I think we can remove this

**Comment by eliasylonen** [comment]
Importing to the old `body` field is disabled in the frontend when `isRichTextV2Enabled` is true, [here](https://github.com/twentyhq/twenty/pull/10083/commits/ca2a2e480b4680754a810a15d7248c60224610ba) 👍

**Review by lucasbordeau — APPROVED** [review]
