### PR TITLE
Fix: add 404 page

### LINKED ISSUE #1163: Implement 404 page
Back to content should go to the default view of companies

Image

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9062-84249&mode=design&t=hSzJrpG9ok25Eoo2-4
```[tasklist]
### Tasks
- [ ] Create a NotFound page that display the content/styling above. Exceptionnaly, you don't have to use the theme to set the font-size (only!) as this will be too big and only used here
- [ ] Use CompanyMockTable to display the table below the background blur
- [ ] Add a CatchAll (*) route at the end of our routing in App.tsx that will redirect to this page
- [ ] On "Back to content", navigate to "/"
```

### PR DESCRIPTION
**Pull request by sunilk4u**
Fixes #1163 

image

### CODE REVIEW

File: front/src/App.tsx [hunk 1]
```diff
@@ -67,6 +69,7 @@ export function App() {
               </Routes>
             }
           />
+          <Route path="*" element={<NotFound />} />
```
Comment (charlesBochet) [inline front/src/App.tsx:72]: Let's introduce an AppPath.NotFoundWildcard to be consistent with other routes

File: front/src/NotFound.tsx [hunk 2]
```diff
@@ -0,0 +1,69 @@
+import { useNavigate } from 'react-router-dom';
+import styled from '@emotion/styled';
+
+import { MainButton } from '@/ui/button/components/MainButton';
+import { useIsMobile } from '@/ui/utilities/responsive/hooks/useIsMobile';
+
+import { CompaniesMockMode } from './pages/companies/CompaniesMockMode';
+
+const BackDrop = styled.div`
```
Comment (charlesBochet) [inline front/src/NotFound.tsx:9]: All styled components should be prefixed with Styled
so:
StyledBackDrop
StyledTextContainer...

This way we easily understand it's just a styled component while using it

**Review by charlesBochet — APPROVED** [review]
Thanks a lot @sunilk4u
I've added minor comments, we can merge once they are fixed
