### PR TITLE
fix: improve CRON schedule validation and display

### LINKED ISSUE #15870: Minor issues for CRON schedule
We would like to have UTC next to a time with hour + minutes, but not for other time descriptions, so that it's clear :

Image

The upcoming execution time computation is not ok, it should be verified for all combinations and fixed : 

Image

### PR DESCRIPTION
**Pull request by abdulrahmancodes**
Fixes multiple issues with CRON schedule input validation and execution time display.

### Issues Fixed

1. **UTC label placement** - Added "UTC" suffix to specific times (e.g., "at 09:30 UTC") but not to interval descriptions (e.g., "every hour")

2. **Upcoming execution time calculation** - Fixed incorrect execution times for malformed CRON expressions by implementing auto-correction

### Changes

- Created `normalizeCronExpression` utility to standardize cron expressions before parsing
- Updated `formatTime` to support optional UTC suffix
- Enhanced `getHoursDescription` to append UTC to specific times
- Added comprehensive test coverage (102 tests passing)

### Before

- `"1 /3 * * *"` showed daily executions at same time (incorrect)
- `"9 * * *"` showed same time repeated 3 times (incorrect)
- No UTC labels on schedule descriptions (confusing)

### After

- All malformed expressions auto-corrected and show correct execution times
- UTC labels clearly indicate timezone for specific times
- User-friendly error messages for truly invalid patterns

Closes #15870

### CODE REVIEW

**Comment by Devessier** [comment]
Hi @abdulrahmancodes. Is your PR ready for review?

**Comment by abdulrahmancodes** [comment]
@Devessier Yes, it's ready for review

**Comment by Devessier** [comment]
Hi @abdulrahmancodes! I’m reviewing your PR.

It seems the computation of the next execution times isn’t working correctly for minutes. If you enter `minutes > 60`, the “Schedule” displays the correct value, but the execution times are capped at 60.

I’m not sure whether we should allow users to enter `minutes > 60` and fix the way next times are calculated, or simply disallow `minutes > 60` altogether. Personally, I think we should also cap minutes at 60 and prevent entering values above that. If users need more customization, they can use a cron expression.

CleanShot 2025-12-08 at 08 21 03@2x

File: packages/twenty-front/src/utils/format/formatTime.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ export const formatTime = (
   hour: string,
   minute: string,
   use24HourFormat: boolean,
+  appendUTC = false,
```
Comment (Devessier) [inline packages/twenty-front/src/utils/format/formatTime.ts]: Let's refactor the function to receive a single object parameter.

Like:

```ts
type FormatTypeParams = {
  hour: string,
  minute: string,
  use24HourFormat: boolean,
  appendUTC?: boolean,
}

export const formatTime = ({
  hour,
  minute,
  use24HourFormat,
  appendUTC = false,
}: {
  hour: string,
  minute: string,
  use24HourFormat: boolean,
  appendUTC?: boolean,
}
```

**Review by Devessier — COMMENTED** [review]
Great work! I left two comments. Let's address them before merging.

File: packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-version-can-be-activated.util.ts [hunk 2]
```diff
@@ -220,12 +220,20 @@ function assertCronTriggerSettingsAreValid(settings: any) {
...
 
-      if (settings.schedule.minute <= 0) {
+      if (settings.schedule.minute <= 0 || settings.schedule.minute > 60) {
+        const isTooSmall = settings.schedule.minute <= 0;
+        const userFriendlyMessage = isTooSmall
+          ? msg`Invalid minute value. Should be integer greater than 1`
+          : msg`Minute value cannot exceed 60. For intervals greater than 60 minutes, use the "Hours" trigger type or a custom cron expression`;
+        const errorMessage = isTooSmall
+          ? 'Invalid minute value. Should be integer greater than 1'
+          : 'Invalid minute value. Cannot exceed 60. For intervals greater than 60 minutes, use the "Hours" trigger type or a custom cron expression';
```
Comment (Devessier) [inline packages/twenty-server/src/modules/workflow/workflow-trigger/utils/assert-version-can-be-activated.util.ts]: Let's use msg`` here too

**Review by Devessier — APPROVED** [review]
Good job!
One small comment but every else looks good to me.

**Comment by lucasbordeau** [comment]
Well done
