### PR TITLE
Fix composite field edition

### LINKED ISSUE #12056: Trying to edit several fields of a composite field clears them all
## Bug Description

https://github.com/user-attachments/assets/d7bb8e1c-be4b-478b-892c-d1f6047f4b60

The issue happens when editing the fields in the side panel **and** the regular show page.

## Expected behavior

Focusing another input in the composite field modal shouldn't clear the input filled just before.

### PR DESCRIPTION
**Pull request by thomtrp**
Fixes https://github.com/twentyhq/twenty/issues/12056

Bug has been introduced by https://github.com/twentyhq/twenty/pull/11983/files

Adding onClick on the container makes it always available. Before it was only when not in edit mode.
It breaks the click outside of the `RecordInlineCell`.

This PR set the onClick only when not in edit mode.

https://github.com/user-attachments/assets/a44337a9-72e6-4de8-afa1-95de6b953459

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx [hunk 1]
```diff
@@ -134,7 +120,6 @@ export const RecordInlineCellContainer = () => {
     <StyledInlineCellBaseContainer
       onMouseEnter={handleContainerMouseEnter}
       onMouseLeave={handleContainerMouseLeave}
-      onClick={handleDisplayModeClick}
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx:137]: It was moved to this component to enable click on label [original issue](https://github.com/twentyhq/twenty/issues/10561).

File: packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx [hunk 2]
```diff
@@ -47,6 +46,7 @@ const StyledValueContainer = styled.div<{ readonly: boolean }>`
   display: flex;
   min-width: 0;
   position: relative;
+  width: 100%;
```
Comment (etiennejouan) [inline packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellContainer.tsx:49]: Small design issue on ActorField readonly field
Screenshot 2025-05-16 at 16 44 59

**Review by etiennejouan — APPROVED** [review]
Thanks for fixing this 🙏 
I'll try to solve the click on label

**Review by etiennejouan — APPROVED** [review]
Nice !! 👏 Thank you for fixing this !
