### PR TITLE
Fix Google Auth displays Status: 401 on screen

### LINKED ISSUE #7584: The failure of Google Auth displays "Status: 401" on screen
## Bug Description

If the user tries to log in using Google Auth, and in the process if he cancels the selected email. The status 401 displayed on the screen.

Video Link: 
https://github.com/user-attachments/assets/cdefbbed-1116-4dcc-a4b2-eeb56be7b8f0

## Expected behavior

After the cancellation of the login process, the user should see "try with different account" or the login page to try out another email Id.

## Technical inputs

We can redirect the cancellation process to desired location.

### PR DESCRIPTION
**Pull request by Pushpender1122**
When the user presses the cancel button, the server sends the following response:
image

{"statusCode": 401, "message": "Unauthorized"}

Now, when the user clicks the cancel button, they are redirected to the home page for login.

Related Issue
Fixes #7584

### CODE REVIEW

**Comment by charlesBochet** [comment]
@Bonapara what do you think? Maybe a snack bar in this case?

**Comment by charlesBochet** [comment]
@Pushpender1122 Thanks for the PR, waiting for product's input

**Comment by Pushpender1122** [comment]
Sure

**Comment by Bonapara** [comment]
Maybe we should redirect to `/welcome` to allow the user to sign up with a different email. I believe selecting the wrong email is the most common scenario. WDYT? Did I get you well @charlesBochet?

**Comment by Pushpender1122** [comment]
It redirects to /welcome. If you go to xyz.com, it automatically navigates to /welcome.

**Comment by Bonapara** [comment]
Sounds like a good behavior, wondering what @charlesBochet had in mind.

**Comment by Pushpender1122** [comment]
Hi @charlesBochet and @Bonapara , are there any other changes you'd like me to make?

File: packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts [hunk 1]
```diff
@@ -33,6 +34,7 @@ export class GoogleAuthController {
 
   @Get('redirect')
   @UseGuards(GoogleProviderEnabledGuard, GoogleOauthGuard)
+  @UseFilters(AuthOAuthExceptionFilter)
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/auth/controllers/google-auth.controller.ts:37]: using an adhoc filter to redirect instead of the ApplyCorsToExceptions globalFilter which is not meant to do that

File: packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts [hunk 2]
```diff
@@ -14,6 +19,13 @@ export class GoogleOauthGuard extends AuthGuard('google') {
     const workspaceInviteHash = request.query.inviteHash;
     const workspacePersonalInviteToken = request.query.inviteToken;
 
+    if (request.query.error === 'access_denied') {
+      throw new AuthException(
+        'Google OAuth access denied',
+        AuthExceptionCode.OAUTH_ACCESS_DENIED,
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/auth/guards/google-oauth.guard.ts:25]: throwing a precise Auth Exception exception in the guard

**Review by charlesBochet — APPROVED** [review]
Thanks @Pushpender1122. I have made a few changes that are more in the "nestjs" philosophy
