### PR TITLE
fix: options value can't contain special characters

### LINKED ISSUE #3296: Field name and options should be normalized to A-Z+0-9
I tried to create a field "industry" on the company object. 
One of the options had emoji in its value:
Screenshot 2024-01-08 at 12 15 35

But now my workspace is broken and I get this error everywhere:
Screenshot 2024-01-08 at 12 04 54

Related: #3066 #2146

### PR DESCRIPTION
**Pull request by magrinj**
When we put special characters like emoji inside options, the value generated by the front-end should strip the special characters and accents.

Fix #3296

### CODE REVIEW

File: packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts [hunk 1]
```diff
@@ -5,8 +5,19 @@ import { Field } from '~/generated-metadata/graphql';
 
 import { FieldMetadataOption } from '../types/FieldMetadataOption';
 
-const getOptionValueFromLabel = (label: string) =>
-  toSnakeCase(label.trim()).toUpperCase();
+const getOptionValueFromLabel = (label: string) => {
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts:8]: it would be awes

Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts:8]: it would be great to add tests on this function

Comment (magrinj) [reply packages/twenty-front/src/modules/object-metadata/utils/formatFieldMetadataItemInput.ts]: @Weiko Thanks for the tests, I've just added an emoji test

**Review by charlesBochet — APPROVED** [review]
Let's go! LGTM :)
