### PR TITLE
Fix banner z-index

### LINKED ISSUE #1102: [Workflow] Fix Canvas display above banner
https://discord.com/channels/1130383047699738754/1383090995729666100

### PR DESCRIPTION
**Pull request by martmull**
## Before
image

## After
image

### CODE REVIEW

File: packages/twenty-ui/src/display/banner/components/Banner.tsx [hunk 1]
```diff
@@ -18,6 +18,7 @@ const StyledBanner = styled.div<{ variant?: BannerVariant }>`
   font-weight: ${({ theme }) => theme.font.weight.medium};
   line-height: 150%;
   box-sizing: border-box;
+  z-index: 1;
```
Comment (charlesBochet) [inline packages/twenty-ui/src/display/banner/components/Banner.tsx]: looks to me that the Banner component itself is not the right place to set a z-index as it's a "global" component and the z-index notion is local.

We have two possibilities: allow a prop zIndex or add a StyledContainer in the caller with the zIndex

I would go with the StyledContainer

Comment (martmull) [reply packages/twenty-ui/src/display/banner/components/Banner.tsx]: Can this be due to reactFlow Canvas that is also global?

Comment (charlesBochet) [reply packages/twenty-ui/src/display/banner/components/Banner.tsx]: z-index is working as a a tree.

```
Div1
- div 1a (z-index: 1)
- div 1b
Div2
- div 2a (z-index 2)
- div 2b
```

These z-index do not matter as div2a z-index can only be compared with its siblings (div 2b), therefore adding a z-index on a component such as Banner does not makes sense :) It will depends on its parents and siblings

File: packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx [hunk 2]
```diff
@@ -4,6 +4,7 @@ import { Button } from 'twenty-ui/input';
 
 const StyledBanner = styled(Banner)`
   position: absolute;
+  z-index: 1;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/information-banner/components/InformationBanner.tsx:7]: Let's add a StyledShowPageBanner in RecordShowContainer

**Review by charlesBochet — APPROVED** [review]
Approved so you can merge after change :)
