### PR TITLE
Eliminate unnecessary API calls when persisting field

### LINKED ISSUE #10177: Unnecessary API Calls when leaving clicked Table Cell
### Description
When clicking on a table cell and then leaving it without making any changes, two API endpoints are triggered:
- update (even though no modifications were made)
- aggregate

This results in unnecessary requests and unintended side effects.

### Steps to Reproduce

- Open the table in the application.
- Click on any cell.
- Click outside the cell without making any changes.
- Observe the network requests.

**Expected Behavior**
No API request should be triggered if no changes were made.
**Actual Behavior**

- Two API requests (update and aggregate) are sent unnecessarily.
- If there is no sorting option in the table, the table gets resorted, which looks weird and disrupts the user experience.

**Impact**

- Performance issue: Unnecessary API requests increase load on the server.
- UI issue: The table unexpectedly resorts itself, causing confusion for users.

Video Evidence

https://github.com/user-attachments/assets/328d8233-0803-487c-b574-eeeb8b984737

### PR DESCRIPTION
**Pull request by bosiraphael**
Fixes #10177

Modified `usePersistField` to check for deep equality between the value to persist and the current record store value before sending an update query.

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts [hunk 1]
```diff
@@ -156,6 +157,23 @@ export const usePersistField = () => {
...
+
+          const currentValue: any = snapshot
+            .getLoadable(recordStoreFamilySelector({ recordId, fieldName }))
+            .getValue();
+
+          let valueToCompare = valueToPersist;
+          let currentValueToCompare = currentValue;
+
+          if (fieldIsRelationToOneObject) {
+            valueToCompare = valueToPersist?.id ?? null;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts]: why do we have an edge case here? does not seems to worth it

File: packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts [hunk 2]
```diff
@@ -156,6 +157,23 @@ export const usePersistField = () => {
 
         if (isValuePersistable) {
           const fieldName = fieldDefinition.metadata.fieldName;
+
+          const currentValue: any = snapshot
+            .getLoadable(recordStoreFamilySelector({ recordId, fieldName }))
+            .getValue();
+
+          let valueToCompare = valueToPersist;
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts]: these assignation do not seem useful

File: packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts (hunk 1 above)
Comment (bosiraphael) [reply packages/twenty-front/src/modules/object-record/record-field/hooks/usePersistField.ts]: Because the value from the record store and the value to persit may not have the same fields for a relation type, what we really want is to compare the id:

CleanShot 2025-06-03 at 12 02 16@2x

**Review by charlesBochet — APPROVED** [review]
