### PR TITLE
fix(auth): Improve error management with sso + fix microsoft saml

### LINKED ISSUE #9760: Error message is unclear when SSO setup fails
We should probably provide a better error message? It's hard to debug

Image

### PR DESCRIPTION
**Pull request by AMoreaux**
Fix #9760 #9758

### CODE REVIEW

File: packages/twenty-server/src/engine/core-modules/guard-manager/utils/get-caller-by-context.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+export const getCallerByContext = (
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/guard-manager/utils/get-caller-by-context.ts:1]: not sure to understand why we need this, this looks a bit complex to me

File: packages/twenty-server/src/engine/core-modules/guard-manager/services/guard-error-manager.service.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+import { DomainManagerService } from 'src/engine/core-modules/domain-manager/services/domain-manager.service';
+import { getCallerByContext } from 'src/engine/core-modules/guard-manager/utils/get-caller-by-context';
+
+@Injectable()
+// eslint-disable-next-line @nx/workspace-inject-workspace-repository
+export class GuardErrorManagerService {
+  constructor(private readonly domainManagerService: DomainManagerService) {}
+
+  dispatchErrorFromGuard(
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/guard-manager/services/guard-error-manager.service.ts:11]: I don't understand internal vs external. This looks a bit overkill to me, why not just redirecting?

File: packages/twenty-server/src/engine/core-modules/guard-manager/guard-manager.module.ts [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import { Module } from '@nestjs/common';
+
+import { GuardErrorManagerService } from 'src/engine/core-modules/guard-manager/services/guard-error-manager.service';
+import { DomainManagerModule } from 'src/engine/core-modules/domain-manager/domain-manager.module';
+
+@Module({
+  imports: [DomainManagerModule],
+  providers: [GuardErrorManagerService],
+  exports: [GuardErrorManagerService],
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/guard-manager/guard-manager.module.ts:9]: Why not introducing this module it's not a "guard-manager". TBH feels a bit overkill to me too. Not strongly against it though!

File: packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts [hunk 4]
```diff
@@ -79,12 +79,14 @@ export class DomainManagerService {
     subdomain,
     pathname,
     searchParams,
+    baseUrl,
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/domain-manager/services/domain-manager.service.ts:82]: why do we allow to change the baseUrl?

File: packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts [hunk 5]
```diff
@@ -9,33 +9,44 @@ import {
...
       }
-
       new SamlAuthStrategy(this.sSOService);
 
       return (await super.canActivate(context)) as boolean;
     } catch (err) {
-      if (err instanceof AuthException) {
-        return false;
-      }
+      this.guardErrorManagerService.dispatchErrorFromGuard(context, err, {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts:45]: do we also want to dispatch it to sentry in some cases?

File: packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts [hunk 6]
```diff
@@ -9,33 +9,44 @@ import {
...
+    private readonly sSOService: SSOService,
+    private readonly guardErrorManagerService: GuardErrorManagerService,
+  ) {
     super();
   }
 
   async canActivate(context: ExecutionContext) {
+    const request = context.switchToHttp().getRequest();
+
+    let identityProvider: Awaited<
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/auth/guards/saml-auth.guard.ts:26]: new pattern: Awaited<>. Can we instead introduce a type and export it (and use Promise<type>)

File: packages/twenty-front/src/modules/auth/hooks/useAuth.ts [hunk 7]
```diff
@@ -458,6 +458,12 @@ export const useAuth = () => {
         url.searchParams.set('workspaceId', workspacePublicData.id);
       }
 
+      if (isDefined(workspacePublicData)) {
+        url.searchParams.set('workspaceId', workspacePublicData.id);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/hooks/useAuth.ts:462]: mistake?

File: packages/twenty-front/src/modules/auth/hooks/useAuth.ts [hunk 8]
```diff
@@ -458,6 +458,12 @@ export const useAuth = () => {
...
+      }
+
+      url.searchParams.set('origin_url', window.origin);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/hooks/useAuth.ts:465]: why is it useful?

File: packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSSO.ts [hunk 9]
```diff
@@ -41,6 +41,12 @@ export const useSSO = () => {
       );
     }
 
+    const url = new URL(
+      authorizationUrlForSSOResult.data?.getAuthorizationUrl.authorizationURL,
+    );
+
+    url.searchParams.set('origin_url', window.origin);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/auth/sign-in-up/hooks/useSSO.ts:48]: same here?

File: packages/twenty-front/src/modules/settings/security/utils/parseSAMLMetadataFromXMLFile.ts [hunk 10]
```diff
@@ -8,6 +8,29 @@ const validator = z.object({
   certificate: z.string().min(1),
 });
 
+const prefixGet = (
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/security/utils/parseSAMLMetadataFromXMLFile.ts:11]: getByPrefixAndKey?

File: packages/twenty-server/src/engine/core-modules/guard-manager/services/guard-error-manager.service.ts [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+      subdomain?: string;
+      baseUrl?: string;
+    },
+  ) {
+    const caller = getCallerByContext(
+      context,
+      this.domainManagerService.getFrontUrl().hostname,
+    );
+
+    if (caller.callerType === 'internal-graphql-caller') {
```
Comment (charlesBochet) [inline packages/twenty-server/src/engine/core-modules/guard-manager/services/guard-error-manager.service.ts:24]: if(isInGraphQLContext(context))

**Review by charlesBochet — APPROVED** [review]
Love it, thanks for addressing all the feedbacks
