### PR TITLE
fix(billing): adapt current phase to current period

### LINKED ISSUE #1748: Billing Issue
When I switch from yearly to monthly, the change takes effect at the end of the month instead of the end of the year.

### PR DESCRIPTION
**Pull request by AMoreaux**
Fix https://github.com/twentyhq/core-team-issues/issues/1748

### CODE REVIEW

File: packages/twenty-front/src/modules/billing/components/SettingsBillingSubscriptionInfo.tsx [hunk 1]
```diff
@@ -339,6 +339,8 @@ export const SettingsBillingSubscriptionInfo = ({
     }
   };
 
+  console.log('>>>>>>>>>>>>>>', nextBillingPhase);
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/billing/components/SettingsBillingSubscriptionInfo.tsx]: we should remove that :p

**Review by charlesBochet — APPROVED** [review]
LGTM, once CI are green!
