### PR TITLE
Fix filter with empty field

### LINKED ISSUE #899: Field "" is not defined by type "XXXFilterInput".
[sentry](https://twenty-v7.sentry.io/issues/6550677680/?project=4507072499810304&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20user.email%3Astephanie%40twenty.com%20Error&referrer=issue-stream&stream_index=1)

### PR DESCRIPTION
**Pull request by ijreilly**
Attempt to fix https://github.com/twentyhq/core-team-issues/issues/899

Could not reproduce but that's the only place in the code where I found that we build filters as such, with values for "in" being equal to select options and not recordIds, as it seems to be the case from the sentries (ex:
Capture d’écran 2025-04-29 à 11 13 56
)

### CODE REVIEW

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts [hunk 1]
```diff
@@ -68,17 +69,38 @@ export const useLoadRecordIndexBoardColumn = ({
...
+  }
 
   const filter = {
     ...requestFilters,
-    [recordIndexKanbanFieldMetadataItem?.name ?? '']: isDefined(
-      recordGroupDefinition?.value,
-    )
-      ? { in: [recordGroupDefinition?.value] }
-      : { is: 'NULL' },
+    ...(isDefined(recordIndexKanbanFieldMetadataFilter) && {
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts:101]: Avoid && as it's not the same as using a ternary and it can return weird stuff, it can be tolerated in a JSX statement but not when creating objects.

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts [hunk 2]
```diff
@@ -68,17 +69,38 @@ export const useLoadRecordIndexBoardColumn = ({
...
+    const recordIndexKanbanFieldMetadataItem = objectMetadataItem.fields.find(
+      (field) => field.id === boardFieldMetadataId,
+    );
+
+    if (!isDefined(recordIndexKanbanFieldMetadataItem)) {
+      throw new Error('Record index kanban field metadata item not found');
+    }
+
+    if (
+      !isDefined(recordIndexKanbanFieldMetadataItem?.name) ||
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts:84]: use our isNonEmptyString typeguard instead

File: packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts [hunk 3]
```diff
@@ -68,17 +69,38 @@ export const useLoadRecordIndexBoardColumn = ({
     recordBoardId,
   });
 
-  const recordIndexKanbanFieldMetadataItem = objectMetadataItem.fields.find(
-    (field) => field.id === boardFieldMetadataId,
-  );
+  let recordIndexKanbanFieldMetadataFilter: { [x: string]: any } | undefined;
```
Comment (lucasbordeau) [inline packages/twenty-front/src/modules/object-record/record-index/hooks/useLoadRecordIndexBoardColumn.ts:72]: Let's initialize this variable with `{}` at least.

**Comment by lucasbordeau** [comment]
Seems like the right thing to do for this bug, at least we're cleaning this area.

**Review by lucasbordeau — APPROVED** [review]
