### PR TITLE
Fix command menu keyboard input & refactor group

### LINKED ISSUE #1703: Bug: command menu keyboard inputs not working
## Bug Description

The command menus keyboard shortcuts are not working at all.

```
1. Open command menu
2. press arrow key down
3. press enter
-> nothing happens 
Video not applicable as nothing changes :)
```

## Expected behavior

Keyboard inputs should work!

## Technical inputs

```
- the handler of the library cmdk seems to not register any keyboard inputs 
- Maybe a stopPropagation?
```

### PR DESCRIPTION
**Pull request by brendanlaschke**
It cost me **some** time but now I found the breaking commit: fb737e2 / #1492 

With the icon refactoring some changes where made  to the CommandMenuItem - I'm not sure about their goal ... Maybe you have an Idea why [not only the Icon was refactored](https://github.com/twentyhq/twenty/commit/fb737e20212f0570bcb839714b4f1174e6ce1828#diff-4ecaa2a218b9c9effbcd3db78d8059b88d9c81634e41f8712107a290f0e95fceL54-R52) @charlesBochet ? 

For now I reverted the change and the keyboard input is now working again 🎉 

While I was at the CommandMenu I made the CommandGroups somewhat reasonable to not render if no items are included - improving the developer experience in the CommandMenu files by not needing so many conditional elements. 

We should also write some tests covering this and other keyboard behaviour on the command menu ... maybe in a follow up issue? 

closes #1703

### CODE REVIEW

File: front/src/modules/command-menu/components/CommandMenuItem.tsx [hunk 1]
```diff
@@ -44,11 +53,25 @@ export const CommandMenuItem = ({
   };
 
   return (
-    <MenuItemCommand
-      LeftIcon={Icon}
-      text={label}
-      command={shortcuts ? shortcuts.join(' then ') : ''}
-      onClick={onItemClick}
-    />
+    <StyledMenuItem onSelect={onItemClick}>
```
Comment (charlesBochet) [inline front/src/modules/command-menu/components/CommandMenuItem.tsx:56]: so is it all about this onSelect?

**Review by charlesBochet — APPROVED** [review]

File: front/src/modules/command-menu/components/CommandMenuItem.tsx [hunk 2]
```diff
@@ -22,9 +30,10 @@ export const CommandMenuItem = ({
   onClick,
   Icon,
   shortcuts,
-}: CommandMenuItemProps) => {
```
Comment (charlesBochet) [inline front/src/modules/command-menu/components/CommandMenuItem.tsx:25]: our new convention is to name the Props after the component name: so CommandMenuItemProps is correct

File: front/src/modules/command-menu/components/CommandGroup.tsx [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import React from 'react';
```
Comment (charlesBochet) [inline front/src/modules/command-menu/components/CommandGroup.tsx:1]: nice!

File: front/src/modules/command-menu/components/CommandMenuItem.tsx (hunk 1 above)
Comment (charlesBochet) [inline front/src/modules/command-menu/components/CommandMenuItem.tsx:56]: mmh ok, so we need to use the cmdk components. Let's actually refactor the MenuItemCommand itself to use cmdk components. (let's move the styles needed within this MenuItemCommand)
