### PR TITLE
Fix use as draft

### LINKED ISSUE #9408: Fix use as draft workflow action
Don't check the statuses to see if the workflow has a draft version but rather query the workflow versions which are in draft.
This is because since workflow statuses are updated asynchronously via a listener, the data may be stale if we don't refresh the page.

### PR DESCRIPTION
**Pull request by bosiraphael**
Closes #9408

### CODE REVIEW

File: packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useUseAsDraftWorkflowVersionSingleRecordAction.tsx [hunk 1]
```diff
@@ -30,19 +30,17 @@ export const useUseAsDraftWorkflowVersionSingleRecordAction: ActionHookWithoutOb
 
     const navigate = useNavigate();
 
-    const workflowStatuses = workflow?.statuses;
+    const hasAlreadyDraftVersion =
+      workflow?.versions.some((version) => version.status === 'DRAFT') || false;
```
Comment (Devessier) [inline packages/twenty-front/src/modules/action-menu/actions/record-actions/single-record/workflow-version-actions/hooks/useUseAsDraftWorkflowVersionSingleRecordAction.tsx:34]: Using `Array#some`? Awesome!

**Review by Devessier — APPROVED** [review]
We can merge.

**Review by thomtrp — APPROVED** [review]
