### PR TITLE
fix: removes re-triggering of OTP provisioning

### LINKED ISSUE #13846: Logging out on the 2FA page triggers a re-render (?)
If you're on the 2FA setup page in settings and then click on "Logout", you will see it tries to re-trigger the OTP provisionning:

Image

Probably there's a re-render that retriggers TwoFactorAuthenticationSetupForSettingsEffect? We should fix the root cause

### PR DESCRIPTION
**Pull request by hc11h**
Fixes : [13846 ](https://github.com/twentyhq/twenty/issues/13846)

### CODE REVIEW

**Comment by neo773** [comment]
This will fail lint as using `useRef` for state management isn't allowed.

image

**Comment by charlesBochet** [comment]
@hc11h, thanks for opening a PR, I'll review it this we

**Comment by charlesBochet** [comment]
@ijreilly would also like to come back with another proposal tomorrow, leaving it open

**Comment by ijreilly** [comment]
Hi @hc11h thank you for your contribution ! 
The issue is actually that qrCodeState is cleared at logout which re-triggers TwoFactorAuthenticationSetupForSettingsEffect's effect. So let's make it early return if there is no user logged in!

File: packages/twenty-front/src/modules/settings/two-factor-authentication/components/TwoFactorAuthenticationSetupForSettingsEffect.tsx [hunk 1]
```diff
@@ -59,8 +61,14 @@ export const TwoFactorAuthenticationSetupForSettingsEffect = () => {
     handleTwoFactorAuthenticationProvisioningInitiation();
 
     // Two factor authentication provisioning only needs to run once at mount
```
Comment (charlesBochet) [inline packages/twenty-front/src/modules/settings/two-factor-authentication/components/TwoFactorAuthenticationSetupForSettingsEffect.tsx]: remove comment

**Review by ijreilly — APPROVED** [review]
